### ISSUE TITLE
Snakemake with --cluster-status flag failing

### ISSUE THREAD

**Issue by dorks81** [snakemake/snakemake#1001]
Hello,

I am trying to get snakemake file to run on LSF using the --cluster-status flag. I create a status1.py file and snakemake is crashing while trying to execute the file. It appears that snakemake trying to execute the command ```./status1.py Job <615515> is submitted to queue <short>``` but is crashing because the <> brackets are not parsable from the bash command line. Is there a work around?

Thank you for the help

```
/bin/sh: -c: line 0: syntax error near unexpected token `615515'
/bin/sh: -c: line 0: `./status1.py Job <615515> is submitted to queue <short>.'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "tools/Anaconda3/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 1036, in job_status
    subprocess.check_output(
  File "tools/Anaconda3/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "tools/Anaconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command './status1.py Job <615515> is submitted to queue <short>.' returned non-zero exit status 1.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "tools/Anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "tools/Anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "tools/Anaconda3/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 1083, in _wait_for_jobs
    status = job_status(active_job)
  File "tools/Anaconda3-2019.10/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 1055, in job_status
    raise WorkflowError(
snakemake.exceptions.WorkflowError: Failed to obtain job status. See above for error message.
```

**Comment by ImNotaGit** [comment]
I ran into the same issue. On many systems a cluster job submission command (e.g. qsub) immediately returns just a job ID string, and it seems that snakemake relies on this behavior to pass the job ID to the --cluster-status script. However, on some systems the returned message by e.g. qsub is more than a job ID. On my system it's like 'Your job xxxxx ("xxx.sh") has been submitted'. The entire message is appended as argument to the --cluster-status script without quoting, leading to this error. A temporary work around seems to be modifying the code snippet below in snakemake/executors/__init__.py script at the line where the exception happened:

Original code:
```
 subprocess.check_output(
                            "{statuscmd} {jobid}".format(
                                jobid=job.jobid, statuscmd=self.statuscmd
                            ),
                            shell=True,
                        )
```

Modified the above code by adding single quotes around {jobid}:
```
 subprocess.check_output(
                            "{statuscmd} '{jobid}'".format(
                                jobid=job.jobid, statuscmd=self.statuscmd
                            ),
                            shell=True,
                        )
```

Then in the --cluster-status python script, do something like:
```
 prompt = sys.argv[1]
 jobid = prompt.split(' ')[2] # do something specific to your system to parse the job ID from the message
print(check_status(jobid))
```

**Comment by schnea** [comment]
closing as --cluster-status is deprecated
