### ISSUE TITLE
Snakemake fails when the same checkpoint is executed more than once

### ISSUE THREAD

**Issue by cgr71ii** [snakemake/snakemake#1021]
**Snakemake version**
Snakemake version 6.4.0 and 6.4.1 (<=6.3.0 seems to be ok).

**Describe the bug**
Same or similar bug that the one described in issue https://github.com/snakemake/snakemake/issues/988.

When a rule follows a checkpoint which is executed more than once, the DAG dependencies cleaning process seems to try to clean the dependencies, but due to the fact that a checkpoint is executed more than once, when the other instances of the checkpoints are executed and finished, they attempt to clean the dependencies which have been cleaned before. The problem seems to be here: https://github.com/snakemake/snakemake/blob/d372707e6bd15831feeda971b5f3e1dc363a649c/snakemake/dag.py#L258

**Logs**
Minimal example (no `KeyError` is displayed, but I've checked out that the problem is the same debugging the cited line above):
```
Error in rule shard:
    jobid: 5
    output: data/batches.fr
    shell:
                             
        for i in $(seq 0 $(( $RANDOM % 5 + 1))); do
            for j in $(seq 0 $(( $RANDOM % 2 + 1))); do
                mkdir -p data/fr/$i/$j
                echo 'hello fr' > data/fr/$i/$j/text
            done
        done
        ls -d data/fr/*/* > data/batches.fr  
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

Running https://github.com/bitextor/bitextor/pull/213/commits/6476d8fb54928d216a1a395505293ebdfe05f9c2 with https://github.com/bitextor/bitextor/blob/2633e6be0eaf228191ad0a784410f0bbe965de2c/run-tests-bitextor-only.sh#L138:
```
Error in rule split_segalign:
    jobid: 2
    output: /home/runner/work/bitextor/bitextor/transient-en-fr/en_fr/en_fr.postprocessing_batches

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 575, in _callback
    callback(job)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/snakemake/scheduler.py", line 543, in _proceed
    potential_new_ready_jobs = self.dag.finish(
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/snakemake/dag.py", line 1348, in finish
    updated_dag = self.update_checkpoint_dependencies(jobs)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/snakemake/dag.py", line 1312, in update_checkpoint_dependencies
    self.postprocess()
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/snakemake/dag.py", line 1193, in postprocess
    self.cleanup()
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/snakemake/dag.py", line 258, in cleanup
    del self.depending[dep][job]
KeyError: dic_docsegalign_idx2ridx_l2tol1
```

**Minimal example**
```python
from itertools import product

src_lang = config['src_lang']
trg_lang = config['trg_lang']

rule all:                        
    input: "data/corpus.txt"

rule whatever:
    output: "data/empty"
    shell: '''
        touch "data/empty"
        '''

checkpoint shard:                    
    input: "data/empty"
    output: "data/batches.{lang}"    
    shell: '''                     
        for i in $(seq 0 $(( $RANDOM % 5 + 1))); do
            for j in $(seq 0 $(( $RANDOM % 2 + 1))); do
                mkdir -p data/{wildcards.lang}/$i/$j
                echo 'hello {wildcards.lang}' > data/{wildcards.lang}/$i/$j/text
            done
        done
        ls -d data/{wildcards.lang}/*/* > {output}  
        '''
                                                                
rule combine:                                              
    input:                                                
        l1='data/{src_lang}/{shard}/{src_batch}/text',
        l2='data/{trg_lang}/{shard}/{trg_batch}/text'
    output: 'data/{src_lang}_{trg_lang}/{shard}.{src_batch}_{trg_batch}.combined'
    shell: ''' paste {input.l1} {input.l2} > {output} '''
                                                                                                
def get_batches_pairs(src_lang, trg_lang):                                 
    src_batches = []      
    trg_batches = []                                        
    with checkpoints.shard.get(lang=src_lang).output[0].open() as src_f, \
            checkpoints.shard.get(lang=trg_lang).output[0].open() as trg_f:
        for line in src_f:                      
            src_batches.append(line.strip().split('/')[-2:])                                                                                
        for line in trg_f:
           trg_batches.append(line.strip().split('/')[-2:])
    iterator = product(src_batches, trg_batches)
    return [(src_shard, (src_batch, trg_batch)) for ((src_shard, src_batch), (trg_shard, trg_batch)) in iterator if src_shard == trg_shard]

rule corpus:           
    input: lambda wildcards: [f'data/{src_lang}_{trg_lang}/{shard}.{src_batch}_{trg_batch}.combined' for (shard, (src_batch, trg_batch)) in get_batches_pairs(src_lang, trg_lang)]
    output: 'data/corpus.txt'
    shell: ''' cat {input} > {output} '''
```

Run:
```bash
# The number of parallel jobs seems to not be related to the issue (tested with 1, 2 and 4)
snakemake -j4 --config src_lang=en trg_lang=fr
```

**Additional context**
This problem seems to be related to https://github.com/snakemake/snakemake/issues/439 too. In fact, the minimal example has been extracted from this issue and describes the same functionality, being the only difference the addition of an initial rule which triggers the checkpoint. It might be related since the situation described in the issue might not being contemplated in the normal usage of Snakemake, but it is not so strange to want to run the same checkpoints more than once.

**Comment by lpla** [comment]
Just upgraded to Snakemake 6.5.1 and now it is working fine.

**Comment by youngchanpark** [comment]
Also confirmed that the minimal example runs okay with 7.1.1.
Close?
