### ISSUE TITLE
KeyError: <rule name>

### ISSUE THREAD

**Issue by sebschmi** [snakemake/snakemake#1024]
**Snakemake version**
6.4.1

**Describe the bug**
In my workflow, I get a KeyError for a rule name. The Snakefile contains the rule name only twice (tested with Ctrl+F), once where the rule is defined, and once in a rule order directive.

**Logs**

```
Traceback (most recent call last):
  File "/home/sebschmi/.conda/envs/main/lib/python3.8/site-packages/snakemake/__init__.py", line 701, in snakemake
    success = workflow.execute(
  File "/home/sebschmi/.conda/envs/main/lib/python3.8/site-packages/snakemake/workflow.py", line 730, in execute
    dag.init()
  File "/home/sebschmi/.conda/envs/main/lib/python3.8/site-packages/snakemake/dag.py", line 190, in init
    self.cleanup()
  File "/home/sebschmi/.conda/envs/main/lib/python3.8/site-packages/snakemake/dag.py", line 258, in cleanup
    del self.depending[dep][job]
KeyError: concat_reference_genome
```

**Minimal example**
Sadly not possible, as I have no idea what causes this. It seems to have been introduced in 6.4.0 though, as I never got the issue in 6.3.0. And in 6.4.0, the `cleanup` method referred in the stack trace has changed a lot.

**Additional context**
Here are the offending rules:

```
ruleorder: concat_ngonorrhoeae1102_reference_genome > concat_reference_genome
rule concat_ngonorrhoeae1102_reference_genome:
    input:  files = lambda wildcards: [os.path.join(DOWNLOAD_DIR, "extracted", "ngonorrhoeae1102", NGONORRHOEAE_PANGENOME_FILENAMES[index]) for index in range(int(wildcards.included_count))],
    output: file = GENOME_ALL_REFERENCES,
    params: references = lambda wildcards, input: "'" + "' '".join(input.files) + "'",
    wildcard_constraints:
            genome = "ngonorrhoeae1102",
    shell:  "cat {params.references} > '{output.file}'"

rule concat_reference_genome:
    input:  files = lambda wildcards: [os.path.join(DOWNLOAD_DIR, "file", escape_dirname(get_genome_url(wildcards, "reference", index)), "file.fa") for index in range(int(wildcards.included_count))],
    output: file = GENOME_ALL_REFERENCES,
    params: references = lambda wildcards, input: "'" + "' '".join(input.files) + "'",
    shell:  "cat {params.references} > '{output.file}'"
```

**Comment by nathanhaigh** [comment]
I too am seeing this issue. However, it seems to occur intermittently - perhaps 50-75% of the time.

**Comment by johanneskoester** [comment]
Thanks a lot for reporting! Fixed in commit 6ebb86c3.

**Comment by lpla** [comment]
Upgraded to Snakemake 6.5.1 and now it is working fine. Thanks!

**Comment by sztankatt** [comment]
Hi. I also get this issue on `6.4.1` if I downgrade to `6.3.0` there is no error. Its a bit  annoying, as I would upgrade to `6.5.1` if I could, but due to this: #1166 I cant...
