### ISSUE TITLE
Command-line `--touch` option results in FileNotFoundError if a pipeline has outputs marked as 'temp'

### ISSUE THREAD

**Issue by iromeo** [snakemake/snakemake#1028]
**Snakemake version**
6.4.1

**Describe the bug**
Our computation server uses a weakly cleanup policy, so for me is important to `touch` all pipeline results each weak.
I use `--touch` snakemake feature, but it has a bug related to temporary files:

The command below fails if I have outputs marked as temporary: 
`snakemake --jobs 1 --touch --forceall`

**Logs**
```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       input
        1       intemediate
        3
Select jobs to execute...

[Sat Jun  5 22:53:44 2021]
rule input:
    output: tmp.txt
    jobid: 2

[Sat Jun  5 22:53:44 2021]
Finished job 2.
1 of 3 steps (33%) done
Select jobs to execute...
Traceback (most recent call last):
  File "/Users/romeo/opt/anaconda3/envs/smk3/lib/python3.9/site-packages/snakemake/__init__.py", line 701, in snakemake
    success = workflow.execute(
  File "/Users/romeo/opt/anaconda3/envs/smk3/lib/python3.9/site-packages/snakemake/workflow.py", line 1036, in execute
    success = scheduler.schedule()
  File "/Users/romeo/opt/anaconda3/envs/smk3/lib/python3.9/site-packages/snakemake/scheduler.py", line 470, in schedule
    run = self.job_selector(needrun)
  File "/Users/romeo/opt/anaconda3/envs/smk3/lib/python3.9/site-packages/snakemake/scheduler.py", line 660, in job_selector_ilp
    sum([size_gb(temp_file) for temp_file in temp_files]), 1
  File "/Users/romeo/opt/anaconda3/envs/smk3/lib/python3.9/site-packages/snakemake/scheduler.py", line 660, in <listcomp>
    sum([size_gb(temp_file) for temp_file in temp_files]), 1
  File "/Users/romeo/opt/anaconda3/envs/smk3/lib/python3.9/site-packages/snakemake/scheduler.py", line 635, in <lambda>
    size_gb = lambda f: f.size / 1e9
  File "/Users/romeo/opt/anaconda3/envs/smk3/lib/python3.9/site-packages/snakemake/io.py", line 242, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/romeo/opt/anaconda3/envs/smk3/lib/python3.9/site-packages/snakemake/io.py", line 257, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/romeo/opt/anaconda3/envs/smk3/lib/python3.9/site-packages/snakemake/io.py", line 560, in size
    return self.size_local
  File "/Users/romeo/opt/anaconda3/envs/smk3/lib/python3.9/site-packages/snakemake/io.py", line 565, in size_local
    self.check_broken_symlink()
  File "/Users/romeo/opt/anaconda3/envs/smk3/lib/python3.9/site-packages/snakemake/io.py", line 570, in check_broken_symlink
    if not self.exists_local and os.lstat(self.file):
FileNotFoundError: [Errno 2] No such file or directory: 'tmp.txt'
```
**Minimal example**
```
rule all:
    input: "out.txt"

rule input:
    output: temp("tmp.txt")
    run:
        with open(f"{output}", "w") as output:
            print("tmp", file=output)

rule intemediate:
    input: "tmp.txt"
    output: "out.txt"
    run:
        with open(f"{input}") as input:
          with open(f"{output}", "w") as output:
            print(*input.readlines(), file=output)
```

**Additional context**
My pull request is almost ready, will attach it a bit later.

**Comment by schnea** [comment]
Closing as corresponding PR has been merged
