### ISSUE TITLE
dag.update_checkpoint_dependencies(): KeyError

### ISSUE THREAD

**Issue by SilasK** [snakemake/snakemake#1036]
**Snakemake version**
Error on latest v6.4 
No error on snakemake 6.3

**Describe the bug**

There is a KeyError called by dag.update_checkpoint_dependencies()
The bug never appeared by previous versions only in v6.4

The error appears after the gathering rule: `combine_annotations` in a simple scatter-gather workflow with some internal steps. 

**Logs**
```
localrule combine_egg_nogg_annotations:
    input: Genecatalog/subsets/genes/subset1.emapper.annotations
    output: Genecatalog/annotations/eggNog.tsv.gz
    jobid: 1240
    resources: mem=60, time=5

localrules directive specifies rules that are not present in the Snakefile:
        verify_eggNOG_files

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/snakemake/__init__.py", line 785, in snakemake
    keepmetadata=keep_metadata,
  File "/home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/snakemake/workflow.py", line 731, in execute
    dag.update_checkpoint_dependencies()
  File "/home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/snakemake/dag.py", line 1312, in update_checkpoint_dependencies
    self.postprocess()
  File "/home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/snakemake/dag.py", line 1193, in postprocess
    self.cleanup()
  File "/home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/snakemake/dag.py", line 258, in cleanup
    del self.depending[dep][job]
KeyError: passtrough_se_merged
Shutting down, this might take some time.
```

**Minimal example**
The error is raised in a small part of a larger snakemake workflow. I try to make a MWE. 
The current code is rased here.

https://github.com/metagenome-atlas/atlas/blob/master/atlas/rules/genecatalog.smk#L581

**Additional context**
See https://github.com/metagenome-atlas/atlas/issues/398

**Comment by johanneskoester** [comment]
This should've been fixed in commit 6ebb86c3c1e21b9f4c37b6efd6b69c4538223738.
