### ISSUE TITLE
ERROR when using sample Group info error

### ISSUE THREAD

**Issue by DerekTerry** [snakemake/snakemake#1052]
**Snakemake version**
`5.25.0` 

**Describe the bug**
I am trying construct a rule by group `merge`-like operation . dry-run is ok, but `snakemake -p -j1` failed with this ERROR
`AttributeError: module 'pulp' has no attribute 'apis'` 

**Logs**
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        2       IDRPeakMerge
        1       all
        3
Traceback (most recent call last):
  File "/public4/home/sc30941/software/miniconda3/lib/python3.7/site-packages/snakemake/__init__.py", line 735, in snakemake
    keepincomplete=keep_incomplete,
  File "/public4/home/sc30941/software/miniconda3/lib/python3.7/site-packages/snakemake/workflow.py", line 972, in execute
    success = scheduler.schedule()
  File "/public4/home/sc30941/software/miniconda3/lib/python3.7/site-packages/snakemake/scheduler.py", line 406, in schedule
    else self.job_selector_ilp(needrun)
  File "/public4/home/sc30941/software/miniconda3/lib/python3.7/site-packages/snakemake/scheduler.py", line 616, in job_selector_ilp
    if pulp.apis.LpSolverDefault is None:
AttributeError: module 'pulp' has no attribute 'apis'
```

**Minimal example**
```
SAMPLES = {
    'group1':["SRR1552451","SRR1552453","ERR127302"],
    'group2':["ERR127302","SRR1552452"]
}

rule all:
    input:
        expand('idr/{group}.idr.peak',group=list(SAMPLES.keys()))

rule IDRPeakMerge:
    input:
        lambda wildcards: expand('macs2/{sample}.summits.bed', sample=SAMPLES[wildcards.group]) 
    output:
        'idr/{group}.idr.peak'
    run:
        shell("head -n 1 {input}  >> {output} ")
```

**Additional context**
file tree
```
s03peaks
├── idr
└── macs2
    ├── ERR127302.summits.bed
    ├── SRR1552451.summits.bed
    ├── SRR1552452.summits.bed
    └── SRR1552453.summits.bed
```

**Comment by johanneskoester** [comment]
Thanks for reporting! Can you please try with the latest Snakemake version?
