### ISSUE TITLE
Snakemake pipeline won't successfully run on cluster with `--cluster` 

### ISSUE THREAD

**Issue by xie186** [snakemake/snakemake#107]
Here is the file to reproduce the error:
[test_smk.tar.gz](https://github.com/snakemake/snakemake/files/3847043/test_smk.tar.gz)

**Snakemake version**
```
$ snakemake -v
5.7.4
```

**Describe the bug**

In the input folder, I have two input files. In the snakemake file, I have two rules. If I ran the pipeline without submitting the jobs to computing node on a cluster, the pipeline works fine. 

```
snakemake -s test.smk.py
```

Here is the log info:
```
['pear', 'apple']
Building DAG of jobs...
Using shell: /usr/local/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       mix_food
        2       prepare_food
        4

[Thu Nov 14 09:43:43 2019]
rule prepare_food:
    input: input/apple.txt
    output: output/prepare_food/apple_clean.txt
    jobid: 3
    wildcards: sample=apple

[Thu Nov 14 09:43:43 2019]
Finished job 3.
1 of 4 steps (25%) done

[Thu Nov 14 09:43:43 2019]
rule prepare_food:
    input: input/pear.txt
    output: output/prepare_food/pear_clean.txt
    jobid: 2
    wildcards: sample=pear

[Thu Nov 14 09:43:43 2019]
Finished job 2.
2 of 4 steps (50%) done

[Thu Nov 14 09:43:43 2019]
rule mix_food:
    input: output/prepare_food/pear_clean.txt, output/prepare_food/apple_clean.txt
    output: output/smoothie/smoothie.txt
    jobid: 1

[Thu Nov 14 09:43:43 2019]
Finished job 1.
3 of 4 steps (75%) done

[Thu Nov 14 09:43:43 2019]
localrule all:
    input: output/smoothie/smoothie.txt
    jobid: 0

[Thu Nov 14 09:43:43 2019]
Finished job 0.
4 of 4 steps (100%) done
Complete log: /depot/bioinfo/data/Projects/Shannahan/toxicity_RNAseq/results/test_snakemake/.snakemake/log/2019-11-14T094343.308705.snakemake.log

```

But if I used `--cluster`, I will encounter an error:  
```
 snakemake -s test.smk.py  --cluster-config cluster.json  --cluster "qsub -V -q {cluster.queue} -l nodes=1:ppn={cluster.n} -l naccesspolicy=singleuser -l walltime={cluster.time} -N {cluster.name} -o {cluster.output} -e {cluster.error}" --jobs 1
```

Here is the error message:

```
['pear', 'apple']
Building DAG of jobs...
Using shell: /usr/local/bin/bash
Provided cluster nodes: 1
Job counts:
        count   jobs
        1       all
        1       mix_food
        2       prepare_food
        4

[Thu Nov 14 09:41:20 2019]
rule prepare_food:
    input: input/apple.txt
    output: output/prepare_food/apple_clean.txt
    jobid: 3
    wildcards: sample=apple

Submitted job 3 with external jobid '4388407.snyder-adm.rcac.purdue.edu'.
[Thu Nov 14 09:42:00 2019]
Finished job 3.
1 of 4 steps (25%) done

[Thu Nov 14 09:42:00 2019]
rule prepare_food:
    input: input/pear.txt
    output: output/prepare_food/pear_clean.txt
    jobid: 2
    wildcards: sample=pear

Submitted job 2 with external jobid '4388408.snyder-adm.rcac.purdue.edu'.
[Thu Nov 14 09:43:00 2019]
Finished job 2.
2 of 4 steps (50%) done

[Thu Nov 14 09:43:00 2019]
rule mix_food:
    input: output/prepare_food/pear_clean.txt, output/prepare_food/apple_clean.txt
    output: output/smoothie/smoothie.txt
    jobid: 1

Traceback (most recent call last):
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/site-packages/snakemake/__init__.py", line 618, in snakemake
    batch=batch,
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/site-packages/snakemake/workflow.py", line 779, in execute
    success = scheduler.schedule()
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/site-packages/snakemake/scheduler.py", line 365, in schedule
    self.run(job)
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/site-packages/snakemake/scheduler.py", line 384, in run
    error_callback=self._error,
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/site-packages/snakemake/executors.py", line 776, in run
    jobscript = self.get_jobscript(job)
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/site-packages/snakemake/executors.py", line 592, in get_jobscript
    f = job.format_wildcards(self.jobname, cluster=self.cluster_wildcards(job))
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/site-packages/snakemake/executors.py", line 664, in cluster_wildcards
    return Wildcards(fromdict=self.cluster_params(job))
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/site-packages/snakemake/executors.py", line 645, in cluster_params
    cluster[key] = job.format_wildcards(value)
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/site-packages/snakemake/jobs.py", line 812, in format_wildcards
    return format(string, **_variables)
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/site-packages/snakemake/utils.py", line 403, in format
    return fmt.format(_pattern, *args, **variables)
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/string.py", line 190, in format
    return self.vformat(format_string, args, kwargs)
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/string.py", line 194, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/string.py", line 234, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/depot/bioinf/Personal_Directories/xie186/miniconda3/envs/test_candel/lib/python3.6/string.py", line 305, in get_field
    obj = getattr(obj, i)
AttributeError: 'Wildcards' object has no attribute 'sample'

```

Could you please help me on this? Thanks.

**Comment by troycomi** [comment]
The issue is in your cluster.json file.  A clue to the cause is that the error is raised while producing the jobscript.  Since you haven't specified the name, output, error for the rule mix_food it uses the default, which depends on the sample wildcard (which doesn't exist for that rule as the output is fully specified).  Try adding something like this to your cluster.json:
```
    "mix_food": {
        "name": "{rule}",
        "output": "{rule}.out",
        "error": "{rule}.err"
    }
```
Any non-specified values will use the default.  I'm not sure which scheduler you are using, but consider also adding the job id number to output and error so they don't get overwritten.

**Comment by xie186** [comment]
I see. Thank you so much for you quick response.
