### ISSUE TITLE
--summary broken in 6.x?

### ISSUE THREAD

**Issue by dariober** [snakemake/snakemake#1101]
Using snakemake 6.6.0, the --summary option gives me:

```
snakemake --printshellcmds --jobs 10     --config ss=$PWD/sample_sheet.tsv              dge_dir=$PWD/set6_dge     --directory /export/projects/III-data/waters/db291g/projects/20190704_sebastian_set6   --summary

Building DAG of jobs...
Traceback (most recent call last):
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20190704_sebastian_set6/lib/python3.6/site-packages/snakemake/__init__.py", line 783, in snakemake
    keepmetadata=keep_metadata,
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20190704_sebastian_set6/lib/python3.6/site-packages/snakemake/workflow.py", line 886, in execute
    print("\n".join(dag.summary(detailed=False)))
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20190704_sebastian_set6/lib/python3.6/site-packages/snakemake/dag.py", line 1974, in summary
    elif self.workflow.persistence.params_changed(job, file=f):
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20190704_sebastian_set6/lib/python3.6/site-packages/snakemake/persistence.py", line 339, in params_changed
    return _bool_or_gen(self._params_changed, job, file=file)
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20190704_sebastian_set6/lib/python3.6/site-packages/snakemake/persistence.py", line 470, in _bool_or_gen
    return func(job, file=file)
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20190704_sebastian_set6/lib/python3.6/site-packages/snakemake/persistence.py", line 355, in _params_changed
    return self.params(file) != self._params(job)
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20190704_sebastian_set6/lib/python3.6/site-packages/snakemake/persistence.py", line 383, in _params
    return sorted(map(repr, job.params))
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20190704_sebastian_set6/lib/python3.6/site-packages/snakemake/jobs.py", line 262, in params
    self.wildcards_dict, self.input, self.output, self.resources
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20190704_sebastian_set6/lib/python3.6/site-packages/snakemake/jobs.py", line 307, in resources
    self.wildcards_dict, self.input, self.attempt
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20190704_sebastian_set6/lib/python3.6/site-packages/snakemake/rules.py", line 1027, in expand_resources
    resources[name] = apply(name, res, threads=threads)
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20190704_sebastian_set6/lib/python3.6/site-packages/snakemake/rules.py", line 1017, in apply
    res = min(global_res, res)
TypeError: '<' not supported between instances of 'int' and 'str'
```

The workflow is otherwise fine:

```
snakemake --printshellcmds --jobs 10     --config ss=$PWD/sample_sheet.tsv              dge_dir=$PWD/set6_dge     --directory /export/projects/III-data/waters/db291g/projects/20190704_sebastian_set6  -n
Building DAG of jobs...
Nothing to be done.
```

and using snakemake 5.32.0 I do get the summary report.

The pipeline is quite complex so I haven't managed to isolate the what causes the problem.

**Comment by jhrcook** [comment]
I had a similar issue and clearing the `.snakemake` directory for the pipeline fixed it. There may be a CLI option to clear the cache that would perhaps be a better first try, too.

**Comment by dariober** [comment]
@jhrcook thanks - removing `.snakemake` seems to work. 

Also, the error does not happen if I use snakemake 6.4.1 (I don't know about versions between >6.4.1 and <6.6.0) so the bug is in a fairly recent change. I'll close the issue in a few days if there is no activity about it.

**Comment by rbpatt2019** [comment]
I am getting a similar issue with `snakemake --report`. Exactly the same bug for all snakemake versions >=6.5. Iterestingly, at least with `snakemake --report` deleting the `.snakemake` directory did *not* solve the issue. Seems related, but different enough that I opened a new issue at #1109.

**Comment by schnea** [comment]
Closing as stale as we are at version 9.x now
