### ISSUE TITLE
Snakemake API throws RuntimeError related to asyncio when used within Jupyter

### ISSUE THREAD

**Issue by ashwinvis** [snakemake/snakemake#1105]
**Snakemake version** 6.6.1

**Describe the bug** Asyncio related. I believe it is because both Jupyter's kernel and snakemake uses an asyncio loop.

**Logs**

```
Building DAG of jobs...
Traceback (most recent call last):
  File "/tmp/test/venv/lib/python3.9/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/tmp/test/venv/lib/python3.9/site-packages/snakemake/workflow.py", line 750, in execute
    dag.init()
  File "/tmp/test/venv/lib/python3.9/site-packages/snakemake/dag.py", line 195, in init
    self.update_needrun(create_inventory=True)
  File "/tmp/test/venv/lib/python3.9/site-packages/snakemake/dag.py", line 916, in update_needrun
    self.workflow.iocache.mtime_inventory(self.jobs)
  File "/tmp/test/venv/lib/python3.9/site-packages/snakemake/io.py", line 136, in mtime_inventory
    async_run(self._mtime_inventory(jobs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 33, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
```

**Minimal example**

```py
import os

rule a:
        resources:
                nproc=os.cpu_count()
        shell:
                "echo {resources.nproc}"
```

Run the following  in a Jupyter notebook

```py
from snakemake import snakemake

snakemake('Snakefile', targets=['a'])
```

**Additional context**
```
ipykernel           6.0.3
ipython             7.25.0
notebook            6.4.0
```

```
❯ python --version                                                                                                                                                                     
Python 3.9.6
```

I tried the same in the simple Python console and the IPython console. There does not seem to be an issue.

I develop a package called snek5000 which relies on the snek5000 API.

**Comment by ashwinvis** [comment]
Related: https://stackoverflow.com/questions/55409641/asyncio-run-cannot-be-called-from-a-running-event-loop

**Comment by ashwinvis** [comment]
This seems to be a well known problem. Which was does not exist IPython but is unavoidable in Jupyter (?)

## In IPython

```py
In [1]: import asyncio

In [2]: asyncio.get_running_loop()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-8edbd6ad7d71> in <module>
----> 1 asyncio.get_running_loop()

RuntimeError: no running event loop
```

## In `jupyter console` or `notebook` or `lab`

```py
n [1]: import asyncio

In [2]: asyncio.get_running_loop()
Out[2]: <_UnixSelectorEventLoop running=True closed=False debug=False>
```

See also: https://github.com/jupyter/notebook/issues/3397

Would it be possible to reuse the running asyncio loop, if it is already running?
