### ISSUE TITLE
snakemake --report broken in snakemake >=6.5

### ISSUE THREAD

**Issue by rbpatt2019** [snakemake/snakemake#1109]
**Snakemake version**
\>=6.5, including most recent release 6.6.1

**Describe the bug**
After a successful run of a snakemake workflow, attempts to run `snakemake --report` fail with the error:

```shell
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Logs**
<details>
  <summary>Full Traceback</summary>
  
```shell
Building DAG of jobs...
Creating report...
Adding multiqc.html (1.2 MB).
Traceback (most recent call last):
  File "/home/rbp33/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/home/rbp33/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 871, in execute
    auto_report(dag, report, stylesheet=report_stylesheet)
  File "/home/rbp33/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/report/__init__.py", line 668, in auto_report
    register_file(f)
  File "/home/rbp33/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/report/__init__.py", line 652, in register_file
    FileRecord(
  File "/home/rbp33/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/report/__init__.py", line 408, in __init__
    logging.format_dict(job.params).replace("\n", r"\n").replace('"', r"\"")
  File "/home/rbp33/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/jobs.py", line 262, in params
    self.wildcards_dict, self.input, self.output, self.resources
  File "/home/rbp33/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/jobs.py", line 306, in resources
    self._resources = self.rule.expand_resources(
  File "/home/rbp33/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/rules.py", line 1027, in expand_resources
    resources[name] = apply(name, res, threads=threads)
  File "/home/rbp33/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/rules.py", line 1017, in apply
    res = min(global_res, res)
TypeError: '<' not supported between instances of 'int' and 'str'
```
</details>

**Minimal example**
As far as I can tell, simply issuing `snakemake --report` after a run triggers the issue.

**Additional context**
This seems to be related to #1101. As there, the last release I can confirm works with the expected behaviour is `6.4.1`.

I have tried deleting the `.snakemake` directory, but the problem persists with or without this folder. Additionally, I can also confirm that this occurs on both MacOS and Linux (RHEL I think, on my University's cluster), so it is likely not OS dependent. 

Thanks for all your work and the excellent tool!

**Comment by SultanOrazbayev** [comment]
A more silent indication of a bug is in handling of code blocks. Consider the Snakefile below:

```python
rule all:
    input: 'test.txt', 'test123.txt'

rule a:
    output: 'test.txt',
    run:
        with open(output[0], 'w') as f:
            f.write('testing123!')

rule b:
    output: touch('test123.txt'),
    script: 'test.py'
```

And contents of 'test.py':

```python
print('Hello!')
```

[Archive.zip](https://github.com/snakemake/snakemake/files/7920356/Archive.zip)

After executing this workflow and running `--report` on version 6.4.1 I get the report that include code contents of `test.py` (see file `report1.html` in the attached zip). Running `--report` on version 6.13.1, I get the report without the code contents (this block is missing in the rule information), see attached file `report2.html` inside zip. Apologies for zipping, but GitHub doesn't allow attaching .html files.

**Comment by cpauvert** [comment]
I am having the same problem in `v6.14.0` as well as after the lastest update to `v6.15.5`. The code is not displayed as well when a snakemake-wrapper is used.

**Comment by schnea** [comment]
Closing as per comment above
