### ISSUE TITLE
Error when using conda 4.10.3 with snakemake 6.6.1

### ISSUE THREAD

**Issue by RipollJ** [snakemake/snakemake#1120]
Hello, 

**Snakemake version**
Snakemake: 6.6.1
Conda: 4.10.3
Python: 3.7.10

**Describe the bug**
After updating snakemake and conda to cited version, I have the following error when I use `--use-conda` option to create an environment from a yaml file.

Command used: `snakemake -p -d ./ -s workflow/snakemake.smk --use-conda -j 1`

**Logs**
```
Building DAG of jobs...
environment: ligne 10: __conda_exe : commande introuvable
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/home/user/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/workflow.py", line 933, in execute
    dag.create_conda_envs(
  File "/home/user/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/dag.py", line 304, in create_conda_envs
    env.create(dryrun)
  File "/home/user/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 281, in create
    conda = Conda(self._container_img)
  File "/home/user/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 433, in __init__
    shell.check_output(self._get_cmd("conda info --json"))
  File "/home/user/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/shell.py", line 63, in check_output
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)
  File "/home/user/miniconda3/envs/snake/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/user/miniconda3/envs/snake/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'conda info --json' returned non-zero exit status 127.
```

**Minimal example**
Command used: `snakemake -p -d ./ -s workflow/snakemake.smk --use-conda -j 1`

**Additional context**
The command `conda info --json` prints a json which looks correct.

I tested on a new conda env with a new installation of snakemake 6.6.1 and the error is still the same.

Using `--dry-run` does not return any error and works without problems.

Any idea on how to solve it?

Best regards

**Comment by adefelicibus** [comment]
Hi,

I'm facing a similar error:

#### Snakemake version

Snakemake: 6.7.0
Conda: 4.10.3
Python: 3.9.6

#### Error:
```
Traceback (most recent call last):
  File "/conda/lib/python3.9/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/conda/lib/python3.9/site-packages/snakemake/workflow.py", line 933, in execute
    dag.create_conda_envs(
  File "/conda/lib/python3.9/site-packages/snakemake/dag.py", line 304, in create_conda_envs
    env.create(dryrun)
  File "/conda/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 281, in create
    conda = Conda(self._container_img)
  File "/conda/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 439, in __init__
    self._check()
  File "/conda/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 505, in _check
    if StrictVersion(version) < StrictVersion("4.2"):
  File "/conda/lib/python3.9/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/conda/lib/python3.9/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number 'warning:'
```

Best,
