### ISSUE TITLE
Linter fails module is imported from github

### ISSUE THREAD

**Issue by marrip** [snakemake/snakemake#1130]
**Version**
6.5.3

**Describe the bug**
When I try to lint my workflow, which contains a remote module import (from github), the lint fails even though I can run the workflow. As far as I can tell from the release notes, the bug has not been fixed yet.

**Logs**
My code:

```
module wgs_std_viper:
    snakefile: "https://github.com/marrip/wgs_std_viper/raw/develop/Snakefile"
    config: config

use rule * from wgs_std_viper as wgs_std_*
```

And the output of the linter:

```
Traceback (most recent call last):
  File "/home/vagrant/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 598, in snakemake
    success = not workflow.lint(json=lint == "json")
  File "/home/vagrant/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 282, in lint
    json_snakefile_lints, snakefile_linted = SnakefileLinter(
  File "/home/vagrant/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/linting/__init__.py", line 23, in lint
    item_lints = [
  File "/home/vagrant/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/linting/__init__.py", line 26, in <listcomp>
    for lint in lint_item(self.read_item(item))
  File "/home/vagrant/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/linting/snakefiles.py", line 18, in read_item
    return open(snakefile).read()
FileNotFoundError: [Errno 2] No such file or directory: 'https://github.com/marrip/wgs_std_viper/raw/develop/Snakefile'
```

**Comment by johanneskoester** [comment]
Thanks for reporting! Should be fixed with PR #1131.
