### ISSUE TITLE
--shadow-prefix does not work, logs, locks and others still written to .snakemake

### ISSUE THREAD

**Issue by amcpherson** [snakemake/snakemake#1187]
**Snakemake version**
```
$snakemake --version
6.8.0
```

**Describe the bug**
When using the --shadow-prefix option to a directory other than .snakemake, the log file, locks and possibly others are still written to the .snakemake directory.

**Logs**
```
Traceback (most recent call last):
  File "/home/mcphersa1/miniconda3/envs/snakemake/bin/snakemake", line 10, in <module>
    sys.exit(main())
  File "/home/mcphersa1/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 2741, in main
    success = snakemake(
  File "/home/mcphersa1/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 518, in snakemake
    logger.setup_logfile()
  File "/home/mcphersa1/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/logging.py", line 308, in setup_logfile
    os.makedirs(os.path.join(".snakemake", "log"), exist_ok=True)
  File "/home/mcphersa1/miniconda3/envs/snakemake/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '.snakemake/log'
```

**Minimal example**
Assuming any pipeline in a Snakefile:
```
touch .snakemake # writing to .snakemake/log will fail
mkdir shadowprefix
snakemake --shadow-prefix shadowprefix/ ...
```

**Additional context**
NA

**Comment by tkchouaki** [comment]
Hello, 
The --shadow-prefix doesn't seem to work in version 9.14.5.
I am still getting a .snakemake with the usual content wheras a directory is created as specified in the --shadow-prefix argument but it just contains an empy shadow folder.
