### ISSUE TITLE
snakemake does not find mamba or conda

### ISSUE THREAD

**Issue by slambrechts** [snakemake/snakemake#1204]
When I run` snakemake --use-conda -k -j 8` I get:

`Error: mamba package manager is not available. .....
`
and when I run

`snakemake --use-conda -k -j 8 --conda-frontend conda`
I get:

```
CreateCondaEnvironmentException:
The 'conda' command is not available in the shell /usr/bin/bash that will be used by Snakemake. You have to ensure that it is in your PATH, e.g., first activating the conda base environment with `conda activate base`.
outside of snakemake, mamba and conda work just fine, so they are definitely available. Snakemake for some reason does not find them?
```

**Comment by aryarm** [comment]
What shell are you using? When you run `echo $0`, does it say `/usr/bin/bash`?

**Comment by slambrechts** [comment]
When I run `echo $0` outside of Snakemake I get

`-bash`

conda and mamba are available in that shell, but I'm not sure how I can find out whether they are available in `/usr/bin/bash`, or how I can install them in that shell instead of the main shell, or how I can make sure they are also available in `/usr/bin/bash`?

**Comment by aryarm** [comment]
hmm, I'm not sure then...
You could maybe try this:
1. Run and enter the bash shell at `\usr\bin\bash`:
    ```
    \usr\bin\bash
    ```
2. Check if `conda` is in your `$PATH`:
    ```
    which conda
    ```
    and/or
    ```
    echo "$PATH"
    ```
    The latter should show something like `miniconda3/bin` or `anaconda3/bin` among the list

**Comment by dlaehnemann** [comment]
I think this issue is similar to issue #1009 , even though the original post there was about cluster jobs and I understand this issue here to be about usage on a regular machine, right? Just wanted to cross-reference, so that these issues are aware of each other...

**Comment by alyenkin** [comment]
I had a similar issue, that seemed to be related to [this mamba issue](https://github.com/mamba-org/mamba/issues/2335). It seems to work ok if I run deactivate to the base environment and then just run writing out the full path to the snakemake command
```shell
~/mambaforge-pypy3/envs/snakemake/bin/snakemake ...
```

**Comment by mkiyer** [comment]
I am having the same issue. I have installed the latest miniforge3 and snakemake 8.0.1.

Running $ snakemake --slurm --jobs 100 --use-conda produces a similar error:

Building DAG of jobs...
/usr/bin/bash: conda: command not found
Traceback (most recent call last):
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/cli.py", line 1970, in args_to_api
    dag_api.execute_workflow(
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/api.py", line 564, in execute_workflow
    workflow.execute(
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/workflow.py", line 1093, in execute
    self.dag.create_conda_envs()
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/dag.py", line 405, in create_conda_envs
    env.create(self.workflow.dryrun)
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 393, in create
    pin_file = self.pin_file
               ^^^^^^^^^^^^^
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake_interface_common/utils.py", line 30, in __get__
    value = self.method(instance)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 103, in pin_file
    f".{self.conda.platform}.pin.txt"
        ^^^^^^^^^^
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake_interface_common/utils.py", line 30, in __get__
    value = self.method(instance)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 96, in conda
    return Conda(
           ^^^^^^
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 653, in __init__
    shell.check_output(self._get_cmd("conda info --json"), text=True)
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/shell.py", line 61, in check_output
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'conda info --json' returned non-zero exit status 127.

**Comment by dlaehnemann** [comment]
Have you double-checked your conda installation as suggested above:
https://github.com/snakemake/snakemake/issues/1204#issuecomment-933732315

**Comment by SamueleSoraggi** [comment]
I also had that problem, but in the end found out the solution @alyenkin also proposes was a good workaround.
