### ISSUE TITLE
Possible regression bugs from 6.8.0 to 6.9.X

### ISSUE THREAD

**Issue by cokelaer** [snakemake/snakemake#1212]
**Snakemake version**: 6.9.0 and 6.9.1

**Describe the bug**

1. Running/Executing pipelines with the --wrapper-prefix and a local git repository works in 6.8.0 but not in 6.9.0 or 6.9.1
    Note this wrapper repository is not the snakemake wrapper but a local repository.
2. If the input is a function, the code does not seem to work either (same versions)

**Logs**

    Traceback (most recent call last):
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 593, in _callback
        raise ex
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 579, in cached_or_run
        run_func(*args)
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2460, in  run_wrapper 
        raise ex
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2441, in run_wrapper
        runtime_sourcecache_path,
      File "/home/cokelaer/Work/github/sequana_pipelines/fastqc/test/data/fastqc/fastqc.rules", line 219, in __rule_rulegraph
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/snakemake/wrapper.py", line 140, in wrapper
        runtime_sourcecache_path,
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/snakemake/script.py", line 1329, in script
         path, SourceCache(runtime_sourcecache_path), basedir, wildcards, params
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/snakemake/script.py", line 1249, in get_source
        path = infer_source_file(format(path, wildcards=wildcards, params=params))
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/snakemake/utils.py", line 430, in format
        return fmt.format(_pattern, *args, **variables)
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/string.py", line 186, in format
        return self.vformat(format_string, args, kwargs)
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/string.py", line 190, in vformat
        result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/string.py", line 200, in _vformat
        self.parse(format_string):
      File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/string.py", line 284, in parse
        return _string.formatter_parser(format_string)
    TypeError: expected str, got NoneType
 

**Minimal example**
This pipeline  https://github.com/sequana/fastqc/sequana_pipelines/fastqc.rules used to work a week ago with version 6.1 and works right now with 6.8.0. You'll need input data so a bit tricky but I believe this is a general issue.

**Additional context**

**Comment by qifei9** [comment]
Is this fixed in recent releases?

**Comment by hermidalc** [comment]
I'm still seeing the problem in 7.8.5

**Comment by johanneskoester** [comment]
Hi, sorry for missing this. Can you provide a minimal test case via a pull request? Also, please ping me on this via discord in case I miss the PR (I get a lot of github notifications, to many to parse them all).

**Comment by corneliusroemer** [comment]
I don't have the time to make a minimal test case right now, maybe you could add an `help need` label so that someone can create this? It shouldn't be too hard with all of pangolin being open source so one can go back and create minimal test case.

**Comment by johanneskoester** [comment]
@cokelaer could you create a minimal example?

**Comment by cokelaer** [comment]
@johanneskoester 

looks like it works with version 7.12.0 and 7.18.0 so I believe we can close the issue. Nevertheless, here is a simple example in case it is usefule for you. 


    samples = {'data': 'data.fastq'}
    def getrawdata():
        return lambda wildcards: samples[wildcards.sample]

    rule pipeline:
        input: expand("samples/{sample}/fastqc.log", sample=samples)

    rule fastqc:
        input: getrawdata()
        output: "samples/{sample}/fastqc.done"
        log:
            "samples/{sample}/fastqc.log"
        threads:
            4
        params:
            options="",
            working_directory="samples/{sample}"
        wrapper:
            "main/wrappers/fastqc"

    onsuccess:
        print('awesome')

You will need just one input file to be saved in a filename called **data.fastq**:

```
@HISEQ:426:C5T65ACXX:5:2301:5633:7203 1:N:0:GTGAAA
TTGCTTAATTCTATACTCATCCTCTACAGGGAGTTGGCAAGATTCAAAGACAACCAAAGAAGTCAACAAGGGATGTTCCACGCTTACCCCGTATTGGTAAG
+
CCCFFFFFHHHHHJJJIIHIHIJJJJJJJJI@HEHIJJJJIIJJJJIAHIIJIIJJIJIIJJIIHGIIIIDHHEHEDDFEFDDDDDDDDDD@BBDDDCDDD
@HISEQ:426:C5T65ACXX:5:2301:5815:7120 1:N:0:GTGAAA
TATCTGCGATTGGTTCCATCTTCCCGGGTGACTGTGCAGCTGACTCCCATGCCCACCATCCCAGAGTGAGTGATATGTCCACCAGATTCTGAGTCCGCAAG
+
CCCFFFFFFHHHGHGGHIIJIIIJIJJIDFHIJIIHHIIIIJJIJJJIHCHIJIIJJJJJHHHHFF;@BB6>ADDCECDDCC@DDDDDDDDED>C@BDDDD
```

That works with v6.8.0 using this command

    snakemake  --wrapper-prefix git+file:///home/cokelaer/Work/github/forked/sequana-wrappers 

You will need to install fastqc (e.g. from bioconda) and no other dependencies.
