### ISSUE TITLE
problem in using a snakefile as module

### ISSUE THREAD

**Issue by LeilyR** [snakemake/snakemake#1237]
Hi, 
I am trying this :

```
module mrna_workflow:
    snakefile: 'https://github.com/maxplanck-ie/snakepipes/blob/1.2.3/snakePipes/workflows/RNA-seq/Snakefile'

use rule * from mrna_workflow as mrna_*

```
on top of my snakefile but I get the indentation error, Could you please tell how I can fix that:
```

IndentationError in line 148 of <tokenize>:
unindent does not match any outer indentation level (<tokenize>, line 148)


```

**Comment by Smeds** [comment]
Have you tried changing blob to raw

'https://github.com/maxplanck-ie/snakepipes/raw/1.2.3/snakePipes/workflows/RNA-seq/Snakefile'

or using  github function to generate a path

github("maxplanck-ie/snakepipes, path="snakePipes/workflows/RNA-seq/Snakefile", tag="1.2.3")

**Comment by LeilyR** [comment]
thanks a lot! I have tried using raw, indeed I do not get the indent error, but it does not recognize the variables which used in the snakefile, even though I provided a yaml file as a config with variables being available there. 
I have also tried github but it fails `name 'github' is not defined`

**Comment by Smeds** [comment]
Have you tried:

snakefile: 'https://raw.githubusercontent.com/maxplanck-ie/snakepipes/master/snakePipes/workflows/mRNA-seq/Snakefile'

**Comment by LeilyR** [comment]
yes, so what i am basically doing now is: 
```
module mrna_workflow:
    snakefile: "https://raw.githubusercontent.com/maxplanck-ie/snakepipes/master/snakePipes/shared/rules/GenomicContamination.snakefile"
    config: '/path/to/test.config.yaml'

use rule * from mrna_workflow as mrna_*
```
 inside the test.conig.yaml:
 
 ```
aligner: STAR
```

run snakemake:

```
$ snakemake -j 2
```
error:
```
Traceback (most recent call last):
  File "/data/processing3/leily/miniconda3/envs/ttseq/lib/python3.7/site-packages/snakemake/__init__.py", line 594, in snakemake
    snakefile, overwrite_first_rule=True, print_compilation=print_compilation
  File "/data/processing3/leily/miniconda3/envs/ttseq/lib/python3.7/site-packages/snakemake/workflow.py", line 1182, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/data/processing1/leily/RNA-pipelines/Snakefile", line 43, in <module>
  File "/data/processing3/leily/miniconda3/envs/ttseq/lib/python3.7/site-packages/snakemake/workflow.py", line 1797, in decorate
    ruleinfo=None if callable(maybe_ruleinfo) else maybe_ruleinfo,
  File "/data/processing3/leily/miniconda3/envs/ttseq/lib/python3.7/site-packages/snakemake/modules.py", line 65, in use_rules
    self.workflow.include(snakefile, overwrite_first_rule=True)
  File "/data/processing3/leily/miniconda3/envs/ttseq/lib/python3.7/site-packages/snakemake/workflow.py", line 1182, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "https://raw.githubusercontent.com/maxplanck-ie/snakepipes/master/snakePipes/shared/rules/GenomicContamination.snakefile", line 7, in <module>
    import os
NameError: name 'aligner' is not defined
```
snakemake version:
```
$ snakemake -v
6.10.0
```

**Comment by Smeds** [comment]
don't you have to create a variable called aligner and assign it the value from the config file or extract if from the config dict config['aligner'] in the rule?

**Comment by LeilyR** [comment]
I agree, I was hoping for something like that too, however `aligner` is not used as a param or an input in the rule, here is the link to the rule:
https://github.com/maxplanck-ie/snakepipes/blob/master/snakePipes/shared/rules/GenomicContamination.snakefile#L4
I was also trying to make a global variable before using the rule but that also does not work. 
so an example of what I have is this: 
```
aligner = config['aligner']
use rule GContamination_featureCounts from mrna_workflow as mrna_GContamination_featureCounts with:
    input:
        bams = "test1",
        gtf = "test2"
    output:
        txt = "out1",
        summary = "out2"
```
which does not work

**Comment by Smeds** [comment]
I have just started to play around with modules and had problems with global variables. I was trying to use the config dict in my module and got some errors

```
configfile: "config.yaml"

 module alignment:
    snakefile: github("hydra-genetics/alignment", path="workflow/Snakefile", tag="develop")
```

resulted in that the module couldn't find the cofig dict

```
configfile: "config.yaml"

 module alignment:
    snakefile: github("hydra-genetics/alignment", path="workflow/Snakefile", tag="develop")
    config: "path/to/config.yaml"
```

now my module found a config variable, but it was a string

the working solution for me was

```
configfile: "config.yaml"

 module alignment:
    snakefile: github("hydra-genetics/alignment", path="workflow/Snakefile", tag="develop")
    config: config
```

now I could access the config dict in my module.

**Comment by LeilyR** [comment]
Hey Patrik, Thanks a lot! although, unfortunately my issue is still there, the thing is that it fails to detect `aligner` from the config file even before using a certain rule, even if I just call: 
```
configfile: '/data/processing1/leily/RNA-pipelines/test.config.yaml'
module mrna_workflow:
    snakefile: "https://raw.githubusercontent.com/maxplanck-ie/snakepipes/master/snakePipes/shared/rules/GenomicContamination.snakefile"
    config: config

use rule * from mrna_workflow as mrna_*
```
The error points to the following directions, do they mean anything to you?

```
Traceback (most recent call last):
  File "/data/processing3/leily/miniconda3/envs/ttseq/lib/python3.7/site-packages/snakemake/__init__.py", line 594, in snakemake
    snakefile, overwrite_first_rule=True, print_compilation=print_compilation
  File "/data/processing3/leily/miniconda3/envs/ttseq/lib/python3.7/site-packages/snakemake/workflow.py", line 1182, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/data/processing1/leily/RNA-pipelines/Snakefile", line 50, in <module>
  File "/data/processing3/leily/miniconda3/envs/ttseq/lib/python3.7/site-packages/snakemake/workflow.py", line 1797, in decorate
    ruleinfo=None if callable(maybe_ruleinfo) else maybe_ruleinfo,
  File "/data/processing3/leily/miniconda3/envs/ttseq/lib/python3.7/site-packages/snakemake/modules.py", line 65, in use_rules
    self.workflow.include(snakefile, overwrite_first_rule=True)
  File "/data/processing3/leily/miniconda3/envs/ttseq/lib/python3.7/site-packages/snakemake/workflow.py", line 1182, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "https://raw.githubusercontent.com/maxplanck-ie/snakepipes/master/snakePipes/shared/rules/GenomicContamination.snakefile", line 7, in <module>
    import os
NameError: name 'aligner' is not defined

```

could it be that it cannot handle the variable structure in my "other" snakefile? 
Here is the link to that:
https://github.com/maxplanck-ie/snakepipes/blob/master/snakePipes/shared/rules/GenomicContamination.snakefile#L4

**Comment by Smeds** [comment]
Have you tried to modify GenomicContamination.snakefile  

´´´
        bams = aligner + "/{sample}.bam",
´´´

to

´´´
        bams = config['aligner'] + "/{sample}.bam",
´´´

**Comment by LeilyR** [comment]
Hey Patrik, yes that would do the trick. Thanks!
So as stands, I may not be able to use `module`, since it needs a lot of changes in the `other` workflow. I am already using subworkflow but since it is depreciated, I was hoping to be able to use the `module`.  Do you maybe have any recommendation there?

**Comment by Hocnonsense** [comment]
variable defined outside `module` cannot be injected into it, it is a designed feature. You can write an "intermediate" snakefile to extract these vars from config, include "other.snakefile" and module: snakefile: "intermediate"
