### ISSUE TITLE
GLS executor fails when requesting GPUs

### ISSUE THREAD

**Issue by JackyHess** [snakemake/snakemake#1245]
**Snakemake version**

Snakemake 6.10.0

**Describe the bug**

I am trying to request GPUs when running Snakemake using the GLS executor, and I'm running into the following error:

```Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/opt/conda/lib/python3.9/site-packages/snakemake/workflow.py", line 1069, in execute
    success = self.scheduler.schedule()
  File "/opt/conda/lib/python3.9/site-packages/snakemake/scheduler.py", line 516, in schedule
    self.run(runjobs)
  File "/opt/conda/lib/python3.9/site-packages/snakemake/scheduler.py", line 563, in run
    executor.run_jobs(
  File "/opt/conda/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 149, in run_jobs
    self.run(
  File "/opt/conda/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 812, in run
    pipeline = self._generate_pipeline(job)
  File "/opt/conda/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 784, in _generate_pipeline
    resources = self._generate_job_resources(job)
  File "/opt/conda/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 435, in _generate_job_resources
    self._add_gpu(gpu_count)
  File "/opt/conda/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 371, in _add_gpu
    self._machine_type_prefix = self._machine_type_prefix or ""
AttributeError: 'GoogleLifeSciencesExecutor' object has no attribute '_machine_type_prefix'
```

The command line I executed with is this:

`snakemake --google-lifesciences --default-remote-prefix gpu_test --use-conda --google-lifesciences-region europe-west1 -j 1`

The job runs fine if I remove the GPU requirement from the Snakefile. 

I have tried explicitly adding machine type both to the resources statement and via the command line, e.g.  via ` --default-resources "machine_type=n1"` which gets integrated into the workflow (see log below), but still throws the same error.

**Log**

````
Building DAG of jobs...
Unable to retrieve additional files from git. This is not a git repository.
Using shell: /usr/bin/bash
Provided cloud nodes: 1
Job stats:
job          count    min threads    max threads
---------  -------  -------------  -------------
all              1              1              1
test_GPU         1              1              1
test_GPU2        1              1              1
total            3              1              1

Select jobs to execute...

[Mon Nov  1 16:47:31 2021]
rule test_GPU:
    output: ont_sequencing/file.txt
    jobid: 2
    resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp, machine_type=n1

Get status with:
gcloud config set project ext-fgen-0921
gcloud beta lifesciences operations describe projects/ext-fgen-0921/locations/europe-west2/operations/9333936305055773042
gcloud beta lifesciences operations list
Logs will be saved to: ont_sequencing/ont_sequencing/google-lifesciences-logs

[Mon Nov  1 16:49:32 2021]
Finished job 2.
1 of 3 steps (33%) done
Select jobs to execute...

[Mon Nov  1 16:49:33 2021]
rule test_GPU2:
    input: ont_sequencing/file.txt
    output: ont_sequencing/file2.txt
    jobid: 1
    resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp, machine_type=n1, nvidia_gpu=1
`````

**Minimal example**

````
rule all:
    input:
        "file2.txt"

rule test_GPU:
    output:
        "file.txt"
    shell:
        'echo "Hello World" > {output}'

rule test_GPU2:
    input:
        "file.txt"
    output:
        "file2.txt"
    resources:
        nvidia_gpu=1
    shell:
        'echo "Bye World" > {output}'

````

**Comment by ricardovialle** [comment]
Hi, I'm wondering if someone found a way to get this fixed. I'm having the same issue using `snakemake:v7.5.0`

**Comment by alephreish** [comment]
Same error with `snakemake=7.12.0`

**Comment by ricardovialle** [comment]
So, I got this fixed by manually changing this function:  
[google_lifesciences.py](https://github.com/snakemake/snakemake/blob/1b3ede19159856a982de65e6293ab064c0987352/snakemake/executors/google_lifesciences.py)

Here is how my `_add_gpu` looks like:
```
    def _add_gpu(self, gpu_count):
        """
        Add a number of NVIDIA gpus to the current executor. This works
        by way of adding nvidia_gpu to the job default resources, and also
        changing the default machine type prefix to be n1, which is
        the currently only supported instance type for using GPUs for LHS.
        """
        if not gpu_count or gpu_count == 0:
            return

        logger.debug(
            "found resource request for {} GPUs. This will limit to n1 "
            "instance types.".format(gpu_count)
        )
        self.default_resources.set_resource("nvidia_gpu", gpu_count)
        self._machine_type_prefix = "n1"
```

**Comment by schnea** [comment]
Closing as GLS executor no longer exists
