### ISSUE TITLE
Snakemake is too keen in deleting directories

### ISSUE THREAD

**Issue by dariober** [snakemake/snakemake#1261]
**Snakemake version** 6.10.0

**Describe the bug**

Two jobs submitted at the same time write to the same directory. This output directory does not exist at the start. If one of the two jobs fails before the other is complete, snakemake deletes the output directory so that the second job also fails with `No such file or directory`.

**Minimal example**

rule `A` and `B` can run in parallel. Rule B fails after 5 seconds but rule A should complete fine but it fails because the output dir has been deleted.

Run with `snakemake -j 2`, make sure directory `out` does not exist yet:

```
import time

rule all:
    input:
        ['out/A.txt', 'out/B.txt'],

rule A:
    output:
        out= 'out/A.txt',
    run:
        time.sleep(10)
        with open(output.out, 'w') as fout:
            fout.write('done')

rule B:
    output:
        'out/B.txt',
    run:
        time.sleep(5)
        raise Exception()
```

**Logs**

```
snakemake -j 2
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
A            1              1              1
B            1              1              1
all          1              1              1
total        3              1              1

Select jobs to execute...

[Mon Nov 15 11:28:19 2021]
rule A:
    output: out/A.txt
    jobid: 1
    resources: tmpdir=/tmp

[Mon Nov 15 11:28:19 2021]
rule B:
    output: out/B.txt
    jobid: 2
    resources: tmpdir=/tmp

[Mon Nov 15 11:28:25 2021]
Error in rule B:
    jobid: 0
    output: out/B.txt

Traceback (most recent call last):
  File "/home/dario/miniconda3/envs/tritume/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 593, in _callback
    raise ex
  File "/home/dario/miniconda3/envs/tritume/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dario/miniconda3/envs/tritume/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 579, in cached_or_run
    run_func(*args)
  File "/home/dario/miniconda3/envs/tritume/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 2461, in run_wrapper
    raise ex
  File "/home/dario/miniconda3/envs/tritume/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 2442, in run_wrapper
    runtime_sourcecache_path,
  File "/home/dario/Downloads/Snakefile", line 34, in __rule_B
Exception
Exiting because a job execution failed. Look above for error message
[Mon Nov 15 11:28:30 2021]
Error in rule A:
    jobid: 0
    output: out/A.txt

Traceback (most recent call last):
  File "/home/dario/miniconda3/envs/tritume/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 593, in _callback
    raise ex
  File "/home/dario/miniconda3/envs/tritume/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dario/miniconda3/envs/tritume/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 579, in cached_or_run
    run_func(*args)
  File "/home/dario/miniconda3/envs/tritume/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 2461, in run_wrapper
    raise ex
  File "/home/dario/miniconda3/envs/tritume/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 2442, in run_wrapper
    runtime_sourcecache_path,
  File "/home/dario/Downloads/Snakefile", line 21, in __rule_A
FileNotFoundError: [Errno 2] No such file or directory: 'out/A.txt'
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/dario/Downloads/.snakemake/log/2021-11-15T112819.024859.snakemake.log
```

**Additional context**

**Comment by SichongP** [comment]
I just ran into this problem as well. It seems to me that cleaning up directories should be handled after a workflow has failed, rather than after each job

**Comment by SichongP** [comment]
I finally had sometime to dig into code. It seems that [this cleanup code](https://github.com/snakemake/snakemake/blob/fe50b5ca4580a0210343bfcee559831888e80a87/snakemake/dag.py#L245-L246) is the culprit here. When two rules writeto the same derctory and one rule fails before any output is written, it sees `len(os.listdir(io_dir))` as 0 and therefore deletes the output directory `io_dir` here.

One easy solution I can think of is to write a `.tmp.rulename` hidden file to output directory when a rule starts and to remove it on success or failure. Only problem is there is potential to conflit with a geniune output file using that name. Also I'm not sure if this might conflict with anything else.
