### ISSUE TITLE
Scheduler has TypeError at same rule

### ISSUE THREAD

**Issue by sandra-selfdecode** [snakemake/snakemake#1268]
**Snakemake version**
6.9.10 (also tried several older version)

**Describe the bug**
I developed a workflow using snakemake in conda. I'm trying to implement the workflow in docker using the API. Every time it reaches one of my rules, the scheduler has a TypeError. The rule runs a shell task with a wildcard that has 23 levels.

**Logs**
Select jobs to execute...
--
Selected jobs (1):
impute
Resources after job selection: {'_cores': 9223372036854775803, '_nodes': 0}
[Fri Nov 19 18:44:56 2021]
rule impute:
input: /mnt/efs/resource_files/30x.bref3/chr19.30x.bref3, filtered/genome-filtered.19.vcf, /mnt/efs/resource_files/b38.map/plink.chr19.GRCh38.map
output: imputed/genome-imputed.19.vcf.gz
log: logs/impute.19.log
jobid: 61
wildcards: y=19
threads: 4
resources: tmpdir=/tmp

Full Traceback (most recent call last):
--
File "/usr/local/lib/python3.10/site-packages/snakemake/__init__.py", line 699, in snakemake
success = workflow.execute(
File "/usr/local/lib/python3.10/site-packages/snakemake/workflow.py", line 1069, in execute
success = self.scheduler.schedule()
File "/usr/local/lib/python3.10/site-packages/snakemake/scheduler.py", line 516, in schedule
self.run(runjobs)
File "/usr/local/lib/python3.10/site-packages/snakemake/scheduler.py", line 563, in run
executor.run_jobs(
File "/usr/local/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 149, in run_jobs
self.run(
File "/usr/local/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 463, in run
super()._run(job)
File "/usr/local/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 243, in _run
super()._run(job)
File "/usr/local/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 169, in _run
self.printjob(job)
File "/usr/local/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 175, in printjob
job.log_info(skip_dynamic=True)
File "/usr/local/lib/python3.10/site-packages/snakemake/jobs.py", line 950, in log_info
logger.shellcmd(self.shellcmd, indent=indent)
File "/usr/local/lib/python3.10/site-packages/snakemake/jobs.py", line 418, in shellcmd
self.format_wildcards(self.rule.shellcmd)
File "/usr/local/lib/python3.10/site-packages/snakemake/jobs.py", line 869, in format_wildcards
return format(string, **_variables)
File "/usr/local/lib/python3.10/site-packages/snakemake/utils.py", line 430, in format
return fmt.format(_pattern, *args, **variables)
File "/usr/local/lib/python3.10/string.py", line 161, in format
return self.vformat(format_string, args, kwargs)
File "/usr/local/lib/python3.10/string.py", line 165, in vformat
result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
File "/usr/local/lib/python3.10/string.py", line 205, in _vformat
obj, arg_used = self.get_field(field_name, args, kwargs)
File "/usr/local/lib/python3.10/string.py", line 278, in get_field
obj = obj[i]
TypeError: string indices must be integers

**Minimal example**
    success = snakemake(
        snakefile=join(workflow_path, "Snakefile"),
        cores=int(multiprocessing.cpu_count()),
        workdir=workflow_path,
        config=config,
        verbose=True,
        forceall=True,
        lint=False,
        dryrun=False,
        use_conda=False,
   )
Have also tried scheduler="greedy"

**Additional context**
Latest python docker image
pip3 install boto3 snakemake pandas

**Comment by sandra-selfdecode** [comment]
This has been resolved
