### ISSUE TITLE
snakemake format_wildcards error "TypeError: keywords must be strings" but my wildcards are strings?

### ISSUE THREAD

**Issue by anitato** [snakemake/snakemake#1314]
**Snakemake version**
(snakemake-6.4.1)

**Describe the bug**
I posted a full formatted description of my issue on StackOverflow, but I believe this issue could be a bug. 
https://stackoverflow.com/questions/70456563/snakemake-format-wildcards-error-typeerror-keywords-must-be-strings-but-my-wi

**Comment by SichongP** [comment]
My guess is the special characters in your wildcards are messing with your shell command. Try quoting (') the wildcards in your shell command and see if that fixes the problem.

**Comment by anitato** [comment]
The error occurs before then. My current version has an empty shell command, and it still spits out this error.

```
rule grep_RBH_seq:
    input: /path/Pseudotsuga/PgauHS002_1.fasta, /path/Original/Psme.HQgenes.fixed4blastdb.fa
    output: /path/input/PgauHS002_1.Psme_annot.c99967_g1_i1.mRNA::jcf7190000086075:207510-229401(-).fasta
    jobid: 1
    wildcards: sppname=PgauHS002_1, outseq=c99967_g1_i1, dfseq=mRNA::jcf7190000086075:207510-229401(-)

Traceback (most recent call last):
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/__init__.py", line 701, in snakemake
    success = workflow.execute(
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/workflow.py", line 1036, in execute
    success = scheduler.schedule()
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/scheduler.py", line 489, in schedule
    self.run(runjobs)
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/scheduler.py", line 500, in run
    executor.run_jobs(
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 136, in run_jobs
    self.run(
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 145, in run
    self._run(job)
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 156, in _run
    self.printjob(job)
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 176, in printjob
    super().printjob(job)
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 162, in printjob
    job.log_info(skip_dynamic=True)
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/jobs.py", line 921, in log_info
    logger.shellcmd(self.shellcmd, indent=indent)
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/jobs.py", line 405, in shellcmd
    self.format_wildcards(self.rule.shellcmd)
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/snakemake-6.4.1/lib/python3.9/site-packages/snakemake/jobs.py", line 840, in format_wildcards
    return format(string, **_variables)
TypeError: keywords must be strings
```

I've tried replacing the wildcards with text-only strings and I still get this error.
