### ISSUE TITLE
job not registred under group when output of checkpoint exists

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [snakemake/snakemake#132]
**Snakemake version**
v5.8.1

**Describe the bug**
When making use of group jobs (e.g. piping) and when the output of a checkpoint (which is executed before the group) already exists, snakemake does not register all jobs as part of the same group and this results in a keyerror:

![image](https://user-images.githubusercontent.com/15323399/69946955-eb418b00-14ec-11ea-93ba-a945d61dfaf0.png)

Here `checkpoint a` is a checkpoint, of which the output already exists. `rule b` and `rule c` are part of the same group, and rule d makes use of both the output of the group and `checkpoint a`. When dryrunning this gives the error:

> Traceback (most recent call last):
>   File "/home/sande/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/snakemake/__init__.py", line 624, in snakemake
>     batch=batch,
>   File "/home/sande/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/snakemake/workflow.py", line 829, in execute
>     success = scheduler.schedule()
>   File "/home/sande/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/snakemake/scheduler.py", line 364, in schedule
>     self.run(job)
>   File "/home/sande/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/snakemake/scheduler.py", line 383, in run
>     error_callback=self._error,
>   File "/home/sande/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/snakemake/executors.py", line 94, in run
>     callback(job)
>   File "/home/sande/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/snakemake/scheduler.py", line 409, in _proceed
>     self.dag.finish(job, update_dynamic=update_dynamic)
>   File "/home/sande/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/snakemake/dag.py", line 1169, in finish
>     for job in jobs
>   File "/home/sande/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/snakemake/dag.py", line 993, in update_ready
>     candidate_groups.add(self._group[job])
> KeyError: c
> 

If we would change `checkpoint a` to `rule a` this does not happen anymore.

**Minimal example**
```
rule all:
    input:
        "d.txt"

checkpoint a:  # <-- change to rule to not have the error anymore
    output:
        'a.txt'
    shell:
        "touch {output}"

rule b:
    input:
        "a.txt"
    output:
        pipe('b.txt')
    shell:
        "touch {output}"

rule c:
    input:
        "b.txt"
    output:
        'c.txt'
    shell:
        "touch {output}"

rule d:
    input:
        a="a.txt",
        c="c.txt"
    output:
        'd.txt'
    shell:
        "touch {output}"
```
Note that `a.txt` needs to already exist in this example.

**Comment by Maarten-vd-Sande** [comment]
Tested this on `v5.30.1` and works
