### ISSUE TITLE
How to run CLEAR/CIRCexplorer3 in my workflow?

### ISSUE THREAD

**Issue by lssb** [snakemake/snakemake#1346]
Hi,
[CLEAR](https://github.com/YangLab/CLEAR) is a tools for circRNA quantification, and requires tophat2, but tophat2 requires python2. So there is a question.
1. I cannot run snakemake in the environment installed CLEAR, because snakemake run with python>3.5.
2. I cannot run snakemake in a python3 environment and run CLEAR with `--use-conda` and specific a `.yaml` file, because CLEAR is not in Anaconda yet. I must install it manually, clone it's git and run `python ./setup.py install`

What should I do? Please.

**Comment by lssb** [comment]
I got an idea and I am trying.
I could: 
1. run `snakemake --use-conda --conda-create-envs-only`
2. `conda activate .snakemake/conda/$HASH`  and install CLEAR in this environment

then run the snakemake

**Comment by lssb** [comment]
there is a new error:
```bash
###Parameters

###Start hisat2 mapping
# start to get sp sites for hisat mapping
# start to align to genome by hisat
# get mapped and unmapped reads
# sort bam file
# index bam file
###End hisat2 mapping


###Start tophat-fusion mapping
###End tophat-fusion mapping


###Start circRNA annotation
Traceback (most recent call last):
  File "/home/ionadmin/miniconda3/envs/circ2/bin/clear_quant", line 11, in <module>
    load_entry_point('CLEAR==1.0.1', 'console_scripts', 'clear_quant')()
  File "/home/ionadmin/miniconda3/envs/circ2/lib/python2.7/site-packages/CLEAR-1.0.1-py2.7.egg/src/run.py", line 269, in main
    args.genome, args.gtf, circ_dir)
  File "/home/ionadmin/miniconda3/envs/circ2/lib/python2.7/site-packages/CLEAR-1.0.1-py2.7.egg/src/run.py", line 181, in circ_annot
    with open('{}/genePred.tmp'.format(circ_dir), 'r') as inf,\
IOError: [Errno 2] No such file or directory: 'temp/test/circ/genePred.tmp'

```
