### ISSUE TITLE
snakemake crashes with group directive in cluster mode due to {wildcards} reference in cluster config

### ISSUE THREAD

**Issue by chrarnold** [snakemake/snakemake#1406]
**Snakemake version**
Latest

**Describe the bug**
See the Logs, I receive a KeyError: wildcards when adding a group: directive to some rules and when submitting to the cluster

The snakemake command is:
`snakemake -s dev/Snakefile  --nolock --configfile config.yaml --latency-wait 120  --use-envmodules --show-failed-logs  --forceall --rerun-incomplete --cores 4  --keep-going  --use-singularity  --singularity-prefix "/g/scb2/zaugg/zaugg_shared/Programs/Snakemake/singularity" --singularity-args "--bind /g/scb,/g/scb2,/scratch" --jobs 500 --cluster-config cluster.json --cluster " sbatch -p {cluster.queueSLURM} -J {cluster.name} -C {cluster.nodes} --cpus-per-task {cluster.nCPUs} --mem {cluster.memory} --time {cluster.maxTime} -o "{cluster.output}" -e "{cluster.error}" --qos={cluster.qos}   --mail-type=None --parsable " --local-cores 1
`

UPDATE: I found the problem. Having any {wildcard} references in the cluster config causes the error. This should be fixed, as the cluster config works for non-group mode and the {wildcard} references are needed for specifying output and error files correctly

**Logs**
`Traceback (most recent call last):
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/utils.py", line 430, in format
    return fmt.format(_pattern, *args, **variables)
  File "bla/miniconda3/envs/snakemake/lib/python3.8/string.py", line 163, in format
    return self.vformat(format_string, args, kwargs)
  File "bla/miniconda3/envs/snakemake/lib/python3.8/string.py", line 167, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "bla/miniconda3/envs/snakemake/lib/python3.8/string.py", line 207, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "bla/miniconda3/envs/snakemake/lib/python3.8/string.py", line 272, in get_field
    obj = self.get_value(first, args, kwargs)
  File "bla/miniconda3/envs/snakemake/lib/python3.8/string.py", line 229, in get_value
    return kwargs[key]
KeyError: 'wildcards'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/workflow.py", line 1073, in execute
    success = self.scheduler.schedule()
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/scheduler.py", line 516, in schedule
    self.run(runjobs)
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/scheduler.py", line 563, in run
    executor.run_jobs(
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 149, in run_jobs
    self.run(
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 986, in run
    jobscript = self.get_jobscript(job)
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 759, in get_jobscript
    f = job.format_wildcards(self.jobname, cluster=self.cluster_wildcards(job))
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 867, in cluster_wildcards
    return Wildcards(fromdict=self.cluster_params(job))
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 848, in cluster_params
    cluster[key] = job.format_wildcards(value)
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/jobs.py", line 1422, in format_wildcards
    return format(string, **_variables)
  File "bla/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/utils.py", line 432, in format
    if str(ex).strip("'") in variables["wildcards"].keys():
KeyError: 'wildcards'`

The cluster config looks like this:

> {
  "__default__": {
    "queueSLURM": "htc",
    "group": "zaugg",
    "nCPUs": "{threads}",
    "memory": 20000,
    "nodes": "avx2",
    "maxTime": "10:00:00",
    "qos": "normal",
    "name": "ANALYSIS_NAME.{rule}.{wildcards}",
    "output": "output/LOGS_AND_BENCHMARKS/{rule}.{wildcards}.out",
    "error": "output/LOGS_AND_BENCHMARKS/{rule}.{wildcards}.err"
  },
  "sampleProcessing": {
    "memory": 25000,
    "maxTime": "10:00:00"
  },
  ...

**Additional context**
The workflow works fine without the groups, it is definitely the group directive

**Comment by half-adder** [comment]
This shows up for me too. The following config errors out with `KeyError: 'wildcards'`, as above:
```
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --account=rc_dmckay1_pi
    --time={resources.time}
default-resources:
  - partition=general
  - mem_mb=8000
  - time="00:30:00"
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-envmodules: True
```

while the following config works:
```
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --account=rc_dmckay1_pi
    --time={resources.time}
default-resources:
  - partition=general
  - mem_mb=8000
  - time="00:30:00"
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-envmodules: True
```

I am running snakemake version `6.6.1` with the following command:
```
snakemake --profile slurm/
```

(the `slurm` directory contains the above file as  `config.yaml`)
