### ISSUE TITLE
should be able to run snakemake with `--use-singularity` and  `--kubernetes` without  pulling image locally first

### ISSUE THREAD

**Issue by rdenham** [snakemake/snakemake#1580]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to run snakemake using kubernetes, and also use singularity in some of the jobs. Currently, the way I understand it, the container you'd like to use gets pulled locally first.  So in a kubernetes situation, this means that first the image would be pulled  locally, and then on the node that same image would also be pulled.

I'd like to avoid pulling the image locally first if I'm using kubernetes (I'm triggering this from a node in which singularity is hard to install).

I'm actually not sure but this might be a bug, since at the moment when run my workflow I get:

```
Traceback (most recent call last):
  File "/home/admin/.venv/lib/python3.8/site-packages/snakemake/__init__.py", line 722, in snakemake
    success = workflow.execute(
  File "/home/admin//.venv/lib/python3.8/site-packages/snakemake/workflow.py", line 1110, in execute
    success = self.scheduler.schedule()
  File "/home/admin/.venv/lib/python3.8/site-packages/snakemake/scheduler.py", line 510, in schedule
    self.run(runjobs)
  File "/home/admin/.venv/lib/python3.8/site-packages/snakemake/scheduler.py", line 558, in run
    executor.run_jobs(
  File "/home/admin//.venv/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 120, in run_jobs
    self.run(
  File "/home/admin/.venv/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 1897, in run
    if job.needs_singularity and self.workflow.use_singularity:
  File "/home/admin//.venv/lib/python3.8/site-packages/snakemake/jobs.py", line 383, in needs_singularity
    return self.container_img is not None
  File "/home/admin//.venv/lib/python3.8/site-packages/snakemake/jobs.py", line 396, in container_img
    return self.dag.container_imgs[self.container_img_url]
KeyError: 'docker://ubuntu'
```

There is a dictionary `self.dag.container_imgs` that is empty when running in kubernetes.

**Describe the solution you'd like**
I'd like the ability to say that if you are running your workflow on kubernetes, and using singularity, then you might not want to pull the image locally first.

I hacked around a little bit, and it works if you modify `jobs.py` a little bit, to eg look like:

```python
    @property
    def container_img(self):
        if self.dag.workflow.use_singularity and self.container_img_url:
            try:
                img = self.dag.container_imgs[self.container_img_url]
            except KeyError:
                logger.warning("couldn't find the container in the dict")
                img = self.container_img_url
                logger.warning(f"Using {img} instead")
            return img
        return None
```

but I realise this isn't ideal.

**Describe alternatives you've considered**

**Additional context**
This is my example workflow:

```python
rule all:
    input:
        "out/b.txt"

rule a:
    output:
        a = "out/a.txt"
    container:
        "docker://ubuntu"
    shell:
        """
        touch {output.a}
        """

rule b:
    input:
        "out/a.txt"
    output:
        "out/b.txt"
    container:
        "docker://jtcressy/cowsay"
    shell:
        """
        /usr/bin/cowsay "both containers ran ok" > {output}
        """
```

And I run it like:

```sh
export REMOTE=S3
export PREFIX=my-bucket

snakemake -j 1 --kubernetes rsc-sandboxes \
               --default-remote-provider $REMOTE \
               --default-remote-prefix $PREFIX \
               --use-singularity \
               --snakefile ./snakefile \
               --envvar AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY 
```

**Comment by szsctt** [comment]
I have this issue too!

**Comment by rdenham** [comment]
@szsctt  I  have been using the modified jobs.py file for while, seems to work ok for me. But it would be good if someone could confirm whether this is a bug or just a lack of my understanding.

**Comment by uniqueg** [comment]
Avoiding local pulls would also be useful for the TES backend.
