### ISSUE TITLE
Merging files over a wildcard (vcf regions) is not straightforward, but is common.

### ISSUE THREAD

**Issue by gilmorera** [snakemake/snakemake#1581]
# Prelude..

This started off as an issue about the "File Name too long" error that was thrown when troubleshooting, but I have now figured out the issue (see comments).  The main goal for my script was to take a VCF file that was broken down into 116 regional chunks and merge it back to one large VCF file.  This seems like a fairly common goal for other bioinformatics workflows as well.  Even for different file formats.  However, this is not a straightforward process for snakemake.  I found it especially difficult as I have multiple wildcards that I use in my merge rule that also causes headaches.

I will link a feature request here shortly.

**Snakemake version**

7.0.4

**Describe the bug**

It seems that my job is completing successfully.  I'm running GATK 4.2.0.0 SelectVariants to subset a large VCFfile.  And all of the data is there.  All 116 VCF file sand 116 .tbi files.  However, an error occurs for some sort of snakemake garbage cleanup:
`Failed to set marker file for job started ([Errno 36] File name too long:`
**Logs**

```shell
cat snakejob.vcfp_br_subset.587.sh.e19786372
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 16
Rules claiming more threads will be scaled down.
Select jobs to execute...

[Thu Apr 14 18:41:14 2022]
rule vcfp_br_subset:
    input: results/vcf_workflows/01_preprocessing/target/00_start_vcf/target.vcf.gz, results/vcf_workflows/01_preprocessing/target/00_start_vcf/target.vcf.gz.tbi
    output: results/vcf_workflows/01_preprocessing/target/00_start_vcf/by_chunk/['chr1:1-30000001', 'chr1:30000001-60000001', 'chr1:60000001-90000001', 'chr1:90000001-120000001', 'chr1:120000001-150000001', 'chr1:150000001-180000001', 'chr1:180000001-210000001', 'chr1:210000001-240000001', 'chr1:240000001-248956422', 'chr2:1-30000001', 'chr2:30000001-60000001', 'chr2:60000001-90000001', 'chr2:90000001-120000001', 'chr2:120000001-150000001', 'chr2:150000001-180000001', 'chr2:180000001-210000001', 'chr2:210000001-240000001', 'chr2:240000001-242193529', 'chr3:1-30000001', 'chr3:30000001-60000001', 'chr3:60000001-90000001', 'chr3:90000001-120000001', 'chr3:120000001-150000001', 'chr3:150000001-180000001', 'chr3:180000001-198295559', 'chr4:1-30000001', 'chr4:30000001-60000001', 'chr4:60000001-90000001', 'chr4:90000001-120000001', 'chr4:120000001-150000001', 'chr4:150000001-180000001', 'chr4:180000001-190214555', 'chr5:1-30000001', 'chr5:30000001-60000001', 'chr5:60000001-90000001', 'chr5:90000001-120000001', 'chr5:120000001-150000001', 'chr5:150000001-180000001', 'chr5:180000001-181538259', 'chr6:1-30000001', 'chr6:30000001-60000001', 'chr6:60000001-90000001', 'chr6:90000001-120000001', 'chr6:120000001-150000001', 'chr6:150000001-170805979', 'chr7:1-30000001', 'chr7:30000001-60000001', 'chr7:60000001-90000001', 'chr7:90000001-120000001', 'chr7:120000001-150000001', 'chr7:150000001-159345973', 'chr8:1-30000001', 'chr8:30000001-60000001', 'chr8:60000001-90000001', 'chr8:90000001-120000001', 'chr8:120000001-145138636', 'chr9:1-30000001', 'chr9:30000001-60000001', 'chr9:60000001-90000001', 'chr9:90000001-120000001', 'chr9:120000001-138394717', 'chr10:1-30000001', 'chr10:30000001-60000001', 'chr10:60000001-90000001', 'chr10:90000001-120000001', 'chr10:120000001-133797422', 'chr11:1-30000001', 'chr11:30000001-60000001', 'chr11:60000001-90000001', 'chr11:90000001-120000001', 'chr11:120000001-135086622', 'chr12:1-30000001', 'chr12:30000001-60000001', 'chr12:60000001-90000001', 'chr12:90000001-120000001', 'chr12:120000001-133275309', 'chr13:1-30000001', 'chr13:30000001-60000001', 'chr13:60000001-90000001', 'chr13:90000001-114364328', 'chr14:1-30000001', 'chr14:30000001-60000001', 'chr14:60000001-90000001', 'chr14:90000001-107043718', 'chr15:1-30000001', 'chr15:30000001-60000001', 'chr15:60000001-90000001', 'chr15:90000001-101991189', 'chr16:1-30000001', 'chr16:30000001-60000001', 'chr16:60000001-90000001', 'chr16:90000001-90338345', 'chr17:1-30000001', 'chr17:30000001-60000001', 'chr17:60000001-83257441', 'chr18:1-30000001', 'chr18:30000001-60000001', 'chr18:60000001-80373285', 'chr19:1-30000001', 'chr19:30000001-58617616', 'chr20:1-30000001', 'chr20:30000001-60000001', 'chr20:60000001-64444167', 'chr21:1-30000001', 'chr21:30000001-46709983', 'chr22:1-30000001', 'chr22:30000001-50818468', 'chrX:1-30000001', 'chrX:30000001-60000001', 'chrX:60000001-90000001', 'chrX:90000001-120000001', 'chrX:120000001-150000001', 'chrX:150000001-156040895', 'chrY:1-30000001', 'chrY:30000001-57227415', 'chrM:1-16569'].vcf.gz, results/vcf_workflows/01_preprocessing/target/00_start_vcf/by_chunk/['chr1:1-30000001', 'chr1:30000001-60000001', 'chr1:60000001-90000001', 'chr1:90000001-120000001', 'chr1:120000001-150000001', 'chr1:150000001-180000001', 'chr1:180000001-210000001', 'chr1:210000001-240000001', 'chr1:240000001-248956422', 'chr2:1-30000001', 'chr2:30000001-60000001', 'chr2:60000001-90000001', 'chr2:90000001-120000001', 'chr2:120000001-150000001', 'chr2:150000001-180000001', 'chr2:180000001-210000001', 'chr2:210000001-240000001', 'chr2:240000001-242193529', 'chr3:1-30000001', 'chr3:30000001-60000001', 'chr3:60000001-90000001', 'chr3:90000001-120000001', 'chr3:120000001-150000001', 'chr3:150000001-180000001', 'chr3:180000001-198295559', 'chr4:1-30000001', 'chr4:30000001-60000001', 'chr4:60000001-90000001', 'chr4:90000001-120000001', 'chr4:120000001-150000001', 'chr4:150000001-180000001', 'chr4:180000001-190214555', 'chr5:1-30000001', 'chr5:30000001-60000001', 'chr5:60000001-90000001', 'chr5:90000001-120000001', 'chr5:120000001-150000001', 'chr5:150000001-180000001', 'chr5:180000001-181538259', 'chr6:1-30000001', 'chr6:30000001-60000001', 'chr6:60000001-90000001', 'chr6:90000001-120000001', 'chr6:120000001-150000001', 'chr6:150000001-170805979', 'chr7:1-30000001', 'chr7:30000001-60000001', 'chr7:60000001-90000001', 'chr7:90000001-120000001', 'chr7:120000001-150000001', 'chr7:150000001-159345973', 'chr8:1-30000001', 'chr8:30000001-60000001', 'chr8:60000001-90000001', 'chr8:90000001-120000001', 'chr8:120000001-145138636', 'chr9:1-30000001', 'chr9:30000001-60000001', 'chr9:60000001-90000001', 'chr9:90000001-120000001', 'chr9:120000001-138394717', 'chr10:1-30000001', 'chr10:30000001-60000001', 'chr10:60000001-90000001', 'chr10:90000001-120000001', 'chr10:120000001-133797422', 'chr11:1-30000001', 'chr11:30000001-60000001', 'chr11:60000001-90000001', 'chr11:90000001-120000001', 'chr11:120000001-135086622', 'chr12:1-30000001', 'chr12:30000001-60000001', 'chr12:60000001-90000001', 'chr12:90000001-120000001', 'chr12:120000001-133275309', 'chr13:1-30000001', 'chr13:30000001-60000001', 'chr13:60000001-90000001', 'chr13:90000001-114364328', 'chr14:1-30000001', 'chr14:30000001-60000001', 'chr14:60000001-90000001', 'chr14:90000001-107043718', 'chr15:1-30000001', 'chr15:30000001-60000001', 'chr15:60000001-90000001', 'chr15:90000001-101991189', 'chr16:1-30000001', 'chr16:30000001-60000001', 'chr16:60000001-90000001', 'chr16:90000001-90338345', 'chr17:1-30000001', 'chr17:30000001-60000001', 'chr17:60000001-83257441', 'chr18:1-30000001', 'chr18:30000001-60000001', 'chr18:60000001-80373285', 'chr19:1-30000001', 'chr19:30000001-58617616', 'chr20:1-30000001', 'chr20:30000001-60000001', 'chr20:60000001-64444167', 'chr21:1-30000001', 'chr21:30000001-46709983', 'chr22:1-30000001', 'chr22:30000001-50818468', 'chrX:1-30000001', 'chrX:30000001-60000001', 'chrX:60000001-90000001', 'chrX:90000001-120000001', 'chrX:120000001-150000001', 'chrX:150000001-156040895', 'chrY:1-30000001', 'chrY:30000001-57227415', 'chrM:1-16569'].vcf.gz.tbi
    jobid: 0
    wildcards: vcf_label=target, chunks=['chr1:1-30000001', 'chr1:30000001-60000001', 'chr1:60000001-90000001', 'chr1:90000001-120000001', 'chr1:120000001-150000001', 'chr1:150000001-180000001', 'chr1:180000001-210000001', 'chr1:210000001-240000001', 'chr1:240000001-248956422', 'chr2:1-30000001', 'chr2:30000001-60000001', 'chr2:60000001-90000001', 'chr2:90000001-120000001', 'chr2:120000001-150000001', 'chr2:150000001-180000001', 'chr2:180000001-210000001', 'chr2:210000001-240000001', 'chr2:240000001-242193529', 'chr3:1-30000001', 'chr3:30000001-60000001', 'chr3:60000001-90000001', 'chr3:90000001-120000001', 'chr3:120000001-150000001', 'chr3:150000001-180000001', 'chr3:180000001-198295559', 'chr4:1-30000001', 'chr4:30000001-60000001', 'chr4:60000001-90000001', 'chr4:90000001-120000001', 'chr4:120000001-150000001', 'chr4:150000001-180000001', 'chr4:180000001-190214555', 'chr5:1-30000001', 'chr5:30000001-60000001', 'chr5:60000001-90000001', 'chr5:90000001-120000001', 'chr5:120000001-150000001', 'chr5:150000001-180000001', 'chr5:180000001-181538259', 'chr6:1-30000001', 'chr6:30000001-60000001', 'chr6:60000001-90000001', 'chr6:90000001-120000001', 'chr6:120000001-150000001', 'chr6:150000001-170805979', 'chr7:1-30000001', 'chr7:30000001-60000001', 'chr7:60000001-90000001', 'chr7:90000001-120000001', 'chr7:120000001-150000001', 'chr7:150000001-159345973', 'chr8:1-30000001', 'chr8:30000001-60000001', 'chr8:60000001-90000001', 'chr8:90000001-120000001', 'chr8:120000001-145138636', 'chr9:1-30000001', 'chr9:30000001-60000001', 'chr9:60000001-90000001', 'chr9:90000001-120000001', 'chr9:120000001-138394717', 'chr10:1-30000001', 'chr10:30000001-60000001', 'chr10:60000001-90000001', 'chr10:90000001-120000001', 'chr10:120000001-133797422', 'chr11:1-30000001', 'chr11:30000001-60000001', 'chr11:60000001-90000001', 'chr11:90000001-120000001', 'chr11:120000001-135086622', 'chr12:1-30000001', 'chr12:30000001-60000001', 'chr12:60000001-90000001', 'chr12:90000001-120000001', 'chr12:120000001-133275309', 'chr13:1-30000001', 'chr13:30000001-60000001', 'chr13:60000001-90000001', 'chr13:90000001-114364328', 'chr14:1-30000001', 'chr14:30000001-60000001', 'chr14:60000001-90000001', 'chr14:90000001-107043718', 'chr15:1-30000001', 'chr15:30000001-60000001', 'chr15:60000001-90000001', 'chr15:90000001-101991189', 'chr16:1-30000001', 'chr16:30000001-60000001', 'chr16:60000001-90000001', 'chr16:90000001-90338345', 'chr17:1-30000001', 'chr17:30000001-60000001', 'chr17:60000001-83257441', 'chr18:1-30000001', 'chr18:30000001-60000001', 'chr18:60000001-80373285', 'chr19:1-30000001', 'chr19:30000001-58617616', 'chr20:1-30000001', 'chr20:30000001-60000001', 'chr20:60000001-64444167', 'chr21:1-30000001', 'chr21:30000001-46709983', 'chr22:1-30000001', 'chr22:30000001-50818468', 'chrX:1-30000001', 'chrX:30000001-60000001', 'chrX:60000001-90000001', 'chrX:90000001-120000001', 'chrX:120000001-150000001', 'chrX:150000001-156040895', 'chrY:1-30000001', 'chrY:30000001-57227415', 'chrM:1-16569']
    resources: mem_mb=253286, disk_mb=253286, tmpdir=scratch/19786372.1.all.q

Failed to set marker file for job started ([Errno 36] File name too long: 'vcf/prod/Batch116-120/.snakemake/incomplete/@cmVzdWx0cy92Y2Zfd29ya2Zsb3dzLzAxX3ByZXByb2Nlc3NpbmcvdGFyZ2V0LzAwX3N0YXJ0X3ZjZi9ieV9jaHVuay9bJ2NocjE6MS0zMDAwMDAwMScsICdjaHIxOjMwMDAwMDAxLTYwMDAwMDAxJywgJ2NocjE6NjAwMDAwMDEtOTAwMDAwMDEnLCAnY2hyMTo5MDAwMDAwMS0xMjAwMDAwMDEnLCAnY2hyMToxMjAwMDAwMDEtMTUwMDAwMD/@AxJywgJ2NocjE6MTUwMDAwMDAxLTE4MDAwMDAwMScsICdjaHIxOjE4MDAwMDAwMS0yMTAwMDAwMDEnLCAnY2hyMToyMTAwMDAwMDEtMjQwMDAwMDAxJywgJ2NocjE6MjQwMDAwMDAxLTI0ODk1NjQyMicsICdjaHIyOjEtMzAwMDAwMDEnLCAnY2hyMjozMDAwMDAwMS02MDAwMDAwMScsICdjaHIyOjYwMDAwMDAxLTkwMDAwMDAxJywgJ2No/@cjI6OTAwMDAwMDEtMTIwMDAwMDAxJywgJ2NocjI6MTIwMDAwMDAxLTE1MDAwMDAwMScsICdjaHIyOjE1MDAwMDAwMS0xODAwMDAwMDEnLCAnY2hyMjoxODAwMDAwMDEtMjEwMDAwMDAxJywgJ2NocjI6MjEwMDAwMDAxLTI0MDAwMDAwMScsICdjaHIyOjI0MDAwMDAwMS0yNDIxOTM1MjknLCAnY2hyMzoxLTMwMDAwMDAxJywgJ2NocjM6Mz/@AwMDAwMDEtNjAwMDAwMDEnLCAnY2hyMzo2MDAwMDAwMS05MDAwMDAwMScsICdjaHIzOjkwMDAwMDAxLTEyMDAwMDAwMScsICdjaHIzOjEyMDAwMDAwMS0xNTAwMDAwMDEnLCAnY2hyMzoxNTAwMDAwMDEtMTgwMDAwMDAxJywgJ2NocjM6MTgwMDAwMDAxLTE5ODI5NTU1OScsICdjaHI0OjEtMzAwMDAwMDEnLCAnY2hyNDozMDAwMDAwMS02/@MDAwMDAwMScsICdjaHI0OjYwMDAwMDAxLTkwMDAwMDAxJywgJ2NocjQ6OTAwMDAwMDEtMTIwMDAwMDAxJywgJ2NocjQ6MTIwMDAwMDAxLTE1MDAwMDAwMScsICdjaHI0OjE1MDAwMDAwMS0xODAwMDAwMDEnLCAnY2hyNDoxODAwMDAwMDEtMTkwMjE0NTU1JywgJ2NocjU6MS0zMDAwMDAwMScsICdjaHI1OjMwMDAwMDAxLTYwMDAwMDAxJy/@wgJ2NocjU6NjAwMDAwMDEtOTAwMDAwMDEnLCAnY2hyNTo5MDAwMDAwMS0xMjAwMDAwMDEnLCAnY2hyNToxMjAwMDAwMDEtMTUwMDAwMDAxJywgJ2NocjU6MTUwMDAwMDAxLTE4MDAwMDAwMScsICdjaHI1OjE4MDAwMDAwMS0xODE1MzgyNTknLCAnY2hyNjoxLTMwMDAwMDAxJywgJ2NocjY6MzAwMDAwMDEtNjAwMDAwMDEnLCAnY2hyNjo2/@MDAwMDAwMS05MDAwMDAwMScsICdjaHI2OjkwMDAwMDAxLTEyMDAwMDAwMScsICdjaHI2OjEyMDAwMDAwMS0xNTAwMDAwMDEnLCAnY2hyNjoxNTAwMDAwMDEtMTcwODA1OTc5JywgJ2Nocjc6MS0zMDAwMDAwMScsICdjaHI3OjMwMDAwMDAxLTYwMDAwMDAxJywgJ2Nocjc6NjAwMDAwMDEtOTAwMDAwMDEnLCAnY2hyNzo5MDAwMDAwMS0xMj/@AwMDAwMDEnLCAnY2hyNzoxMjAwMDAwMDEtMTUwMDAwMDAxJywgJ2Nocjc6MTUwMDAwMDAxLTE1OTM0NTk3MycsICdjaHI4OjEtMzAwMDAwMDEnLCAnY2hyODozMDAwMDAwMS02MDAwMDAwMScsICdjaHI4OjYwMDAwMDAxLTkwMDAwMDAxJywgJ2Nocjg6OTAwMDAwMDEtMTIwMDAwMDAxJywgJ2Nocjg6MTIwMDAwMDAxLTE0NTEzODYzNics/@ICdjaHI5OjEtMzAwMDAwMDEnLCAnY2hyOTozMDAwMDAwMS02MDAwMDAwMScsICdjaHI5OjYwMDAwMDAxLTkwMDAwMDAxJywgJ2Nocjk6OTAwMDAwMDEtMTIwMDAwMDAxJywgJ2Nocjk6MTIwMDAwMDAxLTEzODM5NDcxNycsICdjaHIxMDoxLTMwMDAwMDAxJywgJ2NocjEwOjMwMDAwMDAxLTYwMDAwMDAxJywgJ2NocjEwOjYwMDAwMDAxLT/@kwMDAwMDAxJywgJ2NocjEwOjkwMDAwMDAxLTEyMDAwMDAwMScsICdjaHIxMDoxMjAwMDAwMDEtMTMzNzk3NDIyJywgJ2NocjExOjEtMzAwMDAwMDEnLCAnY2hyMTE6MzAwMDAwMDEtNjAwMDAwMDEnLCAnY2hyMTE6NjAwMDAwMDEtOTAwMDAwMDEnLCAnY2hyMTE6OTAwMDAwMDEtMTIwMDAwMDAxJywgJ2NocjExOjEyMDAwMDAwMS0xMzUw/@ODY2MjInLCAnY2hyMTI6MS0zMDAwMDAwMScsICdjaHIxMjozMDAwMDAwMS02MDAwMDAwMScsICdjaHIxMjo2MDAwMDAwMS05MDAwMDAwMScsICdjaHIxMjo5MDAwMDAwMS0xMjAwMDAwMDEnLCAnY2hyMTI6MTIwMDAwMDAxLTEzMzI3NTMwOScsICdjaHIxMzoxLTMwMDAwMDAxJywgJ2NocjEzOjMwMDAwMDAxLTYwMDAwMDAxJywgJ2Nocj/@EzOjYwMDAwMDAxLTkwMDAwMDAxJywgJ2NocjEzOjkwMDAwMDAxLTExNDM2NDMyOCcsICdjaHIxNDoxLTMwMDAwMDAxJywgJ2NocjE0OjMwMDAwMDAxLTYwMDAwMDAxJywgJ2NocjE0OjYwMDAwMDAxLTkwMDAwMDAxJywgJ2NocjE0OjkwMDAwMDAxLTEwNzA0MzcxOCcsICdjaHIxNToxLTMwMDAwMDAxJywgJ2NocjE1OjMwMDAwMDAxLTYw/@MDAwMDAxJywgJ2NocjE1OjYwMDAwMDAxLTkwMDAwMDAxJywgJ2NocjE1OjkwMDAwMDAxLTEwMTk5MTE4OScsICdjaHIxNjoxLTMwMDAwMDAxJywgJ2NocjE2OjMwMDAwMDAxLTYwMDAwMDAxJywgJ2NocjE2OjYwMDAwMDAxLTkwMDAwMDAxJywgJ2NocjE2OjkwMDAwMDAxLTkwMzM4MzQ1JywgJ2NocjE3OjEtMzAwMDAwMDEnLCAnY2hyMT/@c6MzAwMDAwMDEtNjAwMDAwMDEnLCAnY2hyMTc6NjAwMDAwMDEtODMyNTc0NDEnLCAnY2hyMTg6MS0zMDAwMDAwMScsICdjaHIxODozMDAwMDAwMS02MDAwMDAwMScsICdjaHIxODo2MDAwMDAwMS04MDM3MzI4NScsICdjaHIxOToxLTMwMDAwMDAxJywgJ2NocjE5OjMwMDAwMDAxLTU4NjE3NjE2JywgJ2NocjIwOjEtMzAwMDAwMDEnLCAn/@Y2hyMjA6MzAwMDAwMDEtNjAwMDAwMDEnLCAnY2hyMjA6NjAwMDAwMDEtNjQ0NDQxNjcnLCAnY2hyMjE6MS0zMDAwMDAwMScsICdjaHIyMTozMDAwMDAwMS00NjcwOTk4MycsICdjaHIyMjoxLTMwMDAwMDAxJywgJ2NocjIyOjMwMDAwMDAxLTUwODE4NDY4JywgJ2Noclg6MS0zMDAwMDAwMScsICdjaHJYOjMwMDAwMDAxLTYwMDAwMDAxJy/wgJ2Noclg6NjAwMDAwMDEtOTAwMDAwMDEnLCAnY2hyWDo5MDAwMDAwMS0xMjAwMDAwMDEnLCAnY2hyWDoxMjAwMDAwMDEtMTUwMDAwMDAxJywgJ2Noclg6MTUwMDAwMDAxLTE1NjA0MDg5NScsICdjaHJZOjEtMzAwMDAwMDEnLCAnY2hyWTozMDAwMDAwMS01NzIyNzQxNScsICdjaHJNOjEtMTY1NjknXS52Y2YuZ3o='). Snakemake will work, but cannot ensure that output files are complete in case of a kill signal or power loss. Please ensure write permissions for the directory vcf/prod/Batch116-120/.snakemake
Traceback (most recent call last):
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/__init__.py", line 714, in snakemake
    success = workflow.execute(
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/workflow.py", line 1097, in execute
    success = self.scheduler.schedule()
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/scheduler.py", line 540, in schedule
    self.run(runjobs)
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/scheduler.py", line 588, in run
    executor.run_jobs(
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 153, in run_jobs
    self.run(
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 486, in run
    future = self.run_single_job(job)
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 539, in run_single_job
    self.cached_or_run, job, run_wrapper, *self.job_args_and_prepare(job)
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 491, in job_args_and_prepare
    job.prepare()
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/jobs.py", line 751, in prepare
    self.remove_existing_output()
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/jobs.py", line 718, in remove_existing_output
    f.remove(remove_non_empty_dir=False)
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/io.py", line 639, in remove
    remove(self, remove_non_empty_dir=remove_non_empty_dir)
  File "/sysapps/cluster/software/Anaconda3/2021.05/envs/snakemake-7.0.4/lib/python3.10/site-packages/snakemake/io.py", line 869, in remove
    os.remove(file)
OSError: [Errno 36] File name too long: "results/vcf_workflows/01_preprocessing/target/00_start_vcf/by_chunk/['chr1:1-30000001', 'chr1:30000001-60000001', 'chr1:60000001-90000001', 'chr1:90000001-120000001', 'chr1:120000001-150000001', 'chr1:150000001-180000001', 'chr1:180000001-210000001', 'chr1:210000001-240000001', 'chr1:240000001-248956422', 'chr2:1-30000001', 'chr2:30000001-60000001', 'chr2:60000001-90000001', 'chr2:90000001-120000001', 'chr2:120000001-150000001', 'chr2:150000001-180000001', 'chr2:180000001-210000001', 'chr2:210000001-240000001', 'chr2:240000001-242193529', 'chr3:1-30000001', 'chr3:30000001-60000001', 'chr3:60000001-90000001', 'chr3:90000001-120000001', 'chr3:120000001-150000001', 'chr3:150000001-180000001', 'chr3:180000001-198295559', 'chr4:1-30000001', 'chr4:30000001-60000001', 'chr4:60000001-90000001', 'chr4:90000001-120000001', 'chr4:120000001-150000001', 'chr4:150000001-180000001', 'chr4:180000001-190214555', 'chr5:1-30000001', 'chr5:30000001-60000001', 'chr5:60000001-90000001', 'chr5:90000001-120000001', 'chr5:120000001-150000001', 'chr5:150000001-180000001', 'chr5:180000001-181538259', 'chr6:1-30000001', 'chr6:30000001-60000001', 'chr6:60000001-90000001', 'chr6:90000001-120000001', 'chr6:120000001-150000001', 'chr6:150000001-170805979', 'chr7:1-30000001', 'chr7:30000001-60000001', 'chr7:60000001-90000001', 'chr7:90000001-120000001', 'chr7:120000001-150000001', 'chr7:150000001-159345973', 'chr8:1-30000001', 'chr8:30000001-60000001', 'chr8:60000001-90000001', 'chr8:90000001-120000001', 'chr8:120000001-145138636', 'chr9:1-30000001', 'chr9:30000001-60000001', 'chr9:60000001-90000001', 'chr9:90000001-120000001', 'chr9:120000001-138394717', 'chr10:1-30000001', 'chr10:30000001-60000001', 'chr10:60000001-90000001', 'chr10:90000001-120000001', 'chr10:120000001-133797422', 'chr11:1-30000001', 'chr11:30000001-60000001', 'chr11:60000001-90000001', 'chr11:90000001-120000001', 'chr11:120000001-135086622', 'chr12:1-30000001', 'chr12:30000001-60000001', 'chr12:60000001-90000001', 'chr12:90000001-120000001', 'chr12:120000001-133275309', 'chr13:1-30000001', 'chr13:30000001-60000001', 'chr13:60000001-90000001', 'chr13:90000001-114364328', 'chr14:1-30000001', 'chr14:30000001-60000001', 'chr14:60000001-90000001', 'chr14:90000001-107043718', 'chr15:1-30000001', 'chr15:30000001-60000001', 'chr15:60000001-90000001', 'chr15:90000001-101991189', 'chr16:1-30000001', 'chr16:30000001-60000001', 'chr16:60000001-90000001', 'chr16:90000001-90338345', 'chr17:1-30000001', 'chr17:30000001-60000001', 'chr17:60000001-83257441', 'chr18:1-30000001', 'chr18:30000001-60000001', 'chr18:60000001-80373285', 'chr19:1-30000001', 'chr19:30000001-58617616', 'chr20:1-30000001', 'chr20:30000001-60000001', 'chr20:60000001-64444167', 'chr21:1-30000001', 'chr21:30000001-46709983', 'chr22:1-30000001', 'chr22:30000001-50818468', 'chrX:1-30000001', 'chrX:30000001-60000001', 'chrX:60000001-90000001', 'chrX:90000001-120000001', 'chrX:120000001-150000001', 'chrX:150000001-156040895', 'chrY:1-30000001', 'chrY:30000001-57227415', 'chrM:1-16569'].vcf.gz"
```
**Minimal example**
```python
    params:
        rname = "subset",
        chunk = "{chunks}",
        mod = 'module load GATK/4.2.0.0-Java-1.8.0_92;'
    run:
        shell("{params.mod} $EBROOTGATK/gatk --java-options '-Xmx24g' SelectVariants --reference Homo_sapiens_assembly38_plus.fasta -V {input.vcf} -O {output.vcf} --exclude-non-variants -xl-sn s0391 -xl-sn s009 --intervals {params.chunk};")
```

**Additional context**

I'm not really sure what's going here..

**Comment by dariober** [comment]
I suspect the bug is with your code not with snakemake's. Your rule `vcfp_br_subset` takes in input a vcf and its index and it gives in output a very very long filename with square brackets and spaces in it. Is this intentional? Post the entire rule and ideally something the can be executed to reproduce the issue,

**Comment by gilmorera** [comment]
Hi @dariober .  The issue was actually not with the vcfp_br_subset rule, but with the vcfp_br_merge rule:

```python

rule merge_cumulative:
    input:
        vcf = expand('results/vcf_workflows/01_preprocessing/{vcf_label}/4_filter_spanning_deletions/by_chunk/{chunks}.vcf.gz', vcf_label=vcf_label, chunks=chunks)
    output:
        vcf = 'results/vcf_workflows/01_preprocessing/{vcf_label}/4_filter_spanning_deletions/{vcf_label}.vcf.gz',
        tab = 'results/vcf_workflows/01_preprocessing/{vcf_label}/4_filter_spanning_deletions/{vcf_label}.vcf.gz.tbi',
        vcf_chunk = 'results/vcf_workflows/01_preprocessing/{vcf_label}4_filter_spanning_deletions/chunked_vcf_files_to_merge.txt'
    run:
        with open(output.vcf_chunk,'w') as vc:
            for chunk in input.vcf:
                vc.write(chunk + '\n')
        shell('module load GATK/4.2.0.0-Java-1.8.0_92; $EBROOTGATK/gatk MergeVcfs --OUTPUT {output.vcf} --INPUT {output.vcf_chunk}')
```
I changed this rule several times to fix the issue, so it's hard for me to say the exact reason..  At one point I was using unpack in the merge rule's input:
```python
def get_vcf_chunks(wildcards):
    vcf_label = wildcards.vcf_label
    chunks = chunks # a list of chunks (not the wildcard)
    vcf_chunk = "results/vcf_workflows/01_preprocessing/{vcf_label}/4_filter_spanning_deletions/by_chunk/{chunks}.vcf.gz"
    return {"vcf": vcf_chunk}
    
```

I finally fixed the issue by using a lambda function to keep the string formatting for the vcf_label wildcard:
```python
rule merge_cumulative:
    input:
        vcf = lambda wildcards: expand('results/vcf_workflows/01_preprocessing/{{vcf_label}}/4_filter_spanning_deletions/by_chunk/{chunkers}.vcf.gz', chunkers=label_chunks[wildcards.vcf_label])
    output:
        vcf = 'results/vcf_workflows/01_preprocessing/{vcf_label}/4_filter_spanning_deletions/{vcf_label}.vcf.gz',
        tab = 'results/vcf_workflows/01_preprocessing/{vcf_label}/4_filter_spanning_deletions/{vcf_label}.vcf.gz.tbi',
        vcf_chunk = 'results/vcf_workflows/01_preprocessing/{vcf_label}/4_filter_spanning_deletions/chunked_vcf_files_to_merge.txt'
    params:
        chunk_path = 'results/vcf_workflows/01_preprocessing/{vcf_label}/4_filter_spanning_deletions/by_chunk'
    run:
        shell('ls -A1 {params.chunk_path}/* | grep -E \'\.gz\.tbi\' -v> {output.vcf_chunk}')
        shell('module load GATK/4.2.0.0-Java-1.8.0_92; $EBROOTGATK/gatk MergeVcfs --OUTPUT {output.vcf} --INPUT {output.vcf_chunk}')
```

Sorry for the mistake.  I think this may have been more useful on stack-overflow.  I will add that it does seem strange and made it more difficult to diagnose this error as it was occurring in a rule way further down from where the error was taking place.

Additionally, it seems that a large number of snakemake users have similar workflows where they are trying to merge files (fastq, bam, vcf,  etc) across a wildcard.  So in my case "chunks" would be used in the input, but not the output.  As it's fairly common, I thought there might be a flag to use for this?  Or maybe a keyword (`merge: wildcards.chunks`) or special function that can be used in the input (input: vcf = merge('{chunks}.vcf.gz').

Maybe I overlooked something with this case... But anyways, thanks for you quick response on this.

**Comment by dariober** [comment]
A few thoughts... First, if your problem is resolved can you close this issue?

>  it seems that a large number of snakemake users have similar workflows where they are trying to merge files (fastq, bam, vcf, etc) across a wildcard

I agree that this is quite a stumbling block. Effectively, the feature or keyword you are hinting at already exists in the syntax `lambda wildcards: ...`. I got used to it and I find it quite logical and neat but I do agree it is cryptic at the beginning. I don't know if other workflow managers make it any easier. Perhaps, what we need is a clear reference example and documentation that shows how and why this works.

**Comment by gilmorera** [comment]
Hi @dariober.  Yes this issue is resolved.  I will close it for now.  I have another feature request that I will link to here.  I think at the very least there should be more documentation about this.  I know it would be very helpful for a lot of people.  Especially those that are new to snakemake AND python programming.
