### ISSUE TITLE
WorkflowError when creating report using -j/--jobs instead of -c

### ISSUE THREAD

**Issue by visze** [snakemake/snakemake#1589]
**7.3.8**

**Describe the bug**

When running `snakemake --report report.html --jobs 1` I get an WorkflowError:

```
WorkflowError in line 7 of /data/projects/MPRAsnakeflow/MPRAsnakeflow/workflow/rules/statistic/counts.smk:
Resource _nodes is of type int but global resource constraint defines <class 'str'> with value 1. Resources with the same name need to have the same types (int, float, or str are allowed)
```

With `snakemake --report report.html -c 1` the error does not appear. In theory -j should only be an alias of -c. But it seems that it is converted into a string and does not stay an int.

**Logs**

```
Building DAG of jobs...
Creating report...
Adding counts.freqUMIs.HEPG2_1_RNA.txt (0.00019 MB).
Full Traceback (most recent call last):
  File "/data/home/schubacm/miniconda3/lib/python3.9/site-packages/snakemake/__init__.py", line 722, in snakemake
    success = workflow.execute(
  File "/data/home/schubacm/miniconda3/lib/python3.9/site-packages/snakemake/workflow.py", line 926, in execute
    auto_report(dag, report, stylesheet=report_stylesheet)
  File "/data/home/schubacm/miniconda3/lib/python3.9/site-packages/snakemake/report/__init__.py", line 641, in auto_report
    register_file(f)
  File "/data/home/schubacm/miniconda3/lib/python3.9/site-packages/snakemake/report/__init__.py", line 624, in register_file
    FileRecord(
  File "/data/home/schubacm/miniconda3/lib/python3.9/site-packages/snakemake/report/__init__.py", line 444, in __init__
    logging.format_dict(job.params).replace("\n", r"\n").replace('"', r"\"")
  File "/data/home/schubacm/miniconda3/lib/python3.9/site-packages/snakemake/jobs.py", line 298, in params
    self.wildcards_dict, self.input, self.output, self.resources
  File "/data/home/schubacm/miniconda3/lib/python3.9/site-packages/snakemake/jobs.py", line 342, in resources
    self._resources = self.rule.expand_resources(
  File "/data/home/schubacm/miniconda3/lib/python3.9/site-packages/snakemake/rules.py", line 1113, in expand_resources
    resources[name] = apply(name, res, threads=threads)
  File "/data/home/schubacm/miniconda3/lib/python3.9/site-packages/snakemake/rules.py", line 1096, in apply
    raise WorkflowError(
snakemake.exceptions.WorkflowError: Resource _nodes is of type int but global resource constraint defines <class 'str'> with value 1. Resources with the same name need to have the same types (int, float, or str are allowed).

WorkflowError in line 7 of /data/projects/MPRAsnakeflow/MPRAsnakeflow/workflow/rules/statistic/counts.smk:
Resource _nodes is of type int but global resource constraint defines <class 'str'> with value 1. Resources with the same name need to have the same types (int, float, or str are allowed).
unlocking
removing lock
removing lock
removed all locks
```

**Minimal example**

`snakemake --report report.html -c j`

**Additional context**

**Comment by grepinsight** [comment]
I've encountered the same problem, but with `--dag` flag

```
└─> snakemake --reason --dryrun -j1 --dag
Building DAG of jobs...
WorkflowErrorin line 1 of /redacted/Snakefile:
Resource _nodes is of type int but global resource constraint defines <class 'str'> with value 1. Resources with the same name need to have the same types (int, float, or str are allowed).
```

The snakefile is

```
 cat Snakefile
rule all:
    run:
        print(f"config:")

```

**Comment by iromeo** [comment]
Same error `7.12.0` with `--jobs 1` but works with `-c 1`

**Comment by vmkalbskopf** [comment]
This bug was closed but I'm still getting the error. How have you gotten past this?

**Comment by kelly-sovacool** [comment]
This problem also happens with `--generate-unit-tests`, no matter whether using `-c` or `-j`.

**Comment by iamh2o** [comment]
.... and removing -j from the invocation worked to stop it.

**Comment by vmkalbskopf** [comment]
This bug appears when I specify a rule. If I don't use -j, the rule doesn't actually run but I don't get the error.

**Comment by pvandyken** [comment]
I've tracked this down to a mishandling of `--jobs` in all non-executing states (except for dryrun), which is why it pops up in a variety of circumstances (e.g. `--dag`, `--report`, etc). I'll try to put together a patch
