### ISSUE TITLE
Python error when creating subdirectories

### ISSUE THREAD

**Issue by dhoconno** [snakemake/snakemake#1593]
**Snakemake version**
7.3.8

**Describe the bug**
This may be related to https://github.com/snakemake/snakemake/pull/1588

I need to run Snakemake within a Docker container. Workflows that used snakemake 5.29.0 work fine.

When I updated to the latest version (7.3.8), there is an error when creating temporary directories.

~I'll try to narrow it down further tomorrow but the error appeared between 6.8 and 6.11.1~

The issue appears to arise between 6.8.0 and 6.8.1. 

```
I have no name!@xx-2682:/var/lib/condor/execute/slot1/dir_15578$ /opt/conda/envs/snakemake-6.8.0-0/bin/snakemake --cores 1 --snakefile 27185-CHTC.snakefile
KeyError in line 7 of /var/lib/condor/execute/slot1/dir_15578/27185-CHTC.snakefile:
'sample_name'
  File "/var/lib/condor/execute/slot1/dir_15578/27185-CHTC.snakefile", line 7, in <module>
I have no name!@xx-2682:/var/lib/condor/execute/slot1/dir_15578$ /opt/conda/envs/snakemake-6.11.1-0/bin/snakemake --cores 1 --snakefile 27185-CHTC.snakefile
Traceback (most recent call last):
  File "/opt/conda/envs/snakemake-6.11.1-0/lib/python3.10/site-packages/snakemake/__init__.py", line 540, in snakemake
    workflow = Workflow(
  File "/opt/conda/envs/snakemake-6.11.1-0/lib/python3.10/site-packages/snakemake/workflow.py", line 222, in __init__
    self.sourcecache = SourceCache()
  File "/opt/conda/envs/snakemake-6.11.1-0/lib/python3.10/site-packages/snakemake/sourcecache.py", line 275, in __init__
    os.makedirs(self.cache, exist_ok=True)
  File "/opt/conda/envs/snakemake-6.11.1-0/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/envs/snakemake-6.11.1-0/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/envs/snakemake-6.11.1-0/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/envs/snakemake-6.11.1-0/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'
```

**Logs**
```
I have no name!@xx-2673:/var/lib/condor/execute/slot1/dir_4688$ miniconda/envs/snakemake/bin/snakemake -v
7.3.8
I have no name!@xx-2673:/var/lib/condor/execute/slot1/dir_4688$ miniconda/envs/snakemake/bin/snakemake --cores 1 --snakefile 27185-CHTC.snakefile 
Traceback (most recent call last):
  File "/var/lib/condor/execute/slot1/dir_4688/miniconda/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 553, in snakemake
    workflow = Workflow(
  File "/var/lib/condor/execute/slot1/dir_4688/miniconda/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 232, in __init__
    self.sourcecache = SourceCache()
  File "/var/lib/condor/execute/slot1/dir_4688/miniconda/envs/snakemake/lib/python3.10/site-packages/snakemake/sourcecache.py", line 329, in __init__
    os.makedirs(self.cache, exist_ok=True)
  File "/var/lib/condor/execute/slot1/dir_4688/miniconda/envs/snakemake/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lib/condor/execute/slot1/dir_4688/miniconda/envs/snakemake/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lib/condor/execute/slot1/dir_4688/miniconda/envs/snakemake/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lib/condor/execute/slot1/dir_4688/miniconda/envs/snakemake/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'
```
**Additional context**
Running in a Docker container within an HTCondor cluster.

**Comment by LukaP-BB** [comment]
I have a very similar issue here with the following traceback :
```py
Traceback (most recent call last):
  File "/dev/envs/shared/pipeline/lib/python3.10/site-packages/snakemake/sourcecache.py", line 330, in __init__
    os.makedirs(self.cache, exist_ok=True)
  File "/dev/envs/shared/pipeline/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/dev/envs/shared/pipeline/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/dev/envs/shared/pipeline/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 2 more times]
  File "/dev/envs/shared/pipeline/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home'
```
I added some error handling to the line in sourcecache.py, to see which folder was trying to be created exactly, and this is the one that fails : 
```py
  File "/labos/UGM/dev/envs/shared/pipeline/lib/python3.10/site-packages/snakemake/sourcecache.py", line 332, in __init__
    raise Exception(f"{os.environ.get('USER')} could not create folder tree : '{Path(self.cache).resolve().absolute()}'")
Exception: user could not create folder tree : '/home/user/.cache/snakemake/snakemake/source-cache'
```
This folder actually exists, so this is really mind-boggling and I'm running out of ideas to debug this issue.
Is there a way to specify where the snakemake cache will be written ? Because the space in /home/user is limited

**Comment by LukaP-BB** [comment]
I managed to fix the issue with something that looks completely unrelated. 
Working on a cluster with slurm, my drmaa string included `--mem-per-cpu={cluster.mem}`
Switching this to `--mem={cluster.mem}` and adapting the cluster mem accordingly fixed it.
There was an issue with the process going out of memory and giving enough memory to the batch job fixed it. 
I still don't see how this would interfere with the SourceCache() initialization :thinking:

**Comment by james-s-willis** [comment]
@LukaP-BB thanks for the tip, I didn't realise that `SNAKEMAKE_OUTPUT_CACHE` was something completely different.

Regarding your fix, I can see how setting `--mem-per-cpu={cluster.mem}` would cause it to OOM, but I agree I don't see how this would have anything to do with SourceCache initialisation.

**Comment by dhoconno** [comment]
Thanks to @moxgreen -- this solution worked great!

**Comment by peter-yufan-zeng** [comment]
I had the same problem running snakemake 7.3.8 (installed via pip) on my slurm cluster. On my cluster, HOME directory is not modifiable on the compute nodes. I solved the problem by manually setting the self.cache in sourcecache.py to my scratch directory.

[snakemake/snakemake/sourcecache.py](https://github.com/snakemake/snakemake/blob/2b6950c038ec1614c4efebe3966347d5ace5197c/snakemake/sourcecache.py#L327)

**Comment by AlcaArctica** [comment]
Wow, thank you @peter-yufan-zeng and @moxgreen!
I just spent the whole morning on a very similar problem, but I didnt find your issue, because I am getting a different error. 
Background is, I am trying to run snakemake with `--profile` on our cluster using slurm (snakemake v7.32.4). I obtained the slurm profile via cookiecutter from https://github.com/Snakemake-Profiles/slurm without modifications. Before snakemake would run just fine. But when trying to use the --profile flag, I would get the following very strange error:

```
Traceback (most recent call last):
  File "/lustre/projects/dazzler/uelze/conda_envs/snakemake/lib/python3.11/site-packages/snakemake/__init__.py", line 610, in snakemake
    workflow = Workflow(
               ^^^^^^^^^
  File "/lustre/projects/dazzler/uelze/conda_envs/snakemake/lib/python3.11/site-packages/snakemake/workflow.py", line 235, in __init__
    self._sourcecache = SourceCache()
                        ^^^^^^^^^^^^^
  File "/lustre/projects/dazzler/uelze/conda_envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 353, in __init__
    os.makedirs(self.cache, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 107] Transport endpoint is not connected: '/home/uelze'
```

I tried de-installing and re-installing and updating snakemake, but kept getting the same error. Finally I found your post and I manually set the self.cache in sourcecache.py to my scratch directory, which I then read and writable to all users with giving all users with `chmod a+rwX`.
This fixed the error. I am not sure what caused it, but maybe similar to @peter-yufan-zeng our slurm cluster was unable to access my home? Anyway, our storage quota in our home is quite restricted, so its good to re-direct anything possible to a different location anyway. So thanks so much for having documented this before.
