### ISSUE TITLE
Raise exceptions in the interpreter to have the debugger catch them

### ISSUE THREAD

**Issue by xapple** [snakemake/snakemake#1607]
I just got started with `snakemake` and it seems like a very powerful tool, so thanks to all the contributors.

One thing I'm curious about is why are no exceptions raised by the `snakemake` process? When attaching a debugger to the `snakemake` python process, it simply exits with code `1` instead of dropping into the latest frame of the traceback.

Here is an example when running a `snakemake` workflow through PyCharm with a debugger attached:

    /usr/local/Caskroom/miniconda/base/envs/proj/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 65205 --file /usr/local/Caskroom/miniconda/base/envs/proj/bin/snakemake --cores 4 --snakefile /Users/xapple/repos/proj/proj/workflow/snakefile
    Connected to pydev debugger (build 221.5080.212)
    Building DAG of jobs...
    Using shell: /bin/bash
    Provided cores: 4
    Rules claiming more threads will be scaled down.
    Job stats:
    job                   count    min threads    max threads
    ------------------  -------  -------------  -------------
    cache_xml_metadata        1              1              1
    total                     1              1              1

    Select jobs to execute...

    [Wed Apr 27 05:30:46 2022]
    rule cache_xml_metadata:
        input: lots_of_data.xlsx
        output: /Users/xapple/test/proj/one.xml, /Users/xapple/test/proj/two.xml
        jobid: 0
        resources: tmpdir=/var/folders/dt/ng42f7397mg5t2pbxk8bkhzm0000gn/T

    [Wed Apr 27 05:30:48 2022]
    Error in rule cache_xml_metadata:
        jobid: 0
        output: /Users/xapple/test/proj/one.xml, /Users/xapple/test/proj/two.xml

    RuleException:
    TypeError in line 40 of /Users/xapple/repos/proj/proj/workflow/snakefile:
    'EntryGEO' object is not callable
      File "/Users/xapple/repos/proj/proj/workflow/snakefile", line 40, in __rule_cache_xml_metadata
      File "/usr/local/Caskroom/miniconda/base/envs/proj/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    Exiting because a job execution failed. Look above for error message
    Shutting down, this might take some time.
    Exiting because a job execution failed. Look above for error message
    Complete log: ../.snakemake/log/2022-04-27T053043.939165.snakemake.log

    Process finished with exit code 1

Even when going into an interactive `ipython` session to catch the exception and debug it, it doesn't work:

    Shutting down, this might take some time.
    Exiting because a job execution failed. Look above for error message
    Complete log: ../.snakemake/log/2022-04-27T054120.245046.snakemake.log
    ---------------------------------------------------------------------------
    SystemExit                                Traceback (most recent call last)
    File /usr/local/Caskroom/miniconda/base/envs/proj/bin/snakemake:10, in <module>
          8 if __name__ == '__main__':
          9     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    ---> 10     sys.exit(main())

    File /usr/local/Caskroom/miniconda/base/envs/proj/lib/python3.9/site-packages/snakemake/__init__.py:2960, in main(argv)
       2948         profile.sort("totaltime")
       2949         profile.print_all(
       2950             out=out,
       2951             columns={
       (...)
       2957             },
       2958         )
    -> 2960 sys.exit(0 if success else 1)

    SystemExit: 1

    In [1]: debug
    > /usr/local/Caskroom/miniconda/base/envs/proj/lib/python3.9/site-packages/snakemake/__init__.py(2960)main()
       2958             )
       2959
    -> 2960     sys.exit(0 if success else 1)
       2961
       2962

    ipdb> u
    > /usr/local/Caskroom/miniconda/base/envs/proj/bin/snakemake(10)<module>()
          6 from snakemake import main
          7
          8 if __name__ == '__main__':
          9     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    ---> 10     sys.exit(main())

    ipdb> u
    > /usr/local/Caskroom/miniconda/base/envs/proj/lib/python3.9/site-packages/IPython/utils/py3compat.py(55)execfile()
         53     with open(fname, "rb") as f:
         54         compiler = compiler or compile
    ---> 55         exec(compiler(f.read(), fname, "exec"), glob, loc)
         56
         57

    ipdb> u
    > /usr/local/Caskroom/miniconda/base/envs/proj/lib/python3.9/site-packages/IPython/core/interactiveshell.py(2727)safe_execfile()
       2725             try:
       2726                 glob, loc = (where + (None, ))[:2]
    -> 2727                 py3compat.execfile(
       2728                     fname, glob, loc,
       2729                     self.compile if shell_futures else None)

    ipdb> u
    > /usr/local/Caskroom/miniconda/base/envs/proj/lib/python3.9/site-packages/IPython/core/shellapp.py(360)_exec_file()
        358                     else:
        359                         # default to python, even without extension
    --> 360                         self.shell.safe_execfile(full_filename,
        361                                                  self.shell.user_ns,
        362                                                  shell_futures=shell_futures,

    ipdb> u
    *** Oldest frame
    ipdb>

Is there anyway around this, or does the `snakemake` architecture simply not allow for debugging of python code?

**Comment by frazane** [comment]
It would be amazing to have a built-in IDE debugger (for example in VSCode) be able to debug snakemake python files. I used snakemake for a project, and it's a wonderful tool, but the absence of this feature was a major downside and the reason why, for now, I have stopped using it. I introduced other people to snakemake and after some time they were also complaining about the same thing.

If it's really a missing feature I would encourage the authors of the library to consider adding it as it would be a real game changer for a lot of users 😃 and if it's actually already possible but it just needs some extra steps, documenting it would also be very useful.
