### ISSUE TITLE
Relative import in python script not working when using a module from Gitlab

### ISSUE THREAD

**Issue by RomainFeron** [snakemake/snakemake#1632]
**Snakemake version**
7.6.0

**Describe the bug**
I am using a workflow as module in another workflow. In the workflow imported as module, I have a Python script called from a rule with the *script* directive. In this script, I am importing utility functions from a small Python module using relative imports. I'll give a simplified structure below:

*Structure of the workflow imported as module*
```
workflow/
├── rules/
│   └── module.smk           # Where the rule using "module_script.py" is defined
├── scripts
│   ├── module_script.py   # Python script called by Snakemake which imports functions from "utils.py"
│   └── utils.py                   # Small Python module containing utility functions
└── Snakefile
```

*module_script.py*
```Python
from utils import utility_function

utility_function()
... 
```

*utils.py*
```Python
def utility_function():
    ....
... 
```

When I import this module from Gitlab, i.e. with the code:

```Python
module module_to_import:
    snakefile:
        gitlab('module_to_import', path='workflow/Snakefile', tag='1.0.0')
    config:
        test_config
```

I get an import error:

```
from utils import utility_function
ModuleNotFoundError: No module named 'utils'
```

However, if I clone the repository to a local directory and use that, i.e. with the code:

```Python
module module_to_import:
    snakefile:
        'path/to/local/copy/workflow/Snakefile'
    config:
        test_config
```

then it works.

**Logs**

Here is the full log for this job when importing the module from gitlab, although I don't think it adds much:

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Select jobs to execute...

[Wed May  4 10:09:24 2022]
rule buscophile_get_busco_ids_for_a_species:
    output: results/busco_ids/7394.txt, results/assemblies/7394.txt
    log: logs/busco_ids/7394.txt
    jobid: 0
    wildcards: taxid=7394
    resources: mem_mb=8000, disk_mb=1000, tmpdir=/tmp/6479601, runtime_s=3600

Activating conda environment: .snakemake/conda/d2b6660768c6a046bc144a35108390ee
Activating conda environment: .snakemake/conda/d2b6660768c6a046bc144a35108390ee
Traceback (most recent call last):
  File "/work/FAC/FBM/DEE/rwaterho/evofun/romain/wga/datasets/dev/a2a/.snakemake/scripts/tmpaw5cwuhp.get_busco_ids_for_a_species.py", line 7, in <module>
    from utils import setup_logging, load_json_to_dict
ModuleNotFoundError: No module named 'utils'
Not cleaning up /work/FAC/FBM/DEE/rwaterho/evofun/romain/wga/datasets/dev/a2a/.snakemake/scripts/tmpaw5cwuhp.get_busco_ids_for_a_species.py
[Wed May  4 10:09:32 2022]
Error in rule buscophile_get_busco_ids_for_a_species:
    jobid: 0
    output: results/busco_ids/7394.txt, results/assemblies/7394.txt
    log: logs/busco_ids/7394.txt (check log file(s) for error message)
    conda-env: /work/FAC/FBM/DEE/rwaterho/evofun/romain/wga/datasets/dev/a2a/.snakemake/conda/d2b6660768c6a046bc144a35108390ee

RuleException:
CalledProcessError in line 28 of https://gitlab.com/evogenlab/buscophile-public/-/raw/test/workflow/rules/data.smk:
Command 'source /work/FAC/FBM/DEE/rwaterho/evofun/romain/software/miniconda3/bin/activate '/work/FAC/FBM/DEE/rwaterho/evofun/romain/wga/datasets/dev/a2a/.snakemake/conda/d2b6660768c6a046bc144a35108390ee'; set -euo pipefail;  python /work/FAC/FBM/DEE/rwaterho/evofun/romain/wga/datasets/dev/a2a/.snakemake/scripts/tmpaw5cwuhp.get_busco_ids_for_a_species.py' returned non-zero exit status 1.
  File "https://gitlab.com/evogenlab/buscophile-public/-/raw/test/workflow/rules/data.smk", line 28, in __rule_get_busco_ids_for_a_species
  File "/work/FAC/FBM/DEE/rwaterho/evofun/romain/software/miniconda3/envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Minimal example**
It's difficult to provide because it relies on gitlab repos, I can try to make one if really needed.

**Additional context**

**Comment by sreichl** [comment]
Hi,
have you found a solution or workaround?
I have the same issue in R.

```r
# source utility functions
snakemake@source("utils.R")
```

This works only if I use a locally cloned module, but not if I use a module from Github.

Thanks & Cheers,
Stephan

**Comment by RomainFeron** [comment]
Hi,
I haven't found a solution, I ended up using local copies of the repository for my use case, although it was not ideal

**Comment by sreichl** [comment]
Hi,
thanks for letting me know. That is also what I currently do, but that's not how it is supposed to work.

Cheers,
Stephan

**Comment by euronion** [comment]
We're facing the same issue when importing some auxiliary functions from a `scripts/xzy.py` file into `Snakefile` and then attempting to include the repository with that `Snakefile` as a module.

**Comment by sreichl** [comment]
FYI my current solution is that I provide the path to the auxiliary function file as a parameter and then use the parameter to load it inside of the respective script. 

Like here in the rule as parameter
https://github.com/epigen/dea_limma/blob/ae05f273d2eb81e9108a17b7bf30eb37705a8584/workflow/rules/visualize.smk#L58
and here I load it in the script
https://github.com/epigen/dea_limma/blob/ae05f273d2eb81e9108a17b7bf30eb37705a8584/workflow/scripts/heatmap.R#L11

This is R, but should work equally well for python.

Hope this helps. 
Cheers, Stephan
