### ISSUE TITLE
Directory for `--profile` not resolving relative paths

### ISSUE THREAD

**Issue by lczech** [snakemake/snakemake#1654]
Description: The option `--profile` does not seem to correctly resolve relative paths within the given profile files in more recent versions of Snakemake.

## In production code, Snakemake 7.x.x

With Snakemake 7.0.0 and later, I first encountered this in a larger pipeline, where after a call containing
```.sh
snakemake [...] --profile profiles/slurm/
```
the error message was:
```
WorkflowError:
FileNotFoundError: [Errno 2] No such file or directory: 'profiles/slurm/slurm-jobscript.sh'
```
with a `config.yaml` in the provided profile directory that contains the line 
```.yaml
jobscript: "slurm-jobscript.sh"
```
It hence seems that the relative path `profiles/slurm/slurm-jobscript.sh` is constructed correctly with the provided information, but somehow executed from a wrong working directory, or something akin to that.

## In production code, Snakemake 6.1.0

With Snakemake 6.1.0, the error is similar:
```.sh
WorkflowError:
FileNotFoundError: [Errno 2] No such file or directory: 'profiles/slurm/slurm-jobscript.sh'
  File "/home/lczech/miniconda3/envs/grenepipe-snakemake-6.1.0/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 910, in __init__
  File "/home/lczech/miniconda3/envs/grenepipe-snakemake-6.1.0/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 648, in __init__
```

My pipeline works with Snakemake 6.0.5 though, so I suspect that [this Change Log entry](https://snakemake.readthedocs.io/en/stable/project_info/history.html#id142):

> Profiles using –cluster option can now handle relative submit script paths in combination with arguments

is at least part of the problem.

## In minimal example

It get's a little weirder though. 

I then created a [minimal example](https://github.com/snakemake/snakemake/files/8675004/profile_rel_path.zip) for this. It uses my adaptation of a slightly outdated [slurm cookie-cutter profile](https://github.com/Snakemake-Profiles/slurm), but I don't think that particularly matters. 

For simplicity, I changed the path to the profile simply to `slurm/` within the directory of the `Snakefile`. The call is hence
```.sh
cd /home/lczech/tmp_03_profile_rel_path # or wherever you put this
snakemake --profile slurm/
```

However, with that minimal example, the error only occurs starting with Snakemake 7.6.1 (it works with Snakemake 7.6.0), and the error message changes to:
```.sh
Traceback (most recent call last):
  File "slurm/slurm-submit.py", line 48, in <module>
    cluster_config = slurm_utils.load_cluster_config(CLUSTER_CONFIG)
  File "/home/lczech/tmp_03_profile_rel_path/slurm/slurm_utils.py", line 31, in load_cluster_config
    dcc = io.load_configfile(path)
  File "/home/lczech/miniconda3/envs/snakemake-7.6.1/lib/python3.7/site-packages/snakemake/io.py", line 1644, in load_configfile
    config = _load_configfile(configpath)
  File "/home/lczech/miniconda3/envs/snakemake-7.6.1/lib/python3.7/site-packages/snakemake/io.py", line 1609, in _load_configfile
    obj = open(configpath_or_obj, encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: '/home/lczech/tmp_03_profile_rel_path/slurm/slurm/cluster_config.yaml'
Error submitting jobscript (exit code 1):
```

Looking at the `FileNotFoundError` line, it seems that an additional `slurm/` sneaked its way into that path somehow, meaning that the last segment provided by the `--profile` path is somehow duplicated.

No idea why this error and the version where it occurs are different from the one in my production pipeline, but it might be caused by the same bug - hence, for now, I will not try to create another minimal example to re-create the first bug above.

**Comment by claczny** [comment]
I seem to encounter this bug too.
I have tried first the official, cookiecutter SLURM profiles and ran into this error.
When using the simple profile solution from https://github.com/jdblischak/smk-simple-slurm, it works, i.e., I can submit jobs to our HPC.

However, when I specify a custom jobscript in the `config.yaml`, I am also getting this error (`FileNotFoundError: [Errno 2] No such file or directory:`).
I need the custom jobscript, though, as our HPC seems to require a login bash, whereas the default is to use a regular bash/shell.

**Comment by claczny** [comment]
Brief update: When using `--cluster-status $PWD/profiles/slurm-iris/status-sacct-robust.sh` or `--jobscript $PWD/profiles/slurm-iris/jobscript.sh`, i.e., explicitly specifying the _absolute_ paths via the command line, it works fine for me.
However, that partially defeats the point of having a `profile` in the first place.
Hence, resolving this bug remains to be important IMO.

Best wishes and stay safe,

Cedric

**Comment by pvandyken** [comment]
@lczech, I'm not able to reproduce your minimal example using snakemake v7.16.1+1.g05d92e0a

Do your examples work on the latest version of snakemake?

**Comment by claczny** [comment]
I just revisited this issue in another context. The issue in my case seems to indeed stem from the use of `workdir: "results"`. When I include `jobscript: "../PATH/TO/PROFILES/jobscript.sh"`, i.e., do this relative and go "one-folder-up" (`..`), it works fine.
Same for `cluster-status:`.
