### ISSUE TITLE
CWL export: 'Job' object has no attribute 'conda_env_file'

### ISSUE THREAD

**Issue by zyzzyxdonta** [snakemake/snakemake#1668]
**Snakemake version**

7.7.0

**Describe the bug**

Running `snakemake --export-cwl example.cwl` prints `AttributeError: 'Job' object has no attribute 'conda_env_file'`

**Logs**

```
Building DAG of jobs...
Unable to retrieve additional files from git. This is not a git repository.
Traceback (most recent call last):
  File "/home/pape58/Code/sota_on_uncertainties/venv/lib64/python3.10/site-packages/snakemake/__init__.py", line 722, in snakemake
    success = workflow.execute(
  File "/home/pape58/Code/sota_on_uncertainties/venv/lib64/python3.10/site-packages/snakemake/workflow.py", line 911, in execute
    json.dump(dag_to_cwl(dag), cwl, indent=4)
  File "/home/pape58/Code/sota_on_uncertainties/venv/lib64/python3.10/site-packages/snakemake/cwl.py", line 257, in dag_to_cwl
    dag_cwl = [job_to_cwl(job, dag, outputs, inputs) for job in groups]
  File "/home/pape58/Code/sota_on_uncertainties/venv/lib64/python3.10/site-packages/snakemake/cwl.py", line 257, in <listcomp>
    dag_cwl = [job_to_cwl(job, dag, outputs, inputs) for job in groups]
  File "/home/pape58/Code/sota_on_uncertainties/venv/lib64/python3.10/site-packages/snakemake/cwl.py", line 102, in job_to_cwl
    if job.conda_env_file:
AttributeError: 'Job' object has no attribute 'conda_env_file'
```

**Minimal example**

Directory looks like this:

```
.
├── data
│   ├── genome.fa
│   └── samples
│       ├── A.fastq
│       └── B.fastq
├── scripts
│   └── plot-quals.py
└── Snakefile

3 directories, 5 files
```

The `Snakefile` is the example from [here](https://snakemake.readthedocs.io/en/stable/tutorial/basics.html). All other files are empty.

**Additional context**

**Comment by pdagosto** [comment]
I've seen this also. My context is a Snakefile that has run directives containing python code in one or more rules, e.g.

```
rule map_reads:
	input:
		index=multiext(ref, '.amb', '.ann', '.bwt', '.pac', '.sa'),
		reads=expand('{t}_S2_{l}.paired.fastq', t=taid, l=labels)
	output:
		'{0}.sam'.format(taid)
	run:
		input_files=' '.join(input.reads)
		shell('bwa mem {ref} {input_files} > {output}')
```

**Comment by pdagosto** [comment]
Does anyone have any idea about this? Using --use-conda or --conda-prefix does not seem to solve the problem.? The place in the code that generates this Python error is:

cwl.py:102:    if job.conda_env_file:

It's not obvious to me how I would make the job object have a conda_env_file.

**Comment by Nuwah12** [comment]
Anything on this issue?

**Comment by fgypas** [comment]
I am also running into this.

**Comment by YasCoMa** [comment]
I "solved" commenting the lines 102 and 103. At least it generated the cwl file :)

**Comment by thamnos** [comment]
Same here on Ubuntu 24.04 with snakemake version 7.32.4 and without any conda installed.

Maybe possible solution:
replace in cwl.py line 98/99 by
```python
    try:
        files.add(os.path.relpath(job.conda_env_file))
    except AttributeError:
        pass
```
