### ISSUE TITLE
Defaults in config.yaml schema validation are not set before validation

### ISSUE THREAD

**Issue by martijnvanattekum** [snakemake/snakemake#1701]
**Snakemake version**
7.8.0

**Describe the bug**
I have the following config.yaml file
```
project_name: project15
```
and the following schema
```
$schema: "https://json-schema.org/draft/2020-12/schema"
properties:
  project_name:
    default: "my_project"
    type: string
```

This correctly validates when I use Snakemake's validate function:
```
from snakemake.utils import validate
import yaml
with open('config.yaml') as file:
     config = yaml.safe_load(file)

validate(config, "config.schema.yaml")
```

But when I try to use the default by leaving out the value for `project_name` or setting it to `null` 
```
project_name:
```
the validation fails with the following error:
```
Traceback (most recent call last):
  File "<...>/lib/python3.10/site-packages/snakemake/utils.py", line 146, in validate
    DefaultValidator(schema, resolver=resolver).validate(data)
  File "<...>/miniconda3/envs/scairap_new/lib/python3.10/site-packages/jsonschema/validators.py", line 267, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type 'string'

Failed validating 'type' in schema['properties']['project_name']:
    OrderedDict([('default', 'my_project'), ('type', 'string')])

On instance['project_name']:
    None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<...>/snakemake_validation/validate.py", line 6, in <module>
    validate(config, "config.schema.yaml")
  File "<...>/miniconda3/envs/scairap_new/lib/python3.10/site-packages/snakemake/utils.py", line 150, in validate
    raise WorkflowError("Error validating config file.", e)
snakemake.exceptions.WorkflowError: Error validating config file.
ValidationError: None is not of type 'string'

Failed validating 'type' in schema['properties']['project_name']:
    OrderedDict([('default', 'my_project'), ('type', 'string')])

On instance['project_name']:
    None
```

**Expected behaviour**
As outlined in https://python-jsonschema.readthedocs.io/en/latest/faq/

> we add the default properties to each object before the properties are validated, so the default values themselves will need to be valid under the schema

This seems to be not the case, because when the default would have been set _before_ validation, it would be of type `str`, rather than `None`.
This way, using defaults is not possible in general, as not defining a value will always lead to a type mismatch.

**Comment by martijnvanattekum** [comment]
> Is there a version of snakemake where this default setting behavior worked in the past? It seems like a highly desirable feature to avoid configuration bloat in yaml files.

I also just tried with Snakemake 5.6, which throws the same error, so it seems to have been present for a while.

**Comment by martijnvanattekum** [comment]
After some more research, it seems there is a difference between 1) parameters that are not contained in the config and 2) parameters that are contained but not set (i.e. are null). Only in case 1 will defaults be set, which I feel is a bit counterintuitive.

When one wants to have defaults set for case 2 as well, this can be achieved by (recursively) removing parameters that are `None` before calling validate(), e.g. via
```
def remove_empty_values(dictionary: dict):
    """Recursively removes key-value pairs from dict for which the value is None
    Works for an arbitrarily deeply nested dict
    """
    new_dictionary = dict()
    for key, value in dictionary.items():
        if isinstance(value, dict):
            new_dictionary[key] = remove_empty_values(value)
        elif value is None:
            pass
        else:
            new_dictionary[key] = value

    return new_dictionary
```

This behaviour is the same in the `jsonschema` package, so this seems to be Snakemake-unrelated. Closing this.
