### ISSUE TITLE
`snakemake-wrappers` rules cannot be used without a conda `environment.yaml` file

### ISSUE THREAD

**Issue by cilliannolan** [snakemake/snakemake#1718]
**7.8.1**

**Describe the bug**
Newest version of snakemake introduces an issue where local `snakemake-wrappers` cannot be used without a conda `environment.yaml` file.

**Logs**
`Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] No such file or directory: 'snakemake-wrappers/bio/picard/createsequencedictionary/environment.yaml'`

**Minimal example**
`
# Clone snakemake-wrappers locally
git clone git@github.com:snakemake/snakemake-wrappers.git

# Remove a environment.yaml file
rm snakemake-wrappers/bio/picard/createsequencedictionary

# Create a dummy snakemake file:
cat > reprex.smk <<EOF

rule all:
    input:
        "ref.dict",

rule reprex:
    input:
        "ref.fa",
    output:
        "ref.dict"
    log:
        "stderr"
    wrapper:
        "file:snakemake-wrappers/bio/picard/createsequencedictionary"
EOF
```

Create conda environments and run the snakemake script:

`
mamba create -n snakemake_7.8.0 -c conda-forge -c bioconda -n snakemake_7.8.0 snakemake=7.8.0 snakemake-wrapper-utils
conda activate snakemake_7.8.0
snakemake -s reprex.smk -c1
`

This fails with the following message (desired behaviour, as the wrapper script is run): 

`
Traceback (most recent call last):
  File "/projects/AMSIM_upgrade/reprex_smk/.snakemake/scripts/tmpp_86ruma.wrapper.py", line 21, in <module>
    shell(
  File "/home/c.nolan/miniconda3/envs/snakemake_7.8.0/lib/python3.10/site-packages/snakemake/shell.py", line 296, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  picard CreateSequenceDictionary   --REFERENCE ref.fa --TMP_DIR /tmp/tmpearzfndr --OUTPUT ref.dict  2> stderr' returned non-zero exit status 127.
`

Snakemake 7.8.1 behaviour:

`
mamba create -n snakemake_7.8.1 -c conda-forge -c bioconda -n snakemake_7.8.1 snakemake=7.8.1 snakemake-wrapper-utils
conda activate snakemake_7.8.1
snakemake -s reprex.smk -c1
`

This fails to even run the wrapper script, as there is no `environment.yaml` file present.

`
Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] No such file or directory: 'snakemake-wrappers/bio/picard/createsequencedictionary/environment.yaml'
`

**Additional context**
This is a problem for our workflow as we use a private github repo where we have created `snakemake-wrappers` scripts for frequently used functions, which have docker images passed as params.

**Comment by hermidalc** [comment]
I'm seeing this issue in 7.8.5 as well. Some wrappers do not require any special environment other than `snakemake` and `snakemake-wrapper-utils` which are already installed in the env where the workflow is launched. The workaround now is to create an `environment.yaml` with just `python`

**Comment by tedil** [comment]
> I'm seeing this issue in 7.8.5 as well. Some wrappers do not require any special environment other than `snakemake` and `snakemake-wrapper-utils` which are already installed in the env where the workflow is launched. The workaround now is to create an `environment.yaml` with just `python`

This workaround does not work in the case of containers which ship their own python env setup, such as the broadinstitute/gatk docker images; here we have to use the container's env instead of a new (empty) environment which does not have the correct packages installed/modules available (in this case gcnvkernel).

**Comment by gernophil** [comment]
Sorry to dig this up, but I just stumbled across a similar issue with snakemake 9.19.0. I'm getting this error:
```
...
WorkflowError:
Conda environment for wrapper v9.4.2/bio/gdc-client/download not accessible. Please check the name of the wrapper and your wrapper prefix.
...
```
the same happens for v3.3.0 of the same wrapper. Surprisingly, the same wrapper does work with snakemake 7.32.4.
