### ISSUE TITLE
Export to cwl fails with FileNotFoundError

### ISSUE THREAD

**Issue by wd15** [snakemake/snakemake#1792]
**Snakemake version**

7.12.0

**Describe the bug**

`snakemake --export-cwl workflow.cwl` fails with `FileNotFoundError`.

**Logs**

```
Traceback (most recent call last):
  File "/nix/store/wlvg4adricj130jxpiyly53q767kxf66-snakemake-7.12.0/lib/python3.9/site-packages/snakemake/__init__.py", line 730, in snakemake
    success = workflow.execute(
  File "/nix/store/wlvg4adricj130jxpiyly53q767kxf66-snakemake-7.12.0/lib/python3.9/site-packages/snakemake/workflow.py", line 856, in execute
    json.dump(dag_to_cwl(dag), cwl, indent=4)
  File "/nix/store/wlvg4adricj130jxpiyly53q767kxf66-snakemake-7.12.0/lib/python3.9/site-packages/snakemake/cwl.py", line 231, in dag_to_cwl
    {"class": "File", "location": f} for f in dag.get_sources()
  File "/nix/store/wlvg4adricj130jxpiyly53q767kxf66-snakemake-7.12.0/lib/python3.9/site-packages/snakemake/dag.py", line 2562, in get_sources
    out = subprocess.check_output(
  File "/nix/store/vzqny68wq33dcg4hkdala51n5vqhpnwc-python3-3.9.12/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/vzqny68wq33dcg4hkdala51n5vqhpnwc-python3-3.9.12/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/vzqny68wq33dcg4hkdala51n5vqhpnwc-python3-3.9.12/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/vzqny68wq33dcg4hkdala51n5vqhpnwc-python3-3.9.12/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

**Minimal example**

```
rule all:
    input: "hello.txt"
    output: "hello_again.txt"
    shell:
        "cat hello.txt > hello_again.txt"
```

**Additional context**

The snakemake file is in a git repository and unchanged since last commit.

**Comment by rmoran7** [comment]
Any workaround for this ?
