### ISSUE TITLE
GurobiError caused by pulp checking for all available licenses when snakemake is initialised

### ISSUE THREAD

**Issue by Tomkourou** [snakemake/snakemake#1801]
**Snakemake version**
7.10.0

**Describe the bug**

When gurobipy is installed in the conda environment snakemake will use pulp to check whether a license is available before running your snakemake workflow. This essentially blocks one license presenting a problem when you want to use your Gurobi license for solving a problem. The error message even appears when you use another solver for your problem because pulp is checking for all available solvers. I suspect addressing this would also fix  #845. 

I have had success fixing this issue by using a forked version of Snakemake and removing this [code snippet ](https://github.com/snakemake/snakemake/blob/9da571f29c3e4b2c77f8465edcb7e21c91f5feb7/snakemake/__init__.py#L1416-L1423)

Happy to make a PR and remove this code snippet if you it doesn't cause other issues. 

**Logs**

```
INFO:pypsa.io:Imported network elec.nc has buses, generators, links, loads, storage_units, stores
INFO:pypsa.io:Exported network presolved_final.nc has links, buses, storage_units, generators, loads, stores
######## Solving model with Gurobi
INFO:pypsa.linopf:Prepare linear problem
INFO:pypsa.linopf:Total preparation time: 1.0s
INFO:pypsa.linopf:Solve linear problem using Gurobi solver
Set parameter ServerPassword
Set parameter TokenServer to value "server.name"
Traceback (most recent call last):
  File "/home/thomas/Agora/Modelling/PyPSA-VN/.snakemake/scripts/tmp69seqy3x.solve_network.py", line 150, in <module>
    n = solve_network(n, year, solver=solver, config=snakemake.config)
  File "/home/thomas/Agora/Modelling/PyPSA-VN/.snakemake/scripts/tmp69seqy3x.solve_network.py", line 75, in solve_network
    n.lopf(
  File "/home/thomas/anaconda3/envs/pypsa-ago/lib/python3.10/site-packages/pypsa/components.py", line 660, in lopf
    return network_lopf_lowmem(self, **args)
  File "/home/thomas/anaconda3/envs/pypsa-ago/lib/python3.10/site-packages/pypsa/linopf.py", line 1241, in network_lopf
    res = solve(n, problem_fn, solution_fn, solver_logfile,
  File "/home/thomas/anaconda3/envs/pypsa-ago/lib/python3.10/site-packages/pypsa/linopt.py", line 992, in run_and_read_gurobi
    m = gurobipy.read(problem_fn)
  File "src/gurobipy/gurobi.pxi", line 3575, in gurobipy.read
  File "src/gurobipy/gurobi.pxi", line 84, in gurobipy.gurobi.read
  File "src/gurobipy/gurobi.pxi", line 32, in gurobipy.gurobi._getdefaultenv
  File "src/gurobipy/env.pxi", line 62, in gurobipy.Env.__init__
gurobipy.GurobiError: Request denied: use limit (2) exceeded

```

**Comment by yangchen2** [comment]
Thank you, this worked for me too

**Comment by tgi-climact** [comment]
I did had the same issue. I've forked the latest version available to apply the same patch. See [here](https://github.com/tgi-climact/snakemake/tree/fix/gurobi-pulp).

I used [this](https://snakemake.readthedocs.io/en/stable/getting_started/installation.html#installation-of-a-development-version-via-pip) from the documentation to get it running locally.

```bash
conda activate myenv
pip install git+https://github.com/tgi-climact/snakemake.git@fix/gurobi-pulp
```

**Snakemake version**
v7.32.3

**Comment by tgi-climact** [comment]
I did had the same issue. I've forked the latest version available to apply the same patch. See [here](https://github.com/tgi-climact/snakemake/tree/fix/gurobi-pulp).

I used [this](https://snakemake.readthedocs.io/en/stable/getting_started/installation.html#installation-of-a-development-version-via-pip) from the documentation to get it running locally.

```bash
conda activate myenv
pip install git+https://github.com/tgi-climact/snakemake.git@fix/gurobi-pulp
```

**Snakemake version**
v7.32.3

**Comment by torressa** [comment]
Note this has been fixed on the PuLP side. Just waiting on a release.

**Comment by drifter089** [comment]
saved us hours after wasting a bunch :}

**Comment by tgilon** [comment]
I still needed to fix the version v9.5.1 using the same patch. 

Installing this worked for me:
```bash
pip install git+https://github.com/tgilon/snakemake.git@fix/gurobi-pulp-v9.5.1
```
