### ISSUE TITLE
Cannot install Snakemake with conda/mamba

### ISSUE THREAD

**Issue by mradz19** [snakemake/snakemake#1807]
I am trying to install snakemake as described by the tutorial. These lines of code work fine:
```
conda install -n base -c conda-forge mamba
conda activate base
```
However when I run:
```
mamba create -c conda-forge -c bioconda -n snakemake snakemake
```
I get this error:
```
Traceback (most recent call last):
  File "/kusers/ancillary/mradzieta/anaconda3/bin/mamba", line 11, in <module>
    sys.exit(main())
  File "/kusers/ancillary/mradzieta/anaconda3/lib/python3.8/site-packages/mamba/mamba.py", line 848, in main
    from conda.common.compat import ensure_text_type, init_std_stream_encoding
ImportError: cannot import name 'init_std_stream_encoding' from 'conda.common.compat' (/kusers/ancillary/mradzieta/anaconda3/lib/python3.8/site-packages/conda/common/compat.py)
```

**Comment by john-hen** [comment]
I, for one, cannot reproduce that error. But since the error occurs in Mamba, this is not a bug *in Snakemake*.

**Comment by SultanOrazbayev** [comment]
FWIW, there's [a related SO question here](https://stackoverflow.com/q/73314292/10693596).
