### ISSUE TITLE
ValueError:  min() arg is an empty sequence

### ISSUE THREAD

**Issue by alienzj** [snakemake/snakemake#1815]
```
➤ snakemake --snakefile mag_wf.smk --configfile ./config.yaml --cores 240 --until raw_report --rerun-incomplete --keep-going --printshellcmds --reason --local-cores 8 --jobs 30

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 240
Rules claiming more threads will be scaled down.
Conda environments: ignored
Traceback (most recent call last):
  File "/home/jiezhu/.conda/envs/bioenv3.9/lib/python3.9/site-packages/snakemake/__init__.py", line 730, in snakemake
    success = workflow.execute(
  File "/home/jiezhu/.conda/envs/bioenv3.9/lib/python3.9/site-packages/snakemake/workflow.py", line 1026, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/home/jiezhu/.conda/envs/bioenv3.9/lib/python3.9/site-packages/snakemake/dag.py", line 2408, in stats
    "min threads": min(min_threads.values()),
ValueError: min() arg is an empty sequence
```

Dear snakemake developer,
how to avoid `ValueError: min() arg is an empty sequence`?

**Comment by dariober** [comment]
Can you provide the information asked by the bug report template? In particular, can you post a minimal example reproducing the error and the snakemake version?

**Comment by alienzj** [comment]
### Version
```
$ snakemake --version
7.12.0
```

### Example
```
# Installation
mamba create -n metapi -c conda-forge -c bioconda metapi=2.3.0
conda activate metapi

# Prepare working dir
mkdir -p test_metapi
cd test_metapi

# Download test data
wget https://raw.githubusercontent.com/ablab/spades/spades_3.15.5/assembler/test_dataset/ecoli_1K_1.fq.gz
wget https://raw.githubusercontent.com/ablab/spades/spades_3.15.5/assembler/test_dataset/ecoli_1K_2.fq.gz

# Prepare samples.tsv
fd -t f -d 1 fq.gz . | \
sort | uniq | paste - - | \
awk 'BEGIN {print "sample_id\tassembly_group\tbinning_group\tfq1\tfq2"};{print "ecoli_1K\tecoli_1K\tecoli_1K\t" $0}' \
> samples.tsv

# Init
metapi init -d . -s samples.tsv -b assembly --assembler spades

# Run
metapi mag_wf assembly_all --run-local --use-conda
```

When it was finished, rerun metapi,
```
metapi mag_wf assembly_all --run-local --use-conda
```
We will meet the `ValueError: min() arg is an empty sequence`.

Thanks!

**Comment by johnbradley** [comment]
I was able to reproduce this error using the `snakemake/snakemake:v7.12.1` Docker image.
First I created a **Snakefile** with multiple rules:
```
rule all:
    input:
        "results/two.txt"

rule create_one:
    output:
        "results/one.txt"     
    shell:
        "date > {output}"

rule create_two:
    input:
        "results/one.txt"
    output:
        "results/two.txt"
    shell:
        "cp {input} {output}"
```

Then I run snakemake stopping at the first rule (**which works correctly**):
```
$ snakemake -c1 --until create_one
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
...
1 of 3 steps (33%) done
Complete log: .snakemake/log/2022-08-23T205011.042482.snakemake.log
```

Running the same command again fails with the ValueError:
```
$ snakemake -c1 --until create_one
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Traceback (most recent call last):
  File "/opt/conda/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 724, in snakemake
    success = workflow.execute(
  File "/opt/conda/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 1022, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/opt/conda/envs/snakemake/lib/python3.10/site-packages/snakemake/dag.py", line 2382, in stats
    "min threads": min(min_threads.values()),
ValueError: min() arg is an empty sequence
```

---

The problem seems to occur when there is no further processing necessary due to the `--until <rulename>` argument, but there is additional processing that would be done if run without this argument. So in my case when `results/one.txt` exists and `results/two.txt` doesn't printing `Job stats` fails. If I run `touch results/two.txt` the 
```
snakemake -c1 --until create_one
``` 
runs fine.

**Comment by jhschwartz** [comment]
Can confirm occurs for me as well in 7.25.3, specifically only when I call "--until" and there is nothing left to do until the rule specified. I'm going to upgrade to 7.28.3 and report back if it still happens.

**Comment by jhschwartz** [comment]
Because 7.28.3 is not yet available on bioconda, I tried with 7.25.2. I can confirm this bug still exists. The updated trace is below:

```
env/bin/python -m snakemake -s workflow/1_derive_dimers.smk --until pairs_needing_contact_calc --profile $smk_profile -n
Building DAG of jobs...
Traceback (most recent call last):
  File "/expanse/lustre/projects/mia174/jaschwa/dimerDB/env/lib/python3.8/site-packages/snakemake/__init__.py", line 770, in snakemake
    success = workflow.execute(
  File "/expanse/lustre/projects/mia174/jaschwa/dimerDB/env/lib/python3.8/site-packages/snakemake/workflow.py", line 1044, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/expanse/lustre/projects/mia174/jaschwa/dimerDB/env/lib/python3.8/site-packages/snakemake/dag.py", line 2482, in stats
    "min threads": min(min_threads.values()),
ValueError: min() arg is an empty sequence
```

**Comment by jhschwartz** [comment]
In [`dag.py` line 2482](https://github.com/snakemake/snakemake/blob/ab58c652847c03a9f1529d2d7632f2788a5fadc4/snakemake/dag.py#LL2482C1-L2483C1), min (and max in 2483) could be given the kwarg "default", setting to either 0 or 1 as a simple fix of this issue. I'm not sure, though, if this fits the needs of the rest of snakemake.
