### ISSUE TITLE
TypeError: can only concatenate str (not "tuple") to str when mamba is not installed

### ISSUE THREAD

**Issue by dkoppstein** [snakemake/snakemake#1828]
**Snakemake version**
7.12.1

**Describe the bug**

If mamba is not installed, we get `TypeError: can only concatenate str (not "tuple") to str` instead of a helpful error message. This is because of an extra comma [here](https://github.com/snakemake/snakemake/blob/main/snakemake/deployment/conda.py#L732). 

**Logs**

```
Building DAG of jobs...
Traceback (most recent call last):
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/deployment/conda.py", line 697, in _check
    shell.check_output(self._get_cmd(locate_cmd), stderr=subprocess.STDOUT)
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 63, in check_output
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'type mamba' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 730, in snakemake
    success = workflow.execute(
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 919, in execute
    dag.create_conda_envs(
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/dag.py", line 319, in create_conda_envs
    env.create(dryrun)
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/deployment/conda.py", line 393, in create
    pin_file = self.pin_file
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/common/__init__.py", line 192, in __get__
    value = self.method(instance)
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/deployment/conda.py", line 109, in pin_file
    f".{self.conda.platform}.pin.txt"
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/common/__init__.py", line 192, in __get__
    value = self.method(instance)
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/deployment/conda.py", line 102, in conda
    return Conda(
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/deployment/conda.py", line 670, in __init__
    self._check()
  File "/localenv/koppstein/anaconda/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/deployment/conda.py", line 726, in _check
    msg += (
TypeError: can only concatenate str (not "tuple") to str
```

**Minimal example**

*Do this in an environment without mamba, i.e. `conda remove mamba`*

```
# utils.yaml
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15=ha878542_0
  - htslib=1.15.1=h9753748_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - libcurl=7.83.1=h7bff187_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgomp=12.1.0=h8d9b700_16
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libzlib=1.2.12=h166bdaf_2
  - ncurses=6.3=h27087fc_1
  - openssl=1.1.1q=h166bdaf_0
  - samtools=1.15.1=h1170115_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.12=h166bdaf_2
```

```
# Snakefile
rule echo:
    output: "test.txt"
    conda: "utils.yaml"
    shell: "echo 'hi'; touch {output}"
```

```
$ snakemake -j1 --use-conda
```

**Additional context**

**Comment by dkoppstein** [comment]
OK, and I just saw that there is a PR that addresses it [here](https://github.com/snakemake/snakemake/pull/1804), so I will already close this.
