### ISSUE TITLE
"TypeError: '>' not supported between instances of 'TBDString' and 'int'"when setting rule threads with input.size

### ISSUE THREAD

**Issue by AngLi9849** [snakemake/snakemake#1850]
I am trying to make a featurecounts rule ask for nodes adaptively based on input bam file sizes. Hence I tried to set the threads variable like this:

_threads: lambda wildcards, input: (int(input.size//10000000000) + 3)_

And this triggered the following type error:

_Traceback (most recent call last):
  File "/data/user/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/data/user/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 1062, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/data/user/envs/snakemake/lib/python3.10/site-packages/snakemake/dag.py", line 2169, in stats
    max_threads[job.rule] = max(max_threads[job.rule], job.threads)

**TypeError: '>' not supported between instances of 'TBDString' and 'int'**_

Whereas setting threads to a fixed number (e.g. 8) fixes it.

Is there a way to bypass the max rule threads check by setting the threads variable differently?

**Comment by dariober** [comment]
I suspect `input.size` is a string so maybe you want:

```
 lambda input: (int(input.size)//10000000000) + 3
```

**Comment by AngLi9849** [comment]
Thanks for the reply dariober, int() the input.size variable did not solve it.

I think the issue rose from that snakemake tried to compare a TBD resource tag, which arises from the input.size wildcard variable, to a integer total thread number. 

I have gotten this trick to work with dynamic mem, but it does not work on threads, which is what I trully need.

An alternative I am thinking of is whether I can divide a large bam file into separate smaller ones, featurecount them then add them back together, but I am not sure whether this would break accuracy of featurecount
