### ISSUE TITLE
Snakemake crashes with AttributeError: 'str' object has no attribute 'name

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [snakemake/snakemake#1892]
**Snakemake version**
snakemake --version
7.15.1

**Describe the bug**
The snakemake process crashes on a minimal workflow.

**Logs**
```bash
$ snakemake --snakefile test.smk  -c 1
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/HAMLET/lib/python3.10/site-packages/snakemake/__init__.py", line 733, in snakemake
    success = workflow.execute(
  File "/home/user/miniconda3/envs/HAMLET/lib/python3.10/site-packages/snakemake/workflow.py", line 1031, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/home/user/miniconda3/envs/HAMLET/lib/python3.10/site-packages/snakemake/dag.py", line 2415, in stats
    yield tabulate(rows, headers="keys")
  File "/home/user/miniconda3/envs/HAMLET/lib/python3.10/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/home/user/miniconda3/envs/HAMLET/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/user/miniconda3/envs/HAMLET/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/user/miniconda3/envs/HAMLET/lib/python3.10/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/home/user/miniconda3/envs/HAMLET/lib/python3.10/site-packages/snakemake/rules.py", line 1222, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
```

**Minimal example**
```Snakemake
rule all:
    input: "test.out"

rule make_out:
    output: "test.out"
    shell: "touch {output}"
```

**Additional context**

**Comment by karl-az** [comment]
Happens on my system as well

**Comment by descostesn** [comment]
it is happening to everybody I guess

**Comment by karl-az** [comment]
Tried to roll back to older versions. Could it be the new release of tabulate: https://pypi.org/project/tabulate/#history?

**Comment by ftabaro** [comment]
See issue #1891

**Comment by nh13** [comment]
hitting this as well

**Comment by vsmalladi** [comment]
Hit this as well.

**Comment by standage** [comment]
Yep
