### ISSUE TITLE
Snakemake --profile slurm --dry-run showing AttributeError

### ISSUE THREAD

**Issue by JoshLoecker** [snakemake/snakemake#1908]
**Snakemake version**
I am on version 6.15.5, which is a bit outdated. I've been able to reproduce this multiple times within the same workflow after uninstalling and re-installing my entire conda environment

**Describe the bug**

When running `snakemake --profile slurm --dry-run`, I am getting an AttributeError saying `'str' object has no attribute 'name'`

**Logs**

These are the full logs I am receiving
```
Traceback (most recent call last):
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 701, in snakemake
    success = workflow.execute(
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 1066, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/snakemake/dag.py", line 2191, in stats
    yield tabulate(rows, headers="keys")
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/snakemake/rules.py", line 1138, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
```

**Comment by troycomi** [comment]
Getting a similar error with 7.3.8.  Looks like the tabulate dependency is the cause.  Try pinning tabulate to 0.8.11, not sure of the long-term fix.

**Comment by JoshLoecker** [comment]
This fixed the issue. I've locked to version 0.8.10, as this was the newest version I could [find on PyPi](https://pypi.org/project/tabulate/#history)

**Comment by JoshLoecker** [comment]
Closing this issue as I'm not sure there is anything else that can be done here
