### ISSUE TITLE
suggest restricting version ranges of more dependencies in pyproject.toml

### ISSUE THREAD

**Issue by ctb** [snakemake/snakemake#1989]
**Is your feature request related to a problem? Please describe.**

We recently ran into a problem in genome-grist where a pinned version of snakemake (v6.12.3) broke because the tabulate version was not pinned and tabulate v0.9.0 broke snakemake v6.12.3.

Updating snakemake to v7.18.12 (latest) fixed it, as did reverting to snakemake v6.12.3 together with installing tabulate v0.8.10.

**Describe the solution you'd like**

I'm taking steps to prevent this from happening in my own software (it affected both genome-grist and [spacegraphcats](https://github.com/spacegraphcats/spacegraphcats/issues/471)) by running tests regularly, and also enabling dependabot so that I update snakemake regularly.

But, I think snakemake might consider putting more version requirements on its dependent software; right now there are many unpinned dependencies in [setup.py](https://github.com/snakemake/snakemake/blob/main/setup.py) without upper ranges:

```
   "wrapt",
        "requests",
        "throttler",
        "pyyaml",
        "configargparse",
        "appdirs",
        "datrie",
        "jsonschema",
        "docutils",
        "gitpython",
        "psutil",
        "nbformat",
        "toposort",
        "connection_pool >=0.0.3",
        "pulp >=2.0",
        "smart_open >=3.0",
        "stopit",
        "tabulate",
        "reretry"
```

and at least some of them are going to be runtime requirements.

Happy to help out if this is of interest!

thanks for considering!

**Comment by ferrarimarco** [comment]
Hi folks! I think a recent update to one of snakemake dependencies (`pulp`, version `2.8.0`, release 4 hrs ago) is causing issues when running snakemake.

It would be beneficial to add more constraints, like the OP is suggesting. Thanks!

Logs:
```
Traceback (most recent call last):
#126 11.06   File "/venvs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2037, in main
#126 11.06     parser, args = parse_args(argv)
#126 11.06                    ^^^^^^^^^^^^^^^^
#126 11.06   File "/venvs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 1629, in parse_args
#126 11.06     parser = get_argument_parser()
#126 11.06              ^^^^^^^^^^^^^^^^^^^^^
#126 11.06   File "/venvs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 770, in get_argument_parser
#126 11.06     lp_solvers = pulp.list_solvers(onlyAvailable=True)
#126 11.06                  ^^^^^^^^^^^^^^^^^
#126 11.06 AttributeError: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?. Error code: 1
#126 11.06 2024-01-12 14:06:56 [FATAL]   [snakemake]: Failed to get version info: Traceback (most recent call last):
#126 11.06   File "/venvs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2037, in main
#126 11.06     parser, args = parse_args(argv)
#126 11.06                    ^^^^^^^^^^^^^^^^
#126 11.06   File "/venvs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 1629, in parse_args
#126 11.06     parser = get_argument_parser()
#126 11.06              ^^^^^^^^^^^^^^^^^^^^^
#126 11.06   File "/venvs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 770, in get_argument_parser
#126 11.06     lp_solvers = pulp.list_solvers(onlyAvailable=True)
#126 11.06                  ^^^^^^^^^^^^^^^^^
```

**Comment by muelli** [comment]
`pip install --upgrade 'pulp<2.8' `
help me.

**Comment by zmbc** [comment]
Restricting versions just causes the opposite problem: Then you can get snakemake saying it _isn't_ compatible with something that it actually _is_ compatible with. In many ways this is worse as it can lead to no valid solution to your requirements at all if you have lots of dependencies with tightly restricted subdependency versions.

The crux of the problem is that, when a snakemake version is published, its compatibility with versions of dependencies **that haven't come out yet** is (of course) unknown. Yet the entire package management ecosystem (not just in Python but in every language I've come across) requires this metadata -- are version X.Y.Z of foo and version A.B.C of bar compatible? -- from the _depending_ package, rather than from the _last-published_ package (which is the only one that can check) or from neither and crowdsourcing this information.

**Comment by ctb** [comment]
Hi @zmbc thanks, I take your point and I kinda wish people would do more with semantic versioning in general :).

Being overly restrictive with version dependencies _would_ mean that an installed and functioning version of snakemake would not suddenly break when something _else_ was installed, nor would it fail to suddenly work on a new installation a released version, as happened above.

It could mean that snakemake wouldn't be installable in certain circumstances, as you say.

I would personally prioritize the former over the latter, from a UI perspective.

**Comment by zmbc** [comment]
@ctb SemVer gives you only a little bit more ability to do the (fundamentally impossible) task of predicting the future.

What I mean is, if I am publishing package A that depends on package B, at the time I hit publish I am asked what is the _last_ version of B that will work with my current version of A. I can obviously test up to the latest extant version of B, so that is a good lower bound on my answer to that question. If I really trust B's SemVer practices, and only use its public API, then I can additionally predict that any patch releases on the same minor version will also work. But that doesn't mean that the next minor (or even major) version _won't_ work, it only means that it _might_ not.

Maybe that was already clear from my previous comment.

Regarding

> I would personally prioritize the former over the latter, from a UI perspective.

I cannot find good references right now, but I believe that exactly the opposite position is explicitly taken by almost every package manager. The thinking is that if a package manager lets you install something that doesn't work, you can always fix it: e.g. by specifying a version of pulp as in this thread. Whereas, if a package manager doesn't let you install something even though it _would_ work, there is usually no way around that without seriously monkeying with internals (the solvers of package managers are quite complicated). Therefore, it is typically considered to be more problematic to make the second kind of error.

Fundamentally both errors are quite annoying and they only arise, as I said, because package management does not take _time_ into account. There are interesting discussions to be had about how to manage the risks of both (for example, how conservative to be with upper bounds might have to do with how deeply you integrate with dependencies and therefore how _likely_ it is for a minor release to break your package), but there is no way to really do it right with the tools we've been given.

**Comment by ctb** [comment]
thank you for your thoughts - lots of good food for thought! I gather that there are a variety of approaches to consider here, too, including the use of lock files. I'll look into it! 🤷

**Comment by zmbc** [comment]
@ctb If you are running into this problem when you are just trying to run your workflow, yes, you absolutely should be using lock files! Lock files mean that you (as an end user, not library developer) only update your dependencies when you _intend_ to, and not by accident (e.g. when setting up a new development machine).

However, even with lock files you will still run into issues like this when you try to upgrade your dependencies (which you should do from time to time), so it is still going to be a bit painful that current tools give us no way to reliably and responsibly avoid both (a) inscrutable error messages like the one that began this thread and (b) packages refusing to install due to "incompatibility" when they are actually compatible.
