### ISSUE TITLE
KeyError when trying to use snakemake with iRODS

### ISSUE THREAD

**Issue by lhennig** [snakemake/snakemake#2003]
I have some files on iRODS and I'm trying to process them with snakemake as described [here](https://snakemake.readthedocs.io/en/v6.8.2/snakefiles/remote_files.html#irods). For this, I wrote the following Snakefile, which is supposed to download and copy a file for testing purposes:

``` Python
from snakemake.remote.iRODS import RemoteProvider

irods = RemoteProvider(
    irods_env_file="~/.irods/irods_environment.json",
    timezone="Europe/Berlin",
)


rule gen:
    input:
        irods.remote(
            "/in2p3/file_on_irods.root"
        ),
    output:
        "downloaded/file_local.root",
    shell:
        "cp {input} {output}"
```

that uses the following iRODS configuration file:

```JSON
{
    "irods_host": "ccirods.in2p3.fr",
    "irods_port": 5530,
    "irods_user_name": "user_read",
    "irods_zone_name": "in2p3"
}
```

If I execute `snakemake --cores 1 downloaded/file_local.root -n` , I receive the following error

``` Shell
Building DAG of jobs...
Traceback (most recent call last):
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/snakemake/__init__.py", line 747, in snakemake
    success = workflow.execute(
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/snakemake/workflow.py", line 742, in execute
    dag.init()
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/snakemake/dag.py", line 201, in init
    job = self.update(
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/snakemake/dag.py", line 858, in update
    self.update_(
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/snakemake/dag.py", line 962, in update_
    if not res.file.exists:
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/snakemake/io.py", line 455, in exists
    return self.exists_remote
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/snakemake/io.py", line 249, in wrapper
    v = func(self, *args, **kwargs)
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/snakemake/io.py", line 476, in exists_remote
    return self.remote_object.exists()
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/snakemake/remote/iRODS.py", line 117, in exists
    self._irods_session.data_objects.get(self.remote_path)
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/irods/manager/data_object_manager.py", line 136, in get
    return iRODSDataObject(self, parent, results)
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/irods/data_object.py", line 65, in __init__
    self.replicas = [iRODSReplica(
  File "/pbs/home/l/lhennig/my_envs/snakemake-venv/lib/python3.9/site-packages/irods/data_object.py", line 70, in <listcomp>
    r[DataObject.resc_hier],
KeyError: <irods.column.Column 422 D_RESC_HIER>
```

I don't know if I did something wrong in my attempts to use iRODS with snakemake or if it is a problem with snakemake. Does anybody know more about that problem?

**Comment by messersc** [comment]
Hi,

just had a quick glance. I have never used the irods remote, but have some experience with both snakemake and irods.

`KeyError: <irods.column.Column 422 D_RESC_HIER>` suggests that this might be an irods problem. Can you download the file from the path you specified? E.g. does `ils` or `iget` work?

Because `/in2p3/file_on_irods.root` does not look like a complete irods path to me. Shouldn't there be a zone and/or user? Or is the remote provider only looking in one's irods `$HOME`?

Clemens

**Comment by stsnel** [comment]
I believe this error message is caused by connecting to an iRODS 3.x zone. Python-irodsclient (the client API that the iRODS plugin uses) no longer supports this, so it's also not supported by the iRODS plugin.

See also https://github.com/irods/python-irodsclient/issues/470 for a related report for the same iRODS zone.
