### ISSUE TITLE
Bug with --slurm : ValueError: max() arg is an empty sequence caused by show-failed-logs: True

### ISSUE THREAD

**Issue by chrarnold** [snakemake/snakemake#2023]
**Snakemake version**
Newest 7.19.1

**Describe the bug**
`ValueError: max() arg is an empty sequence` error, aborting snakemake. I tracked it down and I can reproducibly regenerate the error. The reason is having `show-failed-logs: True` in the profile (or probably on the command line, but this I didnt test explicitly)

**Logs**
```
max() arg is an empty sequence
Traceback (most recent call last):
  File "bla/envs/snakemake7/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 838, in _wait_thread
    asyncio.run(self._wait_for_jobs())
  File "bla/envs/snakemake7/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "bla/envs/snakemake7/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "bla/envs/snakemake7/lib/python3.10/site-packages/snakemake/executors/slurm/slurm_submit.py", line 363, in _wait_for_jobs
    self.print_job_error(
  File "bla/envs/snakemake7/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 186, in print_job_error
    job.log_error(msg, **kwargs)
  File "bla/envs/snakemake7/lib/python3.10/site-packages/snakemake/jobs.py", line 1095, in log_error
    logger.job_error(**self.get_log_error_info(msg, indent, aux_logs, **kwargs))
  File "bla/envs/snakemake7/lib/python3.10/site-packages/snakemake/logging.py", line 391, in job_error
    self.handler(msg)
  File "bla/envs/snakemake7/lib/python3.10/site-packages/snakemake/logging.py", line 334, in handler
    handler(msg)
  File "bla/envs/snakemake7/lib/python3.10/site-packages/snakemake/logging.py", line 552, in text_handler
    self.logger.error("\n".join(map(indent, job_error())))
  File "bla/envs/snakemake7/lib/python3.10/site-packages/snakemake/logging.py", line 547, in job_error
    yield from show_logs(msg["log"])
  File "bla/envs/snakemake7/lib/python3.10/site-packages/snakemake/logging.py", line 480, in show_logs
    max_len = max(max(len(l) for l in lines), len(logfile_header))
ValueError: max() arg is an empty sequence
```

**Minimal example**

```
def get_mem_mb(wildcards, attempt):
    return attempt * 150

rule all:
    input: expand("output_{letter}.done2", letter = ["A", "B"])

rule run1:
    input: "input_{letter}.txt"
    output: "output_{letter}.done"
    threads: 2
    log: "log_{letter}.txt"
    resources:
        mem_mb=get_mem_mb,
        runtime=3
    shell: """sleep 5 && echo "test" >{output}"""

# Should fail the first time but work the second time per design
rule run2:
    input: "output_{letter}.done"
    output: "output_{letter}.done2"
    threads: 2
    log: "log2_{letter}.txt"
    resources:
        mem_mb=get_mem_mb,
        runtime=1
    shell: """sleep 90 && echo "test" >{output}"""
```
I edited my post, I accidentally put printshellcmds as reason instead of show-failed-logs

**Comment by tdido** [comment]
I can reproduce this locally with:

```python
rule all:
    log: "test.log"
    output: "test.txt"
    shell: """ 
        touch {output} > {log}
        exit 1
    """
```

and

```bash
snakemake -c --show-failed-logs
```
