### ISSUE TITLE
SSL error when using --report

### ISSUE THREAD

**Issue by pdagosto** [snakemake/snakemake#2027]
**Snakemake version**
7.18.1

**Describe the bug**

Unable to generate the report (snakemake --cores 8 --report). due to ssl error:

ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)

**Logs**

(p310) pdagosto@rckgxf0013 snakemake2cwl]$ snakemake -s main.make --cores 8 --report
Building DAG of jobs...
Creating report...
Traceback (most recent call last):
  File "/work/miniconda3/envs/p310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/work/miniconda3/envs/p310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/work/miniconda3/envs/p310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/work/miniconda3/envs/p310/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/work/miniconda3/envs/p310/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/work/miniconda3/envs/p310/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/work/miniconda3/envs/p310/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/work/miniconda3/envs/p310/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/work/miniconda3/envs/p310/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)

**Minimal example**

```
taid='VCtest'
ref='mmv_NC_001510.fasta'

rule all:
	input:
		'{0}.bam'.format(taid)

rule index_reads:
	input:
		ref
	output:
		 multiext('{0}'.format(ref),'.amb', '.ann', '.bwt', '.pac', '.sa')
	shell:
		'bwa index {input}'

rule map_reads:
	input:
		index=multiext(ref, '.amb', '.ann', '.bwt', '.pac', '.sa'),
		reads='{0}_S2_R1.fastq'.format(taid)
	output:
		'{0}.sam'.format(taid)
	shell:
		'bwa mem {ref} {input.reads} > {output}'

rule samtools_view:
	input:
		'{0}.sam'.format(taid)
	output:
		'{0}.bam'.format(taid)
	shell:
		'samtools view -b -o {output} {input}'


```**Additional context**
<!--Add any other context about the problem here.-->
CentOS 7, Python 3.9

**Comment by pdagosto** [comment]
Perhaps someone could explain why the --report option causes snakemake to try to connect via ssl to somewhere on the internet? It's not obvious to me why the network would be coming into play when creating a report from local data.

**Comment by pvandyken** [comment]
I'm not super familiar with the code for report generation, but it would be helpful if you could strip down the `Snakefile` as much as possible to see if and when the error goes away. For example, I'm not able to reproduce the error with the following Snakefile:

```
rule all:
    input: 'out.txt'


rule runrule:
    input: 'in.txt'
    output: 'out.txt'
    run:
        shell("date > {output}")
```

**Comment by pdagosto** [comment]
In reports/data/packages.py there are references to a number of packages that reference license urls. The one that iin my example seems to trigger the error specifically mentions the host raw.gihubusercontent.com, probably the first one its running into:

requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /snakemake/snakemake/main/LICENSE.md (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:997)')))

Is the report function trying to download these packages? The ones listed are:

snakemake (already installed)
pygments (already installed)

These are all npm packages:

tailwindcss
react
vega
vega-lite
vega-embed
heroicons

I don't do web development but if I were to install these packages somewhere on my Linux VM would snakemake not try to download them? How would I tell snakemake where they're located?

**Comment by pvandyken** [comment]
Just took a look at the source code for this. It is indeed attempting to download all of those libraries to generate the report and there does not appear to be any workaround.

In normal development, just the links to the libraries would be embedded, and the browser would handle the downloads, allowing the report to be generated without an internet connection. The only rationale for the current behaviour that I can come up with is that the report can be completely self-contained and opened without an internet connection.

Unfortunately, any change in this behaviour would technically be breaking: folks may currently be relying on self-contained reports. So getting a fix incorporated into `main` may be challenging. But if I get time I can look into patching on a fork at least.

**Comment by pdagosto** [comment]
I wouldn't spend any time on trying to make a fork or getting this into the main branch. Now that I know what's going on I can try to figure out the network errors I'm getting which is something in my company's environment.
