### ISSUE TITLE
ProcessLookupError: [Errno 3] No such process

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [snakemake/snakemake#2062]
**Snakemake version**

**Describe the bug**

I'm running seq2science, a workflow based on snakemake. This is the error I'm getting:

```
Finished job 10360.
12 of 12669 steps (0.1%) done
Removing temporary output /scratch/sande/rerun_hourglass/results/fastq/GSM1606304_R1.fastq.gz.
Removing temporary output /scratch/sande/rerun_hourglass/results/fastq/GSM1606304_R2.fastq.gz.
Select jobs to execute...
Traceback (most recent call last):
  File "/vol/mbconda/sande/seq2science/lib/python3.8/subprocess.py", line 342, in call
    return p.wait(timeout=timeout)
  File "/vol/mbconda/sande/seq2science/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/vol/mbconda/sande/seq2science/lib/python3.8/subprocess.py", line 1806, in _wait
    (pid, sts) = self._try_wait(0)
  File "/vol/mbconda/sande/seq2science/lib/python3.8/subprocess.py", line 1764, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
stopit.utils.TimeoutException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vol/mbconda/sande/seq2science/lib/python3.8/site-packages/snakemake/__init__.py", line 747, in snakemake
    success = workflow.execute(
  File "/vol/mbconda/sande/seq2science/lib/python3.8/site-packages/snakemake/workflow.py", line 1083, in execute
    raise e
  File "/vol/mbconda/sande/seq2science/lib/python3.8/site-packages/snakemake/workflow.py", line 1079, in execute
    success = self.scheduler.schedule()
  File "/vol/mbconda/sande/seq2science/lib/python3.8/site-packages/snakemake/scheduler.py", line 525, in schedule
    run = self.job_selector(needrun)
  File "/vol/mbconda/sande/seq2science/lib/python3.8/site-packages/snakemake/scheduler.py", line 787, in job_selector_ilp
    self._solve_ilp(prob)
  File "/vol/mbconda/sande/seq2science/lib/python3.8/site-packages/snakemake/scheduler.py", line 836, in _solve_ilp
    prob.solve(solver)
  File "/vol/mbconda/sande/seq2science/lib/python3.8/site-packages/pulp/pulp.py", line 1913, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/vol/mbconda/sande/seq2science/lib/python3.8/site-packages/pulp/apis/glpk_api.py", line 97, in actualSolve
    rc = subprocess.call(proc, stdout=pipe, stderr=pipe)
  File "/vol/mbconda/sande/seq2science/lib/python3.8/subprocess.py", line 344, in call
    p.kill()
  File "/vol/mbconda/sande/seq2science/lib/python3.8/subprocess.py", line 1943, in kill
    self.send_signal(signal.SIGKILL)
  File "/vol/mbconda/sande/seq2science/lib/python3.8/subprocess.py", line 1933, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
```

**Minimal example**

Can't think of what is causing this error

**Comment by Maarten-vd-Sande** [comment]
Yes I understand that the issue in it's current form is not very helpful. I've been getting it pretty consistently, and FWIW switching to the greedy scheduler solves it for me (in case someone else gets this issue)

**Comment by pvandyken** [comment]
Is this a `pip` installation? I wonder if there's some pulp dependencies missing and that's causing problems

**Comment by Maarten-vd-Sande** [comment]
No it's through conda. It does use snakemake-minimal instead of regular snakemake. I don't know if that could cause the issues? 

I'm running a fairly large workflow with 15k+ jobs, and after initially starting the workflow just hangs for a long time not starting any new jobs, but `glpsol` is running in the background.

**Comment by pvandyken** [comment]
Hmm, I wonder if it's quietly erroring out and snakemake isn't getting notified? Have you run with `--debug`?
