### ISSUE TITLE
--env-module not activated for some rules

### ISSUE THREAD

**Issue by troycomi** [snakemake/snakemake#2072]
**Snakemake version**
7.19.1
**Describe the bug**
I have a module I'd like to activate for two rules in my workflow.  A minimal example is below:
```python
rule all:
    input: 'b.out'

rule step1:
    output: touch('a.out')
    envmodules:
        "matlab/R2022b"
    shell:
        'which matlab'

rule step2:
    output: touch('b.out')
    input: 'a.out'
    envmodules:
        "matlab/R2022b"
    shell:
        'which matlab'
```

When I execute snakemake, the module is not loaded for step2:
```shell
$ snakemake --use-envmodules -c1
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
all          1              1              1
step1        1              1              1
step2        1              1              1
total        3              1              1

Select jobs to execute...

[Thu Jan 19 16:43:26 2023]
rule step1:
    output: a.out
    jobid: 2
    reason: Missing output files: a.out
    resources: tmpdir=/tmp

Activating environment modules: matlab/R2022b
/usr/licensed/matlab-R2022b/bin/matlab
Touching output file a.out.
[Thu Jan 19 16:43:27 2023]
Finished job 2.
1 of 3 steps (33%) done
Select jobs to execute...

[Thu Jan 19 16:43:27 2023]
rule step2:
    input: a.out
    output: b.out
    jobid: 1
    reason: Missing output files: b.out; Input files updated by another job: a.out
    resources: tmpdir=/tmp

[Thu Jan 19 16:43:27 2023]
Error in rule step2:
    jobid: 1
    input: a.out
    output: b.out
    shell:
        which matlab
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-01-19T164326.654604.snakemake.log
```

I expected each module to be loaded for every rule.  Rerunning the workflow does not fix the issue.  Commenting out step1 (if its output exists) causes the step2 module to load and work properly.

Note that while step1 states the module is activating, step2 does not.  Identical behavior when submitting to a cluster.

**Comment by pvandyken** [comment]
Unfortunately, I'm not able to replicate. Possibly an issue with your module system? Do you always have trouble using modules?

**Comment by troycomi** [comment]
Interesting.  I haven't noticed any other issues related to modules.  When I run with `--verbose` I get some more information when the error is thrown:
```
Full Traceback (most recent call last):
  File "$HOME/.conda/snake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2602, in run_wrapper
    runtime_sourcecache_path,
  File "$HOME/projects/snake-temp/Snakefile", line 47, in __rule_step2
  File "$HOME/.conda/snake/lib/python3.7/site-packages/snakemake/shell.py", line 176, in __new__
    if env_modules and "slurm" not in (item.filename for item in inspect.stack()):
  File "$HOME/.conda/snake/lib/python3.7/inspect.py", line 1513, in stack
    return getouterframes(sys._getframe(1), context)
  File "$HOME/.conda/snake/lib/python3.7/inspect.py", line 1490, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "$HOME/.conda/snake/lib/python3.7/inspect.py", line 1464, in getframeinfo
    lines, lnum = findsource(frame)
  File "$HOME/.conda/snake/lib/python3.7/inspect.py", line 828, in findsource
    if pat.match(lines[lnum]): break
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/.conda/snake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 667, in _callback
    raise ex
  File "$HOME/.conda/snake/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "$HOME/.conda/snake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 653, in cached_or_run
    run_func(*args)
  File "$HOME/.conda/snake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2616, in run_wrapper
    ex, lineno, linemaps=linemaps, snakefile=file, show_traceback=True
snakemake.exceptions.RuleException: IndexError in file $HOME/projects/snake-temp/Snakefile, line 18:
list index out of range
  File "$HOME/projects/snake-temp/Snakefile", line 18, in __rule_step2
  File "$HOME/.conda/snake/lib/python3.7/inspect.py", line 1513, in stack
  File "$HOME/.conda/snake/lib/python3.7/inspect.py", line 1490, in getouterframes
  File "$HOME/.conda/snake/lib/python3.7/inspect.py", line 1464, in getframeinfo
  File "$HOME/.conda/snake/lib/python3.7/inspect.py", line 828, in findsource
```
Is there some additional information I could take to the sysadmins to have them help with this error?

**Comment by pvandyken** [comment]
Interesting. The line that errors is fairly new, coming in #1015, which I believe first appears in snakemake 7.19.0. So a couple of things: are you able to reproduce the error on an older snakemake, especially snakemake v7.18.2? And then could you comment out that block in `snakemake.shell` (lines 176:178) and see if the error goes away?

**Comment by pvandyken** [comment]
Actually, forget the commenting out bit, that will definitely break it completely. More interested in the version change

**Comment by pvandyken** [comment]
Okay, that's helpful (and probably explains why I couldn't reproduce, as I wasn't using python 3.7). Since snakemake is supposed to support python 3.7, I think this still counts as a bug, so I'll see later if I can reproduce
