### ISSUE TITLE
ModuleNotFoundError: No module named 'yappi'

### ISSUE THREAD

**Issue by fafaris39** [snakemake/snakemake#2214]
I am runing  a snakemake script "snakemake --profile config/profiles/local -n"  and i get this error: 
```
 Traceback (most recent call last):
  File "/home/user/miniconda3/envs/snakemake/bin/snakemake", line 6, in <module>
    sys.exit(snakemake.main())
  File "/home/user/miniconda3/envs/snakemake/lib/python3.6/site-packages/snakemake/__init__.py", line 1076, in main
    import yappi
ModuleNotFoundError: No module named 'yappi'
```
This how i installed snakemake env
`conda create -c bioconda -c conda-forge -n snakemake snakemake`
 The version of the environment
```
conda info --env
snakemake                /home/user/miniconda3/envs/snakemake
```

**Comment by cademirch** [comment]
Can you do `snakemake --version` and report the output of that?
