### ISSUE TITLE
Historical snakemake versions error: AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by ShouWenWang** [snakemake/snakemake#2219]
I installed a historical version in this way
```
mamba create -c conda-forge -c bioconda -n snakemake_v5 snakemake==6.10.0  --yes
```
Then, I used the following snake file called done_snakemake.py
```
rule all:
    input:
        "output/concatenated.done"

rule concatenate_files:
    input:
        file1="input/file1.txt",
        file2="input/file2.txt",
        file3="input/file3.txt"
    output:
       "output/concatenated.done"
    run:
        output_file = "output/concatenated.txt"
        os.system(f"echo step1; cat {input.file1} {input.file2} {input.file3} > {output_file}")

        # Touch the output file to create/update the timestamp
        Path(output[0]).touch()
```

I then executed the code
```
snakemake -s done_snakemake.py --cores 3 -R concatenate_files
```

This is my error message
```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 3
Rules claiming more threads will be scaled down.
Traceback (most recent call last):
  File "/Users/shouwen/opt/miniconda3/envs/snakemake_v4/lib/python3.10/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/Users/shouwen/opt/miniconda3/envs/snakemake_v4/lib/python3.10/site-packages/snakemake/workflow.py", line 1052, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/Users/shouwen/opt/miniconda3/envs/snakemake_v4/lib/python3.10/site-packages/snakemake/dag.py", line 2187, in stats
    yield tabulate(rows, headers="keys")
  File "/Users/shouwen/opt/miniconda3/envs/snakemake_v4/lib/python3.10/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/Users/shouwen/opt/miniconda3/envs/snakemake_v4/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/Users/shouwen/opt/miniconda3/envs/snakemake_v4/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/Users/shouwen/opt/miniconda3/envs/snakemake_v4/lib/python3.10/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/Users/shouwen/opt/miniconda3/envs/snakemake_v4/lib/python3.10/site-packages/snakemake/rules.py", line 1127, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
```

**Comment by dariober** [comment]
See this https://stackoverflow.com/a/74231483/1114453 and links therein.

Probably you need to add `tabulate==0.8` to your requirements.
