### ISSUE TITLE
additional UnboundLocalError when lambda evaluation throws exception

### ISSUE THREAD

**Issue by hertzsprung** [snakemake/snakemake#224]
Snakemake 5.10.0.  Snakefile:
```yaml
rule: "test"                                                                    
    output: "{runtime}"
    resources:
        runtime=lambda wildcards: runtime//2 # deliberate type error
```

Running `snakemake 4` correctly reports the type error (runtime is a str, not a numeric type), but also reports an additional exception:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/snakemake/__init__.py", line 633, in snakemake
    keepincomplete=keep_incomplete,
  File "/usr/local/lib/python3.6/dist-packages/snakemake/workflow.py", line 850, in execute
    success = scheduler.schedule()
  File "/usr/local/lib/python3.6/dist-packages/snakemake/scheduler.py", line 360, in schedule
    run = self.job_selector(needrun)
  File "/usr/local/lib/python3.6/dist-packages/snakemake/scheduler.py", line 503, in job_selector
    a = list(map(self.job_weight, jobs))  # resource usage of jobs
  File "/usr/local/lib/python3.6/dist-packages/snakemake/scheduler.py", line 577, in job_weight
    res = job.resources
  File "/usr/local/lib/python3.6/dist-packages/snakemake/jobs.py", line 268, in resources
    self.wildcards_dict, self.input, self.attempt
  File "/usr/local/lib/python3.6/dist-packages/snakemake/rules.py", line 941, in expand_resources
    resources[name] = apply(name, res, threads=threads)
  File "/usr/local/lib/python3.6/dist-packages/snakemake/rules.py", line 926, in apply
    except e:
UnboundLocalError: local variable 'e' referenced before assignment
```

**Comment by johanneskoester** [comment]
Thanks a lot for reporting and sorry for the late response. Snakemake is currently entering a stabilization phase and I want to ideally tackle all open bugs. This one is fixed since some time already.
