### ISSUE TITLE
Snakemake crashes with a KeyError when using `--immediate-submit`

### ISSUE THREAD

**Issue by xapple** [snakemake/snakemake#2274]
Running version 7.25.3 and just got this bug when using `--immediate-submit` and thus submitting more jobs than usual to SLURM. Here is the traceback:

    Traceback (most recent call last):
      File "~/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/__init__.py", line 757, in snakemake
        success = workflow.execute(
      File "~/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/workflow.py", line 1100, in execute
        raise e
      File "~/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/workflow.py", line 1096, in execute
        success = self.scheduler.schedule()
      File "~/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/scheduler.py", line 516, in schedule
        self._finish_jobs()
      File "~/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/scheduler.py", line 642, in _finish_jobs
        self.dag.finish(job, update_dynamic=self.update_dynamic)
      File "~/miniconda3/envs/snake/lib/python3.9/site-packages/snakemake/dag.py", line 1609, in finish
        self._running.remove(job)
    KeyError: run_mapping

_Originally posted by @xapple in https://github.com/snakemake/snakemake/issues/1244#issuecomment-1560962367_

**Comment by ivadym** [comment]
We've been experiencing the same problem and couldn't reproduce it since it appears sporadically. The `KeyError` seems to occur in the middle of a job submission. However, Snakemake successfully submits the jobs until it throws this error. If, after the completion of the partially submitted rules, one resumes the workflow, it manages to submit the remaining job and complete the execution.

My first guess was that one of the first jobs submitted was finishing before the entire process ended, resulting in a KeyError during a cleanup. However, upon examining the code, I couldn't find where this is occurring. Therefore, I suspect there might be an unexpected exception somewhere, as most of the `KeyError` instances seem to be caught, logged, or [ignored](https://github.com/snakemake/snakemake/blob/0586f04d2b03443a25deddd017f303156acdcd9c/snakemake/dag.py#L250C2-L275).

**Comment by ivadym** [comment]
Hello @johanneskoester! Could you help us identify the problem here?

We encountered this issue in `v6.5.3` and also after updating to `v7.32.4`. It has become quite a blocking error for us, as it fails "silently," allowing only a small portion of the jobs to be submitted before encountering the key error. We have observed a worsening of this issue since adding even smaller rules at the beginning of our pipeline. It may be related to them finishing before the complete set of rules is submitted to the cluster. I'll be happy to provide more information if needed! Thanks!


```
Traceback (most recent call last):
  File ".../lib/python3.11/site-packages/snakemake/__init__.py", line 792, in snakemake
    success = workflow.execute(
              ^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/snakemake/workflow.py", line 1246, in execute
    raise e
  File ".../lib/python3.11/site-packages/snakemake/workflow.py", line 1242, in execute
    success = self.scheduler.schedule()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/snakemake/scheduler.py", line 550, in schedule
    self._finish_jobs()
  File ".../lib/python3.11/site-packages/snakemake/scheduler.py", line 672, in _finish_jobs
    self.dag.finish(job, update_dynamic=self.update_dynamic)
  File ".../lib/python3.11/site-packages/snakemake/dag.py", line 1617, in finish
    self._running.remove(job)
KeyError: fastqc
```
