### ISSUE TITLE
Some Singularity versions cannot be parsed in v7.29.0

### ISSUE THREAD

**Issue by boasvdp** [snakemake/snakemake#2319]
**Snakemake version**

7.29.0

**Describe the bug**

Singularity releases are now checked according to PEP440, to which they do not comply. This appears to be due to the change made in commit https://github.com/snakemake/snakemake/commit/9b8c3620e8c14e322ba15b7d044b9deab1854b2a, where distutils.version.LooseVersion is replaced by packaging.version.parse. 

This happens on my work laptop (`singularity --version` returns `singularity-ce version 3.10.4-dirty`) and on our HPC (`singularity --version` returns `singularity-ce version 3.11.1-1.el7`). Many [Singularity releases](https://github.com/sylabs/singularity/releases) (e.g. all releases for RHEL) have non-PEP440-compliant suffixes.

**Logs**

```
Traceback (most recent call last):
  File "/home/boas/mambaforge/lib/python3.10/site-packages/snakemake/__init__.py", line 771, in snakemake
    success = workflow.execute(
  File "/home/boas/mambaforge/lib/python3.10/site-packages/snakemake/workflow.py", line 919, in execute
    dag.pull_container_imgs(
  File "/home/boas/mambaforge/lib/python3.10/site-packages/snakemake/dag.py", line 367, in pull_container_imgs
    img.pull(dryrun)
  File "/home/boas/mambaforge/lib/python3.10/site-packages/snakemake/deployment/singularity.py", line 46, in pull
    self.singularity.check()
  File "/home/boas/mambaforge/lib/python3.10/site-packages/snakemake/deployment/singularity.py", line 179, in check
    if parse(v) < parse("2.4.1"):
  File "/home/boas/mambaforge/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/boas/mambaforge/lib/python3.10/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '3.10.4-dirty
'
```

**Minimal example**

Using `Snakefile`:
```
rule all:
    input:
        "out.txt"

rule whalesay:
    output:
        "out.txt"
    container:
        "docker://docker/whalesay:latest"
    shell:
        """
cowsay boo > {output}
        """
```
And then running:
```
# At the time of writing, v7.29.0 is not on conda yet
pip install snakemake==7.29.0
snakemake --version
singularity --version
snakemake --use-singularity -j 1
```

While this works fine:
```
singularity pull "docker://docker/whalesay:latest"
singularity exec whalesay_latest.sif cowsay boo
```

**Additional context**

**Comment by ASLeonard** [comment]
Not surprising, but it is the same for the other if statement checking singularity->apptainer version
```
packaging.version.InvalidVersion: Invalid version: '1.1.8-1.el7
```

Obviously not ideal, but this is an [intentional decision](https://github.com/pypa/setuptools/issues/3772) to not handle such non-PEP440 versions. Although the minimum allowed singularity version was released in Nov 22, 2017, so maybe its just better to remove the version check and feel sorry for anyone using such an old version (which wouldn't run anyway in snakemake).

**Comment by maarten-k** [comment]
Removing the check is a bad idea in my opinion: there are enough cluster systems around with ancient software installed on them.

There are multiple ways to solve this error:
-  strip the last bit of characters if Parse could not parse it and try again
-  use a module that implements LooseVersion (the question is how well it is maintained)
-  implement an own version of LooseVersion

I tend to the first solution, but please let me know if there is a better solution.

**Comment by boasvdp** [comment]
I'm also in favour of the first option where characters are stripped if `parse` does not work. I have access to at least one system which is running an unsupported version of Singularity, so I can imagine the check remains necessary
