### ISSUE TITLE
singularity version issue

### ISSUE THREAD

**Issue by epersoon** [snakemake/snakemake#2334]
I am trying to use singularity with snakemake with version 7.30 and I am seeing the following error:
```Traceback (most recent call last):
  File "/panfs/jay/groups/27/mccuem/perso208/mambaforge/envs/snakemake/lib/python3.11/site-packages/snakemake/__init__.py", line 771, in snakemake
    success = workflow.execute(
              ^^^^^^^^^^^^^^^^^
  File "/panfs/jay/groups/27/mccuem/perso208/mambaforge/envs/snakemake/lib/python3.11/site-packages/snakemake/workflow.py", line 919, in execute
    dag.pull_container_imgs(
  File "/panfs/jay/groups/27/mccuem/perso208/mambaforge/envs/snakemake/lib/python3.11/site-packages/snakemake/dag.py", line 367, in pull_container_imgs
    img.pull(dryrun)
  File "/panfs/jay/groups/27/mccuem/perso208/mambaforge/envs/snakemake/lib/python3.11/site-packages/snakemake/deployment/singularity.py", line 46, in pull
    self.singularity.check()
  File "/panfs/jay/groups/27/mccuem/perso208/mambaforge/envs/snakemake/lib/python3.11/site-packages/snakemake/deployment/singularity.py", line 173, in check
    if parse(v) < parse("1.0.0"):
       ^^^^^^^^
  File "/panfs/jay/groups/27/mccuem/perso208/mambaforge/envs/snakemake/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/panfs/jay/groups/27/mccuem/perso208/mambaforge/envs/snakemake/lib/python3.11/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '1.1.8-1.el7
'```

**Comment by tdido** [comment]
Fixed in #2337
