### ISSUE TITLE
shadow: copy-minimal causes IsADirectoryError when input is directory

### ISSUE THREAD

**Issue by fritjoflammers** [snakemake/snakemake#2383]
**Snakemake version**
7.30.1

**Describe the bug**
When an input is a directory, `copy-minimal` fails due to the usage of  `shutil.copy`, which expectedly throws an error in this case.  Possibly using `shutil.copytree` solves this ('snakemake/jobs.py', line 896) , although it may - depending on file structure - not be a minimal copy anymore. 

I encountered this bug in the [bismark align wrapper.](https://github.com/snakemake/snakemake-wrappers/blob/master/bio/bismark/bismark/wrapper.py) Patching it there by specifying all input files individually and write a function to provide the directory to bismark would also work. However, my understanding is that shadowing should universally work even if an input is a directory. 

**Logs**
```Traceback (most recent call last):
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 771, in snakemake
    success = workflow.execute(
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1088, in execute
    raise e
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1084, in execute
    success = self.scheduler.schedule()
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 627, in schedule
    self.run(runjobs)
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 676, in run
    executor.run_jobs(
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 144, in run_jobs
    self.run(
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 525, in run
    future = self.run_single_job(job)
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 578, in run_single_job
    self.cached_or_run, job, run_wrapper, *self.job_args_and_prepare(job)
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 530, in job_args_and_prepare
    job.prepare()
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/site-packages/snakemake/jobs.py", line 896, in prepare
    shutil.copy(rel_path, copy)
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/fritjof/micromamba/envs/snakemake/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: 'output/AZ-ALT-2021-007/Bisulfite_Genome'
```

**Minimal example**

Run the `BISMARK` wrapper with `shadow: copy-minimal`.

**Additional context**

**Comment by jorgenriseth** [comment]
Met this bus as well in version 7.32.3. Fixed it by switching the `shutil.copy` on line 896 (line 924 on my version) of `jobs.py` with the following:
```python
if os.path.isdir(rel_path):
    shutil.copytree(rel_path, copy)
else:
    shutil.copy(rel_path, copy)
```
Not sure if this will have some potential undesired effects.

**Comment by mobilegenome** [comment]
I also used `shutil.copytree` inside some of my jobscripts and implemented my own shadowing that way. It might be worthwhile adding  `dirs_exist_ok=True` to `copytree()` .

**Comment by vedranmiletic** [comment]
> Met this bus as well in version 7.32.3. Fixed it by switching the `shutil.copy` on line 896 (line 924 on my version) of `jobs.py` with the following:
> 
> if os.path.isdir(rel_path):
>     shutil.copytree(rel_path, copy)
> else:
>     shutil.copy(rel_path, copy)
> 
> Not sure if this will have some potential undesired effects.

This looks sensible. Is there any reason why you didn't propose it for a pull request?
