### ISSUE TITLE
The latest snakemake-interface-executor-plugins release will cause snakemake import error

### ISSUE THREAD

**Issue by agil27** [snakemake/snakemake#2426]
https://github.com/snakemake/snakemake-interface-executor-plugins/issues/16 is the same issue but for `snakemake-interface-executor-plugins release`. Basically the release of the plugins library result in an error with snakemake. The snakemake is installed with pip in my case.

```
Traceback (most recent call last):
  File "/usr/local/bin/snakemake", line 5, in <module>
    from snakemake.cli import main
  File "/usr/local/lib/python3.10/dist-packages/snakemake/__init__.py", line 9, in <module>
    from snakemake.shell import shell
  File "/usr/local/lib/python3.10/dist-packages/snakemake/shell.py", line 16, in <module>
    from snakemake.utils import format, argvquote, cmd_exe_quote
  File "/usr/local/lib/python3.10/dist-packages/snakemake/utils.py", line 19, in <module>
    from snakemake.io import regex, Namedlist, Wildcards, _load_configfile
  File "/usr/local/lib/python3.10/dist-packages/snakemake/io.py", line 27, in <module>
    from snakemake.exceptions import (
  File "/usr/local/lib/python3.10/dist-packages/snakemake/exceptions.py", line 10, in <module>
    from snakemake.logging import logger
  File "/usr/local/lib/python3.10/dist-packages/snakemake/logging.py", line 18, in <module>
    from snakemake_interface_executor_plugins.utils import ExecMode
ImportError: cannot import name 'ExecMode' from 'snakemake_interface_executor_plugins.utils' (/usr/local/lib/python3.10/dist-packages/snakemake_interface_executor_plugins/utils.py)
```

**Comment by agil27** [comment]
Maybe specify the version of the plugin library in the pip dependency files to prevent this from happening again?

**Comment by johanneskoester** [comment]
This is an error only happening in the main branch right? Not in one of the releases. I am currently performing large refactorings in Snakemake, in preparation of release 8.0. Once that is done, this error will disappear.

**Comment by nigiord** [comment]
Is there a workaround for this? Apparently I can’t build a test environment anymore :( .
