### ISSUE TITLE
snakemake --help broken?

### ISSUE THREAD

**Issue by vsoch** [snakemake/snakemake#2492]
I just pulled the latest from the main branch, and a basic `--help` seems to be broken?

```
$ snakemake --help
Traceback (most recent call last):
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/cli.py", line 2008, in main
    parser, args = parse_args(argv)
                   ^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/cli.py", line 1587, in parse_args
    args = parser.parse_args(argv)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/env/lib/python3.11/site-packages/configargparse.py", line 797, in parse_args
    args, argv = self.parse_known_args(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/env/lib/python3.11/site-packages/configargparse.py", line 979, in parse_known_args
    namespace, unknown_args = argparse.ArgumentParser.parse_known_args(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/anaconda3/lib/python3.11/argparse.py", line 1902, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/anaconda3/lib/python3.11/argparse.py", line 2114, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/anaconda3/lib/python3.11/argparse.py", line 2054, in consume_optional
    take_action(action, args, option_string)
  File "/home/vanessa/anaconda3/lib/python3.11/argparse.py", line 1978, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/vanessa/anaconda3/lib/python3.11/argparse.py", line 1119, in __call__
    parser.print_help()
  File "/home/vanessa/anaconda3/lib/python3.11/argparse.py", line 2601, in print_help
    self._print_message(self.format_help(), file)
                        ^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/env/lib/python3.11/site-packages/configargparse.py", line 1361, in format_help
    return (argparse.ArgumentParser.format_help(self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/anaconda3/lib/python3.11/argparse.py", line 2578, in format_help
    formatter.add_arguments(action_group._group_actions)
  File "/home/vanessa/anaconda3/lib/python3.11/argparse.py", line 280, in add_arguments
    self.add_argument(action)
  File "/home/vanessa/anaconda3/lib/python3.11/argparse.py", line 265, in add_argument
    invocations = [get_invocation(action)]
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/anaconda3/lib/python3.11/argparse.py", line 579, in _format_action_invocation
    args_string = self._format_args(action, default)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/anaconda3/lib/python3.11/argparse.py", line 625, in _format_args
    raise ValueError("invalid nargs value") from None
ValueError: invalid nargs value
```

**Comment by SichongP** [comment]
Looks like a big refactoring is still going on in the main?

**Comment by vsoch** [comment]
This was from October - I just updated my snakemake-interface-common and the pulled changes seem to resolve the issue! So good to close (for me).
