### ISSUE TITLE
name attribute ValueError when running on the cluster

### ISSUE THREAD

**Issue by erfanshekarriz** [snakemake/snakemake#2531]
Hi and hope all is well! 

I've caught onto a bug around the ```name``` attribute in Snakemake rules. Specifically that the character ```:``` is not allowed and raises an error, but strangely only when running it on the cluster with the --cluster function. 

This is the error:
```
snakemake/7.32.3 is loaded 
Traceback (most recent call last):
  File "/software/snakemake/7.28.1/lib/python3.11/site-packages/snakemake/common/__init__.py", line 47, in parse_key_value_arg
    key, val = arg.split("=", 1)
    ^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/software/snakemake/7.28.1/lib/python3.11/site-packages/snakemake/__main__.py", line 4, in <module>
    main()
  File "/software/snakemake/7.28.1/lib/python3.11/site-packages/snakemake/__init__.py", line 3056, in main
    target_jobs=parse_target_jobs_cli_args(args),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/snakemake/7.28.1/lib/python3.11/site-packages/snakemake/target_jobs.py", line 21, in parse_target_jobs_cli_args
    wildcards = dict(
                ^^^^^
  File "/software/snakemake/7.28.1/lib/python3.11/site-packages/snakemake/target_jobs.py", line 22, in <genexpr>
    parse_wildcard(entry) for entry in wildcards.split(",")
    ^^^^^^^^^^^^^^^^^^^^^
  File "/software/snakemake/7.28.1/lib/python3.11/site-packages/snakemake/target_jobs.py", line 19, in parse_wildcard
    return parse_key_value_arg(entry, errmsg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/snakemake/7.28.1/lib/python3.11/site-packages/snakemake/common/__init__.py", line 49, in parse_key_value_arg
    raise ValueError(errmsg + f" (Unparseable value: {repr(arg)})")
ValueError: Invalid target wildcards definition: entries have to be defined as WILDCARD=VALUE pairs (Unparseable value: ' preprocess report:')
```

my snakemake rule is:

```
rule multiqc:
  name : "preprocessing.py: preprocess report"
  input:
    fastplogs = expand("results/preprocess/{sample_id}/report.fastp.json", sample_id = samples.keys())
  output:
    "workflow/report/preprocess/preprocess_report.html",
    "workflow/report/preprocess/preprocess_report_data/multiqc.log"
  params:
    search_dir = "results/preprocess/",
    output_dir = "workflow/report/preprocess/",
    tmp_dir = "$TMPDIR/multiqc/"
  log: "logs/preprocess_multiqc.log"
  threads: 1
  conda: "../envs/multiqc.yml"
  shell:
    """
    rm -rf {params.tmp_dir} {params.output_dir}
    mkdir -p {params.tmp_dir} {params.output_dir}

    multiqc {params.search_dir} -f -o {params.tmp_dir} -n preprocess_report.html 2> {log}

    mv {params.tmp_dir}preprocess_report* {params.output_dir}
    rm -rf {params.tmp_dir}

    """
```

The command that caused the error:
```
snakemake workflow/report/preprocess/preprocess_report.html --use-conda -j 88 -f --rerun-incomplete --cluster "qsub -N {log} -l nodes=1:ppn={threads} -l mem={resources.mem_mb}m -l walltime=120:00:00 -q test -o qsub.out -e qsub.err " -k  --rerun-triggers mtime
```

Two things resolved the error:
1) Removing the ```:``` immediately resolved my problem. The problem doesn't come with dry runs, but when actually submitting to the cluster. 
2) Running without the cluster 
```
snakemake workflow/report/preprocess/preprocess_report.html --use-conda -j 1 -f --rerun-incomplete  -k  --rerun-triggers mtime
```

**Comment by erfanshekarriz** [comment]
Also wanted to add that adding a ```\``` to escape the ```:``` pythonic dictionary format works, but It makes the name printed also have a backlash which is undesirable.
