### ISSUE TITLE
Conda error while using conda envs within container

### ISSUE THREAD

**Issue by DavideBrex** [snakemake/snakemake#2538]
**Snakemake version**
7.31.0

**Describe the bug**

On my local machine, I developed a pipeline with conda envs and it runs. 
Now, I wanted to test the pipeline on another machine (server from the institute), and so I run the command

`snakemake --containerize > Dockerfile`

I got a dockerfile and I generated an image that was uploaded on dockerhub.
At this point, I copied the workflow on the other machine, I added to the Snakefile the line:

`containerized: "docker://davidebrex/chiprxsnakemake:latest"`

and tried to run the pipeline with: `snakemake -c 10 --use-conda --use-singularity.` Ideally, snakemake should run the conda envs within the docker container for each rule

The problem is that i get an error related to the fact that conda is missing.. I checked the docker image and I can run conda and see the installed envs.

Any suggestions about what is going on?
Could this be related to the fact that my local conda installation is Miniconda, and on the server is Mambaforge?

Thank you!

**Logs**
```
/usr/bin/bash: conda: command not found
Traceback (most recent call last):
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/__init__.py", line 786, in snakemake
    success = workflow.execute(
              ^^^^^^^^^^^^^^^^^
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1245, in execute
    raise e
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1241, in execute
    success = self.scheduler.schedule()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/scheduler.py", line 634, in schedule
    self.run(runjobs)
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/scheduler.py", line 683, in run
    executor.run_jobs(
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/executors/__init__.py", line 157, in run_jobs
    self.run(
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/executors/__init__.py", line 581, in run
    future = self.run_single_job(job)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/executors/__init__.py", line 634, in run_single_job
    self.cached_or_run, job, run_wrapper, *self.job_args_and_prepare(job)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/executors/__init__.py", line 622, in job_args_and_prepare
    self.workflow.conda_base_path,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 457, in conda_base_path
    return Conda().prefix_path
           ^^^^^^^
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 653, in __init__
    shell.check_output(self._get_cmd("conda info --json"), text=True)
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 61, in check_output
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davide.bressan-1/mambaforge/envs/new_snakemake/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'conda info --json' returned non-zero exit status 127.
```

**Minimal example**

**Additional context**

**Comment by m-jahn** [comment]
I think if you want to run a single remote container with all conda envs installed in it, you need to use `container`. Add this line at the top of your workflow:

```
container: "docker://davidebrex/chiprxsnakemake:latest"
```

`containerized` is the keyword to run a locally stored container such as a .sif singularity image.
