### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by Ulthran** [snakemake/snakemake#2549]
**Snakemake version**

7.32.4 (also tried with 7.31.0)

**Describe the bug**

Things just started breaking a few days ago, without changes being made. It seems like all the errors are centered around IO errors. One rule runs cutadapt with subprocess in a python script. I've tried multiple versions of Python (3.12, 3.10, 3.7) with multiple versions of cutadapt (2.6, 4.6). In each case, I can run the cutadapt command outside of snakemake and it works without issue. The exact stack trace varies between versions but here's one (they all involve xopen):

```
Traceback (most recent call last):
  File ".../.snakemake/807bc1f0b96d6448a694a159dca16589_/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
  File ".../.snakemake/807bc1f0b96d6448a694a159dca16589_/lib/python3.10/site-packages/cutadapt/cli.py", line 67, in <module>
    import dnaio
  File ".../.snakemake/807bc1f0b96d6448a694a159dca16589_/lib/python3.10/site-packages/dnaio/__init__.py", line 38, in <module>
    from xopen import xopen
  File ".../.snakemake/807bc1f0b96d6448a694a159dca16589_/lib/python3.10/site-packages/xopen/__init__.py", line 62, in <module>
    from isal import igzip, igzip_threaded, isal_zlib
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
OSError: [Errno 5] Input/output error: '.../.snakemake/807bc1f0b96d6448a694a159dca16589_/lib/python3.10/site-packages/isal/igzip_threaded.py'
```

Here's another one running a python script again (this time no subprocess call, pandas seems to be the culprit):

```
Traceback (most recent call last):
  File ".../.snakemake/scripts/tmpfxhm3_5r.preprocess_report.py", line 6, in <module>
  File ".../.snakemake/cb8810a5c0e1eddcd2ee473f41dfc0bf_/lib/python3.11/site-packages/pandas/__init__.py", line 46, in <module>
  File ".../.snakemake/cb8810a5c0e1eddcd2ee473f41dfc0bf_/lib/python3.11/site-packages/pandas/core/api.py", line 1, in <module>
  File ".../.snakemake/cb8810a5c0e1eddcd2ee473f41dfc0bf_/lib/python3.11/site-packages/pandas/_libs/__init__.py", line 18, in <module>
  File "interval.pyx", line 1, in init pandas._libs.interval
  File "hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "missing.pyx", line 1, in init pandas._libs.missing
  File ".../.snakemake/cb8810a5c0e1eddcd2ee473f41dfc0bf_/lib/python3.11/site-packages/pandas/_libs/tslibs/__init__.py", line 39, in <module>
  File "conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "parsing.pyx", line 45, in init pandas._libs.tslibs.parsing
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1080, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1504, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1476, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1616, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1659, in _fill_cache
OSError: [Errno 5] Input/output error: '.../.snakemake/cb8810a5c0e1eddcd2ee473f41dfc0bf_/lib/python3.11/site-packages/dateutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../.snakemake/scripts/tmpfxhm3_5r.preprocess_report.py", line 21, in <module>
OSError: [Errno 5] Input/output error: '.../projects/good/sunbeam_output/logs/preprocess_report.log'
```

Errored out trying to get import something and then errored out trying to write the snakemake log in the block that caught the initial exception. And here's another python script trying to import pandas:

```
Traceback (most recent call last):
  File ".../.snakemake/scripts/tmp2qk3mbk4.preprocess_report.py", line 6, in <module>
  File ".../.snakemake/cb8810a5c0e1eddcd2ee473f41dfc0bf_/lib/python3.11/site-packages/pandas/__init__.py", line 46, in <module>
  File ".../.snakemake/cb8810a5c0e1eddcd2ee473f41dfc0bf_/lib/python3.11/site-packages/pandas/core/api.py", line 1, in <module>
  File ".../.snakemake/cb8810a5c0e1eddcd2ee473f41dfc0bf_/lib/python3.11/site-packages/pandas/_libs/__init__.py", line 18, in <module>
  File "interval.pyx", line 1, in init pandas._libs.interval
  File "hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "missing.pyx", line 1, in init pandas._libs.missing
  File ".../.snakemake/cb8810a5c0e1eddcd2ee473f41dfc0bf_/lib/python3.11/site-packages/pandas/_libs/tslibs/__init__.py", line 39, in <module>
  File "conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "parsing.pyx", line 45, in init pandas._libs.tslibs.parsing
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1080, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1504, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1476, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1616, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1659, in _fill_cache
OSError: [Errno 5] Input/output error: '.../.snakemake/cb8810a5c0e1eddcd2ee473f41dfc0bf_/lib/python3.11/site-packages/dateutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../.snakemake/scripts/tmp2qk3mbk4.preprocess_report.py", line 21, in <module>
OSError: [Errno 5] Input/output error: '.../projects/good/sunbeam_output/logs/preprocess_report.log'
```

A couple notes:
-  This works on the CI builds still
- I've rebuilt all these environments with different versions of python and the packages
- I've removed and reinstalled conda
- Running the pipeline with `-j 1 -c 1` makes the cutadapt problem go away but not the others

Any help would be greatly appreciated. Here's the affected repo but I haven't been able to reproduce the problem on any other machine (https://github.com/sunbeam-labs/sunbeam/tree/7a6979c700328aee9e061d95be4da3ba2ece9cd8). Really hoping the answer isn't to throw my computer out a window.

**Comment by Ulthran** [comment]
OK I found a "solution" which is to switch to a new WSL shell. I was using Ubuntu 20 before and I switched to Ubuntu 22. Still no idea what went wrong but hopefully this can help if anyone encounters this in the future.
