### ISSUE TITLE
snakemake command line cannot run after installing storage plugin

### ISSUE THREAD

**Issue by mkiyer** [snakemake/snakemake#2564]
**Snakemake version**
8.0.1

**Describe the bug**
I used bioconda to install snakemake 8.0.1 

and then installed snakemake-storage-plugin-ftp

Now if I type "snakemake" I get the following error:

$ snakemake
Traceback (most recent call last):
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/cli.py", line 2045, in main
    parser, args = parse_args(argv)
                   ^^^^^^^^^^^^^^^^
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/cli.py", line 1637, in parse_args
    parser = get_argument_parser()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/cli.py", line 1620, in get_argument_parser
    StoragePluginRegistry().register_cli_args(parser)
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake_interface_common/plugin_registry/__init__.py", line 60, in register_cli_args
    plugin.register_cli_args(argparser)
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake_interface_common/plugin_registry/plugin.py", line 152, in register_cli_args
    settings.add_argument(*args, **kwargs)
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/snakemake/common/argparse.py", line 32, in add_argument
    super().add_argument(*args, **kwargs)
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/site-packages/configargparse.py", line 1399, in add_argument
    action = self.original_add_argument_method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/peterallen/mki3/sw/miniforge3/envs/smk/lib/python3.12/argparse.py", line 1472, in add_argument
    action = action_class(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: _StoreTrueAction.__init__() got an unexpected keyword argument 'metavar'

I think there is some issue with adding plugins. Command line arguments need to be registered and there is a "store_true" command line argument that breaks the registration because "metavar" shouldn't be used. I'm not sure. Please help as I would love to upgrade to the next version of snakemake

https://stackoverflow.com/questions/11999416/python-argparse-metavar-and-action-store-true-together

**Logs**
None available.. this occurs just by typing "snakemake" at the command line

**Minimal example**
See above

**Additional context**
red hat enterprise linux 8
python 3.12

**Comment by lparsons** [comment]
I have run into this same issue. After installing the ftp plugin, snakemake will not run. See https://github.com/snakemake/snakemake-storage-plugin-ftp/issues/3.
