### ISSUE TITLE
v8 traceback line numbers incorrect 

### ISSUE THREAD

**Issue by conchoecia** [snakemake/snakemake#2565]
**Snakemake version**
The error occurs on `snakemake/8.0.1-3.12.1` #2535, and I verified that the unwanted behavior does not occur in previous versions, such as `snakemake/7.32.4-3.12.1`.

**Describe the bug**
In snakemake v8, the line numbers in syntax error or  runtime error tracebacks are incorrect. This makes debugging very difficult!

**Logs**
In one snakefile that I was running, there is a dictionary that was missing a key. In `snakemake v8` the traceback leads me to line 253 of the code. This file does not actually have line 253, and it appears that it is line 253 because snakemake compiles some new set of code using the new module feature. Here is the traceback when running this script with snakemake v8:

```
> snakemake --cores 5 -p --snakefile GenDB_build_db_annotated_chr.snakefile -n
Traceback (most recent call last):
  File "/home/apps/snakemake/8.0.1-3.12.1/snakemake/cli.py", line 1895, in args_to_api
    dag_api = workflow_api.dag(
              ^^^^^^^^^^^^^^^^^
  File "/home/apps/snakemake/8.0.1-3.12.1/snakemake/api.py", line 326, in dag
    return DAGApi(
           ^^^^^^^
  File "<string>", line 6, in __init__
  File "/home/apps/snakemake/8.0.1-3.12.1/snakemake/api.py", line 421, in __post_init__
    self.workflow_api._workflow.dag_settings = self.dag_settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apps/snakemake/8.0.1-3.12.1/snakemake/api.py", line 372, in _workflow
    workflow.include(
  File "/home/apps/snakemake/8.0.1-3.12.1/snakemake/workflow.py", line 1363, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/scratch/molevo/dts/odp/dev_scripts/GenDB_build_db_annotated_chr.snakefile", line 253,
```

The offending line with the dictionary in question is actually on line 135 of my snakefile. When I run the same snakefile with snakemake v7, I get an error message pointing me to the correct line:

```
> module load snakemake/7.32.4-3.12.1
> snakemake --cores 5 -p --snakefile GenDB_build_db_annotated_chr.snakefile -n
KeyError in file GenDB_build_db_annotated_chr.snakefile, line 135:
'annotated_genome_tsv'
  File "GenDB_build_db_annotated_chr.snakefile", line 135, in <module>
```

**Minimal example**
I don't have a minimal example due to the complexity of the input files, but I am including the snakefile and the file containing the helper functions that are invoked here. The error is being caused by line 135 of `GenDB_build_db_annotated_chr.snakefile`, in which this dictionary isn't correctly populated when the function from the `GenDB.py` file is called before DAG calculation.
[GenDB.py.txt](https://github.com/snakemake/snakemake/files/13785432/GenDB.py.txt)
[GenDB_build_db_annotated_chr.snakefile.txt](https://github.com/snakemake/snakemake/files/13785433/GenDB_build_db_annotated_chr.snakefile.txt)

**Additional context**
N/A

**Comment by dariober** [comment]
See also #2574 and links therein.

**Comment by corneliusroemer** [comment]
This is still occurring in the latest snakemake v9.12

When there's a syntax error in the main Snakefile, the error message shows file "<string>" instead of the actual Snakefile path, making it very difficult to debug.

Example error output:

```
❯ snakemake
  Using workflow specific profile profiles/default for setting default command line arguments.
  IndentationError in file "<string>", line 21:
  unindent does not match any outer indentation level:
          ),
    File "/Users/cr/micromamba/envs/pp-integrity/lib/python3.12/tokenize.py", line 588, in _generate_tokens_from_c_tokenizer
    File "/Users/cr/micromamba/envs/pp-integrity/lib/python3.12/tokenize.py", line 584, in _generate_tokens_from_c_tokenizer
```
