### ISSUE TITLE
IsADirectoryError on .snakemake/metadata in persistence.py: _read_record_uncached method (line564)

### ISSUE THREAD

**Issue by pdagosto** [snakemake/snakemake#2571]
**Snakemake version**
7.32.4

**Describe the bug**
I get the following error:

IsADirectoryError: [Errno 21] Is a directory: '/work/repos/sbg_workflow_execution/output/vca_221007_M07989_KJ6R8_internal_snp100-x2_010224-203953-432766_pdagosto/vca/.snakemake/metadata'

**Logs**
Here's the stack trace:
ERROR - 2024-01-02 15:39:54,182 Building DAG of jobs...
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/persistence.py", line 613, in _record_path
    b64id = ["@" + s for s in b64id[:-1]] + [b64id[-1]]
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/persistence.py", line 613, in _record_path
    b64id = ["@" + s for s in b64id[:-1]] + [b64id[-1]]
Traceback (most recent call last):
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/__init__.py", line 792, in snakemake
    success = workflow.execute(
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/workflow.py", line 895, in execute
    dag.init()
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/dag.py", line 248, in init
    self.update_needrun(create_inventory=True)
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/dag.py", line 1221, in update_needrun
    if update_needrun(job):
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/dag.py", line 1167, in update_needrun
    reason.params_changed = any(
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/persistence.py", line 641, in <genexpr>
    return (f for f in job.expanded_output if func(job, file=f))
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/persistence.py", line 431, in _params_changed
    recorded = self.params(file)
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/persistence.py", line 370, in params
    return self.metadata(path).get("params")
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/persistence.py", line 352, in metadata
    return self._read_record(self._metadata_path, path)
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/persistence.py", line 559, in _read_record_cached
    return self._read_record_uncached(subject, id)
  File "/work/miniconda3/envs/sbg/lib/python3.9/site-packages/snakemake/persistence.py", line 564, in _read_record_uncached
    with open(self._record_path(subject, id), "r") as f:
IsADirectoryError: [Errno 21] Is a directory: '/work/repos/sbg_workflow_execution/output/vca_221007_M07989_KJ6R8_internal_snp100-x2_010224-203953-432766_pdagosto/vca/.snakemake/metadata'

**Minimal example**
I don't have a minimal example yet. I will try to create a minimal example but I don't know what's going wrong so I'm unsure how to build it.

**Comment by pdagosto** [comment]
Update - this is not a bug. I found that the problem was that one or more output file names were not initialized. Please disregard this issue.
