### ISSUE TITLE
Download dependencies when running CI jobs

### ISSUE THREAD

**Issue by ferrarimarco** [snakemake/snakemake#2608]
**Snakemake version**
8.1.1

**Describe the bug**

As described in #1989, snakemake dependencies don't have version constraints configured, so they get the latest versions available. Is the [main](https://github.com/snakemake/snakemake/blob/main/.github/workflows/main.yml) workflow going to catch this kind of issues, even if it apparently restores the environment from a cache?

https://github.com/snakemake/snakemake/blob/551cba1eb121bbafaf04c296e7c6863bb354bd89/.github/workflows/main.yml#L61-L66

Thanks for looking this up!

**Logs**

```
Traceback (most recent call last):
#126 11.06   File "/venvs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2037, in main
#126 11.06     parser, args = parse_args(argv)
#126 11.06                    ^^^^^^^^^^^^^^^^
#126 11.06   File "/venvs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 1629, in parse_args
#126 11.06     parser = get_argument_parser()
#126 11.06              ^^^^^^^^^^^^^^^^^^^^^
#126 11.06   File "/venvs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 770, in get_argument_parser
#126 11.06     lp_solvers = pulp.list_solvers(onlyAvailable=True)
#126 11.06                  ^^^^^^^^^^^^^^^^^
#126 11.06 AttributeError: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?. Error code: 1
```

**Minimal example**
See the main snakemake workflow.

**Additional context**
#1989

https://github.com/coin-or/pulp/pull/691

**Comment by ernstki** [comment]
For the benefit of people arriving here after searching for `AttributeError: module 'pulp' has no attribute 'list_solvers'`, who just want to get past the error:

```bash
# assuming you're within a virtualenv*
pip uninstall pulp
pip install 'pulp<2.8'
```

Or, add this to your `requirements.txt`**:

```
pulp<2.8
```

then:

```bash
pip uninstall pulp
pip install -r requirements.txt
```

To be sure, this will be a short-lived workaround, but at least you can _use_ Snakemake after installing it.

---
\*or use `pip install --local`, or `pipx inject`, or whatever it is the cool kids are using these days
\*\*or `pyproject.toml`, or `setup.py`, or whatever

**Comment by ernstki** [comment]
See also #2607, which claims to have fixed this issue by switching to the new `pulp` API, but only for Pythons > 3.10.

If you're stuck with an LTS Linux, or just an older Python, such as 3.8. You'll still need to use the workaround above.
