### ISSUE TITLE
Installing snakemake-storage-plugin-azure results in unworkable snakemake

### ISSUE THREAD

**Issue by NPPO-NL** [snakemake/snakemake#2635]
**version 8.2.1**

Hello,
I am testing Snakemake and its azure-batch functionalities. However, after installation of the snakemake-storage-plugin-azure in my conda environment Snakemake became unworkable. 

---In summary
First I installed Snakemake version 8.2.1 in a new conda environment:
```console
$ conda create -n az-snakemake_v8.2.1 -c bioconda -c conda-forge snakemake
$ conda activate az-snakemake_v8.2.1
```

next I installed the snakemake-executor-plugin-azure-batch
```console
$ conda install -c bioconda -c conda-forge bioconda::snakemake-executor-plugin-azure-batch
```

When testing this plugin, I got the following message:
```console
Error: If no shared filesystem is assumed for input and output files, a default storage provider (--default-storage-provider) and default storage prefix (--default-storage-prefix) has to be set. See https://snakemake.github.io/snakemake-plugin-catalog for possible storage provider plugins
```

Therefore, I installed the azure storage plugin
```console
$ conda install -c bioconda -c conda-forge bioconda::snakemake-storage-plugin-azure
```

After this, even checking the snakemake version showed the following error message:
```console
$ snakemake --version                                                                                
Traceback (most recent call last):
  File "/home/michael/.conda/envs/az-snakemake_v8.2.1/lib/python3.12/site-packages/snakemake/cli.py", line 2038, in main
    parser, args = parse_args(argv)
                   ^^^^^^^^^^^^^^^^
  File "/home/michael/.conda/envs/az-snakemake_v8.2.1/lib/python3.12/site-packages/snakemake/cli.py", line 1628, in parse_args
    parser = get_argument_parser()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/.conda/envs/az-snakemake_v8.2.1/lib/python3.12/site-packages/snakemake/cli.py", line 1611, in get_argument_parser
    StoragePluginRegistry().register_cli_args(parser)
  File "/home/michael/.conda/envs/az-snakemake_v8.2.1/lib/python3.12/site-packages/snakemake_interface_common/plugin_registry/__init__.py", line 60, in register_cli_args
    plugin.register_cli_args(argparser)
  File "/home/michael/.conda/envs/az-snakemake_v8.2.1/lib/python3.12/site-packages/snakemake_interface_common/plugin_registry/plugin.py", line 149, in register_cli_args
    kwargs["help"] += (
TypeError: can only concatenate tuple (not "str") to tuple
```

I expect this is a bug of the snakemake-storage-plugin-azure. Moreover, I tried installing the azure plugins using pip but this resulted in the same error message. Hopefully this bug can be fixed.

Kind regards,
Michael

**Comment by saulobejo** [comment]
@NPPO-NL 

I've made a pull request ( https://github.com/snakemake/snakemake-storage-plugin-azure/pull/8#issue-2094030340 ) to fix this error.

**Comment by johanneskoester** [comment]
Thanks! Merged and released!
