### ISSUE TITLE
Containerization fails when workflow has global Conda directive

### ISSUE THREAD

**Issue by kbseah** [snakemake/snakemake#2693]
**Snakemake version**
v8.3.7

**Describe the bug**
Attempt to generate a Dockerfile with `snakemake --containerize` fails when the workflow has a global Conda directive.

**Logs**
The following error message was produced when attempting to containerize a workflow with a global Conda environment depending on `pandas`:

```
Traceback (most recent call last):
  File "/mnt/data/uebergabe/MB_Pipeline_dev/workflow/snakemake_8/lib/python3.12/site-packages/snakemake/cli.py", line 1898, in args_to_api
    dag_api = workflow_api.dag(
              ^^^^^^^^^^^^^^^^^
  File "/mnt/data/uebergabe/MB_Pipeline_dev/workflow/snakemake_8/lib/python3.12/site-packages/snakemake/api.py", line 326, in dag
    return DAGApi(
           ^^^^^^^
  File "<string>", line 6, in __init__
  File "/mnt/data/uebergabe/MB_Pipeline_dev/workflow/snakemake_8/lib/python3.12/site-packages/snakemake/api.py", line 436, in __post_init__
    self.workflow_api._workflow.dag_settings = self.dag_settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/uebergabe/MB_Pipeline_dev/workflow/snakemake_8/lib/python3.12/site-packages/snakemake/api.py", line 383, in _workflow
    workflow.include(
  File "/mnt/data/uebergabe/MB_Pipeline_dev/workflow/snakemake_8/lib/python3.12/site-packages/snakemake/workflow.py", line 1379, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/mnt/data/uebergabe/troubleshoot-snakemake-containerize/toy-wf/workflow/Snakefile", line 10, in <module>
    pd.show_versions()
ModuleNotFoundError: No module named 'pandas'
```

**Minimal example**
I've set up a toy workflow in this repository to reproduce the error: https://github.com/kbseah/toy-wf

The `master` branch does not use a global Conda directive, and a Dockerfile can be successfully generated:
```bash
git clone git@github.com:kbseah/toy-wf.git
git checkout master
snakemake --containerize > Dockerfile # success
```

In the `global` branch I've added a global Conda directive. The workflow executes successfully with `--sdm conda`, but Snakemake returns an error when I attempt to containerize:
```bash
git checkout global
snakemake --containerize > Dockerfile # failure
```

**Additional context**

**Comment by kbseah** [comment]
Update:

Adding option `--sdm conda` to the containerize command allows Dockerfile to be built:

```bash
git checkout global
snakemake --sdm conda --containerize > Dockerfile # success
```

However there are still two points unclear to me:

1.
The conda environment defined in the global directive is not containerized, unlike those defined in rules. Shouldn't that be included in the container too?

2. 
If I containerize a workflow without global Conda directive, I can add the `containerized` directive, and run it with `snakemake --sdm apptainer`. For each job, Snakemake tells me that it is activating the singularity image.

However, if the workflow contains a global Conda directive, I can still containerize it with `snakemake --sdm conda --containerize >Dockerfile`, build the Docker image, and add a `containerized` directive to the Snakefile. However, if I then try to run `snakemake --sdm apptainer`, the workflow does not run because Conda is needed for the global environment. If I specify instead `snakemake --sdm conda apptainer`, the workflow does run, but now for each job it reports that it is activating a singularity image AND activating a conda environment.

This behavior doesn't seem right to me, because I would expect that either (a) conda is used for the global directive, and only apptainer for all the containerized rules, or (b) both the global and per-rule conda environments are containerized, and only `--sdm apptainer` is necessary.

I hope that this makes sense

**Comment by kbseah** [comment]
possibly relevant: #2602

**Comment by m-jahn** [comment]
I had similar issues and needed to play around building singularity containers with and without the global directive. 
To me it appeared that the global env is not included in the container definition nor the final built image, regardless if I use `snakemake --containerize` with `--sdm conda` or not.
Eventually I got it to work but the relationship of a global conda env and a remote singularity/apptainer image remains vague to me. It should at least be documented in upcoming releases if and how these two options are compatible with each other.
