### ISSUE TITLE
`mtime` comparison between remote and local storage incompatible

### ISSUE THREAD

**Issue by ebete** [snakemake/snakemake#2723]
This exception is thrown when the the DAG solver tries to compare the `mtime` of a local file and one from a remote storage provider (iRODS in my case).

**Snakemake version**
```
snakemake 8.5.3
snakemake-storage-plugin-irods 0.1.1
python 3.12.2
```

**Describe the bug**

This line may compare incompatible types (`datetime.datetime` vs. `float`), throwing a `TypeError`:

https://github.com/snakemake/snakemake/blob/b6b16a7e735869343a094a5e5d475a3eac14afe3/snakemake/io.py#L617

AFAIK this is due to the `mtime` of a storage plugin returning a float, as defined in the ABC here:
[snakemake/snakemake-interface-storage-plugins/snakemake_interface_storage_plugins/storage_object.py#L135](https://github.com/snakemake/snakemake-interface-storage-plugins/blob/265690c00dc8d784dc5e1c599903168ecfa21b63/snakemake_interface_storage_plugins/storage_object.py#L135
)

While the local storage returns `Mtime`, I think? And then does something else that produces a `datetime.datetime`?

**Logs**
```
. . .

Building DAG of jobs...
WARNING:snakemake.logging:Building DAG of jobs...
Traceback (most recent call last):
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2010, in args_to_api
    dag_api.execute_workflow(
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/site-packages/snakemake/api.py", line 590, in execute_workflow
    workflow.execute(
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1068, in execute
    self._build_dag()
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1024, in _build_dag
    async_run(self.dag.init())
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/site-packages/snakemake/common/__init__.py", line 89, in async_run
    return asyncio.run(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 210, in init
    await self.update_needrun(create_inventory=True)
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 1289, in update_needrun
    if await update_needrun(job):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 1190, in update_needrun
    and await f.is_newer(output_mintime_)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$CONDA_ROOT/envs/snakemake/lib/python3.12/site-packages/snakemake/io.py", line 617, in is_newer
    return (await self.mtime()).local_or_storage(follow_symlinks=True) > time
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'datetime.datetime' and 'float'
```

**Minimal example**

1. Have a rule with a remote input file.
2. Execute the workflow so the file stats get cached.
3. Rerun the workflow.
4. :tada:

```py
storage:
    provider = "irods"

rule all:
    message: "All target files have been generated/updated"
    default_target: True
    threads: 1
    input:
        expand("{project}/from_remote.txt", project=OUTPUT_DIR)


rule download_samples:
    message: "[IRODS] Copying {input} to local storage"
    input:
        storage.irods("irods://zone/file.txt")
    output:
        "{project}/from_remote.txt"
    threads: 1
    resources:
        mem_mb = 100,
        runtime_max = 3600
    shell:
        "cp --preserve=timestamps --no-target-directory --verbose --dereference"
        " {input:q}"
        " {output:q}"

```

**Additional context**

**Comment by ebete** [comment]
I am using this small hack to work around this issue for now. The actual fix should fix the root cause as otherwise it'll probably cause issues elsewhere where `mtime` is expected to be a `datetime.datetime`.

```diff
diff --git a/snakemake/io.py b/snakemake/io.py
index 5f1f5eed..1652abef 100755
--- a/snakemake/io.py
+++ b/snakemake/io.py
@@ -614,6 +614,9 @@ class _IOFile(str, AnnotatedStringInterface):
         if self.is_ancient:
             return False
 
+        if isinstance(time, (float, int)):
+            time = datetime.datetime.fromtimestamp(time)
+
         return (await self.mtime()).local_or_storage(follow_symlinks=True) > time
 
     async def retrieve_from_storage(self):

```

**Comment by johanneskoester** [comment]
This has to be fixed in the irods plugin. Basically we have to ensure that it does not return datetime but the timestamp in its mtime methods.

**Comment by johanneskoester** [comment]
https://github.com/snakemake/snakemake-storage-plugin-irods/pull/5
https://github.com/snakemake/snakemake-interface-storage-plugins/pull/38

**Comment by ebete** [comment]
@johanneskoester Great! It looks like it's working now. Thanks for the patch
