### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by ltalignani** [snakemake/snakemake#2724]
I am using snakemake 7.25.0 on a slurm cluster. I am trying to use a slurm profile:

```
jobs: 100
use-singularity: True
keep-going: True
rerun-incomplete: True
printshellcmds: True
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 600

cluster:
  sbatch
    --account=invalbo
    --parsable
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name={rule}-{wildcards}
    --output={rule}-{wildcards}-%j.out
default-resources:
  - mem_mb=5000
  - cpus_per_task=8
  - partition=fast

```
but but when I use it with the command: 
```
snakemake --profile=slurm/ --directory ${workdir}/ --snakefile workflow/Snakefile --unlock
snakemake --profile=slurm/ \
          --jobs 50 \
          --directory ${workdir}/ \
          --snakefile workflow/Snakefile \
          --configfile config/config.yaml \
          --retries 8 \
          --rerun-incomplete \
          --keep-going \
          --scheduler greedy \
          --printshellcmds \
          --latency-wait 600 \
          --max-jobs-per-second 10 \
          --max-status-checks-per-second 5 \
          --use-singularity \
          --use-conda 
```
Snakemake crashes. This is an extract from the log file:
```
Unlocking working directory.
Config file config/config.yaml is extended by additional config specified via the command line.
Config file config/config.yaml is extended by additional config specified via the command line.
Config file config/config.yaml is extended by additional config specified via the command line.
Config file config/config.yaml is extended by additional config specified via the command line.
Config file config/config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 50
Conda environments: ignored
Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
GenomicsDBImport           4              1              1
GenotypeGVCFs_merge        4              1              1
HaplotypeCaller          116              1              1
all                        1              1              1
bcftools_concat            4              1              1
total                    129              1              1

mkdir -p Cluster_logs/
Select jobs to execute...

[Mon Feb 26 15:23:39 2024]
Job 325: GATK's HaplotypeCaller SNPs and indels calling for Sample_1_EKDN230051723-1A_H2F5FDSXC_L3 sample
Reason: Missing output files: results/05_Variants/Sample_1_EKDN230051723-1A_H2F5FDSXC_L3.3.g.vcf

module load gatk4/4.2.6.1
            gatk HaplotypeCaller --java-options "-Xmx16000M" -ERC GVCF --output-mode EMIT_ALL_CONFIDENT_SITES -R resources/genomes/GCF_035046485.1_AalbF5_genomic.fna -I results/04_Polishing/Sample_1_EKDN230051723-1A_H2F5FDSXC_L3_md_fixed.bam -O results/05_Variants/Sample_1_EKDN230051723-1A_H2F5FDSXC_L3.3.g.vcf             -L 3             1>results/11_Reports/haplotypecaller/Sample_1_EKDN230051723-1A_H2F5FDSXC_L3.3_variant-call.o 2>results/11_Reports/haplotypecaller/Sample_1_EKDN230051723-1A_H2F5FDSXC_L3.3_variant-call.e
        
Traceback (most recent call last):
  File "/shared/ifbstor1/software/miniconda/envs/snakemake-7.25.0/lib/python3.11/site-packages/snakemake/__init__.py", line 757, in snakemake
    success = workflow.execute(
              ^^^^^^^^^^^^^^^^^
  File "/shared/ifbstor1/software/miniconda/envs/snakemake-7.25.0/lib/python3.11/site-packages/snakemake/workflow.py", line 1095, in execute
    raise e
  File "/shared/ifbstor1/software/miniconda/envs/snakemake-7.25.0/lib/python3.11/site-packages/snakemake/workflow.py", line 1091, in execute
    success = self.scheduler.schedule()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/ifbstor1/software/miniconda/envs/snakemake-7.25.0/lib/python3.11/site-packages/snakemake/scheduler.py", line 606, in schedule
    self.run(runjobs)
  File "/shared/ifbstor1/software/miniconda/envs/snakemake-7.25.0/lib/python3.11/site-packages/snakemake/scheduler.py", line 655, in run
    executor.run_jobs(
  File "/shared/ifbstor1/software/miniconda/envs/snakemake-7.25.0/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 155, in run_jobs
    self.run(
  File "/shared/ifbstor1/software/miniconda/envs/snakemake-7.25.0/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 1153, in run
    jobscript = self.get_jobscript(job)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/ifbstor1/software/miniconda/envs/snakemake-7.25.0/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 872, in get_jobscript
    f = self.get_jobname(job)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/shared/ifbstor1/software/miniconda/envs/snakemake-7.25.0/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 869, in get_jobname
    return job.format_wildcards(self.jobname, cluster=self.cluster_wildcards(job))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/ifbstor1/software/miniconda/envs/snakemake-7.25.0/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 931, in cluster_wildcards
    return Wildcards(fromdict=self.cluster_params(job))

File "/shared/ifbstor1/software/miniconda/envs/snakemake-7.25.0/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 906, in cluster_params
    cluster = self.cluster_config.get("__default__", dict()).copy()
              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

```

I should point out that I've created a snakefile that calls modules. It's the last module "calling.smk" that causes the crash, but I don't know where the problem comes from. 
Here's an example of the rule I am using:

```
# CONFIGURATION FILES #
configfile: "config/config.yaml"
cluster_config: "slurm/config.yaml"

# PARAMETERS #
REFPATH = config["ref"]["path"]                     # Path to reference genome
DICTIONARY = config["ref"]["dictionary"]            # Reference dictionary filename
REFINDEX = config["ref"]["index"]                   # Samtools reference index
reference_file =  config["ref"]["reference"]
basename_reference = Path(reference_file).stem

###############################################################################
rule HaplotypeCaller:
    message:
        "GATK's HaplotypeCaller SNPs and indels calling for {wildcards.sample} sample"
    resources:
        partition  = 'long',
        mem_mb     = 32000,
        runtime    = 12000,
    input:
        bam        = rules.fixmateinformation.output.fixed,
        index      = rules.index_fixed_bam.output.index,
        reference  = reference_file,
        dictionary = REFPATH+DICTIONARY,
        fai        = REFPATH+REFINDEX,
    output:
        gvcf       = "results/05_Variants/{sample}.{chromosomes}.g.vcf",

    log:
        output     = "results/11_Reports/haplotypecaller/{sample}.{chromosomes}_variant-call.o",
        error      = "results/11_Reports/haplotypecaller/{sample}.{chromosomes}_variant-call.e",
    params:
        other_options = config["gatk"]["haplotypecaller"],
        output_mode   = config["gatk"]["output_mode"],
        interval      = "{chromosomes}",
    benchmark:
        "benchmarks/haplotypecaller/{sample}_{chromosomes}_variant-call.tsv"
    container:
        "https://depot.galaxyproject.org/singularity/gatk4-spark:4.5.0.0--hdfd78af_0"
    shell:
        """
        gatk HaplotypeCaller --java-options "-Xmx{resources.mem_mb}M" {params.other_options} --output-mode {params.output_mode} -R {input.reference} -I {input.bam} -O {output.gvcf} -L {params.interval} 1>{log.output} 2>{log.error}
        """
```

**Comment by cademirch** [comment]
In Snakemake 7.xx you should use the `--slurm` option in favor of the cluster profile. See here for relevant docs:
https://snakemake.readthedocs.io/en/v7.32.3/executing/cluster.html#executing-on-slurm-clusters

In Snakemake 8.xx you should use the executor plugin for slurm. Read more here: https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html

**Comment by Hocnonsense** [comment]
It seems to be caused by a typo, and in snakemake >=8 the logic is rewrote. If this bug still exists in the newer version, you could create a new issue.
