### ISSUE TITLE
Trace back fails due to spelling mistake in exceptions.py

### ISSUE THREAD

**Issue by svsuresh** [snakemake/snakemake#2763]
snakemake version: 8.8.0
OS: MacOS 13. 6 (M1 pro)
Python version: 3.12.2
pip3 version: 24
Homebrew version: >=4.1.0

**Bug**
Trace back fails due to spelling error in /opt/homebrew/Cellar/snakemake/8.8.0/libexec/lib/python3.12/site-packages/snakemake/exceptions.py.

**Logs**

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/snakemake/8.8.0/libexec/lib/python3.12/site-packages/snakemake/cli.py", line 1921, in args_to_api
    workflow_api = snakemake_api.workflow(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/snakemake/8.8.0/libexec/lib/python3.12/site-packages/snakemake/api.py", line 141, in workflow
    self.setup_logger(mode=workflow_settings.exec_mode)
  File "/opt/homebrew/Cellar/snakemake/8.8.0/libexec/lib/python3.12/site-packages/snakemake/api.py", line 250, in setup_logger
    setup_logger(
  File "/opt/homebrew/Cellar/snakemake/8.8.0/libexec/lib/python3.12/site-packages/snakemake/logging.py", line 748, in setup_logger
    raise ValueError(
ValueError: Unsupported value provided for quiet mode (either bool, None or list allowed).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/snakemake/8.8.0/libexec/lib/python3.12/site-packages/snakemake/cli.py", line 2129, in main
    success = args_to_api(args, parser)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/snakemake/8.8.0/libexec/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    snakemake_api.print_exception(e)
  File "/opt/homebrew/Cellar/snakemake/8.8.0/libexec/lib/python3.12/site-packages/snakemake/api.py", line 241, in print_exception
    print_exception(ex, linemaps)
  File "/opt/homebrew/Cellar/snakemake/8.8.0/libexec/lib/python3.12/site-packages/snakemake/exceptions.py", line 162, in print_exception
    logger.error(traceback.format_exeption(ex))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'traceback' has no attribute 'format_exeption'. Did you mean: 'format_exception'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/snakemake", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/snakemake/8.8.0/libexec/lib/python3.12/site-packages/snakemake/cli.py", line 2131, in main
    print_exception(e)
  File "/opt/homebrew/Cellar/snakemake/8.8.0/libexec/lib/python3.12/site-packages/snakemake/exceptions.py", line 162, in print_exception
    logger.error(traceback.format_exeption(ex))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'traceback' has no attribute 'format_exeption'. Did you mean: 'format_exception'

**Comment by peterjc** [comment]
This can be closed, it was fixed in ee9639385cb2c9cec425800088faee4e4bf77c9a
