### ISSUE TITLE
ModuleNotFoundError: No module named 'asyncore'

### ISSUE THREAD

**Issue by PandengWang** [snakemake/snakemake#2841]
**Snakemake version**：8.10.8
**Python version**：3.12.3

**Describe the bug**：

Traceback (most recent call last):

  File "/public1/fsoftware/conda_envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 1949, in args_to_api
    config_settings=ConfigSettings(
                    ^^^^^^^^^^^^^^^

  File "<string>", line 6, in __init__

  File "/public1/fsoftware/conda_envs/snakemake/lib/python3.12/site-packages/snakemake/settings.py", line 315, in __post_init__
    self.overwrite_config = self._get_overwrite_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/public1/fsoftware/conda_envs/snakemake/lib/python3.12/site-packages/snakemake/settings.py", line 323, in _get_overwrite_config
    update_config(overwrite_config, load_configfile(f))
                                    ^^^^^^^^^^^^^^^^^^

  File "/public1/fsoftware/conda_envs/snakemake/lib/python3.12/site-packages/snakemake/common/configfile.py", line 38, in load_configfile
    config = _load_configfile(configpath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/public1/fsoftware/conda_envs/snakemake/lib/python3.12/site-packages/snakemake/common/configfile.py", line 23, in _load_configfile
    import yte

  File "/public1/fsoftware/conda_envs/snakemake/lib/python3.12/site-packages/yte/__init__.py", line 3, in <module>
    import plac

  File "/public1/fsoftware/conda_envs/snakemake/lib/python3.12/site-packages/plac.py", line 29, in <module>
    from plac_ext import (Interpreter, import_main, ReadlineInput,

  File "/public1/fsoftware/conda_envs/snakemake/lib/python3.12/site-packages/plac_ext.py", line 806, in <module>
    import asyncore

ModuleNotFoundError: No module named 'asyncore'

**Additional context**

![image](https://github.com/snakemake/snakemake/assets/48956396/33a98ef6-f110-4226-a3fe-192cea5509b6)

**Comment by maarten-k** [comment]
This issue should be fixed in the latest version of place. Can you try to update plac?

**Comment by PandengWang** [comment]
> This issue should be fixed in the latest version of plac. Can you try to update plac?

I downgraded the version of snakemake to 8.10.0, and it works.
