### ISSUE TITLE
Error while installing snakemake 5.11.* on WSL1 using PIP

### ISSUE THREAD

**Issue by bkohrn** [snakemake/snakemake#286]
I am attempting to install snakemake 5.11.* on WSL1 (Windows Subsystem for Linux 1) using PIP with the following command (which to my knowledge should work):

`sudo pip3 install --upgrade snakemake `

I get a bunch of dependency updates, which seem to work. followed by:  

```
Installing collected packages: snakemake, setuptools
  Found existing installation: snakemake 5.5.4
    Uninstalling snakemake-5.5.4:
      Successfully uninstalled snakemake-5.5.4
  Running setup.py install for snakemake ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-og_5zrcr/snakemake/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7idq03dl-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/snakemake
    copying snakemake/__init__.py -> build/lib/snakemake
    copying snakemake/__main__.py -> build/lib/snakemake
    copying snakemake/_version.py -> build/lib/snakemake
    copying snakemake/benchmark.py -> build/lib/snakemake
    copying snakemake/checkpoints.py -> build/lib/snakemake
    copying snakemake/common.py -> build/lib/snakemake
    copying snakemake/cwl.py -> build/lib/snakemake
    copying snakemake/dag.py -> build/lib/snakemake
    copying snakemake/decorators.py -> build/lib/snakemake
    copying snakemake/exceptions.py -> build/lib/snakemake
    copying snakemake/executors.py -> build/lib/snakemake
    copying snakemake/gui.py -> build/lib/snakemake
    copying snakemake/io.py -> build/lib/snakemake
    copying snakemake/jobs.py -> build/lib/snakemake
    copying snakemake/logging.py -> build/lib/snakemake
    copying snakemake/notebook.py -> build/lib/snakemake
    copying snakemake/output_index.py -> build/lib/snakemake
    copying snakemake/parser.py -> build/lib/snakemake
    copying snakemake/persistence.py -> build/lib/snakemake
    copying snakemake/resources.py -> build/lib/snakemake
    copying snakemake/rules.py -> build/lib/snakemake
    copying snakemake/scheduler.py -> build/lib/snakemak
    copying snakemake/script.py -> build/lib/snakemake
    copying snakemake/shell.py -> build/lib/snakemake
    copying snakemake/stats.py -> build/lib/snakemake
    copying snakemake/utils.py -> build/lib/snakemake
    copying snakemake/workflow.py -> build/lib/snakemake
    copying snakemake/wrapper.py -> build/lib/snakemake
    creating build/lib/snakemake/remote
    copying snakemake/remote/AzureStorage.py -> build/lib/snakemake/remote
    copying snakemake/remote/EGA.py -> build/lib/snakemake/remote
    copying snakemake/remote/FTP.py -> build/lib/snakemake/remote
    copying snakemake/remote/GS.py -> build/lib/snakemake/remote
    copying snakemake/remote/HTTP.py -> build/lib/snakemake/remote
    copying snakemake/remote/NCBI.py -> build/lib/snakemake/remote
    copying snakemake/remote/S3.py -> build/lib/snakemake/remote
    copying snakemake/remote/S3Mocked.py -> build/lib/snakemake/remote
    copying snakemake/remote/SFTP.py -> build/lib/snakemake/remote
    copying snakemake/remote/XRootD.py -> build/lib/snakemake/remote
    copying snakemake/remote/__init__.py -> build/lib/snakemake/remote
    copying snakemake/remote/dropbox.py -> build/lib/snakemake/remote
    copying snakemake/remote/gfal.py -> build/lib/snakemake/remote
    copying snakemake/remote/gridftp.py -> build/lib/snakemake/remote
    copying snakemake/remote/iRODS.py -> build/lib/snakemake/remote
    copying snakemake/remote/webdav.py -> build/lib/snakemake/remote
    creating build/lib/snakemake/report
    copying snakemake/report/__init__.py -> build/lib/snakemake/report
    creating build/lib/snakemake/caching
    copying snakemake/caching/__init__.py -> build/lib/snakemake/caching
    copying snakemake/caching/hash.py -> build/lib/snakemake/caching
    copying snakemake/caching/local.py -> build/lib/snakemake/caching
    copying snakemake/caching/remote.py -> build/lib/snakemake/caching
    creating build/lib/snakemake/deployment
    copying snakemake/deployment/__init__.py -> build/lib/snakemake/deployment
    copying snakemake/deployment/conda.py -> build/lib/snakemake/deployment
    copying snakemake/deployment/env_modules.py -> build/lib/snakemake/deployment
    copying snakemake/deployment/singularity.py -> build/lib/snakemake/deployment
    creating build/lib/snakemake/linting
    copying snakemake/linting/__init__.py -> build/lib/snakemake/linting
    copying snakemake/linting/links.py -> build/lib/snakemake/linting
    copying snakemake/linting/rules.py -> build/lib/snakemake/linting
    copying snakemake/linting/snakefiles.py -> build/lib/snakemake/linting
    copying snakemake/report.css -> build/lib/snakemake
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-og_5zrcr/snakemake/setup.py", line 87, in <module>
        "Topic :: Scientific/Engineering :: Bio-Informatics",
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-og_5zrcr/snakemake/versioneer.py", line 1552, in run
        _build_py.run(self)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_py.py", line 53, in run
        self.build_package_data()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_py.py", line 126, in build_package_data
        srcfile in self.distribution.convert_2to3_doctests):
    TypeError: argument of type 'NoneType' is not iterable
    
    ----------------------------------------
  Rolling back uninstall of snakemake
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-og_5zrcr/snakemake/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7idq03dl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-og_5zrcr/snakemake/  
```

I am running WSL1 Ubuntu on Windows 10 1809

**Comment by cademirch** [comment]
Closing due to extended inactivity. Please re-open if this is a still an issue on current Snakemake.
