### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by liamxg** [snakemake/snakemake#2884]
Dear @antunderwood.

```
mamba create -c conda-forge -c bioconda -n snakemake snakemake


                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.2.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['snakemake']

warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
bioconda/osx-64                                               No change
bioconda/noarch                                               No change
filesystem error: last_write_time: Permission denied ["/Users/liam/opt/miniconda3/pkgs/cache/3e39a7aa.json"]

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 936, in exception_converter
        raise e
      File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 929, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 887, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = create(args, parser)
      File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 630, in create
        return install(args, parser, "create")
      File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 497, in install
        index = load_channels(pool, channels, repos)
      File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 129, in load_channels
        index = get_index(
      File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 110, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: filesystem error: last_write_time: Permission denied ["/Users/liam/opt/miniconda3/pkgs/cache/3e39a7aa.json"]

`$ /Users/liam/opt/miniconda3/bin/mamba create -c conda-forge -c bioconda -n snakemake snakemake`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/liam/opt/miniconda3/bin/conda
             CONDA_PREFIX=/Users/liam/opt/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/liam/opt/miniconda3/bin/python
               CONDA_ROOT=/Users/liam/opt/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=/Users/liam/opt/miniconda3/lib/jvm/lib/server
               LD_PRELOAD=<not set>
                     PATH=/Users/liam/opt/miniconda3/bin:/Users/liam/opt/miniconda
                          3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:
                          /usr/sbin:/sbin:/usr/local/ncbi/blast/bin:/Library/TeX/texbin:/opt/X11
                          /bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/var
                          /run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:
                          /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/v
                          ar/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleint
                          ernal/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/liam/opt/miniconda3
            shell level : 1
       user config file : /Users/liam/.condarc
 populated config files : /Users/liam/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.9.15.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=13.6.6=0
                          __unix=0=0
       base environment : /Users/liam/opt/miniconda3  (writable)
      conda av data dir : /Users/liam/opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/liam/opt/miniconda3/pkgs
                          /Users/liam/.conda/pkgs
       envs directories : /Users/liam/opt/miniconda3/envs
                          /Users/liam/.conda/envs
               platform : osx-64
             user-agent : conda/23.1.0 requests/2.31.0 CPython/3.9.15 Darwin/22.6.0 OSX/13.6.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by fgvieira** [comment]
I just tried running `mamba create -c conda-forge -c bioconda -n snakemake snakemake` and it went fine.
If the error persists, than it probably is something with either your `mamba`/`conda` instalation or your filesystem (you are getting a `Permission denied` error).
