### ISSUE TITLE
`snakemake --list-changes code` fails with `TypeError: object async_generator can't be used in 'await' expression`

### ISSUE THREAD

**Issue by denisalevi** [snakemake/snakemake#2956]
**Snakemake version**

`8.16.0+0.g838b2fce.dirty` (from latest stable docker container)
Same error on `8.13.0`

**Describe the bug**

`snakemake --list-changes code` fails with `TypeError: object async_generator can't be used in 'await' expression`.

**Logs**

```bash
$ snakemake --list-changes code
Building DAG of jobs...
Traceback (most recent call last):

  File "/home/denis/.conda/envs/threat/lib/python3.12/site-packages/snakemake/cli.py", line 2060, in args_to_api
    dag_api.list_changes(args.list_changes)

  File "/home/denis/.conda/envs/threat/lib/python3.12/site-packages/snakemake/api.py", line 598, in _handle_no_exec
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/denis/.conda/envs/threat/lib/python3.12/site-packages/snakemake/api.py", line 718, in list_changes
    self.workflow_api._workflow.list_changes(change_type=change_type)

  File "/home/denis/.conda/envs/threat/lib/python3.12/site-packages/snakemake/workflow.py", line 866, in list_changes
    items = async_run(self.dag.get_outputs_with_changes(change_type))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/denis/.conda/envs/threat/lib/python3.12/site-packages/snakemake/common/__init__.py", line 94, in async_run
    return asyncio.run(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^

  File "/home/denis/.conda/envs/threat/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^

  File "/home/denis/.conda/envs/threat/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/denis/.conda/envs/threat/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^

  File "/home/denis/.conda/envs/threat/lib/python3.12/site-packages/snakemake/dag.py", line 2769, in get_outputs_with_changes
    list(await job.outputs_older_than_script_or_notebook())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: object async_generator can't be used in 'await' expression

```
**Minimal example**

I ran it on the [tutorial on Gitpod](https://gitpod.io/#https://github.com/snakemake/snakemake-tutorial-data) with the [summary Snakefile](https://snakemake.readthedocs.io/en/stable/tutorial/basics.html#summary) from the tutorial.

**Comment by lvignoli** [comment]
I confirm the issue is still present on 8.18.0 (python 3.11.8, macOS 14.4.1, arm M1 Pro)

**Comment by nigiord** [comment]
Still present in `9.1.9` (linux-64). Any idea that could be causing this? Is that environment specific or does nobody really use `--list-changes code` to clean-up metadata?

**Comment by johanneskoester** [comment]
Sorry for the delay. It is often hard to find urgent issues given the massive traffic on this repo. Notifying me via discord is the best way to get attention. Above PR fixes the issue.
