### ISSUE TITLE
Error building docs: AttributeError: 'member_descriptor' object has no attribute 'expandtabs'

### ISSUE THREAD

**Issue by Aniket-Pradhan** [snakemake/snakemake#296]
Hello there

I am packaging snakemake for the Fedora operating system, and while building the documentation for snakemake I am getting the following error:

```
sphinx-build -b changes -d _build/doctrees   . _build/changes
Running Sphinx v2.4.4
making output directory... done
/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/util/compat.py:30: RemovedInSphinx30Warning: The config variable "source_parsers" is deprecated. Please update your extension for the parser and remove the setting.
  warnings.warn('The config variable "source_parsers" is deprecated. '
/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/util/compat.py:36: RemovedInSphinx30Warning: app.add_source_parser() does not support suffix argument. Use app.add_source_suffix() instead.
  app.add_source_parser(suffix, parser)
building [mo]: targets for 0 po files that are out of date
building [changes]: /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/docs/_build/changes
updating environment: [new config] 33 added, 0 changed, 0 removed
reading sources... [  6%] api_reference/internal/snakemake                                                                                                                                                                                  
Exception occurred:
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/util/docstrings.py", line 24, in prepare_docstring
    lines = s.expandtabs(tabsize).splitlines()
AttributeError: 'member_descriptor' object has no attribute 'expandtabs'
The full traceback has been saved in /tmp/sphinx-err-1yvw42oq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:154: changes] Error 2
``` 
Now, although this does look like a bug with `sphinx`, but before I report this to those guys, I just wanted to cross-check whether you are facing a similar problem, or is it just me?

**Snakemake version**
5.12.3

**Logs**
The additional log file is here:

```
# Sphinx version: 2.4.4
# Python version: 3.8.2 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.11.1
# Last messages:
#   Running Sphinx v2.4.4
#   making output directory...
#   done
#   building [mo]: targets for 0 po files that are out of date
#   building [changes]: /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/docs/_build/changes
#   updating environment:
#   [new config]
#   33 added, 0 changed, 0 removed
#   reading sources... [  3%] api_reference/internal/modules
#   reading sources... [  6%] api_reference/internal/snakemake
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.4) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (2.4.4) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (2.4.4) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.viewcode (2.4.4) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinxcontrib.napoleon (0.7) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinxcontrib/napoleon/__init__.py
#   sphinxarg.ext (unknown version) from /home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinxarg/ext.py
Traceback (most recent call last):
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(['__all__'], to_build)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/io.py", line 316, in read_doc
    pub.publish()
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/core.py", line 216, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/io.py", line 130, in read
    self.parse()
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/parsers.py", line 93, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2053, in directive
    return self.run_directive(
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/directive.py", line 146, in run
    documenter.generate(more_content=self.content)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 734, in generate
    self.document_members(all_members)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 654, in document_members
    documenter.generate(
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1197, in generate
    return super().generate(more_content=more_content,
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 721, in generate
    sig = self.format_signature()
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1105, in format_signature
    return super().format_signature(**kwargs)
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 937, in format_signature
    result = self._find_signature()
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 894, in _find_signature
    docstrings = self.get_doc()
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1168, in get_doc
    return [prepare_docstring(docstring, ignore, tab_width) for docstring in docstrings]
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1168, in <listcomp>
    return [prepare_docstring(docstring, ignore, tab_width) for docstring in docstrings]
  File "/home/major/Documents/NeuroFedora/packages/snakemake/snakemake-5.12.3/.venv/lib/python3.8/site-packages/sphinx/util/docstrings.py", line 24, in prepare_docstring
    lines = s.expandtabs(tabsize).splitlines()
AttributeError: 'member_descriptor' object has no attribute 'expandtabs'
```

**Minimal example**
Just run `make html` inside `docs/`

**Additional context**
If there is anything else that I am missing while building the docs, it would be very helpful if you can guide me towards it.

Thanks a lot, for working on and providing `snakemake`. :smile:

**Comment by vladimirjendrol** [comment]
There is similar problem with Debian package [Bug 955056](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955056).

It seems that Sphinx has trouble getting doc info from:
`snakemake/common.py`
```python
class lazy_property(property):
    __slots__ = ["method", "cached", "__doc__"]
```
Method `prepare_docstring` in `sphinx/util/docstrings.py` expects string argument but will get argument of type `member_descriptor` in this case.

**Comment by rebecca-palmer** [comment]
Excluding lazy_property from the documentation does make Sphinx succeed (I haven't tested a whole build):
```
--- snakemake-5.10.0.orig/docs/conf.py
+++ snakemake-5.10.0/docs/conf.py
@@ -107,6 +107,8 @@ pygments_style = 'sphinx'
 # If true, keep warnings as "system message" paragraphs in the built documents.
 #keep_warnings = False

+# skip internal class that Sphinx 2 can't process (#296)
+autodoc_default_options = {'exclude-members': 'lazy_property'}

 # -- Options for HTML output ----------------------------------------------
 
```
This is obviously not an ideal fix, but it's an internal class with [little documentation](https://snakemake.readthedocs.io/en/stable/api_reference/internal/snakemake.html#snakemake.common.lazy_property) to begin with.

**Comment by Aniket-Pradhan** [comment]
The bug seems to be fixed now, probably due to a version update in either autodoc or sphinx. [Here](https://koji.fedoraproject.org/koji/taskinfo?taskID=71303173) are the build logs for the same.

Closing this ticket, as it seems to be resolved. :D
