### ISSUE TITLE
Regression of KeyError: <rule name>

### ISSUE THREAD

**Issue by lczech** [snakemake/snakemake#2980]
I believe this is a regression of #1024 and/or #1244, or at least related to those. Similar to there, it does not always occur, and I could not get a minimal example to reproduce this consistently. However, the traceback looks somewhat different, so I think this error was introduce somewhere else, and might not just be a simple regression.

**Snakemake version**
Snakemake 8.15.2, running with `--executor slurm`

**Describe the bug**
Main snakemake instance gets killed occasionally. Cannot reproduce consistently.

**Logs**
```
Traceback (most recent call last):

  File "[...]/grenepipe-v0.13.0/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(

  File "[...]/grenepipe-v0.13.0/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(

  File "[...]/grenepipe-v0.13.0/lib/python3.12/site-packages/snakemake/workflow.py", line 1248, in execute
    raise e

  File "[...]/grenepipe-v0.13.0/lib/python3.12/site-packages/snakemake/workflow.py", line 1244, in execute
    success = self.scheduler.schedule()
              ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "[...]/grenepipe-v0.13.0/lib/python3.12/site-packages/snakemake/scheduler.py", line 198, in schedule
    self._finish_jobs()

  File "[...]/grenepipe-v0.13.0/lib/python3.12/site-packages/snakemake/scheduler.py", line 388, in _finish_jobs
    async_run(postprocess())

  File "[...]/grenepipe-v0.13.0/lib/python3.12/site-packages/snakemake/common/__init__.py", line 94, in async_run
    return asyncio.run(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^

  File "[...]/grenepipe-v0.13.0/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^

  File "[...]/grenepipe-v0.13.0/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "[...]/grenepipe-v0.13.0/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^

  File "[...]/grenepipe-v0.13.0/lib/python3.12/site-packages/snakemake/scheduler.py", line 383, in postprocess
    await self.workflow.dag.finish(

  File "[...]/grenepipe-v0.13.0/lib/python3.12/site-packages/snakemake/dag.py", line 1879, in finish
    potential_new_ready_jobs = self.update_ready(depending)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "[...]/grenepipe-v0.13.0/lib/python3.12/site-packages/snakemake/dag.py", line 1578, in update_ready
    group = self._group[job]
            ~~~~~~~~~~~^^^^^

KeyError: bam_index
```

where `bam_index` is the name of a rule.

**Minimal example**
n/a, unfortunately

**Comment by lczech** [comment]
This is still an issue, and users of my pipeline are stuck due to this bug now, see [here](https://github.com/moiexpositoalonsolab/grenepipe/issues/66). 

Unfortunately, I cannot reproduce this myself, and hence not really help with resolving this, but would appreciate any hint! Any idea what is going on there and how to fix this? 

Also, stalebot, please un-stale this. It's still an issue!

Cheers and so long
Lucas
