### ISSUE TITLE
TypeError: resource() got an unexpected keyword argument 'keep_local'

### ISSUE THREAD

**Issue by TMiguelT** [snakemake/snakemake#30]
**Snakemake version**
5.7.0

**Describe the bug**
If I run snakemake via tibanna, I get the error:
```
TypeError: resource() got an unexpected keyword argument 'keep_local'
```

**Logs**
```
snakemake --tibanna --default-remote-prefix=tibanna/run_1                      
Traceback (most recent call last):
  File "/tmp/tmp.1BY3tqvG9v/venv/lib/python3.6/site-packages/snakemake/__init__.py", line 421, in snakemake
    keep_local=True, is_default=True
  File "/tmp/tmp.1BY3tqvG9v/venv/lib/python3.6/site-packages/snakemake/remote/S3.py", line 41, in __init__
    self._s3c = S3Helper(*args, **kwargs)  # _private variable by convention
  File "/tmp/tmp.1BY3tqvG9v/venv/lib/python3.6/site-packages/snakemake/remote/S3.py", line 167, in __init__
    self.s3 = boto3.resource("s3", **kwargs)
  File "/tmp/tmp.1BY3tqvG9v/venv/lib/python3.6/site-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
TypeError: resource() got an unexpected keyword argument 'keep_local'
```

**Minimal example**
Simply cloning https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling, copying the .test directory into the root, and then running `snakemake --tibanna --default-remote-prefix=some_bucket/key` will cause this issue

**Some python package versions**
```
appdirs==1.4.3
attrs==19.2.0
Benchmark-4dn==0.5.6
boto3==1.9.248
botocore==1.12.248
certifi==2019.9.11
chardet==3.0.4
ConfigArgParse==0.15.1
datrie==0.8
docutils==0.15.2
gitdb2==2.0.6
GitPython==3.0.3
idna==2.8
importlib-metadata==0.23
jmespath==0.9.4
jsonschema==3.1.1
more-itertools==7.2.0
pkg-resources==0.0.0
psutil==5.6.3
pyrsistent==0.15.4
python-dateutil==2.8.0
python-lambda-4dn==0.12.2
PyYAML==5.1.2
ratelimiter==1.2.0.post0
requests==2.22.0
s3transfer==0.2.1
six==1.12.0
smmap2==2.0.5
snakemake==5.7.0
tibanna==0.10.0
urllib3==1.25.6
wrapt==1.11.2
zipp==0.6.0
```

**Comment by johanneskoester** [comment]
Fixed by PR #31.

**Comment by TMiguelT** [comment]
Thanks! I'll give that a shot tomorrow and see if it's fixed.

**Comment by TMiguelT** [comment]
Yep, confirming this seems to have been fixed.
