### ISSUE TITLE
Annoying cryptography deprecation warning via paramiko, via smart_open

### ISSUE THREAD

**Issue by corneliusroemer** [snakemake/snakemake#3004]
When using snakemake with cryptography >=43.0.0 one gets 2 deprecation warnings:

```
$ snakemake
Using workflow specific profile profiles/default for setting default command line arguments.
/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
...
```

By adding an exception in the relevant paramiko file, I found out that the import happens through smart_open.

I wonder if it would be possible to add a (temporary) workaround for the deprecation warning until upstream (paramiko and/or smart_open have a fix).

```
Traceback (most recent call last):

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/snakemake/cli.py", line 2022, in args_to_api
    dag_api = workflow_api.dag(
              ^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/snakemake/api.py", line 328, in dag
    return DAGApi(
           ^^^^^^^

  File "<string>", line 6, in __init__

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/snakemake/api.py", line 438, in __post_init__
    self.workflow_api._workflow.dag_settings = self.dag_settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/snakemake/api.py", line 386, in _workflow
    workflow.include(

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/snakemake/workflow.py", line 1368, in include
    snakefile = infer_source_file(snakefile, basedir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/snakemake/sourcecache.py", line 320, in infer_source_file
    if is_local_file(path_or_uri):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/snakemake/common/__init__.py", line 122, in is_local_file
    return parse_uri(path_or_uri).scheme == "file"
           ^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/snakemake/common/__init__.py", line 126, in parse_uri
    from smart_open import parse_uri

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/smart_open/__init__.py", line 34, in <module>
    from .smart_open_lib import open, parse_uri, smart_open, register_compressor  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/smart_open/smart_open_lib.py", line 35, in <module>
    from smart_open import doctools

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/smart_open/doctools.py", line 21, in <module>
    from . import transport

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/smart_open/transport.py", line 105, in <module>
    register_transport("smart_open.ssh")

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/smart_open/transport.py", line 49, in register_transport
    submodule = importlib.import_module(submodule)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/smart_open/ssh.py", line 37, in <module>
    import paramiko

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import (

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/paramiko/transport.py", line 93, in <module>
    from paramiko.dsskey import DSSKey

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/paramiko/dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey

  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/paramiko/pkey.py", line 23, in <module>
    raise Exception("import of paramiko")

Exception: import of paramiko
```

**Comment by cmeesters** [comment]
Shall we really silence deprecation warnings, or rather wait for the decency to be fixed? I understand the intention, but fear that this code change will hit Snakemake eventually. It might just be forgotten, that this change has been introduced and then something else will be deprecated and after a while vanish entirely, only to be noticed when the code breaks.
