### ISSUE TITLE
Incompatible with singularity installed through conda

### ISSUE THREAD

**Issue by haizi-zh** [snakemake/snakemake#303]
Singularity installed through conda may have not-traditional version numbers. For example:

```
conda install -c conda-forge singularity=3.5.3
```

The version number of singularity installed this way will be: 

```
singularity version d5eaf8a+dirty
```

Under this circumstance, `snakemake --use-singularity --use-conda` won't go through, because the following line of code breaks: https://github.com/snakemake/snakemake/blob/53c1589162f296dc509db26235ca6fd232814135/snakemake/deployment/singularity.py#L47

Output:

```
Traceback (most recent call last):
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/snakemake/__init__.py", line 647, in snakemake
    keepincomplete=keep_incomplete,
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/snakemake/workflow.py", line 782, in execute
    dryrun=dryrun or list_conda_envs, quiet=list_conda_envs
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/snakemake/dag.py", line 268, in pull_container_imgs
    img = singularity.Image(img_url, self)
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/snakemake/deployment/singularity.py", line 47, in __init__
    if not LooseVersion(v) >= LooseVersion("2.4.1"):
  File "/home/galaxy/miniconda3/lib/python3.7/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/home/galaxy/miniconda3/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by mbhall88** [comment]
This sounds like an issue that should be raised on the [conda-forge singularity-feedstock](https://github.com/conda-forge/singularity-feedstock) rather than a snakemake issue. They are using a release tarball to install singularity so it should have a valid semvar version.

**Comment by scottgigante** [comment]
This is not an issue with singularity. The error is in the snakemake parsing.
```
singularity --version
Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
Running under Python 3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/scottgigante/.local/share/singularity/log/error.log (lazily created when something is logged)
1.00

```
Running the code to get the version from https://github.com/snakemake/snakemake/blob/53c1589162f296dc509db26235ca6fd232814135/snakemake/deployment/singularity.py#L37:
```
>>> import subprocess
>>> v = subprocess.check_output(
...                 ["singularity", "--version"], stderr=subprocess.PIPE
...             ).decode()
>>>
>>> v
'Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)\nRunning under Python 3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]\npygame 1.9.6\nHello from the pygame community. https://www.pygame.org/contribute.html\nThe error-log configured as /home/scottgigante/.local/share/singularity/log/error.log (lazily created when something is logged)\n1.00\n'
>>> v = v.rsplit(" ", 1)[-1]
>>> v
'logged)\n1.00\n'
>>> v = v[1:]
>>> v
'ogged)\n1.00\n'
```
