### ISSUE TITLE
`pdb` returns false 'NameError' exception for variables in list comprehension

### ISSUE THREAD

**Issue by irm-codebase** [snakemake/snakemake#3047]
**Snakemake version**

I've tried this in 8.10.2, 8.16, and 8.18.

**Describe the bug**

`snakemake` causes `pdb` to "forget" the python context inside list comprehension, causing it to return false error messages during debugging.

This seems to only happen in list comprehension.

For example, imagine I import the following faulty code:

```python
def test():
    years = list[range(1990, 2030)]
    other_years = np.arange(2000, 2050, 2, dtype=int)
    breakpoint()
    a = [y for y in years if y > other_years.max()]

test()
```

`pdb` will return very different messages for equivalent actions (I'm using `ipdb`, but this also occurs in regular `pdb`).
Here, I run a buggy line by copy pasting it, and `pdb` **forgets** that the `other_years` variable exists!

```
     19     breakpoint()
---> 20     a = [y for y in years if y > other_years.max()]
     21 

ipdb> [y for y in years if y > other_years.max()]
*** NameError: name 'other_years' is not defined
```

Yet, if I run the script via `snakemake` without breakpoints, use `continue` in `pdb` or just run it on regular `python` the message will be correct:

```
ipdb> continue
Traceback (most recent call last):
  File "/home/ivanruizmanuel/Documents/git/ec_modules/modules/industry/.snakemake/scripts/tmpwrlvcrky.iron_and_steel.py", line 22, in <module>
    test()
  File "/home/ivanruizmanuel/Documents/git/ec_modules/modules/industry/.snakemake/scripts/tmpwrlvcrky.iron_and_steel.py", line 20, in test
    a = [y for y in years if y > other_years.max()]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanruizmanuel/Documents/git/ec_modules/modules/industry/.snakemake/scripts/tmpwrlvcrky.iron_and_steel.py", line 20, in <listcomp>
    a = [y for y in years if y > other_years.max()]
                             ^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'types.GenericAlias'
```

I've tested this in `pdb` without `snakemake`, and this issue does not occur. Maybe `snakemake` is affecting something in the `pdb` stack?

**Minimal example**

Just try to use `pdb` for any list comprehension using variables defined beforehand. It'll pop up.

**Additional context**

I've tried this on two different machines (one with ubuntu, one with fedora), and the same issue occurs.

**Comment by irm-codebase** [comment]
Had to update the issue, turns out this is way more general than I initially though.

I hope this is fixed soon, this makes debugging horrible
