### ISSUE TITLE
snakemake --dag fails if there are ambiguities because workflow.execution_settings is None

### ISSUE THREAD

**Issue by tesujimath** [snakemake/snakemake#3118]
**Snakemake version**
8.10.6

**Describe the bug**
I am trying to troubleshoot why SnakeMake thinks [my rules ](https://github.com/AgResearch/snakemake-playpen/blob/main/workflow/playpen.smk)are ambiguous, so I am trying `snakemake --dag`, but this fails here:

```
 File "/nix/store/m6fr507c2z16hp1k9kj2p33s84ahn75r-snakemake-8.10.6/lib/python3.11/site-packages/snakemake/dag.py", line 983, in update
    if ambiguities and not self.workflow.execution_settings.ignore_ambiguity:
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'ignore_ambiguity'
```

because `execution_settings` is `None`.

**Logs**
```
it23677> snakemake --dag -s workflow/playpen.smk
Building DAG of jobs...
Traceback (most recent call last):

  File "/nix/store/m6fr507c2z16hp1k9kj2p33s84ahn75r-snakemake-8.10.6/lib/python3.11/site-packages/snakemake/cli.py", line 2028, in args_to_api
    dag_api.printdag()

  File "/nix/store/m6fr507c2z16hp1k9kj2p33s84ahn75r-snakemake-8.10.6/lib/python3.11/site-packages/snakemake/api.py", line 598, in _handle_no_exec
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/m6fr507c2z16hp1k9kj2p33s84ahn75r-snakemake-8.10.6/lib/python3.11/site-packages/snakemake/api.py", line 646, in printdag
    self.workflow_api._workflow.printdag()

  File "/nix/store/m6fr507c2z16hp1k9kj2p33s84ahn75r-snakemake-8.10.6/lib/python3.11/site-packages/snakemake/workflow.py", line 907, in printdag
    self._build_dag()

  File "/nix/store/m6fr507c2z16hp1k9kj2p33s84ahn75r-snakemake-8.10.6/lib/python3.11/site-packages/snakemake/workflow.py", line 1037, in _build_dag
    async_run(self.dag.init())

  File "/nix/store/m6fr507c2z16hp1k9kj2p33s84ahn75r-snakemake-8.10.6/lib/python3.11/site-packages/snakemake/common/__init__.py", line 94, in async_run
    return asyncio.run(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^

  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^

  File "/nix/store/m6fr507c2z16hp1k9kj2p33s84ahn75r-snakemake-8.10.6/lib/python3.11/site-packages/snakemake/dag.py", line 178, in init
    job = await self.update([job], progress=progress, create_inventory=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/m6fr507c2z16hp1k9kj2p33s84ahn75r-snakemake-8.10.6/lib/python3.11/site-packages/snakemake/dag.py", line 930, in update
    await self.update_(

  File "/nix/store/m6fr507c2z16hp1k9kj2p33s84ahn75r-snakemake-8.10.6/lib/python3.11/site-packages/snakemake/dag.py", line 1047, in update_
    selected_job = await self.update(
                   ^^^^^^^^^^^^^^^^^^

  File "/nix/store/m6fr507c2z16hp1k9kj2p33s84ahn75r-snakemake-8.10.6/lib/python3.11/site-packages/snakemake/dag.py", line 983, in update
    if ambiguities and not self.workflow.execution_settings.ignore_ambiguity:
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'ignore_ambiguity'

```

**Minimal example**
I made a [tiny repo](https://github.com/AgResearch/snakemake-playpen) with it all in.  Then:

```
$ echo "Wahoo!" > wahoo.a
$ gzip wahoo.a
$ snakemake -s workflow/playpen.smk --cores 1
```

**Additional context**
I suspect there's a simple solution to my ambiguous rule problem.  But I think SnakeMake should be able to produce a DAG even if there are ambiguous rules?  Because, very useful tool for troubleshooting!

**Comment by tesujimath** [comment]
I did fix this particular ambiguity problem ([PR in my repo](https://github.com/AgResearch/snakemake-playpen/pull/1)), but the underlying bug in SnakeMake remains. 😄
