### ISSUE TITLE
Running Snakemake --touch gives PulpSolverError

### ISSUE THREAD

**Issue by tbenavi1** [snakemake/snakemake#3128]
**Snakemake version**
I have snakemake 8.20.6.

**Describe the bug**
When I run "snakemake BLPt0001/assembly/verkko/assembly.haplotype1.fasta --touch --cores 1" I get a PulpSolverError.

**Logs**
```
Traceback (most recent call last):

  File "/tgen_labs/barthel/software/miniforge3/envs/snakemake/lib/python3.11/site-packages/snakemake/cli.py", line 2095, in args_to_api
    dag_api.execute_workflow(

  File "/tgen_labs/barthel/software/miniforge3/envs/snakemake/lib/python3.11/site-packages/snakemake/api.py", line 595, in execute_workflow
    workflow.execute(

  File "/tgen_labs/barthel/software/miniforge3/envs/snakemake/lib/python3.11/site-packages/snakemake/workflow.py", line 1302, in execute
    raise e

  File "/tgen_labs/barthel/software/miniforge3/envs/snakemake/lib/python3.11/site-packages/snakemake/workflow.py", line 1298, in execute
    success = self.scheduler.schedule()
              ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/tgen_labs/barthel/software/miniforge3/envs/snakemake/lib/python3.11/site-packages/snakemake/scheduler.py", line 270, in schedule
    run = self.job_selector(needrun)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/tgen_labs/barthel/software/miniforge3/envs/snakemake/lib/python3.11/site-packages/snakemake/scheduler.py", line 483, in job_selector
    return self._job_selector(jobs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/tgen_labs/barthel/software/miniforge3/envs/snakemake/lib/python3.11/site-packages/snakemake/scheduler.py", line 616, in job_selector_ilp
    status = self._solve_ilp(prob, time_limit=10)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/tgen_labs/barthel/software/miniforge3/envs/snakemake/lib/python3.11/site-packages/snakemake/scheduler.py", line 665, in _solve_ilp
    return prob.solve(solver)
           ^^^^^^^^^^^^^^^^^^

  File "/tgen_labs/barthel/software/miniforge3/envs/snakemake/lib/python3.11/site-packages/pulp/pulp.py", line 1913, in solve
    status = solver.actualSolve(self, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/tgen_labs/barthel/software/miniforge3/envs/snakemake/lib/python3.11/site-packages/pulp/apis/coin_api.py", line 137, in actualSolve
    return self.solve_CBC(lp, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/tgen_labs/barthel/software/miniforge3/envs/snakemake/lib/python3.11/site-packages/pulp/apis/coin_api.py", line 198, in solve_CBC
    raise PulpSolverError(

pulp.apis.core.PulpSolverError: Pulp: Error while trying to execute, use msg=True for more detailscbc
```

Any help? Thanks.

**Comment by tbenavi1** [comment]
And actually, this bug still happens when actually trying to run the pipeline (without --touch).

**Comment by robert-marik** [comment]
I had the same problem. Created the new mamba python environment from scratch and the problem disappeared.

**Comment by CHENSIOFFICIAL** [comment]
Have you solved this issue? How did you solve it? I have encountered the same problem. I tried to install using the command mamba create -c conda-forge -c bioconda --name snakemake snakemake snakedeploy.

**Comment by tbenavi1** [comment]
I downgraded snakemake to a previous version. In my case, I used 8.14.0.

**Comment by nh13** [comment]
Used python 3.11 and snakemake 8.27.1.  Downgraded to 8.14.0 and it worked
