### ISSUE TITLE
Question: Can you make an execute a snakemake workflow in pure python

### ISSUE THREAD

**Issue by harrymatthews50** [snakemake/snakemake#3136]
I am trying to define and execute a snakemake workflow in pure python using the snakemake  python package. I imagine something like this

```
from snakemake.rules import Rule
from snakemake.workflow import Workflow

# implement logic for defining rules

# add rules to workflow

# run workflow

```
This evidently used to be possible as shown in the second answer to [this question] (https://stackoverflow.com/questions/75721651/is-there-a-way-to-create-a-snakemake-rule-dynamically). However it does not work any more in snakemake 8.18.2. For example they create a Rule object by giving input and output files to snakemake Rule class's init function. Now the init function does not take such arguments.

I am playing with the toy example below where I try to create in python the workflow defined in this snakefile.

```
# write into 
rule all:
    input:
        'my_file.txt'

rule writer:
    output:
        out_pipe=pipe('my_pipe.txt')
    shell:
        """
        for i in {{1..10000}}; 
        do echo "All work and no play makes Jack a dull boy."; 
        done > {output.out_pipe}
        """
# read from pipe
rule reader:
    input:
        in_pipe='my_pipe.txt'
    output:
        out_file='my_file.txt'
    shell:
        """
        cat {input.in_pipe} > {output.out_file}
        """
```

But I have problems immediately at defining the 'all' rule

```
import snakemake.io
import snakemake.rules 

all_output_files = snakemake.io.OutputFiles('my_file.txt')
all = snakemake.rules.Rule('my_rule','workflow')
all.set_output(all_output_files)
```

Gives the error

```
Traceback (most recent call last):
  File "/mnt/local_data/snakemake_demo/make_workflow.py", line 11, in <module>
    all.set_output(all_output_files)
  File "/mnt/local_data/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/rules.py", line 325, in set_output
    self._set_inoutput_item(item, output=True)
  File "/mnt/local_data/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/rules.py", line 519, in _set_inoutput_item
    self._set_inoutput_item(i, output=output)
  File "/mnt/local_data/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/rules.py", line 431, in _set_inoutput_item
    item = self.apply_path_modifier(item, path_modifier, property=property)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/local_data/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/rules.py", line 357, in apply_path_modifier
    assert path_modifier is not None```
```

I am wondering if this is still possible in the modern snakemake and if there is any guidance you can offer.
Any help is greatly appreciated.
Harry

**Comment by papanikos** [comment]
I would also be interested in any guidance here. The [API docs](https://snakemake-api.readthedocs.io/en/stable/api_reference/snakemake_api.html) look promising, but there is not enough to jump from there. 

The `--print-compilation` CLI command gives a python file, but it still is dependent on the presence of a  `Snakefile`. There is [this gist]( https://gist.github.com/marcelm/7e432275dfa5e762b4f8) that showcases it with a previous version of snakemake.
