### ISSUE TITLE
Running Snakemake with slurm executor returns AttributeError

### ISSUE THREAD

**Issue by ericxytong** [snakemake/snakemake#3179]
Running

`snakemake --executor slurm --default-resources slurm_account=<your SLURM account> slurm_partition=<your SLURM partition> --jobs 10 --runtime 2880`

Returns the error

```
AttributeError: 'StorageProviderProxy' object has no attribute '__name__'. Did you mean: '__ne__'?


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/elt8256/miniforge3/envs/snakemake-dummy/lib/python3.12/site-packages/snakemake/cli.py", line 2014, in args_to_api
    dag_api = workflow_api.dag(
              ^^^^^^^^^^^^^^^^^

  File "/home/elt8256/miniforge3/envs/snakemake-dummy/lib/python3.12/site-packages/snakemake/api.py", line 334, in dag
    return DAGApi(
           ^^^^^^^

  File "<string>", line 6, in __init__

  File "/home/elt8256/miniforge3/envs/snakemake-dummy/lib/python3.12/site-packages/snakemake/api.py", line 439, in __post_init__
    self.workflow_api._workflow.dag_settings = self.dag_settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/elt8256/miniforge3/envs/snakemake-dummy/lib/python3.12/site-packages/snakemake/api.py", line 384, in _workflow
    workflow = self._get_workflow()
               ^^^^^^^^^^^^^^^^^^^^

  File "/home/elt8256/miniforge3/envs/snakemake-dummy/lib/python3.12/site-packages/snakemake/api.py", line 399, in _get_workflow
    return Workflow(
           ^^^^^^^^^

  File "<string>", line 20, in __init__

  File "/home/elt8256/miniforge3/envs/snakemake-dummy/lib/python3.12/site-packages/snakemake/workflow.py", line 200, in __post_init__
    self._storage_registry = StorageRegistry(self)
                             ^^^^^^^^^^^^^^^^^^^^^

  File "/home/elt8256/miniforge3/envs/snakemake-dummy/lib/python3.12/site-packages/snakemake/storage.py", line 37, in __init__
    def __init__(self, workflow: Workflow):
    

SystemError: <sys.legacy_event_handler object at 0x2b85c302b7f0> returned a result with an exception set
```

The error is only returned once the --runtime argument is added. The same command is able to be run from a different computer onto the same cluster. Could this be a version issue? And if so, how do I upgrade/downgrade snakemake versions within the same conda environment?

**Comment by ericxytong** [comment]
It was the snakemake version
