### ISSUE TITLE
test_cluster_sync fails if run in parallel

### ISSUE THREAD

**Issue by rebecca-palmer** [snakemake/snakemake#322]
test_cluster_sync is identical to test14 except for (since 25601e510572c8c35dfb72b930e3d48f32edd9fd) not setting TESTVAR.

When run in series this passes (probably because TESTVAR is still there from test14), but when run in parallel (pytest-xdist `-n auto`) it fails.

Given the duplication, I suggest removing test_cluster_sync, and probably renaming test14 to test_cluster_sync to have a meaningful name.

Version tested: [Debian package of 5.14.0](https://salsa.debian.org/med-team/snakemake/-/tree/debian_for_upstream_5.14.0_which_requires_conda)

```
______________________________ test_cluster_sync _______________________________
[gw0] linux -- Python 3.8.2 /usr/bin/python3

    def test_cluster_sync():
>       run(dpath("test14"), snakefile="Snakefile.nonstandard", cluster_sync="./qsub")

../build.JQ0/src/tests/tests.py:247: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

path = '/tmp/autopkgtest.0XAsFs/build.JQ0/src/tests/test14', shouldfail = False
snakefile = '/tmp/autopkgtest.0XAsFs/build.JQ0/src/tests/test14/Snakefile.nonstandard'
subpath = None, no_tmpdir = False, check_md5 = True, cores = 3
set_pythonpath = True, cleanup = True, params = {'cluster_sync': './qsub'}
results_dir = '/tmp/autopkgtest.0XAsFs/build.JQ0/src/tests/test14/expected-results'
tmpdir = '/tmp/snakemake-9mlkayop', config = {}, f = 'qsub.py', success = False

    def run(
        path,
        shouldfail=False,
        snakefile="Snakefile",
        subpath=None,
        no_tmpdir=False,
        check_md5=True,
        cores=3,
        set_pythonpath=True,
        cleanup=True,
        **params
    ):
        """
        Test the Snakefile in path.
        There must be a Snakefile in the path and a subdirectory named
        expected-results. If cleanup is False, we return the temporary
        directory to the calling test for inspection, and the test should
        clean it up.
        """
        if set_pythonpath:
            # Enforce current workdir (the snakemake source dir) to also be in PYTHONPATH
            # when subprocesses are invoked in the tempdir defined below.
            os.environ["PYTHONPATH"] = os.getcwd()
        elif "PYTHONPATH" in os.environ:
            del os.environ["PYTHONPATH"]
    
        results_dir = join(path, "expected-results")
        snakefile = join(path, snakefile)
        assert os.path.exists(snakefile)
        assert os.path.exists(results_dir) and os.path.isdir(
            results_dir
        ), "{} does not exist".format(results_dir)
    
        # If we need to further check results, we won't cleanup tmpdir
        tmpdir = next(tempfile._get_candidate_names())
        tmpdir = os.path.join(tempfile.gettempdir(), "snakemake-%s" % tmpdir)
        os.mkdir(tmpdir)
    
        config = {}
    
        # handle subworkflow
        if subpath is not None:
            # set up a working directory for the subworkflow and pass it in `config`
            # for now, only one subworkflow is supported
            assert os.path.exists(subpath) and os.path.isdir(
                subpath
            ), "{} does not exist".format(subpath)
            subworkdir = os.path.join(tmpdir, "subworkdir")
            os.mkdir(subworkdir)
    
            # copy files
            for f in os.listdir(subpath):
                copy(os.path.join(subpath, f), subworkdir)
            config["subworkdir"] = subworkdir
    
        # copy files
        for f in os.listdir(path):
            print(f)
            copy(os.path.join(path, f), tmpdir)
    
        # run snakemake
        success = snakemake(
            snakefile,
            cores=cores,
            workdir=path if no_tmpdir else tmpdir,
            stats="stats.txt",
            config=config,
            verbose=True,
            **params
        )
        if shouldfail:
            assert not success, "expected error on execution"
        else:
>           assert success, "expected successful execution"
E           AssertionError: expected successful execution

../build.JQ0/src/tests/common.py:148: AssertionError
----------------------------- Captured stdout call -----------------------------
qsub
test.in
expected-results
Snakefile.nonstandard
qsub.py
----------------------------- Captured stderr call -----------------------------
Full Traceback (most recent call last):
  File "/tmp/autopkgtest.0XAsFs/build.JQ0/src/snakemake/__init__.py", line 495, in snakemake
    workflow.include(
  File "/tmp/autopkgtest.0XAsFs/build.JQ0/src/snakemake/workflow.py", line 987, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/tmp/autopkgtest.0XAsFs/build.JQ0/src/tests/test14/Snakefile.nonstandard", line 5, in <module>
    envvars:
  File "/tmp/autopkgtest.0XAsFs/build.JQ0/src/snakemake/workflow.py", line 934, in register_envvars
    raise WorkflowError(
snakemake.exceptions.WorkflowError: The following environment variables are requested by the workflow but undefined. Please make sure that they are correctly defined before running Snakemake:
TESTVAR

WorkflowError in line 5 of /tmp/autopkgtest.0XAsFs/build.JQ0/src/tests/test14/Snakefile.nonstandard:
The following environment variables are requested by the workflow but undefined. Please make sure that they are correctly defined before running Snakemake:
TESTVAR
  File "/tmp/autopkgtest.0XAsFs/build.JQ0/src/tests/test14/Snakefile.nonstandard", line 5, in <module>
------------------------------ Captured log call -------------------------------
DEBUG    snakemake.logging:logging.py:378 Full Traceback (most recent call last):
                                            File "/tmp/autopkgtest.0XAsFs/build.JQ0/src/snakemake/__init__.py", line 495, in snakemake
                                              workflow.include(
                                            File "/tmp/autopkgtest.0XAsFs/build.JQ0/src/snakemake/workflow.py", line 987, in include
                                              exec(compile(code, snakefile, "exec"), self.globals)
                                            File "/tmp/autopkgtest.0XAsFs/build.JQ0/src/tests/test14/Snakefile.nonstandard", line 5, in <module>
                                              envvars:
                                            File "/tmp/autopkgtest.0XAsFs/build.JQ0/src/snakemake/workflow.py", line 934, in register_envvars
                                              raise WorkflowError(
                                          snakemake.exceptions.WorkflowError: The following environment variables are requested by the workflow but undefined. Please make sure that they are correctly defined before running Snakemake:
                                          TESTVAR
ERROR    snakemake.logging:logging.py:376 WorkflowError in line 5 of /tmp/autopkgtest.0XAsFs/build.JQ0/src/tests/test14/Snakefile.nonstandard:
                                          The following environment variables are requested by the workflow but undefined. Please make sure that they are correctly defined before running Snakemake:
                                          TESTVAR
                                            File "/tmp/autopkgtest.0XAsFs/build.JQ0/src/tests/test14/Snakefile.nonstandard", line 5, in <module>
```

**Comment by rebecca-palmer** [comment]
On closer inspection, they're not identical so test_cluster_sync should stay, but both of them should set TESTVAR.

**Comment by johanneskoester** [comment]
Thanks for spotting this!
