### ISSUE TITLE
Cryptic error if the output is an empty string

### ISSUE THREAD

**Issue by ashwinvis** [snakemake/snakemake#341]
**Snakemake version**
5.14.0

**Describe the bug**
Snakemake does not exit gracefully if the output filename is an empty string

**Logs**
```python
$ snakemake -j1 archive

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       archive
        1

[Tue Apr 21 04:13:50 2020]
rule archive:
    output: 
    jobid: 0

Traceback (most recent call last):
  File "/home/avmo/.conda/envs/eturb/lib/python3.7/site-packages/snakemake/__init__.py", line 633, in snakemake
    keepincomplete=keep_incomplete,
  File "/home/avmo/.conda/envs/eturb/lib/python3.7/site-packages/snakemake/workflow.py", line 850, in execute
    success = scheduler.schedule()
  File "/home/avmo/.conda/envs/eturb/lib/python3.7/site-packages/snakemake/scheduler.py", line 374, in schedule
    self.run(job)
  File "/home/avmo/.conda/envs/eturb/lib/python3.7/site-packages/snakemake/scheduler.py", line 393, in run
    error_callback=self._error,
  File "/home/avmo/.conda/envs/eturb/lib/python3.7/site-packages/snakemake/executors.py", line 356, in run
    super()._run(job)
  File "/home/avmo/.conda/envs/eturb/lib/python3.7/site-packages/snakemake/executors.py", line 178, in _run
    self.register_job(job)
  File "/home/avmo/.conda/envs/eturb/lib/python3.7/site-packages/snakemake/executors.py", line 171, in register_job
    job.register()
  File "/home/avmo/.conda/envs/eturb/lib/python3.7/site-packages/snakemake/jobs.py", line 938, in register
    self.dag.workflow.persistence.started(self)
  File "/home/avmo/.conda/envs/eturb/lib/python3.7/site-packages/snakemake/persistence.py", line 161, in started
    f,
  File "/home/avmo/.conda/envs/eturb/lib/python3.7/site-packages/snakemake/persistence.py", line 304, in _record
    recpath = self._record_path(subject, id)
  File "/home/avmo/.conda/envs/eturb/lib/python3.7/site-packages/snakemake/persistence.py", line 362, in _record_path
    b64id = ["@" + s for s in b64id[:-1]] + [b64id[-1]]
IndexError: list index out of range
```

**Minimal example**
```python
import os

def file_name_generator(base):
    if os.path.exists(base):
        return "my_file.tar"
    else:
        return ""

rule clean:
    params:
        tarball = file_name_generator("source.txt")
    shell:
        """
        if [ "{params.tarball}" ] && [  ! -f "{params.tarball}" ]; then
            echo "ERROR: Archive {params.tarball} not found. Refusing to clean simulation files! Run 'snakemake archive'"
            exit 1
        fi
        rm -f source.txt
        """
rule archive:
    params: msg = "Hello"
    output: file_name_generator("source.txt")
    shell: "tar -cf {output} source.txt"

```

**Additional context**
 Both rules execute if `source.txt` is present. I used the empty string as a placeholder, when `source.txt` is missing which triggered this error message.

**Comment by engenegr** [comment]
Got the same error when the generator function in the input. 

Can't understand what's happened since `list index out of range` appears not in the start or in the end of the list but several elements before the end. I'm iterating over in the for loop.

```
    input:
        *path_adapter(config['all_targets'])
    output:
        "postReport.log",
        report(directory("results"),
               caption="report/field_annotation.rst",
               patterns=["{name}.png"],
               category="Fuzzy Logic Results")
    run:
        import os
        from python.baseline import BaselineCaseData, BaselineFuzzyEstimator

        workflow_results = {}
        print(input)
        for archive_path in input:
            print(archive_path)
```

**Comment by Hocnonsense** [comment]
Instead, you should use a empty list as the correct return value. in `shell` block, 'if [ "{params.tarball}" ]' will be formated as 'if [ "" ]'

**Comment by ashwinvis** [comment]
@Hocnonsense Sure, that bash command could use some work.

You can ignore the `rule clean` and go for an even more minimal example, which results in the same error.


```py
import os

def file_name_generator(base):
    if os.path.exists(base):
        return "my_file.tar"
    else:
        return ""

rule archive:
    params: msg = "Hello"
    output: file_name_generator("source.txt")
    shell: "tar -cf {output} source.txt"
```

```pytb
❯ uvx snakemake -j1 archive
Assuming unrestricted shared filesystem usage.
host: rivendell
Building DAG of jobs...
  + Exception Group Traceback (most recent call last):

  |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/cli.py", line 2187, in args_to_api
  |     dag_api.execute_workflow(

  |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/api.py", line 634, in execute_workflow
  |     workflow.execute(

  |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/workflow.py", line 1265, in execute
  |     self._build_dag()

  |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/workflow.py", line 1208, in _build_dag
  |     async_run(self.dag.init())

  |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/common/__init__.py", line 100, in async_run
  |     return asyncio.run(coroutine)
  |            ^^^^^^^^^^^^^^^^^^^^^^

  |   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^

  |   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  |   File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^

  |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/dag.py", line 268, in init
  |     await self.check_incomplete()

  |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/dag.py", line 572, in check_incomplete
  |     incomplete_files = await self.incomplete_files()
  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/dag.py", line 675, in incomplete_files
  |     for job in await self.workflow.persistence.incomplete(job)
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/persistence.py", line 401, in incomplete
  |     async with asyncio.TaskGroup() as tg:

  |   File "/usr/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None

  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)

  +-+---------------- 1 ----------------

    | Traceback (most recent call last):

    |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/persistence.py", line 398, in is_incomplete
    |     marked = marked_incomplete(f)
    |              ^^^^^^^^^^^^^^^^^^^^

    |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/persistence.py", line 393, in marked_incomplete
    |     rec_path = self._record_path(self._incomplete_path, f)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/home/ashwinmo/.cache/uv/archive-v0/YueSJTZUQ1b7AZY3CisrS/lib/python3.12/site-packages/snakemake/persistence.py", line 757, in _record_path
    |     b64id = ["@" + s for s in b64id[:-1]] + [b64id[-1]]
    |                                              ~~~~~^^^^

    | IndexError: list index out of range

    +------------------------------------
```

**Comment by Hocnonsense** [comment]
Oh, It's invalid to use a blank string as output. Probably you should return a blank list?
```python
import os

def file_name_generator(base):
    if os.path.exists(base):
        return ["my_file.tar"]
    else:
        return []

rule archive:
    params: msg = "Hello"
    output: file_name_generator("source.txt")
    run: shell("tar -cf {output} source.txt") if len(output) else ()
```

<img width="1256" height="1480" alt="Image" src="https://github.com/user-attachments/assets/96436df6-8a03-48d9-965b-a3636f54a37e" />

**Comment by ashwinvis** [comment]
Of course, it is invalid to use an empty string as output! I hope you actually read this issue.

>  Snakemake does not exit gracefully if the output filename is an empty string

The error message does not give any hint that there was an empty string.

**Comment by Hocnonsense** [comment]
I'm sorry I didn't understand your meaning earlier, but now I see. There should be a clear error message here, and I'll try to add one.
