### ISSUE TITLE
resources not working with wrapper scripts. 

### ISSUE THREAD

**Issue by geertvandeweyer** [snakemake/snakemake#354]
**Snakemake version** 
5.15.0

**Describe the bug**
Specifying resources for qsub in the rule config works for "shell:" syntax. 
When using a wrapper script, it gives "unexpected keyword" error. 

**Logs**

```
Full Traceback (most recent call last):
  File "/opt/software/python3.5.2/lib/python3.5/site-packages/snakemake/parser.py", line 710, in block_content
    token.string, rulename=self.rulename
  File "/opt/software/python3.5.2/lib/python3.5/site-packages/snakemake/parser.py", line 119, in subautomaton
    return self.subautomata[automaton](
KeyError: 'mem_gb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/software/python3.5.2/lib/python3.5/site-packages/snakemake/__init__.py", line 497, in snakemake
    snakefile, overwrite_first_rule=True, print_compilation=print_compilation
  File "/opt/software/python3.5.2/lib/python3.5/site-packages/snakemake/workflow.py", line 975, in include
    rulecount=self._rulecount,
  File "/opt/software/python3.5.2/lib/python3.5/site-packages/snakemake/parser.py", line 846, in parse
    for t, orig_token in automaton.consume():
  File "/opt/software/python3.5.2/lib/python3.5/site-packages/snakemake/parser.py", line 105, in consume
    for t, orig in self.state(token):
  File "/opt/software/python3.5.2/lib/python3.5/site-packages/snakemake/parser.py", line 789, in python
    for t in self.subautomaton(token.string).consume():
  File "/opt/software/python3.5.2/lib/python3.5/site-packages/snakemake/parser.py", line 105, in consume
    for t, orig in self.state(token):
  File "/opt/software/python3.5.2/lib/python3.5/site-packages/snakemake/parser.py", line 177, in block
    for t in self.block_content(token):
  File "/opt/software/python3.5.2/lib/python3.5/site-packages/snakemake/parser.py", line 716, in block_content
    token,
  File "/opt/software/python3.5.2/lib/python3.5/site-packages/snakemake/parser.py", line 116, in error
    raise SyntaxError(msg, (self.snakefile.path, lineno(token), None, None))
  File "/home/gboons/cfDNA_CNA/Scripts/FastqToCNA_cfDNA_TFx.snakefile", line 48
SyntaxError: Unexpected keyword mem_gb in rule definition`
```

**Minimal example**

_Failing config_

```
rule bwa_mem: # map reads
    input:
        reads=config["dataDir"]+"/raw/{samples}_{lane}_R1_001.fastq.gz"
    output:
        config["dataDir"]+"/bam/{samples}_{lane}_R1_001.bam"
    log:
        config["logDir"]+"/bwa_mem/{samples}_{lane}.log"
    params:
        index="/opt/NGS/References/nipt/human_g1k_v37.fasta",
        extra=r"-R '@RG\tID:{samples}\tSM:{samples}' -M", # add -M because Picard wouldn't work with split reads cfr manual
        sort="none",             # Can be 'none', 'samtools' or 'picard'.
        sort_order="queryname",  # Can be 'queryname' or 'coordinate'.
        sort_extra=""            # Extra args for samtools/picard.
    threads: 8
    resources:
	mem_gb=8,
	ppn=8
    wrapper:
    	"file:///home/gboons/cfDNA_CNA/Scripts/bwa_mem_wrapper.py" #"0.50.4/bio/bwa/mem"
```

_working rule in same pipeline_

```
rule picard_sort_AfterMerge:
	input:
		config["dataDir"]+"/bam/{samples}.merged.bam"
	output:
		config["dataDir"]+"/bam/{samples}.merged.sorted.bam"
	resources:
		mem_gb=6,
		ppn=2
	params:
		sort_order="coordinate",
		extra="VALIDATION_STRINGENCY=SILENT" # cfr NIPT, default=lenient ; optional: Extra arguments for picard.
	shell:
		"/opt/software/sun-jre-8/bin/java -jar /opt/NGS/binaries/picard/2.21.7/picard.jar SortSam"
		" INPUT={input}"
		" OUTPUT={output}"
		" {params.extra}"
		" SORT_ORDER={params.sort_order}"
```
_execution command_
`snakemake --snakefile FastqToCNA_cfDNA_TFx.snakefile --cluster "qsub -l mem={resources.mem_gb}G,nodes=1:ppn={resources.ppn}" -j 32 -n`

**Comment by johanneskoester** [comment]
Hi,
this is an indentation issue. Python (to which Snakemake workflows are compiled) can be very picky about indentation. In your resources directive above, you use a tab for indenting the mem_gb resource. This makes Python accidentally think it is at the wrong indentation level, complaining to not know it as a general rule keyword.

Make sure to consistently only use spaces for indentation, as it is also recommended for Python itself. I have added a lint to snakemake --lint  that will capture this from the next release on (commit 73194ed5).
