### ISSUE TITLE
UnboundLocalError: local variable 'incomplete' referenced before assignment

### ISSUE THREAD

**Issue by holtgrewe** [snakemake/snakemake#357]
**Snakemake version**
5.15

**Describe the bug**
I'm able to trigger a bug with an undefined variable.

**Logs**
```
Traceback (most recent call last):
  File "/fast/projects/medgen_research/work/2019-07-08_Exome_Workspace/miniconda3/lib/python3.7/site-packages/snakemake/__init__.py", line 654, in snakemake
    keepincomplete=keep_incomplete,
  File "/fast/projects/medgen_research/work/2019-07-08_Exome_Workspace/miniconda3/lib/python3.7/site-packages/snakemake/workflow.py", line 610, in execute
    dag.init()
  File "/fast/projects/medgen_research/work/2019-07-08_Exome_Workspace/miniconda3/lib/python3.7/site-packages/snakemake/dag.py", line 172, in init
    job = self.update(self.file2jobs(file), file=file, progress=progress)
  File "/fast/projects/medgen_research/work/2019-07-08_Exome_Workspace/miniconda3/lib/python3.7/site-packages/snakemake/dag.py", line 1458, in file2jobs
    jobs.append(self.new_job(rule, targetfile=targetfile))
  File "/fast/projects/medgen_research/work/2019-07-08_Exome_Workspace/miniconda3/lib/python3.7/site-packages/snakemake/dag.py", line 1216, in new_job
    targetfile=targetfile,
  File "/fast/projects/medgen_research/work/2019-07-08_Exome_Workspace/miniconda3/lib/python3.7/site-packages/snakemake/jobs.py", line 131, in __init__
    self.wildcards_dict
  File "/fast/projects/medgen_research/work/2019-07-08_Exome_Workspace/miniconda3/lib/python3.7/site-packages/snakemake/rules.py", line 801, in expand_input
    incomplete_checkpoint_func=handle_incomplete_checkpoint,
  File "/fast/projects/medgen_research/work/2019-07-08_Exome_Workspace/miniconda3/lib/python3.7/site-packages/snakemake/rules.py", line 724, in _apply_wildcards
    if is_unpack and not incomplete:
UnboundLocalError: local variable 'incomplete' referenced before assignment
```

**Comment by holtgrewe** [comment]
This is triggered when calling `unpack()` on a function returning a list.

**Comment by blaiseli** [comment]
You should probably show some code. Where do you define `incomplete`? Where is it used?

**Comment by holtgrewe** [comment]
cf. https://github.com/snakemake/snakemake/blob/master/snakemake/rules.py#L724 as shown in the error trace.

In the case where `_is_callable` is `False`, you will get this error.

**Comment by fgvieira** [comment]
Where are you calling `unpack`?

I got the same error if I used:
```
input:
    unpack(input_function())
```

but it worked fine if I changed to:
```
input:
    unpack(input_function)
```

Of course the second example assumes that the function takes up, at least, a wildcards argument.
