### ISSUE TITLE
unsupported pickle protocol 3 when running with environment module for Python 2

### ISSUE THREAD

**Issue by otting** [snakemake/snakemake#361]
**Snakemake version**
5.15.0

**Describe the bug**
Trying to run a script via "script:" tag whilst a python 2 environment module is loaded results in the unsupported pickle protocol 3 error.

I can not load Python 2 and 3 modules simultaneously.

**Logs**
Traceback (most recent call last): File "/gpfs/fs1/home/chotting/workflows/evoreg_assembly/workflows/.snakemake/scripts/tmpdeyk8bxz.rCorrector.py", line 3, in }q7sbX\\x06\\x00\\x00\\x00configq8}q9(X\\x0b\\x00\\x00\\x00RAW_RNA_DIRq:XV\\x00\\x00\\x00/project/jgu-multiomics/Michal/EvoReg/RNAseq_rawdata/imb_butter_2014_04a_EvoReg_RNASeqq;X\\n\\x00\\x00\\x00OUTPUT_DIRq<X/\\x00\\x00\\x00/gpfs/fs2/project/jgu-multiomics/Otting/Resultsq=X\\x0e\\x00\\x00\\x00EVO_REG_CONFIGq>X\\x19\\x00\\x00\\x00./data/Evo_Reg_config.txtq?X\\x0b\\x00\\x00\\x00STAR_FOLDERq@X\`\\x00\\x00\\x00/gpfs/fs2/project/jgu-multiomics/Michal/EvoReg/EvoReg_refs/STAR_genome_index_wo_gene_annotation/qAX\\x0f\\x00\\x00\\x00ENSEMBL_VERSIONqBK_X\\x0c\\x00\\x00\\x00PERMUTATIONSqCX\\x07\\x00\\x00\\x00A B C DqDuX\\x04\\x00\\x00\\x00ruleqEX\\n\\x00\\x00\\x00rcorrectorqFX\\x0f\\x00\\x00\\x00bench_iterationqGNX\\t\\x00\\x00\\x00scriptdirqHXC\\x00\\x00\\x00/gpfs/fs1/home/chotting/workflows/evoreg_assembly/workflows/scriptsqIub.'); from snakemake.logging import logger; logger.printshellcmds = False; **real_file** = **file**; **file** = '/gpfs/fs1/home/chotting/workflows/evoreg_assembly/workflows/scripts/rCorrector.py'; File "/usr/lib64/python2.7/pickle.py", line 1382, in loads return Unpickler(file).load() File "/usr/lib64/python2.7/pickle.py", line 858, in load dispatch[key](/hpc-jgu-lifescience/workflows/-/blob/master/self) File "/usr/lib64/python2.7/pickle.py", line 886, in load_proto raise ValueError, "unsupported pickle protocol: %d" % proto ValueError: unsupported pickle protocol: 3

**Minimal example**
snakemake -s Snakemake.smk -f --use-envmodules -j 23 --cluster-config cluster.json --cluster "sbatch --parsable -A {cluster.account} -p {cluster.partition} -n {cluster.threads} -t {cluster.time} --mem={cluster.memory} -J {cluster.jobname}"
#Snakefile############################################
WILD = glob_wildcards("./input/{wild}_a.in").wild
PERM = ["a","b"]

rule all:
    input: expand("{wild}.out", wild=WILD)

rule a:
    input:
        expand("./input/{{wild}}_{perm}.in", perm=PERM)
    output:
        "{wild}.out"
    envmodules:
         "lang/Python/2.7.14-foss-2018a"
    script:
        "test.py"
#test.py############################################
from snakemake.shell import shell
from tempfile import TemporaryDirectory
names = str(snakemake.input)
shell(
      "srun echo {names} >> {snakemake.output[0]}"
)
##################################################
**Additional context**
This was done in a SLURM environment

**Comment by cmeesters** [comment]
This is NOT a bug, it is an inconsistency, which cannot be solved: As snakemake pickles (its attributes), when using the 'script:' tag and snakemake itself requires Py3, no script can be used, which requires Python2. Scripts are expected to work in a snakemake compatible environment. 

You could ressort to 'shell:', provided the script in question is in PATH.

A remedy to prevent future issues could be to issue an error when attempting to load a Py2 module. That, however, could be problematic, as different module naming conventions would have to be checked and there can be more then one versionstring per module (e.g. one for Python and one for the software requiring Python). So, technically, a check whether or not Py2 is in PATH _after loading the modules_ would be fail safe. 

My question to everybody would be: This is my attitude. Python 2 is obsolete and scientific projects still relying on it are probably not maintained. Hence, simply informing a user, that Python2 together with 'script:' is impossible should suffice. After all, it is still possible to use a Py2-script via the shell command. Any objections?

If not, I will try making an PR in the near future.

**Comment by cmeesters** [comment]
Seems like a perfectly smooth solution. Shall we consider the matter as settled, @otting?

**Comment by otting** [comment]
great, thanks :)
