### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int' while passing --use-singularity

### ISSUE THREAD

**Issue by wenweiliang** [snakemake/snakemake#443]
**Snakemake version**
Snakemake: 5.19.2
Conda: 4.8.3
Singularity: 3.5.3
Those are installed by `conda create -n pvacseq_msi python=3.7 snakemake=5.19.2 pandas=1.0.1 singularity=3.5.3`

**Describe the bug**
Snakemake ran into TypeError when I use`--use-singularity`

**Logs**
```
Building DAG of jobs...
Traceback (most recent call last):
  File "/diskmnt/Projects/Users/wliang/miniconda3/envs/pvacseq_msi/lib/python3.7/site-packages/snakemake/__init__.py", line 703, in snakemake
    keepincomplete=keep_incomplete,
  File "/diskmnt/Projects/Users/wliang/miniconda3/envs/pvacseq_msi/lib/python3.7/site-packages/snakemake/workflow.py", line 830, in execute
    dryrun=dryrun or list_conda_envs, quiet=list_conda_envs
  File "/diskmnt/Projects/Users/wliang/miniconda3/envs/pvacseq_msi/lib/python3.7/site-packages/snakemake/dag.py", line 278, in pull_container_imgs
    img = singularity.Image(img_url, self)
  File "/diskmnt/Projects/Users/wliang/miniconda3/envs/pvacseq_msi/lib/python3.7/site-packages/snakemake/deployment/singularity.py", line 47, in __init__
    if not LooseVersion(v) >= LooseVersion("2.4.1"):
  File "/diskmnt/Projects/Users/wliang/miniconda3/envs/pvacseq_msi/lib/python3.7/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/diskmnt/Projects/Users/wliang/miniconda3/envs/pvacseq_msi/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Minimal example**
commend
```
snakemake -p all --use-singularity --singularity-args "--bind ${path2data}:/data" --cores 1
```

Snakefile
```
rule vep:
    input:
        vcf = f"{OUTPUT}{{sample}}.chi.vcf"
    output:
        f"{OUTPUT}{{sample}}.chi.vep.vcf"
    params:
        i = "/data/{sample}.chi.vcf",
        o = "/data/{sample}.chi.vcf.vcf"
    singularity:
        "docker://ensemblorg/ensembl-vep:release_97.4"
    shell:
        "vep --input_file {params.i} \
             --output_file {params.o} \
             --assembly GRCh37 \
             --fasta {path2fasta} \
             --force_overwrite --species homo_sapiens --cache --check_ref \
             --dir {path2vep/cache} \
             --vcf --offline --symbol --terms SO --tsl --hgvs --plugin Downstream --plugin Wildtype --format vcf"

rule all:
    input:
        expand(f"{OUTPUT}{{sample}}.chi.vep.vcf", sample=SAMPLE)
```

**Additional context**

**Comment by wenweiliang** [comment]
It is the same issue as #303. Solved the TypeError as #303.

**Comment by cademirch** [comment]
Closing since we are at Snakemake 9 now. If this still occurs on the latest version, please reopen.
