### ISSUE TITLE
Rules included from `workflow/rules` search for conda environments in `workflow/rules/envs` instead of `workflow/envs`

### ISSUE THREAD

**Issue by kevinrue** [snakemake/snakemake#445]
**Snakemake version**
Note the Snakemake version for which you experience the bug.
Always make sure to try out the latest version before creating a new bug report.
```
$ snakemake --version
5.19.2
```

**Describe the bug**

Following the [recommended structure](https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html) of workflows, I have placed rules in `workflow/rules` and conda environments in `workflow/envs`.
However, for rules that are defined within `workflow/rules` and imported in the main `Snakefile`, Snakemake searches for the conda environment in `workflow/rules/envs` (within the `rules` subdirectory) instead of looking in `workflow/envs`, which is the recommended place to store environments.

I can see how this makes sense in terms of "real" relative paths on the system, but once imported in the main Snakefile, it would make more sense that Snakemake searches for the rule in the `workflow/envs` directory, so that all environments are stored in the same place.

**Logs**
If applicable, any terminal output to help explain your problem.
```
$ snakemake --use-conda --cores 1 --verbose
Building DAG of jobs...
Full Traceback (most recent call last):
  File "/ifs/devel/kevin/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/__init__.py", line 626, in snakemake
    success = workflow.execute(
  File "/ifs/devel/kevin/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/workflow.py", line 834, in execute
    dag.create_conda_envs(
  File "/ifs/devel/kevin/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 270, in create_conda_envs
    env.create(dryrun)
  File "/ifs/devel/kevin/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 216, in create
    env_hash = self.hash
  File "/ifs/devel/kevin/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 97, in hash
    md5hash.update(self.content)
  File "/ifs/devel/kevin/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 82, in content
    self._content = content(self.file)
  File "/ifs/devel/kevin/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 51, in content
    raise WorkflowError("Conda env file does not " "exist: {}".format(env_file))
snakemake.exceptions.WorkflowError: Conda env file does not exist: /ifs/research-groups/sims/kevin/test/workflow/rules/envs/myenv.yaml

WorkflowError:
Conda env file does not exist: /ifs/research-groups/sims/kevin/test/workflow/rules/envs/myenv.yaml
  File "/ifs/devel/kevin/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 216, in create
  File "/ifs/devel/kevin/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 97, in hash
  File "/ifs/devel/kevin/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 82, in content
  File "/ifs/devel/kevin/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 51, in content
unlocking
removing lock
removing lock
removed all locks
```

**Minimal example**
Add a minimal example for reproducing the bug.
```
git@github.com:kevinrue/snakemake_minimal_example.git test
cd snakemake_minimal_example
git checkout bb120a27d7cce96c1ddf24997292b27a39de5bbf
snakemake --use-conda --cores 1 --verbose
```

**Additional context**

**Comment by kevinrue** [comment]
Oh wait. After reading the docs 10 times, I still missed the important bit: 

> The path to the environment definition is interpreted as relative to the Snakefile that contains the rule (unless it is an absolute path, which is discouraged).
Source: https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#integrated-package-management

Sorry for the noise.
