### ISSUE TITLE
Too Many Open files error with more remote FTP inputs than ulimit

### ISSUE THREAD

**Issue by jmeppley** [snakemake/snakemake#455]
**Snakemake version**
latest as of today: 5.19.3+1.g7026550f

**Describe the bug**
A workflow with too many FTP remote files will fail. Too many is defined by `ulimit -n`. Using HTTP remotes for the same files does not fail. It looks like maybe the FTP remote mechanism isn't closing file handles after checking remote files. 

**Logs**

```
[jmeppley@tyrosine test_ftp_bug]$ snakemake -n --config limit=15 protocol=FTP
Building DAG of jobs...
Updating job 0 (all).
Traceback (most recent call last):
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/host.py", line 885, in _FTPHost_dir_command
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/ftplib.py", line 575, in dir
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/ftplib.py", line 468, in retrlines
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/ftplib.py", line 399, in transfercmd
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/ftplib.py", line 361, in ntransfercmd
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/socket.py", line 724, in create_connection
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/socket.py", line 708, in create_connection
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/socket.py", line 144, in __init__
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/__init__.py", line 703, in snakemake
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/workflow.py", line 668, in execute
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/dag.py", line 1179, in update_checkpoint_dependencies
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/dag.py", line 1357, in replace_job
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/dag.py", line 705, in update
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/dag.py", line 788, in update_
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/dag.py", line 705, in update
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/dag.py", line 776, in update_
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/io.py", line 334, in exists
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/io.py", line 174, in wrapper
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/io.py", line 355, in exists_remote
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/snakemake/snakemake/remote/FTP.py", line 206, in exists
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/path.py", line 68, in exists
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/host.py", line 921, in lstat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 835, in _lstat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 801, in __call_with_parser_retry
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 719, in _real_lstat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/path.py", line 145, in isdir
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/path.py", line 125, in _is_file_system_entity
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/host.py", line 937, in stat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 846, in _stat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 801, in __call_with_parser_retry
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 768, in _real_stat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 719, in _real_lstat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/path.py", line 145, in isdir
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/path.py", line 125, in _is_file_system_entity
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/host.py", line 937, in stat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 846, in _stat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 801, in __call_with_parser_retry
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 768, in _real_stat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 719, in _real_lstat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/path.py", line 145, in isdir
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/path.py", line 125, in _is_file_system_entity
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/host.py", line 937, in stat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 846, in _stat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 801, in __call_with_parser_retry
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 768, in _real_stat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 729, in _real_lstat
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 620, in _stat_results_from_dir
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/stat.py", line 613, in _host_dir
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/host.py", line 889, in _dir
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/host.py", line 610, in _robust_ftp_command
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/host.py", line 885, in _FTPHost_dir_command
  File "/mnt/histidine/scratch2/jmeppley/tmp/snakemake_bug/test.env/lib/python3.6/site-packages/ftputil/error.py", line 172, in __exit__
ftputil.error.FTPOSError: [Errno 24] Too many open files
Debugging info: ftputil 4.0.0, Python 3.6.10 (linux)
```

**Minimal example**
The snakefile for the above error is:
```
from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

protocol = config.get('protocol', 'FTP').upper()
if protocol == 'FTP':
    RP = FTPRemoteProvider()
elif protocol == 'HTTP':
    RP = HTTPRemoteProvider()
else:
    raise Exception("Unknown protocol " + protocol)

# remote loaction
REMOTE_TEMPLATE = \
    'ftp.ncbi.nlm.nih.gov/refseq/release/complete/{fragment}protein.gpff.gz'
LOCAL_TEMPLATE = 'download/{fragment}protein.gpff.gz'

# find files to download
fragments, = RP.glob_wildcards(REMOTE_TEMPLATE)

# limit download so test doesn't take forever
limit = config.get('limit', 2500)
rule all:
    input: expand(LOCAL_TEMPLATE, fragment=fragments[:limit])

rule dl_proteins:
    input: RP.remote(REMOTE_TEMPLATE)
    output: LOCAL_TEMPLATE,
    shell: """ ln -s ../{input} {output} """
```
Note: you get to the error faster if you shrink your ulimit first: `ulimit -n 10` and run with a small file limit `snakemake --config limit=15 -n'.

**Comment by jmeppley** [comment]
I just found the immediate_close option.
