### ISSUE TITLE
SyntaxError in pickle procress

### ISSUE THREAD

**Issue by SilasK** [snakemake/snakemake#49]
**Snakemake version**
5.7 
no bug in 5.4.1

**Describe the bug**
We encountered a [bug](https://github.com/metagenome-atlas/atlas/issues/254) in the metagneome-atlas snakemake pipeline, when running an external python script which uses multiple threads and uses snakemake.shell.shell tu run command application. 
The rule works on most sytems, but multiple users encountered the problem

The error message complains about a SyntaxError in a pickle process, done by snakemake. 
From the error message, it is difficult to go back and see where there might be an error in my snakemake or python script. 

**Logs**
```
Activating conda environment: /stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/f6f0da5b
Job counts:
count jobs
1 predict_genes_genomes
1
Traceback (most recent call last):
File "/stor/work/Ochman/sean/projects/bee_metagenomes/full_run_1/.snakemake/shadow/tmp8mzrmw3k/.snakemake/scripts/tmp7l63qsgu.predict_genes_of_genomes.py", line 3, in
import sys; sys.path.extend(["/stor/home/spl552/miniconda3/envs/atlas/lib/python3.6/site-packages", "/stor/work/Ochman/sean/projects/atlas-tutorial/atlas/atlas/rules"]); import pickle; snakemake = pickle.loads(b'\x80\x03csnakemake.script\nSnakemake\nq\x00)\x81q\x01}q\x02(X\x05\x00\x0
genes_genomesq\xcbX\x0f\x00\x00\x00bench_iterationq\xccNX\t\x00\x00\x00scriptdirq\xcdX@\x00\x00\x00/stor/work/Ochman/sean/projects/atlas-tutorial/atlas/atlas/rulesq\xceub.'); from snakemake.logging import logger; logger.printshellcmds = False; real_file = file; file = '/stor/work/Ochman/sean/projects/atlas-tutorial/atlas/atlas/rules/predict_genes_of_genomes.py';
File "/stor/home/spl552/miniconda3/envs/atlas/lib/python3.6/site-packages/snakemake/init.py", line 21, in
from snakemake.workflow import Workflow
File "/stor/home/spl552/miniconda3/envs/atlas/lib/python3.6/site-packages/snakemake/workflow.py", line 30, in
from snakemake.dag import DAG
File "/stor/home/spl552/miniconda3/envs/atlas/lib/python3.6/site-packages/snakemake/dag.py", line 1618
return f"#{hex_r:0>2X}{hex_g:0>2X}{hex_b:0>2X}"
^
SyntaxError: invalid syntax
[Tue Oct 22 11:34:23 2019]
Error in rule predict_genes_genomes:
jobid: 0
output: genomes/annotations/genes
log: logs/genomes/prodigal.log (check log file(s) for error message)
conda-env: /stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/f6f0da5b

RuleException:
CalledProcessError in line 451 of /stor/work/Ochman/sean/projects/atlas-tutorial/atlas/atlas/rules/genomes.smk:
Command 'source /stor/home/spl552/miniconda3/bin/activate '/stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/f6f0da5b'; set -euo pipefail; python /stor/work/Ochman/sean/projects/bee_metagenomes/full_run_1/.snakemake/shadow/tmp8mzrmw3k/.snakemake/scripts/tmp7l63qsgu.predict_genes_of_genomes.py' returned non-zero exit status 1.
File "/stor/work/Ochman/sean/projects/atlas-tutorial/atlas/atlas/rules/genomes.smk", line 451, in __rule_predict_genes_genomes
```

**Comment by iromeo** [comment]
I've got similar `SyntaxError` in `cairosvg` test from `snakemake-wrappers` project for build launched in CircleCI for my pull request https://github.com/snakemake/snakemake-wrappers/pull/3. Basically same test fails just in my fork master branch (it doesn't have my commits), see https://circleci.com/gh/iromeo/snakemake-wrappers/10

**Comment by johanneskoester** [comment]
This is fixed in the latest release. It was an issue with using the latest python format syntax without requiring the latest python version. I have reverted it to the old style formatting.

**Comment by SilasK** [comment]
This would be snakelike 5.7.4 or later?

**Comment by SilasK** [comment]
I think in this script I use phyton 3.5 and the old .format string formating.
