### ISSUE TITLE
Cannot run snakemake from within flask app

### ISSUE THREAD

**Issue by millerh1** [snakemake/snakemake#491]
**Snakemake version**
5.20.0

**Describe the bug**
Running snakemake from within a flask app produces an error

**Logs**
```
(mamba_env) millerh1@cbbi16:~/Bishop.lab/Projects/RSeq$ flask run -p 7667 -h 0.0.0.0
 * Serving Flask app "app.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:7667/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 270-989-380
Building DAG of jobs...
Traceback (most recent call last):
  File "/home/UTHSCSA/millerh1/miniconda3/envs/mamba_env/lib/python3.8/site-packages/snakemake/__init__.py", line 626, in snakemake
    success = workflow.execute(
  File "/home/UTHSCSA/millerh1/miniconda3/envs/mamba_env/lib/python3.8/site-packages/snakemake/workflow.py", line 859, in execute
    scheduler = JobScheduler(
  File "/home/UTHSCSA/millerh1/miniconda3/envs/mamba_env/lib/python3.8/site-packages/snakemake/scheduler.py", line 318, in __init__
    signal.signal(signal.SIGTERM, self.exit_gracefully)
  File "/home/UTHSCSA/millerh1/miniconda3/envs/mamba_env/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
129.111.223.99 - - [10/Jul/2020 16:02:05] "GET / HTTP/1.1" 200 -
```

**Minimal example**
`app.py` is

```
from flask import Flask
import snakemake as snk

app = Flask(__name__)

@app.route('/')
def hello_world():
    snk.snakemake(snakefile='example_snake')
    return 'Hello, World!'
    
```

`example_snake` is:

```
rule all:
    output: 'helloworld.txt'
    shell: 'echo "hello world!" > {output}'
```

shell commands:

```
export FLASK_APP=app.py
flask run -p 7667 -h 0.0.0.0
```

output:

```
 * Serving Flask app "app.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:7667/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 270-989-380
Building DAG of jobs...
Traceback (most recent call last):
  File "/home/UTHSCSA/millerh1/miniconda3/envs/mamba_env/lib/python3.8/site-packages/snakemake/__init__.py", line 626, in snakemake
    success = workflow.execute(
  File "/home/UTHSCSA/millerh1/miniconda3/envs/mamba_env/lib/python3.8/site-packages/snakemake/workflow.py", line 859, in execute
    scheduler = JobScheduler(
  File "/home/UTHSCSA/millerh1/miniconda3/envs/mamba_env/lib/python3.8/site-packages/snakemake/scheduler.py", line 318, in __init__
    signal.signal(signal.SIGTERM, self.exit_gracefully)
  File "/home/UTHSCSA/millerh1/miniconda3/envs/mamba_env/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
129.111.223.99 - - [10/Jul/2020 16:02:05] "GET / HTTP/1.1" 200 -

```

**Additional context**
The `--gui` flag also throws an error so it's unclear if this problem is present in that mode.

**Comment by millerh1** [comment]
I should mention that this does work -- though it is not idea...

```
from flask import Flask
import snakemake as snk
import os

app = Flask(__name__)

@app.route('/')
def hello_world():
    os.system('snakemake -s example_snake --cores 1')
    return 'Hello, World!'
```

**Comment by millerh1** [comment]
Okay -- so it turns out this is a conflict between how flask and snakemake handle processes. The only solution I have found is to separate them with `Popen`:

`app.py`:

```
from flask import Flask
import subprocess

app = Flask(__name__)


@app.route('/')
def hello_world():
    subprocess.Popen(['python', 'run_snake.py'])
    return 'Hello, World!'
```

`run_snake.py`:

```
import snakemake as snk

snk.snakemake(snakefile='example.smk')
```

`example.smk`:

```
rule all:
    output: 'helloworld.txt'
    shell: 'echo "hello world!" > {output}'
```


execution:

```
export FLASK_APP=app
flask run -p 7090 -h 0.0.0.0
```

output:

```
 * Serving Flask app "app"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:9080/ (Press CTRL+C to quit)
129.111.223.99 - - [14/Jul/2020 08:18:54] "GET / HTTP/1.1" 200 -
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1

[Tue Jul 14 08:18:54 2020]
rule all:
    output: helloworld.txt
    jobid: 0

[Tue Jul 14 08:18:54 2020]
Finished job 0.
1 of 1 steps (100%) done
Complete log: /home/UTHSCSA/millerh1/Bishop.lab/Projects/RSeq/rseq/misc/example/.snakemake/log/2020-07-14T081854.954626.snakemake.log

```

**Comment by andersgs** [comment]
Commenting out line 327 in `scheduler.py` makes things work for me:

`signal.signal(signal.SIGTERM, self.exit_gracefully)`

Maybe `snakemake.snakemake` can take a `in_thread` boolean parameter that is passed to the `Workflow` class instance, and then to the `JobScheduler` call, which in turn turns off the call to `signal.signal` in the thread.

As detailed in the Python docs, signals can only be called in the main thread, and from Py3.8, the ID of the main thread is now being tracked. 

Good discussions on the topic here https://bugs.python.org/issue38904 and here https://bugs.python.org/issue39042
