### ISSUE TITLE
DAG evaluation causes jobs to fail with --immediate-submit

### ISSUE THREAD

**Issue by reslp** [snakemake/snakemake#507]
Hi,

I came across a strange problem, which I am not sure how to solve. From what I can see it ash to do the reevaluating the DAG before a rule starts to run. I would greatly appreciate any suggestion on how to resolve this. 

best,
Philipp

**Snakemake version**
5.19.3

**Describe the bug**
I use snakemake together with --use-singularity and --immediate-submit. I have several rules which run in the following order:
mask -> predict -> tar_predict. The last rule compresses some files produced by rule predict due to space limitations on our cluster. I run this set of rules (including rules before and after) for a larger number of samples. Now when submitting all jobs for all samples to our cluster, I have the problem that sometimes for sample B rule mask fails because for sample A rule tar_predict already ran and removed some files which rule predict produced (they get gzipped). I posted the error message I get below. The missing files are neither needed by rule mask nor by an other rule after tar_predict.  This is why I gzip the folders to save space. 

Another thing is that this not only affects the mask rule, also other rules occasionally fail, although the files which are not found are neither input files to the rule which fails nor to any other rule.

**Logs**
This is the log from one sample from rule mask. As you can see the missing files belong to a differently named sample. I should not interfere at all with the sample which fails:
```
$ cat Mycoblastus_sanguinarius-mask-slurm-311196.err
Building DAG of jobs...
Traceback (most recent call last):
  File "/home/fs71312/reslp/.miniconda3/envs/sm/lib/python3.8/site-packages/snakemake/__init__.py", line 626, in snakemake
    success = workflow.execute(
  File "/home/fs71312/reslp/.miniconda3/envs/sm/lib/python3.8/site-packages/snakemake/workflow.py", line 667, in execute
    dag.init()
  File "/home/fs71312/reslp/.miniconda3/envs/sm/lib/python3.8/site-packages/snakemake/dag.py", line 177, in init
    job = self.update(self.file2jobs(file), file=file, progress=progress)
  File "/home/fs71312/reslp/.miniconda3/envs/sm/lib/python3.8/site-packages/snakemake/dag.py", line 706, in update
    self.update_(
  File "/home/fs71312/reslp/.miniconda3/envs/sm/lib/python3.8/site-packages/snakemake/dag.py", line 777, in update_
    file.inventory()
  File "/home/fs71312/reslp/.miniconda3/envs/sm/lib/python3.8/site-packages/snakemake/io.py", line 208, in inventory
    self._local_inventory(cache)
  File "/home/fs71312/reslp/.miniconda3/envs/sm/lib/python3.8/site-packages/snakemake/io.py", line 221, in _local_inventory
    with os.scandir(path) as scan:
FileNotFoundError: [Errno 2] No such file or directory: 'results/Acarospora_spec/aca_spe_preds/predict_misc/busco/run_acarospora_spec/augustus_output'
```

**Comment by reslp** [comment]
Hi, I am still wondering about this problem. I have seen it now on different occasions in different workflow. The error seems to occur randomly, when I run the same pipeline multiple times not always the same jobs are failing, nor does the error indicate the same files as missing every time a job fails. Here is how I think the error happens:

After submission with --immediate-submit the jobs are submitted to the queue on our cluster. Then, as jobs start to run, the DAG for the rule is evaluated and output files are created and the job finishes correctly. Sometimes however, while the DAG is evaluated for one rule, files produced from another rule which is currently running (or the same rule but from another sample) change or get removed (as part of the rule). This causes the DAG evaluation to fail. In a large workflow with thousands of submitted jobs and many jobs starting to run and finishing at the same time this can happen fairly often. For example I have a workflow where I submitted jobs for a single rule for >2000 samples. In this case I saw that over 800 jobs failed with this error. I am still wondering what the problem could be. Could it be a mistake of how I design my workflows? Are there any suggestions on how to fix this? I am thinking of implementing shadow rules to avoid this, but I am not sure if this will work...

best,
Philipp

**Comment by adelfma3** [comment]
Hi Philipp,

Hope you sort out your problem with snakmake as I've come across the exact issue. I used to run snakemake smoothly before one year. Today, I've run it again and it has been failed with the following error.  

Building DAG of jobs...
Traceback (most recent call last):
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7ffa250516d0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ftp.ensembl.org', port=443): Max retries exceeded with url: /pub/release-95/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.10.fa.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ffa250516d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/__init__.py", line 633, in snakemake
    keepincomplete=keep_incomplete,
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/workflow.py", line 565, in execute
    dag.init()
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/dag.py", line 168, in init
    job = self.update([job], progress=progress)
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/dag.py", line 757, in update_
    if not file.exists:
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/io.py", line 262, in exists
    return self.exists_remote
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/io.py", line 135, in wrapper
    v = func(self, *args, **kwargs)
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/io.py", line 314, in exists_remote
    return self.remote_object.exists()
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/remote/HTTP.py", line 159, in exists
    with self.httpr(verb="HEAD") as httpr:
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/snakemake/remote/HTTP.py", line 152, in httpr
    r = requests.head(url, *args_to_use, **kwargs_to_use)
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/requests/api.py", line 101, in head
    return request('head', url, **kwargs)
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/afma3/miniconda3/envs/Pinfish/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ftp.ensembl.org', port=443): Max retries exceeded with url: /pub/release-95/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.10.fa.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ffa250516d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

[error.txt](https://github.com/snakemake/snakemake/files/5433960/error.txt)

Best,
Adel

**Comment by kdm9** [comment]
I've just found this same issue, and using `--scheduler greedy` fixed it. Is suspect the ILP solver looks up file stats or sizes etc, which obviously won't work with --immediate-submit. @johanneskoester perhaps `--immediate-submit` should imply `--scheduler greedy`? I can try and make a PR with that if you agree.
