### ISSUE TITLE
Conda version checker fails in case of singularity

### ISSUE THREAD

**Issue by mariafiruleva** [snakemake/snakemake#520]
**Snakemake version**

`5.20.1`

**singularity version** : singularity version 47b018f-dirty (installed via conda)

**Describe the bug**

When I run a pipeline with `--use-singularity --use-conda` mode, it fails because it detects the wrong version of conda.

**Logs**
```
Full Traceback (most recent call last):
  File "/nfs/home/mfiruleva/anaconda3/envs/guide/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
    run(
  File "/mnt/tank/scratch/mfiruleva/other_stuff/sin_guide/smk_sing_guide/rules/script_2.smk", line 16, in __rule_geom_point
  File "/nfs/home/mfiruleva/anaconda3/envs/guide/lib/python3.8/site-packages/snakemake/shell.py", line 134, in __new__
    cmd = Conda(container_img).shellcmd(conda_env, cmd)
  File "/nfs/home/mfiruleva/anaconda3/envs/guide/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 381, in __new__
    inst.__init__(container_img=container_img)
  File "/nfs/home/mfiruleva/anaconda3/envs/guide/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 394, in __init__
    self._check()
  File "/nfs/home/mfiruleva/anaconda3/envs/guide/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 451, in _check
    if StrictVersion(version) < StrictVersion("4.2"):
  File "/nfs/home/mfiruleva/anaconda3/envs/guide/lib/python3.8/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/nfs/home/mfiruleva/anaconda3/envs/guide/lib/python3.8/distutils/version.py", line 138, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number 'Convert'

```

**Minimal example**
1. Snakefile:

```
container: "docker://continuumio/miniconda3:latest"

rule scatter:
    output: "scatter.pdf"
    conda: "scn.yaml"
    shell: "python scatter.py"
```

2. scn.yaml:

```
channels:
  - anaconda
  - defaults
dependencies:
  - seaborn=0.10.0
```

3. scatter.py:

```
import seaborn as sns

df = sns.load_dataset('iris')
sns.scatterplot(x="sepal_length", y="petal_length", data=df).get_figure().savefig("scatter.pdf")
```

run:
`snakemake -j 1 --use-singularity --use-conda`

**Additional context**
To fix it, I've changed the code in this [line](https://github.com/snakemake/snakemake/blob/77ea82768338ac45025583b9b8b97e7f188939bb/snakemake/deployment/conda.py#L447):

`version = version.split()[1]` -> `version = re.findall('\d+.\d+.\d+', version)[0]`

**Comment by akiledal** [comment]
I'm also seeing this issue when running snakemake with --use-conda (but not --use-singularity).
