### ISSUE TITLE
Tibanna Execution breaks Wildcards

### ISSUE THREAD

**Issue by nhartwic** [snakemake/snakemake#525]
I have a snakemake workflow that includes a rule "busco". Rule below...

```
rule busco:
    input:
        "{base}.fasta"
    output:
        "busco_summary_{base}.txt",
        "busco_table_{base}.tsv"
    params:
        outbase = lambda wcs: wcs["base"],
        lineage = lambda wcs: config["busco"],
        summary = lambda wcs: f"{wcs['base']}/run_{config['busco']}/short_summary.txt",
        table = lambda wcs: f"{wcs['base']}/run_{config['busco']}/full_table.tsv",
        opt = opts.get("busco", "")
    threads:
        32
    conda:
        "envs/general.yml"
    shell:
        """
        busco {params.opt} -i {input[0]} -c {threads} -o {params.outbase} -l {params.lineage}  --mode geno
        mv {params.summary} {output[0]}
        mv {params.table} {output[1]}
        """
```

In plain English, this rule will run busco on some fasta file using the busco database specified by the config.

When I try to run this rule in this workflow, snakemake/tibanna seems unable to meaningfully resolve the wildcards. I get a "MissingRuleException". When I run the same command without the tibanna flag, everything works fine. Command for reference...

```
snakemake busco_summary_Vaccinium_oxycoccos_genome_v1.txt \
    -p --use-conda --tibanna \
    --default-remote-prefix mybucket/cranberry/oxycoccos/ \
    --default-resources disk_mb=200000 \
    --config basename=Vaccinium_oxycoccos_genome_v1 busco=viridiplantae_odb10 \
    --tibanna-config log_bucket=my-log-bucket
```

This behavior confuses me. Tibanna seems to be breaking the wildcard logic somehow. Running in verbose mode produces the following useless error...

```
Building DAG of jobs...
Full Traceback (most recent call last):
  File "/home/ubuntu/workflows/snakemake/snakemake/__init__.py", line 699, in snakemake
    keepincomplete=keep_incomplete,
  File "/home/ubuntu/workflows/snakemake/snakemake/workflow.py", line 641, in execute
    dag.init()
  File "/home/ubuntu/workflows/snakemake/snakemake/dag.py", line 172, in init
    job = self.update(self.file2jobs(file), file=file, progress=progress)
  File "/home/ubuntu/workflows/snakemake/snakemake/dag.py", line 1467, in file2jobs
    raise MissingRuleException(targetfile)
snakemake.exceptions.MissingRuleException: No rule to produce busco_summary_Vaccinium_oxycoccos_genome_v1.txt (if you use input functions make sure that they don't raise unexpected exceptions).

MissingRuleException:
No rule to produce busco_summary_Vaccinium_oxycoccos_genome_v1.txt (if you use input functions make sure that they don't raise unexpected exceptions).
```

**Comment by nhartwic** [comment]
Resolved. Command should be...

snakemake mybucket/cranberry/oxycoccos/busco_summary_Vaccinium_oxycoccos_genome_v1.txt \
    -p --use-conda --tibanna \
    --default-remote-prefix mybucket/cranberry/oxycoccos/ \
    --default-resources disk_mb=200000 \
    --config basename=Vaccinium_oxycoccos_genome_v1 busco=viridiplantae_odb10 \
    --tibanna-config log_bucket=my-log-bucket

...I don't particularly love this behavior but at least it works.
