### ISSUE TITLE
--export-cwl: maximum recursion error when input file has an absolute path

### ISSUE THREAD

**Issue by pdagosto** [snakemake/snakemake#542]
**Snakemake version**
Note the Snakemake version for which you experience the bug.
Always make sure to try out the latest version before creating a new bug report.
5.15.0

**Describe the bug**
I am getting a maximum recursion error when using the --export-cwl option if the input file has an absolute path. It works fine when the input file is in the working directory and the input is the basename of the file or if the input file is in a sub-directory of the working directory and a relative path is used as input.

**Logs**
If applicable, any terminal output to help explain your problem.
```
(base) pdagosto@rckgxf0013 simple]$ snakemake -s makefiles/main.make --cores 8 --export-cwl simple.cwl
Building DAG of jobs...
Traceback (most recent call last):
  File "/work/miniconda/lib/python3.7/site-packages/snakemake/__init__.py", line 654, in snakemake
    keepincomplete=keep_incomplete,
  File "/work/miniconda/lib/python3.7/site-packages/snakemake/workflow.py", line 722, in execute
    json.dump(dag_to_cwl(dag), cwl, indent=4)
  File "/work/miniconda/lib/python3.7/site-packages/snakemake/cwl.py", line 258, in dag_to_cwl
    dag_cwl = [job_to_cwl(job, dag, outputs, inputs) for job in groups]
  File "/work/miniconda/lib/python3.7/site-packages/snakemake/cwl.py", line 258, in <listcomp>
    dag_cwl = [job_to_cwl(job, dag, outputs, inputs) for job in groups]
  File "/work/miniconda/lib/python3.7/site-packages/snakemake/cwl.py", line 160, in job_to_cwl
    (f for dep in dag.dependencies[job] for f in dep.output),
  File "/work/miniconda/lib/python3.7/site-packages/snakemake/cwl.py", line 157, in <listcomp>
    for i, f in enumerate(
  File "/work/miniconda/lib/python3.7/site-packages/snakemake/cwl.py", line 122, in workdir_entry
    json.dumps(outer_entry(f, entry)).replace('"??', "").replace('??"', "")
  File "/work/miniconda/lib/python3.7/site-packages/snakemake/cwl.py", line 133, in outer_entry
    "listing": [entry],
  File "/work/miniconda/lib/python3.7/site-packages/snakemake/cwl.py", line 133, in outer_entry
    "listing": [entry],
  File "/work/miniconda/lib/python3.7/site-packages/snakemake/cwl.py", line 133, in outer_entry
    "listing": [entry],
  [Previous line repeated 985 more times]
  File "/work/miniconda/lib/python3.7/site-packages/snakemake/cwl.py", line 126, in outer_entry
    parent = os.path.dirname(f)
  File "/work/miniconda/lib/python3.7/posixpath.py", line 157, in dirname
    sep = _get_sep(p)
  File "/work/miniconda/lib/python3.7/posixpath.py", line 42, in _get_sep
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object

```
**Minimal example**
Add a minimal example for reproducing the bug.
```
rule all:
	input: 'python.txt'
	output: 'result.txt'
	shell: 'cat {input} > {output}'

rule find:
	input: '/home/pdagosto/.emacs'
	output: 'python.txt'
	shell: 'grep -nH python {input} > {output}'
```

**Additional context**

**Comment by pdagosto** [comment]
I also found that the working directory had to be a git repository otherwise I got the following error:

```
Building DAG of jobs...
Unable to retrieve additional files from git. This is not a git repository.
```
