### ISSUE TITLE
Error when using --debug with GLS (and likely other executors)

### ISSUE THREAD

**Issue by vsoch** [snakemake/snakemake#557]
To reproduce:

```bash
$ snakemake --google-lifesciences --default-remote-prefix snakemake-testing-data --use-conda --google-lifesciences-region us-central1 --debug
Traceback (most recent call last):
  File "/home/vanessa/snakemake/env/bin/snakemake", line 11, in <module>
    load_entry_point('snakemake', 'console_scripts', 'snakemake')()
  File "/home/vanessa/snakemake/snakemake/__init__.py", line 2384, in main
    log_handler=log_handler,
  File "/home/vanessa/snakemake/snakemake/__init__.py", line 447, in snakemake
    if debug and (cluster_mode or cores > 1):
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
I already have a fix and will PR shortly, we basically shouldn't do a comparison with cores if it's been set to None.

**Comment by johanneskoester** [comment]
Fixed by PR #559.
