### ISSUE TITLE
Comparison between datetime and float with Google Storage backend

### ISSUE THREAD

**Issue by hannes-brt** [snakemake/snakemake#572]
**Snakemake version**
5.22.1

**Describe the bug**
I am running a workflow with `--default-remote-provider=GS` which always results in a TypeError, because Snakemake attempts to compare a `datetime.datetime` object to a float.

**Logs**
```
Traceback (most recent call last):
  File "/home/hannes/miniconda3/envs/target-id/lib/python3.6/site-packages/snakemake/__init__.py", line 704, in snakemake
    keepincomplete=keep_incomplete,
  File "/home/hannes/miniconda3/envs/target-id/lib/python3.6/site-packages/snakemake/workflow.py", line 667, in execute
    dag.init()
  File "/home/hannes/miniconda3/envs/target-id/lib/python3.6/site-packages/snakemake/dag.py", line 182, in init
    self.update_needrun()
  File "/home/hannes/miniconda3/envs/target-id/lib/python3.6/site-packages/snakemake/dag.py", line 936, in update_needrun
    update_needrun(job)
  File "/home/hannes/miniconda3/envs/target-id/lib/python3.6/site-packages/snakemake/dag.py", line 912, in update_needrun
    f for f in job.input if f.exists and f.is_newer(output_mintime_)
  File "/home/hannes/miniconda3/envs/target-id/lib/python3.6/site-packages/snakemake/dag.py", line 912, in <listcomp>
    f for f in job.input if f.exists and f.is_newer(output_mintime_)
  File "/home/hannes/miniconda3/envs/target-id/lib/python3.6/site-packages/snakemake/io.py", line 195, in wrapper
    return func(self, *args, **kwargs)
  File "/home/hannes/miniconda3/envs/target-id/lib/python3.6/site-packages/snakemake/io.py", line 419, in is_newer
    return self.mtime > time
TypeError: '>' not supported between instances of 'datetime.datetime' and 'float'
```

**Comment by johanneskoester** [comment]
@vsoch mtime coming from GS must be converted into a float since epoch, or vice versa, before storing into the inventory cache. Can you have a look?

**Comment by vsoch** [comment]
See https://github.com/snakemake/snakemake/pull/579. I'm not sure why this wasn't caught before!
