### ISSUE TITLE
Error reading file update times on GS

### ISSUE THREAD

**Issue by eric-czech** [snakemake/snakemake#577]
I am encountering an exception when remote GS output files for a rule already exist.  This seems to occur whether the file is empty or not, and appears to be related to interpreting object update times.

The offending rule is very similar to the one described in https://github.com/snakemake/snakemake/issues/576, except that it uses individual files rather than directories as outputs.

**Snakemake version**

5.22.1

**Describe the bug**

I am attempting to have a rule write data directly to a directory on GS but make the output for the rule simply a checkpoint file that indicates the status of the execution.  Here is the rule:

```python
def bgen_samples_path(wc):
    n_samples = bgen_contigs.loc[wc.bgen_contig]['n_consent_samples']
    return [f"raw-data/gt-imputation/ukb59384_imp_chr{wc.bgen_contig}_v3_s{n_samples}.sample"]

rule bgen_to_zarr:
    input:
        bgen_path="raw-data/gt-imputation/ukb_imp_chr{bgen_contig}_v3.bgen",
        variants_path="raw-data/gt-imputation/ukb_mfi_chr{bgen_contig}_v3.txt",
        samples_path=bgen_samples_path
    output:
        "prep-data/gt-imputation/ukb_chr{bgen_contig}.ckpt"
    params:
        zarr_path=lambda wc: f"rs-ukb/prep-data/gt-imputation/ukb_chr{wc.bgen_contig}.zarr",
        contig_index=lambda wc: bgen_contigs.loc[str(wc.bgen_contig)]['index']
    conda:
        "envs/gwas.yaml"
    log:
        "logs/bgen_to_zarr.{bgen_contig}.txt"
    shell:
        # The script itself will write directly to a GS directory in this case
        # and the {output} file is a placemark
        "python scripts/convert.py bgen_to_zarr "
        "--input-path-bgen={input.bgen_path} "
        "--input-path-variants={input.variants_path} "
        "--input-path-samples={input.samples_path} "
        "--output-path={params.zarr_path} "
        "--contig-name={wildcards.bgen_contig} "
        "--contig-index={params.contig_index} "
        "--remote=True "
        "&& touch {output}"
```

If the `prep-data/gt-imputation/ukb_chr{bgen_contig}.ckpt` doesn't already exist on GS, then this rule runs correctly.  If it does exist though I get this error:

```
> snakemake --use-conda --cores 1 --default-remote-provider GS --default-remote-prefix rs-ukb rs-ukb/prep-data/gt-imputation/ukb_chrXY.ckpt
Building DAG of jobs...
Traceback (most recent call last):
  File "/home/eczech/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/__init__.py", line 627, in snakemake
    success = workflow.execute(
  File "/home/eczech/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/workflow.py", line 667, in execute
    dag.init()
  File "/home/eczech/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 182, in init
    self.update_needrun()
  File "/home/eczech/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 936, in update_needrun
    update_needrun(job)
  File "/home/eczech/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 911, in update_needrun
    updated_input = [
  File "/home/eczech/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 912, in <listcomp>
    f for f in job.input if f.exists and f.is_newer(output_mintime_)
  File "/home/eczech/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/io.py", line 195, in wrapper
    return func(self, *args, **kwargs)
  File "/home/eczech/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/io.py", line 419, in is_newer
    return self.mtime > time
TypeError: '>' not supported between instances of 'datetime.datetime' and 'float'
```

I have also tried modifying `touch {output}` to be something like `echo 'done' > {output}` but I get the same result so it doesn't appear to be related to empty files.

**Comment by vsoch** [comment]
hey @eric-czech ! This is a repeat of https://github.com/snakemake/snakemake/issues/572 so I'm going to close here - putting in a fix for this right now.

**Comment by eric-czech** [comment]
👍  ty!
