### ISSUE TITLE
ModuleNotFoundError: No module named 'pulp'

### ISSUE THREAD

**Issue by moldach** [snakemake/snakemake#586]
**Snakemake version**

> 5.23.0

**Describe the bug**

`conda` installation not bringing in `pulp`?

**Logs**

```
Workflow defines that rule get_vep_cache is eligible for caching between workflows (use the --cache argument to enable this).
Building DAG of jobs...
Creating conda environment https:/github.com/snakemake/snakemake-wrappers/raw/0.64.0/bio/vep/cache/environment.yaml...
Downloading and installing remote packages.
Environment for ../../../tmp/tmpe1s8iray.yaml created (location: .snakemake/conda/b26d7857)
Using shell: /usr/bin/bash
Provided cluster nodes: 1
Job counts:
        count   jobs
        1       all
        1       get_vep_cache
        2
Traceback (most recent call last):
  File "/home/moldach/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/__init__.py", line 631, in snakemake
    success = workflow.execute(
  File "/home/moldach/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/workflow.py", line 957, in execute
    success = scheduler.schedule()
  File "/home/moldach/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/scheduler.py", line 402, in schedule
    else self.job_selector_ilp(needrun)
  File "/home/moldach/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/scheduler.py", line 538, in job_selector_ilp
    import pulp
ModuleNotFoundError: No module named 'pulp'
```

**Minimal example**

## install & activate env

```
conda install -c conda-forge mamba
mamba create -c conda-forge -c bioconda -n snakemake snakemake
conda activate snakemake
```

## Snakefile

```
rule all:
    input:
	"resources/vep/cache"

rule get_vep_cache:
    output:
	directory("resources/vep/cache")
    params:
	species="saccharomyces_cerevisiae",
        build="R64-1-1",
        release="98"
    log:
        "logs/vep/cache.log"
    cache: True
    wrapper:
	"0.64.0/bio/vep/cache"
```

## Submission

```
bash -c "nohup snakemake --profile slurm --use-conda --jobs 1 &"
```

**Additional context**

```
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by lexleong** [comment]
Had the same issue. Downloaded the version 5.23.0 of snakemake and pulp was not imported. So reverted to 5.3.0 and it worked! `conda install snakemake=5.3.0`

**Comment by FelixMoelder** [comment]
This bug should have been fixed [here](https://github.com/snakemake/snakemake/issues/584).
`pulp` was missing in the conda recipe as a dependency.
Please check if conda installs version `5.23.0-2` as version `5.23.0-0` and `5.23.0-1` are broken.

**Comment by jafors** [comment]
Seems to work now - conda pulls the correct `snakemake-minimal` build.

**Comment by FelixMoelder** [comment]
> Seems to work now - conda pulls the correct `snakemake-minimal` build.

Have you tested to install snakemake or just snakemake-minimal?
In case I install `snakemake-minimal` everything is fine and conda installs `snakemake-minimal-5.3.0-py36_2`
But if I try to install `snakemake` conda suggests to install `snakemake-minimal-5.3.0-py36_1` and `snakemake-5.3.0-py36_1`.

**Comment by moldach** [comment]
Can confirm @jafors report that it pulls the correct build and runs okay
