### ISSUE TITLE
FileNotFoundError for files not specified in rule definition

### ISSUE THREAD

**Issue by RomainFeron** [snakemake/snakemake#611]
Snakemake 5.23.0

When running a snakemake workflow on an HPC, I'm getting the following error:

```
Building DAG of jobs...
Traceback (most recent call last):
  File "<base_path>/software/miniconda/envs/snakemake/lib/python3.7/site-packages/snakemake/__init__.py", line 709, in snakemake
    keepincomplete=keep_incomplete,
  File "<base_path>/software/miniconda/envs/snakemake/lib/python3.7/site-packages/snakemake/workflow.py", line 670, in execute
    dag.init()
  File "<base_path>/software/miniconda/envs/snakemake/lib/python3.7/site-packages/snakemake/dag.py", line 177, in init
    job = self.update(self.file2jobs(file), file=file, progress=progress)
  File "<base_path>/software/miniconda/envs/snakemake/lib/python3.7/site-packages/snakemake/dag.py", line 715, in update
    progress=progress,
  File "<base_path>/software/miniconda/envs/snakemake/lib/python3.7/site-packages/snakemake/dag.py", line 792, in update_
    file.inventory()
  File "<base_path>/software/miniconda/envs/snakemake/lib/python3.7/site-packages/snakemake/io.py", line 210, in inventory
    self._local_inventory(cache)
  File "<base_path>/software/miniconda/envs/snakemake/lib/python3.7/site-packages/snakemake/io.py", line 224, in _local_inventory
    with os.scandir(path) as scan:
FileNotFoundError: [Errno 2] No such file or directory: '<analysis_patch>/tmp_batch113/codons'
```
The directory `tmp_batch113/codons` is created and deleted during the execution of another job from the same rule, *i.e.* this specific error occurs for the job dealing with batch166 which never uses this directory. I suspect this could be related to a slow file system (this error does not occur consistently) but I'm surprised Snakemake crashes because of files/directory that are never specified in the rule. For reference, here is the rule behind the jobs that generate this error:

```
rule phyloCSF_batch:
    input:
        batch_file = 'output/analyses/{assembly_code}/maf_batches/batches/{batch}.lst',
        maf_dir = rules.split_maf_contig.output,
        parameters = rules.create_parameter_set.output
    output:
        'output/analyses/{assembly_code}/phyloCSF/batches/{batch}.tsv'
    benchmark:
        'benchmarks/analyses/{assembly_code}/phyloCSF/batches/{batch}.tsv'
    log:
        'logs/analyses/{assembly_code}/phyloCSF/batches/{batch}.txt'
    conda:
        '../envs/analyses.yaml'
    threads: get_threads('phyloCSF_batch')
    resources:
        mem_mb = lambda wildcards, attempt: get_mem('phyloCSF_batch', attempt),
        runtime_s = lambda wildcards, attempt: get_runtime('phyloCSF_batch', attempt)
    params:
        batch_size = config['phyloCSF']['batch_size']
    script:
        '../scripts/phyloCSF_batch.py'
```

Any idea what could be causing this issue? Any input is appreciated!

Thanks

**Comment by thibautlavole** [comment]
Same here!

Problem not consistent, and seems to be related to slow filesystem, but we couldn't find exactly what occurs and why its complaining about a file created by another rule....

Did you find a workaround?

**Comment by RomainFeron** [comment]
Sorry, I haven't found a workaround yet. It's pretty difficult as a user I think since it seems to be something internal
