### ISSUE TITLE
PermissionError in io.py caused by unrelated file in same file tree

### ISSUE THREAD

**Issue by Marc-Ruebsam** [snakemake/snakemake#640]
**Snakemake version**
```
$ snakemake --version
5.25.0
```

**Describe the bug**
Snakemake fails with a PermissionError when the folder structure contains inaccessible files, even though the files in question have no association with the current snakemake call.

We have a environment with multiple users. The users might want to execute the same pipeline on different files. Not all users have access rights to all files. The snakemake call fails when this is the case (see minimal example). This is caused by the os.scandir() call inside the _local_inventory function of the io.py script. 

**Minimal example**
We create the following example with two input files, of which only one is accessible by the current user:
```
$ cat minimal_example.sh
#!/bin/bash
mkdir -p Input/WithOUTRights
mkdir -p Input/WithRights
touch Input/WithOUTRights/File
touch Input/WithRights/File
chmod 000 Input/WithOUTRights/
```
Together with the following Snakefile:
```
$ cat Snakefile
rule all:
    input:
        'Input/{dir}/{file}'
    output:
        'Output/{dir}/{file}'
    shell:
        'cp {input} {output}'
```
When executing snakemake, an error occures:
```
$ snakemake -n Output/WithRights/File
Building DAG of jobs...
Traceback (most recent call last):
  File "/home/me/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/__init__.py", line 735, in snakemake
    keepincomplete=keep_incomplete,
  File "/home/me/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/workflow.py", line 683, in execute
    dag.init()
  File "/home/me/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/dag.py", line 177, in init
    job = self.update(self.file2jobs(file), file=file, progress=progress)
  File "/home/me/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/dag.py", line 715, in update
    progress=progress,
  File "/home/me/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/dag.py", line 792, in update_
    file.inventory()
  File "/home/me/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/io.py", line 210, in inventory
    self._local_inventory(cache)
  File "/home/me/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/io.py", line 224, in _local_inventory
    with os.scandir(path) as scan:
PermissionError: [Errno 13] Permission denied: 'Input/WithOUTRights'
```
The error refers to the directory inaccessible by the current user, even though this directory is unrelated to the current snakemake call.

**(Temporary) fix**
Following EAFP, the Error can be resolved by introducing an exception in the _local_inventory function
```
    def _local_inventory(self, cache):
        # for local files, perform BFS via os.scandir to determine existence of files
        root = cache.get_inventory_root(self)
        if root == self:
            # there is no root directory that could be used
            return
        if os.path.exists(root):
            queue = [root]
            while queue:
                path = queue.pop(0)
                # path must be a dir
                cache.exists_local[path] = True
                try:
                    with os.scandir(path) as scan:
                        for entry in scan:
                            if entry.is_dir():
                                queue.append(entry.path)
                            else:
                                # path is a file
                                cache.exists_local[entry.path] = True
                except PermissionError:
                    pass

        cache.has_inventory.add(root)
```
Resulting in a successful execution.
In case the users are unaware about their missing permission, this (only) results in a missing input file error:
```
$ snakemake -n Output/WithOUTRights/File
Building DAG of jobs...
MissingInputException in line 1 of /home/ruebsam/_Temp/snaketest/Snakefile:
Missing input files for rule all:
Input/WithOUTRights/File
```

**Additional information**
In our case the directories contain symlinks, which are accessible themselves. However, the access permissions for the linked files differ. Here a minimal example of this situation:
```
$ cat minimal_example.sh
#!/bin/bash
mkdir -p DistantDir/WithOUTRights
mkdir -p DistantDir/WithRights
touch DistantDir/WithOUTRights/File
touch DistantDir/WithRights/File
chmod 000 DistantDir/WithOUTRights/
mkdir Input
ln -s ../DistantDir/WithOUTRights/File Input/FileWithOUTRights
ln -s ../DistantDir/WithRights/File Input/FileWithRights
```
and
```
$ cat Snakefile
rule all:
    input:
        'Input/{file}'
    output:
        'Output/{file}'
    shell:
        'cp {input} {output}'
```
The error here comes from the .is_dir() call in the same function and gets fixed by the same change in the io.py script.

**Comment by vsoch** [comment]
This seems like a reasonable solution to catch the permissions error - what about another elif that checks for a symbolic link, and if this is the case, adds the resolved file path? And in the exception would it make sense to put a debug print?

Would you care to open a PR to suggest changes formally?
