### ISSUE TITLE
5.27.2 - Migration v1 to v2 breaks on directories

### ISSUE THREAD

**Issue by epruesse** [snakemake/snakemake#711]
Using v5.27.2 via github tag, I'm seeing errors in migration. It appears it's because I have directories in `.snakemake/metadata`. The directories seem to each contain only one file. I think this happened when the string got too long for a file name. The migration function just truncates, tries to read the directory and gets an `IsADirectory` exception. 

It also stumbles across empty directories that are left around, potentially due to bugs in v1?

```
Traceback (most recent call last):
  File "/Seibold/home/pruessee/projects/snakemake/snakemake/__init__.py", line 668, in snakemake
    success = workflow.execute(
  File "/Seibold/home/pruessee/projects/snakemake/snakemake/workflow.py", line 657, in execute
    self.persistence = Persistence(
  File "/Seibold/home/pruessee/projects/snakemake/snakemake/persistence.py", line 79, in __init__
    self.migrate_v1_to_v2()
  File "/Seibold/home/pruessee/projects/snakemake/snakemake/persistence.py", line 108, in migrate_v1_to_v2
    with open(os.path.join(self._metadata_path, filename), "r") as f:
```

**Comment by johanneskoester** [comment]
Thanks for reporting, I'll have a look.

**Comment by johanneskoester** [comment]
Should be fixed with the referred PR (plus test case to avoid such issues in the future).
