### ISSUE TITLE
error about "/python3.8/runpy.py"

### ISSUE THREAD

**Issue by charishelen** [snakemake/snakemake#760]
Hi, when I execute my snakemake.py file, there were some error as followed:

[Fri Nov 20 12:47:24 2020]
rule stringtie_2:
    input: mapping_hisat2/CMV1_1.gtf, mapping_hisat2/CMV1_2.gtf, mapping_hisat2/CMV1_3.gtf, mapping_hisat2/CMV1_4.gtf, mapping_hisat2/CMV1_5.gtf, mapping_hisat2/Control1.gtf, mapping_hisat2/Control2.gtf, mapping_hisat2/Control3.gtf, mapping_hisat2/Control4.gtf, mapping_hisat2/Control5.gtf
    output: mapping_hisat2/gtf.txt
    jobid: 83

Traceback (most recent call last):
  File "/opt/biosoft/anaconda3/envs/py3/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/biosoft/anaconda3/envs/py3/lib/python3.8/runpy.py", line 155, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ligang/RNA_seq/snakemake.py", line 9
    rule all:
         ^
SyntaxError: invalid syntax
Shutting down, this might take some time.

the rule is showed as followed:
rule stringtie_2:
    input:
        expand("mapping_hisat2/{sample}.gtf", sample = SAMPLES)
    output:
        txt = "mapping_hisat2/gtf.txt"
    run:
        import os
        for name in input:
            i = os.path.split(name)[-1]
            t = os.path.splitext(i)[0]
            j = t + "\t" + i + "\n"
            with open(output.txt, "a") as f:
                f.write(j)

I don't how to deal with this problem. Could you help me about that, I will be very appreciated.
Looking forward from you 

Sincerely
Gang Li

**Comment by schnea** [comment]
You should not try to execute your Snakefile as a python file. Try following the Tutorial in the snakemake documentation.
