### ISSUE TITLE
Help with phantom files on LSF server.

### ISSUE THREAD

**Issue by twylie** [snakemake/snakemake#766]
Hi, all. Hoping someone can shed some light on this. I'm running Snakemake on a compute server that runs LSF under a cache layer system. The server can experience latency in seeing that files have been removed. For example, the act of listing a directory that has been removed (but still looks to be there) will report the files are not there. After listing, the system flushes the removed directory and the removed files are no longer "there". This happens in the .snakemake/tmp* directories during parallel processing:

`ls: cannot access .snakemake/tmp.yodq9cq4/write_sam.64.sh: No such file or director`

Snakemake actually finishes all rules/steps and then post all-rule throws an error looking for phantom files.

```
[Tue Nov 24 16:17:52 2020]
Finished job 5.
676 of 677 steps (100%) done

[Tue Nov 24 16:17:52 2020]
localrule all:
    input: REPORT.trans_nuc_counts.txt, REPORT.nuc_counts.txt, REPORT.nuc_ambiguous_counts.txt, REPORT.trans_nuc_ambiguous_counts.txt, viromatch_results/tmp_dir_cleanup/DONE.tmp_dir_cleanup.txt
    jobid: 0

[Tue Nov 24 16:17:52 2020]
Finished job 0.
677 of 677 steps (100%) done
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/snakemake/__init__.py", line 735, in snakemake
    keepincomplete=keep_incomplete,
  File "/usr/local/lib/python3.7/dist-packages/snakemake/workflow.py", line 972, in execute
    success = scheduler.schedule()
  File "/usr/local/lib/python3.7/dist-packages/snakemake/scheduler.py", line 383, in schedule
    self._executor.shutdown()
  File "/usr/local/lib/python3.7/dist-packages/snakemake/executors/__init__.py", line 668, in shutdown
    shutil.rmtree(self.tmpdir)
  File "/usr/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: '566.jobfinished'
```

This is frustrating, as Snakemake has actually finished all of the steps in the pipeline successfully. I see support for latency _waiting_ for files to appear, but this seems to be a different problem.

Anyway, any insight or suggestions for obviating this post-DAG error would be greatly appreciated. Thanks in advance!

**Comment by twylie** [comment]
Is there a way to decouple the .snakemake directory from the --directory (output) directory --- i.e. have them write to separate disks? Or, can we write the .snakemake/tmp* files to another disk? We have a fast scratch disk space that is not layered (as outlined above). If I could write the .snakemake/tmp* files to the fast disk, but keep writing output to the --directory, I think the issue would be resolved.

**Comment by twylie** [comment]
I re-wrote my pipeline to symlink the output directory to slower, larger disks and keep all of the Snakemake processing files/directory on fast disks. Essentially, the master script reads/writes all of the pipeline housekeeping stuff to fast space and the heavy, computational files are written to slower space. And ... it worked. No errors, the tmp dirs cleaned themselves up, and the stats files were written on completion. The latency for process monitoring was removed.
