### ISSUE TITLE
Google Storage download retry predicate is incorrect

### ISSUE THREAD

**Issue by eric-czech** [snakemake/snakemake#785]
The current code is looking for snakemake.exceptions.CheckSumMismatchException when deciding whether or not to retry a download: 
https://github.com/snakemake/snakemake/blob/223bcc52d058e9704e69dac65c101ea1b18f3361/snakemake/remote/GS.py#L42-L48

However, I am seeing a suspiciously large number of failures like this in my pipeline:

```
Traceback (most recent call last):
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 687, in snakemake
    success = workflow.execute(
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1005, in execute
    success = scheduler.schedule()
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 489, in schedule
    self.run(runjobs)
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 500, in run
    executor.run_jobs(
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 131, in run_jobs
    self.run(
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 447, in run
    future = self.run_single_job(job)
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 491, in run_single_job
    self.cached_or_run, job, run_wrapper, *self.job_args_and_prepare(job)
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 452, in job_args_and_prepare
    job.prepare()
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/jobs.py", line 710, in prepare
    self.download_remote_input()
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/jobs.py", line 682, in download_remote_input
    f.download_from_remote()
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/io.py", line 584, in download_from_remote
    self.remote_object.download()
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/remote/GS.py", line 226, in download
    return download_blob(self.blob, self.local_file())
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/remote/GS.py", line 69, in download_blob
    blob.download_to_file(parser)
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1041, in download_to_file
    self._do_download(
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 900, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/google/resumable_media/requests/download.py", line 171, in consume
    self._write_to_stream(result)
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/google/resumable_media/requests/download.py", line 120, in _write_to_stream
    raise common.DataCorruption(response, msg)
google.resumable_media.common.DataCorruption: Checksum mismatch while downloading:

  https://storage.googleapis.com/download/storage/v1/b/rs-ukb/o/raw%2Fgt-imputation%2Fukb_imp_chr9_v3.bgen?generation=1602861266282729&alt=media

The X-Goog-Hash header indicated an MD5 checksum of:

  J3RmHIDzGmBKkklx/ImWtg==

but the actual MD5 checksum of the downloaded contents was:

  XHqx7gai/Eij53rF8bMrKg==
```

It looks like this `google.resumable_media.common.DataCorruption` is not being wrapped as a `snakemake.exceptions.CheckSumMismatchException` or some other design flaw exists that keeps these requests from being retried.

Note: [if_transient_error](https://googleapis.dev/python/google-api-core/latest/retry.html#google.api_core.retry.if_transient_error) does not appear to apply to this error either

**Comment by johanneskoester** [comment]
@vsoch may I ask you to have a look at this?

**Comment by vsoch** [comment]
That's interesting, the error is triggered much earlier in the function (where we wouldn't expect it) than where we manually check the checksum and throw the expected (snakemake) mismatch error, here https://github.com/snakemake/snakemake/blob/223bcc52d058e9704e69dac65c101ea1b18f3361/snakemake/remote/GS.py#L69. One troubling thing is that the function appears deprecated https://googleapis.dev/python/storage/latest/_modules/google/cloud/storage/blob.html#Blob.download_to_file. I found a similar report but it's very old: https://stackoverflow.com/questions/46804668/gcs-datacorruption-checksum-mismatch-while-downloading.

There are a few ways to go about debugging this. The first would be to give me a way to reproduce the error - @eric-czech is the storage / workflow public so I could run and reproduce? That would be the easiest way for me to debug.

if that's not possible, then what we would want to do is try a few things. The way I would go about this is by cloning the repository, installing a development version of snakemake:

```
pip install -e .[google-cloud]
```
And then with a smaller or dummy version of your pipeline, inserting an interactive statement in the download function, e.g.,

```
import IPython
IPython.embed
```
around [here](https://github.com/snakemake/snakemake/blob/223bcc52d058e9704e69dac65c101ea1b18f3361/snakemake/remote/GS.py#L64). Then what needs to be done is reproducing the error, namely running the first two lines that cause the retry to be triggered in the first place: https://github.com/snakemake/snakemake/blob/223bcc52d058e9704e69dac65c101ea1b18f3361/snakemake/remote/GS.py#L67-L69

Then what we would want to try are the following:

1. First try the function [blob.download_to_filename](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.download_to_filename) as that doesn't seem to be deprecated.
2. If that doesn't work, try disabling the check for the download_from_file command (it looks like you can set checksum to None) and then run the rest of the function to see if the crc32c matches. It could be that just disabling this first check (and keeping our second, working check) does the trick.
3. If that doesn't work, try downloads using the same method between different file types and sizes, in case it's related to that.

What we don't want to do is just add the exception to be retried, because there might be something wrong with using this function in the first place. So TLDR: if you can give me something to reproduce the error, I can do all of the above. If not, it will be up to you @eric-czech to try these things, and we can walk through the above debugging together.

**Comment by eric-czech** [comment]
> The first would be to give me a way to reproduce the error - @eric-czech is the storage / workflow public so I could run and reproduce?

Technically yes (https://github.com/related-sciences/ukb-gwas-pipeline-nealelab), but this only occurs when downloading large files in fairly expensive workflows.  I'm not sure how to reproduce it since the same snakemake step will work 9 times out of 10.

> Then what needs to be done is reproducing the error

I've resorted to retrying whole tasks when they fail like this which happens to be a good workaround here since these failures happen early.  Sorry, but I don't plan on setting up a development environment and trying to debug this myself.

I thought it would be pretty straightforward to trace `google.resumable_media.common.DataCorruption` from the bottom of that stack and see why it isn't caught like the other checksum errors that are supposed to trigger a retry.  Maybe I missed something?

**Comment by vsoch** [comment]
> I thought it would be pretty straightforward to trace google.resumable_media.common.DataCorruption from the bottom of that stack and see why it isn't caught like the other checksum errors that are supposed to trigger a retry. Maybe I missed something?

Yes, we could easily put that particular exception into the retry, but I think it's important to understand why it's happening - just having it be an exception would be akin to applying a bandaid that hides the problem without fixing it. If the function is deprecated, possibly we need to update it to download_to_filename. If it's related to the files being too big / of a particular type (for example I saw issues that raised this exception because of an improperly set content header) then we would need to fix that.

@johanneskoester how do you suggest that we proceed? I don't know how to work on this if I can't reproduce it, and the submitting user doesn't want to.

**Comment by eric-czech** [comment]
> If the function is deprecated, possibly we need to update it to download_to_filename

👍 

> If it's related to the files being too big / of a particular type (for example I saw issues that raised this exception because of an improperly set content header)

FWIW, these files are between 40 and 200 GB in size.  I've seen no obvious correlation between these errors and the sizes within that range though.

**Comment by vsoch** [comment]
What doesn't make sense is that it would try to calculate a checksum during the streamed download. Reading this:

> checksum (str) – (Optional) The type of checksum to compute to verify the integrity of the object. If the upload is completed in a single request, the checksum will be entirely precomputed and the remote server will handle verification and error handling. If the upload is too large and must be transmitted in multiple requests, the checksum will be incrementally computed and the client will handle verification and error handling, raising google.resumable_media.common.DataCorruption on a mismatch and attempting to delete the corrupted file. Supported values are “md5”, “crc32c” and None. The default is None.

I think what is probably happening is that the checksum is being computed at increments, and there is something buggy going on there. I think we could try to just do download_to_file with checksum = None, and then download_to_filename (not deprecated) also with checksum = None to essentially disable this extra check. @eric-czech since I can't reproduce the error, how can I help to make this easy for you to test?

**Comment by vsoch** [comment]
@johanneskoester or @eric-czech do you have any huge objects that you could share, and we can put into snakemake-testing and I can try to reproduce the checksum issue? That might be the easiest way to go about doing this!

**Comment by eric-czech** [comment]
> do you have any huge objects that you could share, and we can put into snakemake-testing and I can try to reproduce the checksum issue?

Hm, here are a couple large files accessible without requester pays:

```
gs://gcp-public-data--gnomad/release/3.1/vcf/genomes/gnomad.genomes.v3.1.hgdp_1kg_subset.chr1.vcf.bgz # 272GB
gs://gcp-public-data--gnomad/release/3.1/vcf/genomes/gnomad.genomes.v3.1.hgdp_1kg_subset.chr22.vcf.bgz # 58GB
```

The size of the files would steadily decrease as you change the N in "chrN" to anything between 1 and 22.  

I can't share the exact files I was using unfortunately but these are very similar.

**Comment by johanneskoester** [comment]
trying with these files sounds like a good plan. Thank you for looking into this @eric-czech and @vsoch.

**Comment by vsoch** [comment]
Okay, here is a record of what I'm doing so it might be reproduced in the future. I first created an instance on the snakemake-testing account (I didn't have enough storage locally to test this!) with ubuntu 18.04 and anaconda3 for the conda environment. I added the conda environment to my path, installed ipython, and then cloned snakamake:

```bash
git clone https://github.com/snakemake/snakemake
cd snakemake
pip install -e .[google-cloud]
```
And then started an interactive ipython session. I basically needed to create an anonymous client to download the file (the authenticated one gave me permissions errors)

```python
from snakemake.remote.GS import *
client = storage.Client.create_anonymous_client()
```

and then create a handle to the bucket and blob provided above (I chose the larger of the two)

```python
bucket = client.bucket('gcp-public-data--gnomad')
blob = bucket.blob('release/3.1/vcf/genomes/gnomad.genomes.v3.1.hgdp_1kg_subset.chr1.vcf.bgz')

blob
# <Blob: gcp-public-data--gnomad, release/3.1/vcf/genomes/gnomad.genomes.v3.1.hgdp_1kg_subset.chr1.vcf.bgz, None>
```
And then use the same method to download the file - this is where the error was being triggered:

```python
filename = '/tmp/blob.vcf.bgz'

with open(filename, "wb") as blob_file:
    parser = Crc32cCalculator(blob_file)
    blob.download_to_file(parser)
os.sync()
```
and I'm letting this run to see if it triggers the error. Hopefully I won't get disconnected from the terminal, it's a fairly large / long download.

**Comment by vsoch** [comment]
okay I've done this twice now, and unable to trigger any error. Does your server have a bad internet connection? I'm not sure I can reproduce that on Google cloud :)

**Comment by vsoch** [comment]
@eric-czech I'd really like you to try this just setting checksum=None for the function. If you don't want to add this variable to your snakemake install, if I create a branch for you with the variable added would you be willing to test it?

**Comment by eric-czech** [comment]
> okay I've done this twice now, and unable to trigger any error. Does your server have a bad internet connection? 

Not really, I'm using standard reserved instances in GCP's premium network tier.  I'd be surprised if you were able to get it to happen in only trying it twice.  I had downloads like this running in kubernetes clusters and I get the sense that the failure rate is somewhere between 1/10 and 1/100.  It's definitely not easy to reproduce but with a big enough cluster and enough files, it happens often enough to be a minor problem.  

> @eric-czech I'd really like you to try this just setting checksum=None for the function. If you don't want to add this variable to your snakemake install, if I create a branch for you with the variable added would you be willing to test it?

I won't be able to, sorry.  Unfortunately I won't need to run that same workflow for a while since using "--restart-times" as the nuclear option was a fine workaround.  Otherwise, I had be happy to patch that in and see what happens.

**Comment by vsoch** [comment]
Ok, well then I think it’s probably best to pick up on this when you return to running the workflow again, or another user reports the error.

**Comment by johanneskoester** [comment]
@vsoch we could also ask google for debugging this. Did I understand right that you rather expect the bug to be within the google storage API?

**Comment by vsoch** [comment]
Yes the exception comes from blob.download_to_file().

**Comment by johanneskoester** [comment]
ok. @moschetti may I ask you to have a look at this? We think that we have triggered a bug in the google storage Python API, however, it occurs rarely (between 1/10 to 1/100 of long downloads). Hence, we and the reporter @eric-czech are unable to test this without wasting lots of credits. Maybe this is a known issue, or the storage API team could try to test this directly?

**Comment by moschetti** [comment]
I'll follow up on this

**Comment by johanneskoester** [comment]
@hnawar can you have a look into this? Is it maybe reasonable to just add that exception [here](https://github.com/snakemake/snakemake/blob/main/snakemake/remote/GS.py#L30)? My question would however be why all these cases are not considered to be transient errors anyway? Seems cumbersome to keep track of new exceptions to occur and on which one would want to just retry.
