### ISSUE TITLE
GroupJob fails with preemptible cloud VMs

### ISSUE THREAD

**Issue by simone-pignotti** [snakemake/snakemake#793]
**Snakemake version**
5.30.1

**Describe the bug**
Grouped jobs raise the following exception when setting the `--preemption-default` cmd line option with `--google-lifesciences` executor.

**Logs**
```
Traceback (most recent call last):
  File "/Users/simonepignotti/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 687, in snakemake
    success = workflow.execute(
  File "/Users/simonepignotti/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1005, in execute
    success = scheduler.schedule()
  File "/Users/simonepignotti/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 489, in schedule
    self.run(runjobs)
  File "/Users/simonepignotti/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 500, in run
    executor.run_jobs(
  File "/Users/simonepignotti/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 131, in run_jobs
    self.run(
  File "/Users/simonepignotti/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 789, in run
    pipeline = self._generate_pipeline(job)
  File "/Users/simonepignotti/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 761, in _generate_pipeline
    resources = self._generate_job_resources(job)
  File "/Users/simonepignotti/.conda/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 516, in _generate_job_resources
    "preemptible": job.rule.name in self.preemptible_rules,
AttributeError: 'GroupJob' object has no attribute 'rule'
```

**Comment by thouis** [comment]
This might be an easy fix.  I'm using this workaround for this line

`"preemptible": all([(name in self.preemptible_rules) for name in job.rules])`

at this line:
https://github.com/snakemake/snakemake/blob/main/snakemake/executors/google_lifesciences.py#L519
