### ISSUE TITLE
Jobs duplicated

### ISSUE THREAD

**Issue by cgr71ii** [snakemake/snakemake#806]
**Snakemake version**
5.30.2

**Describe the bug**
Rules and checkpoints seem to be being duplicated with the same ID. I have checked out with 5.26.1, which is the latest stable version which is not affected by #727 (at least that is the version I am using in the project where Snakemake is being used, which is [Bitextor](https://github.com/bitextor/bitextor/tree/snake_performance)). I am creating a new issue because I am not really sure that this situation is the same case that #727, but since this last update claims to solve #727, both problems might be related.

When jobs are duplicated, I have observed that input files are removed because "might be corrupted" according to Snakemake, and when the duplicated job attempts to retrieve the file, it does not exist anymore, so it throws `FileNotFoundError` exception.

**Logs**
Command used: `snakemake -s files/tmp/min_snakemake_5_30_2/Snakefile --config src_lang="es" trg_lang="en" -j 4`

When is working as expected, with version 5.26.1, the log is:
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	corpus
	2	shard
	4

[Wed Dec 16 11:43:06 2020]
checkpoint shard:
    output: data/batches.es
    jobid: 2
    wildcards: lang=es
Downstream jobs will be updated after completion.


[Wed Dec 16 11:43:06 2020]
checkpoint shard:
    output: data/batches.en
    jobid: 3
    wildcards: lang=en
Downstream jobs will be updated after completion.

Updating job 1 (corpus).
Updating job 0 (all).
[Wed Dec 16 11:43:42 2020]
Finished job 2.
1 of 4 steps (25%) done
Updating job 5 (corpus).
Updating job 4 (all).
[Wed Dec 16 11:44:06 2020]
Finished job 3.
2 of 40 steps (5%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/0/0/text, data/en/0/1/text
    output: data/es_en/0.0_1.combined
    jobid: 9
    wildcards: src_lang=es, trg_lang=en, shard=0, src_batch=0, trg_batch=1


[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/1/0/text, data/en/1/0/text
    output: data/es_en/1.0_0.combined
    jobid: 17
    wildcards: src_lang=es, trg_lang=en, shard=1, src_batch=0, trg_batch=0

[Wed Dec 16 11:44:06 2020]
Finished job 9.
3 of 40 steps (8%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/1/2/text, data/en/1/1/text
    output: data/es_en/1.2_1.combined
    jobid: 24
    wildcards: src_lang=es, trg_lang=en, shard=1, src_batch=2, trg_batch=1


[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/2/2/text, data/en/2/0/text
    output: data/es_en/2.2_0.combined
    jobid: 32
    wildcards: src_lang=es, trg_lang=en, shard=2, src_batch=2, trg_batch=0

[Wed Dec 16 11:44:06 2020]
Finished job 17.
4 of 40 steps (10%) done
[Wed Dec 16 11:44:06 2020]
Finished job 24.
5 of 40 steps (12%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/3/1/text, data/en/3/1/text
    output: data/es_en/3.1_1.combined
    jobid: 39
    wildcards: src_lang=es, trg_lang=en, shard=3, src_batch=1, trg_batch=1

[Wed Dec 16 11:44:06 2020]
Finished job 32.
6 of 40 steps (15%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/0/0/text, data/en/0/2/text
    output: data/es_en/0.0_2.combined
    jobid: 10
    wildcards: src_lang=es, trg_lang=en, shard=0, src_batch=0, trg_batch=2


[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/1/0/text, data/en/1/1/text
    output: data/es_en/1.0_1.combined
    jobid: 18
    wildcards: src_lang=es, trg_lang=en, shard=1, src_batch=0, trg_batch=1

[Wed Dec 16 11:44:06 2020]
Finished job 39.
7 of 40 steps (18%) done
[Wed Dec 16 11:44:06 2020]
Finished job 10.
8 of 40 steps (20%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/1/2/text, data/en/1/2/text
    output: data/es_en/1.2_2.combined
    jobid: 25
    wildcards: src_lang=es, trg_lang=en, shard=1, src_batch=2, trg_batch=2


[Wed Dec 16 11:44:06 2020]
[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/2/2/text, data/en/2/1/text
    output: data/es_en/2.2_1.combined
    jobid: 33
    wildcards: src_lang=es, trg_lang=en, shard=2, src_batch=2, trg_batch=1
Finished job 18.

9 of 40 steps (22%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/3/1/text, data/en/3/2/text
    output: data/es_en/3.1_2.combined
    jobid: 40
    wildcards: src_lang=es, trg_lang=en, shard=3, src_batch=1, trg_batch=2

[Wed Dec 16 11:44:06 2020]
Finished job 25.
10 of 40 steps (25%) done
[Wed Dec 16 11:44:06 2020]
Finished job 33.
11 of 40 steps (28%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/0/1/text, data/en/0/0/text
    output: data/es_en/0.1_0.combined
    jobid: 11
    wildcards: src_lang=es, trg_lang=en, shard=0, src_batch=1, trg_batch=0

[Wed Dec 16 11:44:06 2020]
Finished job 40.
12 of 40 steps (30%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/1/0/text, data/en/1/2/text
    output: data/es_en/1.0_2.combined
    jobid: 19
    wildcards: src_lang=es, trg_lang=en, shard=1, src_batch=0, trg_batch=2


[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/2/0/text, data/en/2/0/text
    output: data/es_en/2.0_0.combined
    jobid: 26
    wildcards: src_lang=es, trg_lang=en, shard=2, src_batch=0, trg_batch=0

[Wed Dec 16 11:44:06 2020]
Finished job 11.
13 of 40 steps (32%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/2/2/text, data/en/2/2/text
    output: data/es_en/2.2_2.combined
    jobid: 34
    wildcards: src_lang=es, trg_lang=en, shard=2, src_batch=2, trg_batch=2

[Wed Dec 16 11:44:06 2020]
Finished job 19.

[Wed Dec 16 11:44:06 2020]
14 of 40 steps (35%) done
rule combine:
    input: data/es/3/2/text, data/en/3/0/text
    output: data/es_en/3.2_0.combined
    jobid: 41
    wildcards: src_lang=es, trg_lang=en, shard=3, src_batch=2, trg_batch=0

[Wed Dec 16 11:44:06 2020]
Finished job 26.
15 of 40 steps (38%) done
[Wed Dec 16 11:44:06 2020]
Finished job 34.
16 of 40 steps (40%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/0/1/text, data/en/0/1/text
    output: data/es_en/0.1_1.combined
    jobid: 12
    wildcards: src_lang=es, trg_lang=en, shard=0, src_batch=1, trg_batch=1


[Wed Dec 16 11:44:06 2020]
[Wed Dec 16 11:44:06 2020]
Finished job 41.
rule combine:
    input: data/es/1/1/text, data/en/1/0/text
    output: data/es_en/1.1_0.combined
    jobid: 20
    wildcards: src_lang=es, trg_lang=en, shard=1, src_batch=1, trg_batch=0
17 of 40 steps (42%) done


[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/2/0/text, data/en/2/1/text
    output: data/es_en/2.0_1.combined
    jobid: 27
    wildcards: src_lang=es, trg_lang=en, shard=2, src_batch=0, trg_batch=1

[Wed Dec 16 11:44:06 2020]
Finished job 12.
18 of 40 steps (45%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/3/0/text, data/en/3/0/text
    output: data/es_en/3.0_0.combined
    jobid: 35
    wildcards: src_lang=es, trg_lang=en, shard=3, src_batch=0, trg_batch=0
[Wed Dec 16 11:44:06 2020]

Finished job 20.
19 of 40 steps (48%) done
[Wed Dec 16 11:44:06 2020]

Finished job 27.
[Wed Dec 16 11:44:06 2020]
20 of 40 steps (50%) done
rule combine:
    input: data/es/3/2/text, data/en/3/1/text
    output: data/es_en/3.2_1.combined
    jobid: 42
    wildcards: src_lang=es, trg_lang=en, shard=3, src_batch=2, trg_batch=1


[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/0/1/text, data/en/0/2/text
    output: data/es_en/0.1_2.combined
    jobid: 13
    wildcards: src_lang=es, trg_lang=en, shard=0, src_batch=1, trg_batch=2

[Wed Dec 16 11:44:06 2020]
Finished job 35.
21 of 40 steps (52%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/1/1/text, data/en/1/1/text
    output: data/es_en/1.1_1.combined
    jobid: 21
    wildcards: src_lang=es, trg_lang=en, shard=1, src_batch=1, trg_batch=1

[Wed Dec 16 11:44:06 2020]
Finished job 42.
22 of 40 steps (55%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/2/0/text, data/en/2/2/text
    output: data/es_en/2.0_2.combined
    jobid: 28
    wildcards: src_lang=es, trg_lang=en, shard=2, src_batch=0, trg_batch=2


[Wed Dec 16 11:44:06 2020]
[Wed Dec 16 11:44:06 2020]
Finished job 13.
rule combine:
    input: data/es/3/0/text, data/en/3/1/text
    output: data/es_en/3.0_1.combined
    jobid: 36
    wildcards: src_lang=es, trg_lang=en, shard=3, src_batch=0, trg_batch=1
23 of 40 steps (57%) done

[Wed Dec 16 11:44:06 2020]
Finished job 21.
24 of 40 steps (60%) done
[Wed Dec 16 11:44:06 2020]
Finished job 28.
25 of 40 steps (62%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/3/2/text, data/en/3/2/text
    output: data/es_en/3.2_2.combined
    jobid: 43
    wildcards: src_lang=es, trg_lang=en, shard=3, src_batch=2, trg_batch=2


[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/0/2/text, data/en/0/0/text
    output: data/es_en/0.2_0.combined
    jobid: 14
    wildcards: src_lang=es, trg_lang=en, shard=0, src_batch=2, trg_batch=0

[Wed Dec 16 11:44:06 2020]
Finished job 36.
26 of 40 steps (65%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/1/1/text, data/en/1/2/text
    output: data/es_en/1.1_2.combined
    jobid: 22
    wildcards: src_lang=es, trg_lang=en, shard=1, src_batch=1, trg_batch=2


[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/2/1/text, data/en/2/0/text
    output: data/es_en/2.1_0.combined
    jobid: 29
    wildcards: src_lang=es, trg_lang=en, shard=2, src_batch=1, trg_batch=0

[Wed Dec 16 11:44:06 2020]
Finished job 14.
27 of 40 steps (68%) done
[Wed Dec 16 11:44:06 2020]
Finished job 43.
28 of 40 steps (70%) done
[Wed Dec 16 11:44:06 2020]
Finished job 22.
29 of 40 steps (72%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/3/0/text, data/en/3/2/text
    output: data/es_en/3.0_2.combined
    jobid: 37
    wildcards: src_lang=es, trg_lang=en, shard=3, src_batch=0, trg_batch=2

[Wed Dec 16 11:44:06 2020]
Finished job 29.
30 of 40 steps (75%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/0/0/text, data/en/0/0/text
    output: data/es_en/0.0_0.combined
    jobid: 8
    wildcards: src_lang=es, trg_lang=en, shard=0, src_batch=0, trg_batch=0


[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/0/2/text, data/en/0/1/text
    output: data/es_en/0.2_1.combined
    jobid: 15
    wildcards: src_lang=es, trg_lang=en, shard=0, src_batch=2, trg_batch=1

[Wed Dec 16 11:44:06 2020]
Finished job 37.
31 of 40 steps (78%) done
[Wed Dec 16 11:44:06 2020]
Finished job 8.
32 of 40 steps (80%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/1/2/text, data/en/1/0/text
    output: data/es_en/1.2_0.combined
    jobid: 23
    wildcards: src_lang=es, trg_lang=en, shard=1, src_batch=2, trg_batch=0


[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/2/1/text, data/en/2/1/text
    output: data/es_en/2.1_1.combined
    jobid: 30
    wildcards: src_lang=es, trg_lang=en, shard=2, src_batch=1, trg_batch=1

[Wed Dec 16 11:44:06 2020]
Finished job 15.
33 of 40 steps (82%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/3/1/text, data/en/3/0/text
    output: data/es_en/3.1_0.combined
    jobid: 38
    wildcards: src_lang=es, trg_lang=en, shard=3, src_batch=1, trg_batch=0
[Wed Dec 16 11:44:06 2020]

Finished job 23.
34 of 40 steps (85%) done

[Wed Dec 16 11:44:06 2020]
rule combine:
    input: data/es/0/2/text, data/en/0/2/text
    output: data/es_en/0.2_2.combined
    jobid: 16
    wildcards: src_lang=es, trg_lang=en, shard=0, src_batch=2, trg_batch=2

[Wed Dec 16 11:44:06 2020]

Finished job 30.
[Wed Dec 16 11:44:06 2020]
35 of 40 steps (88%) done
rule combine:
    input: data/es/2/1/text, data/en/2/2/text
    output: data/es_en/2.1_2.combined
    jobid: 31
    wildcards: src_lang=es, trg_lang=en, shard=2, src_batch=1, trg_batch=2

[Wed Dec 16 11:44:06 2020]
Finished job 38.
36 of 40 steps (90%) done
[Wed Dec 16 11:44:06 2020]
Finished job 16.
37 of 40 steps (92%) done
[Wed Dec 16 11:44:06 2020]
Finished job 31.
38 of 40 steps (95%) done

[Wed Dec 16 11:44:06 2020]
rule corpus:
    input: data/es_en/0.0_0.combined, data/es_en/0.0_1.combined, data/es_en/0.0_2.combined, data/es_en/0.1_0.combined, data/es_en/0.1_1.combined, data/es_en/0.1_2.combined, data/es_en/0.2_0.combined, data/es_en/0.2_1.combined, data/es_en/0.2_2.combined, data/es_en/1.0_0.combined, data/es_en/1.0_1.combined, data/es_en/1.0_2.combined, data/es_en/1.1_0.combined, data/es_en/1.1_1.combined, data/es_en/1.1_2.combined, data/es_en/1.2_0.combined, data/es_en/1.2_1.combined, data/es_en/1.2_2.combined, data/es_en/2.0_0.combined, data/es_en/2.0_1.combined, data/es_en/2.0_2.combined, data/es_en/2.1_0.combined, data/es_en/2.1_1.combined, data/es_en/2.1_2.combined, data/es_en/2.2_0.combined, data/es_en/2.2_1.combined, data/es_en/2.2_2.combined, data/es_en/3.0_0.combined, data/es_en/3.0_1.combined, data/es_en/3.0_2.combined, data/es_en/3.1_0.combined, data/es_en/3.1_1.combined, data/es_en/3.1_2.combined, data/es_en/3.2_0.combined, data/es_en/3.2_1.combined, data/es_en/3.2_2.combined
    output: data/corpus.txt
    jobid: 7

[Wed Dec 16 11:44:06 2020]
Finished job 7.
39 of 40 steps (98%) done

[Wed Dec 16 11:44:06 2020]
localrule all:
    input: data/corpus.txt, data/batches.es, data/batches.en
    jobid: 6

[Wed Dec 16 11:44:06 2020]
Finished job 6.
40 of 40 steps (100%) done
```

When using 5.30.2:
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	corpus
	2	shard
	4

[Wed Dec 16 11:46:00 2020]
checkpoint shard:
    output: data/batches.es
    jobid: 2
    wildcards: lang=es
Downstream jobs will be updated after completion.


[Wed Dec 16 11:46:00 2020]
checkpoint shard:
    output: data/batches.en
    jobid: 3
    wildcards: lang=en
Downstream jobs will be updated after completion.

Updating job 1 (corpus).
Updating job 0 (all).
[Wed Dec 16 11:46:36 2020]
Finished job 2.
1 of 4 steps (25%) done

[Wed Dec 16 11:46:36 2020]
checkpoint shard:
    output: data/batches.en
    jobid: 3
    wildcards: lang=en
Downstream jobs will be updated after completion.

Updating job 4 (corpus).
Updating job 5 (all).
[Wed Dec 16 11:47:00 2020]
Finished job 3.
2 of 40 steps (5%) done
Traceback (most recent call last):
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/__init__.py", line 687, in snakemake
    success = workflow.execute(
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/workflow.py", line 1006, in execute
    success = scheduler.schedule()
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/scheduler.py", line 470, in schedule
    run = self.job_selector(needrun)
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/scheduler.py", line 764, in job_selector_greedy
    c = list(map(self.job_reward, jobs))  # job rewards
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/scheduler.py", line 847, in job_reward
    input_size = job.inputsize
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/jobs.py", line 378, in inputsize
    self._inputsize = sum(f.size for f in self.input)
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/jobs.py", line 378, in <genexpr>
    self._inputsize = sum(f.size for f in self.input)
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/io.py", line 242, in wrapper
    return func(self, *args, **kwargs)
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/io.py", line 257, in wrapper
    return func(self, *args, **kwargs)
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/io.py", line 556, in size
    return self.size_local
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/io.py", line 561, in size_local
    self.check_broken_symlink()
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/io.py", line 566, in check_broken_symlink
    if not self.exists_local and os.lstat(self.file):
FileNotFoundError: [Errno 2] No such file or directory: 'data/corpus.txt'
[Wed Dec 16 11:47:36 2020]
Error in rule shard:
    jobid: 3
    output: data/batches.en
    shell:
                             
        for i in $(seq 0 $(( 2 % 5 + 1))); do # 0 .. 3 -> 4
            for j in $(seq 0 $(( 1 % 2 + 1))); do # 0 .. 2 -> 3
                mkdir -p data/en/$i/$j
                echo 'hello en' > data/en/$i/$j/text
                if [[ "en" == "es" ]]; then
                    sleep 3
                else
                    sleep 5
                fi
            done
        done
        ls -d data/en/*/* > data/batches.en  
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job shard since they might be corrupted:
data/batches.en
exception calling callback for <Future at 0x7f745430c3a0 state=finished raised RuleException>
Traceback (most recent call last):
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2318, in run_wrapper
    run(
  File "/home/cristian/Documentos/bitextor/files/tmp/min_snakemake_5_30_2/Snakefile", line 37, in __rule_shard
    checkpoints.shard.get(lang=trg_lang).output[0].open() as trg_f:
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/shell.py", line 202, in __new__
    del cls._processes[jobid]
KeyError: 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 560, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
    run_func(*args)
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2349, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: KeyError in line 11 of /home/cristian/Documentos/bitextor/files/tmp/min_snakemake_5_30_2/Snakefile:
3
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2318, in run_wrapper
  File "/home/cristian/Documentos/bitextor/files/tmp/min_snakemake_5_30_2/Snakefile", line 11, in __rule_shard

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 572, in _callback
    error_callback(job)
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/scheduler.py", line 579, in _error
    self._handle_error(job)
  File "/home/cristian/Documentos/bitextor/files/tmp/env_snake_performance_snakemake_fix_checkpoints/lib/python3.8/site-packages/snakemake/scheduler.py", line 589, in _handle_error
    self.running.remove(job)
KeyError: shard
```

**Minimal example**
```
from itertools import product

src_lang = config['src_lang']
trg_lang = config['trg_lang']

rule all:                        
    input: "data/corpus.txt", f"data/batches.{src_lang}", f"data/batches.{trg_lang}"

checkpoint shard:                    
    output: "data/batches.{lang}"    
    shell: '''                     
        for i in $(seq 0 $(( 2 % 5 + 1))); do # 0 .. 3 -> 4
            for j in $(seq 0 $(( 1 % 2 + 1))); do # 0 .. 2 -> 3
                mkdir -p data/{wildcards.lang}/$i/$j
                echo 'hello {wildcards.lang}' > data/{wildcards.lang}/$i/$j/text
                if [[ "{wildcards.lang}" == "{src_lang}" ]]; then
                    sleep 3
                else
                    sleep 5
                fi
            done
        done
        ls -d data/{wildcards.lang}/*/* > {output}  
        '''
                                                                
rule combine:                                              
    input:                                                
        l1='data/{src_lang}/{shard}/{src_batch}/text',
        l2='data/{trg_lang}/{shard}/{trg_batch}/text'
    output: 'data/{src_lang}_{trg_lang}/{shard}.{src_batch}_{trg_batch}.combined'
    shell: ''' paste {input.l1} {input.l2} > {output} '''
                                                                                                
def get_batches_pairs(src_lang, trg_lang):                                 
    src_batches = []      
    trg_batches = []                                        
    with checkpoints.shard.get(lang=src_lang).output[0].open() as src_f, \
            checkpoints.shard.get(lang=trg_lang).output[0].open() as trg_f:
        for line in src_f:                      
            src_batches.append(line.strip().split('/')[-2:])                                                                                
        for line in trg_f:
           trg_batches.append(line.strip().split('/')[-2:])
    iterator = product(src_batches, trg_batches)
    return [(src_shard, (src_batch, trg_batch)) for ((src_shard, src_batch), (trg_shard, trg_batch)) in iterator if src_shard == trg_shard]

rule corpus:           
    input: lambda wildcards: [f'data/{src_lang}_{trg_lang}/{shard}.{src_batch}_{trg_batch}.combined' for (shard, (src_batch, trg_batch)) in get_batches_pairs(src_lang, trg_lang)]
    output: 'data/corpus.txt'
    shell: ''' cat {input} > {output} '''
```

**Additional context**
I was checking the last version in order to check out that #727 had been fixed.

**Comment by pb-cdunn** [comment]
(Posting to follow this ...)

**Comment by johanneskoester** [comment]
Thanks for reporting, may I ask you to try with latest master? I've spotted a potentially related bug that hopefully caused this behavior.

**Comment by cgr71ii** [comment]
No problem! So sorry to say, but still not working. `snakemake --version` -> `5.30.2+2.g24c2655d` and after running the minimal example posted above, the result is the same (`.snakefile` and previous output have been removed). I am not going to submit the output because it is exactly the same (checked out with `diff`; only dates and memory addrs differ).

**Comment by johanneskoester** [comment]
Thanks a lot for the minimal example, I have missed that before. I'll debug based on that now.

**Comment by johanneskoester** [comment]
PR #808 should finally provide a proper fix. Your minimal example is included as a testcase, thanks a lot!

**Comment by cgr71ii** [comment]
You are welcome! :) I have checked the pull request with the minimal example as well as a more complex Snakemake (the one i mentioned in the issue description) are working fine! It seems that #727 and this issue are solved now.

**Comment by johanneskoester** [comment]
thanks for checking!
