### ISSUE TITLE
No such file or directory: '/proc/24076/stat'

### ISSUE THREAD

**Issue by nick-youngblut** [snakemake/snakemake#83]
I'm running `snakemake 5.5.1` on a SGE cluster, and I'm getting a lot of the following errors:

```
Exception in thread Thread-13461173:
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/psutil/_common.py", line 342, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/snakemake/benchmark.py", line 108, in run
    self.function(*self.args, **self.kwargs)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/snakemake/benchmark.py", line 138, in _action
    self.work()
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/snakemake/benchmark.py", line 169, in work
    self._update_record()
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/snakemake/benchmark.py", line 186, in _update_record
    main = psutil.Process(self.pid)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/psutil/__init__.py", line 446, in __init__
    self._init(pid)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/psutil/__init__.py", line 473, in _init
    self.create_time()
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/psutil/__init__.py", line 823, in create_time
    self._create_time = self._proc.create_time()
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/psutil/_pslinux.py", line 1507, in wrapper
    return fun(self, *args, **kwargs)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/psutil/_pslinux.py", line 1717, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/psutil/_pslinux.py", line 1507, in wrapper
    return fun(self, *args, **kwargs)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/psutil/_common.py", line 345, in wrapper
    return fun(self)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/psutil/_pslinux.py", line 1553, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/snakemake_dev/lib/python3.6/site-packages/psutil/_common.py", line 587, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/24076/stat'
```

The pipeline is still running even though these errors have been occurring regularly during the ~7 day run, so the errors are not causing the snakemake job to die. 

It appears that `_parse_stat_file()` can't open the stat file. Any idea on what may be causing this? I am running 200 parallel jobs, so maybe it's some sort of latency issue?

**Comment by johanneskoester** [comment]
I think this might be fixed by now. We had some significant improvements in the benchmarking lately. Please try with the latest release and reopen if the problem persists.
