### ISSUE TITLE
WebDAV support broken

### ISSUE THREAD

**Issue by MartinHammarstedt** [snakemake/snakemake#844]
**Snakemake version**
5.32.0 (or any other version after 5.26.1)

**Describe the bug**
WebDAV support seems to be broken since 5.27.2. It works in 5.26.1, but in any version I've tried since then I get a `RuntimeError: Cannot run the event loop while another loop is running`.

**Logs**
<details>
  <summary>Full traceback</summary>

```Building DAG of jobs...
Traceback (most recent call last):
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/__init__.py", line 668, in snakemake
    success = workflow.execute(
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/workflow.py", line 696, in execute
    dag.init()
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/dag.py", line 188, in init
    self.update_needrun(create_inventory=True)
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/dag.py", line 883, in update_needrun
    self.workflow.iocache.mtime_inventory(self.jobs)
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/io.py", line 137, in mtime_inventory
    asyncio.run(self._mtime_inventory(jobs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/io.py", line 170, in _mtime_inventory
    await asyncio.gather(*tasks)
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/io.py", line 154, in worker
    raise e
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/io.py", line 150, in worker
    self.mtime[item] = await self.collect_mtime(item)
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/io.py", line 173, in collect_mtime
    return path.mtime_uncached
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/io.py", line 477, in mtime_uncached
    mtime_remote = self.remote_object.mtime() if self.is_remote else None
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/remote/webdav.py", line 121, in mtime
    if self.exists():
  File "/home/martin/webdavtest/.venv/lib/python3.8/site-packages/snakemake/remote/webdav.py", line 118, in exists
    return self.loop.run_until_complete(self.conn.exists(self.webdav_file))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 554, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
sys:1: RuntimeWarning: coroutine 'Client.exists' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f036665feb0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f03663b48e0>, 3809364.850832218)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f036665f8b0>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f03663b20a0>
transport: <_SelectorSocketTransport closing fd=10>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 908, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 685, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 914, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 709, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 721, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
</details>

**Minimal example**
I'm using the following (slightly modified) example from the documentation:
```from snakemake.remote import webdav

webdav = webdav.RemoteProvider(username="test", password="test", protocol="https://")

rule a:
    input:
        webdav.remote("example.com/path/document.xml")
    output:
        "document.xml"
    shell:
        "cp {input} {output}"
```

**Additional context**
Python version 3.8.5 on Ubuntu 20.04.1.

**Comment by spaenigs** [comment]
In case anyone has the same error, solve it as follows:

```
from snakemake.remote import webdav

import nest_asyncio
nest_asyncio.apply()
```

Credits to https://stackoverflow.com/a/61847214/4697995
