### ISSUE TITLE
ModuleNotFoundError: No module named 'tes'

### ISSUE THREAD

**Issue by superbsky** [snakemake/snakemake#901]
**Snakemake version**
snakemake --version
6.0.0

**Describe the bug**
I try to test a new GA4GH TES submitting feature from the fresh snakemake installation via conda but getting "ModuleNotFoundError: No module named 'tes'" error

**Logs**
Building DAG of jobs...
Traceback (most recent call last):
  File "/home/genx/anaconda3/envs/snakemake-latest/lib/python3.9/site-packages/snakemake/__init__.py", line 694, in snakemake
    success = workflow.execute(
  File "/home/genx/anaconda3/envs/snakemake-latest/lib/python3.9/site-packages/snakemake/workflow.py", line 917, in execute
    scheduler = JobScheduler(
  File "/home/genx/anaconda3/envs/snakemake-latest/lib/python3.9/site-packages/snakemake/scheduler.py", line 328, in __init__
    self._executor = TaskExecutionServiceExecutor(
  File "/home/genx/anaconda3/envs/snakemake-latest/lib/python3.9/site-packages/snakemake/executors/ga4gh_tes.py", line 40, in __init__
    import tes
ModuleNotFoundError: No module named 'tes'

**Minimal example**
snakemake --cores all --use-conda --use-singularity --singularity-prefix=/media --singularity-args="-B /media:/media" -p all --tes http://40.69.200.138:8000/ --envvars CONDA_PKGS_DIRS CONDA_ENVS_PATH --conda-prefix $CONDA_ENVS_PATH

**Additional context**
uname -a
Linux genx 5.4.0-1023-azure #23~18.04.1-Ubuntu SMP Thu Aug 20 14:46:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by superbsky** [comment]
I am having some problems installing this package using conda since it is required python-dateutil 2.6.1 (2.8.1 installed) which is required python2 👎 as a workaround I used pip3.

The task was successfully submitted using Funnel:

![image](https://user-images.githubusercontent.com/19895289/109993084-fd782d80-7d1c-11eb-902e-b7ae58cd31ec.png)

Thank you!

Not quite sure how to add dependencies to the Snakemake itself. There are mentions only for tests and docs in [contributing.rst](https://github.com/snakemake/snakemake/blob/master/docs/project_info/contributing.rst).

**Comment by uniqueg** [comment]
Cool, thanks for the feedback and glad it worked :)

I'll see what I can do about convincing `py-tes` maintainers to bump dependencies to something less ancient 🙈

**Comment by schnea** [comment]
Closing as py-tes no longer appears to be used in the codebase
