### ISSUE TITLE
--configfile flag is broken in combination with Kubernetes and GS buckets

### ISSUE THREAD

**Issue by TheBready** [snakemake/snakemake#914]
**Snakemake version**
- snakemake=6.0.5
- python-kubernetes=12.0.1

**Describe the bug**
#### *Excpected:*
Executing a Snakemake workflow using Kubernetes and GS buckets with --configfile.
Content of config file is available in snakemake workflow as config.

#### *Actual:*
Snakemake can't find the config file and is shutting down. It is working when providing the parameters with the --config flag.

**Logs**
<details>
  <summary>Snakemake log</summary>
  
```
Building DAG of jobs...
Unable to retrieve additional files from git. This is not a git repository.
Using shell: /usr/bin/bash
Provided cloud nodes: 1
Job counts:
        count   jobs
        1       all
        1       cat_dub
        1       fastqc
        3
Select jobs to execute...

[Sat Mar 13 14:48:46 2021]
rule cat_dub:
    input: bucket-name/path/to/some.fastq
    output:  bucket-name/output/sample.fastq,  bucket-name/output/somefile.txt
    jobid: 2


                cat  bucket-name/path/to/some.fastq >  bucket-name/output/sample.fastq
                touch  bucket-name/output/somefile.txt

Get status with:
kubectl describe pod snakejob-id
kubectl logs snakejob-id
[Sat Mar 13 14:48:56 2021]
Error in rule cat_dub:
    jobid: 2
    output:  bucket-name/output/sample.fastq,  bucket-name/output/somefile.txt
    shell:
        
                cat  bucket-name/path/to/some.fastq >  bucket-name/output/sample.fastq
                touch  bucket-name/output/somefile.txt

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    jobid: snakejob-id

For details, please issue:
kubectl describe pod snakejob-id
kubectl logs snakejob-id
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/user/kubertest/.snakemake/log/2021-03-13T144842.529963.snakemake.log
```
</details>

<details>
  <summary>Error message with kubectl logs {snakejob} </summary>
  
```
Traceback (most recent call last):
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/io.py", line 1564, in _load_configfile
    with open(configpath) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/kubertest/config.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/snakemake/bin/snakemake", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 2592, in main
    success = snakemake(
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 505, in snakemake
    overwrite_config.update(load_configfile(f))
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/io.py", line 1594, in load_configfile
    config = _load_configfile(configpath)
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/io.py", line 1589, in _load_configfile
    raise WorkflowError("{} file {} not found.".format(filetype, configpath))
snakemake.exceptions.WorkflowError: Config file /home/user/kubertest/config.yml not found.
```
</details>

**Minimal example**
<details>
  <summary>Snakefile</summary>
  
```
rule all:
        input:
                zip = "output/sample_fastqc.zip",
                html = "output/sample_fastqc.html"

rule cat_dub:
        input:
                a =  config['input'],
                c = config['random'],
        output:
                b = "output/sample.fastq" 
        threads: 1
        shell:
                """
                cat {input.a} > {output.b}
                touch {input.c}
                """

rule fastqc:
        input:
                a = rules.cat_dub.output.b
        output:
                zip = "output/sample_fastqc.zip",
                html = "output/sample_fastqc.html"
        threads: 1
        conda: "envs/fastqc.yml"
        shell:
                "fastqc {input.a} "
```
</details>

<details>
  <summary>config.yaml</summary>
  
```
input: 'path/to/some.fastq'
random: 'output/somefile.txt'
```
</details>
<details>
  <summary>envs/fastqc.yaml</summary>
  
```
name: fastqc
channels:
  - bioconda
dependencies:
  - fastqc
```
</details>

<details>
  <summary>Execute with --configfile flag -> failed </summary>
  
```
snakemake  --default-remote-provider 'GS' --default-remote-prefix 'bucket-name' --cores 1 --use-conda --kubernetes --configfile config.yml
```
</details>

<details>
  <summary>Execute with --config flag -> works</summary>
  
```
snakemake  --default-remote-provider 'GS' --default-remote-prefix 'bucket-name' --cores 1 --use-conda --kubernetes --config input="path/to/some.fastq" random="output/somefile.txt"
```
</details>

**Additional context**
It seems that snakemake is trying to read the config file in the Kubernetes pod, but it fails because it is not listed in the bucket or the pod. I would expect the same behavior from the --config and --configfile flag.

**Comment by nigiord** [comment]
I think this is related: I encountered the same issue with `--tibanna`. The file provided through `--configfile` is not uploaded as a workflow file, resulting in:
```shell
[…]
## Downloading workflow files
main workflow file: Snakefile
workflow files: ['Snakefile'] # Missing 'config-test.yaml' here
[…]
running snakemake all --snakefile Snakefile --force -j1 --keep-target-files --keep-remote --latency-wait 0 --scheduler ilp --attempt 1 --force-use-threads --max-inventory-time 0 --configfiles config-test.yaml --allowed-rules all --nocolor --notemp --no-hooks --nolock --use-conda in docker image snakemake/snakemake:v6.3.0...
[…]
FileNotFoundError: [Errno 2] No such file or directory: 'config-test.yaml'
```

**Comment by peter-fsdx** [comment]
Not sure if I should open a new issue or post in this one. Did anyone ever find a way to get this working on kubernetes? 

I am getting this error using `snakemake==7.12.1`. My job is failing if I use `--kubernetes` and `--configfile` but not if I use the `--config` flag. Error message is a little different and I can't find the pod logs (not sure the pod is starting)

**Logs**
```
Get status with:
kubectl describe pod snakejob-c3426f86-5dbc-58ab-925f-25e009e1838b
kubectl logs snakejob-c3426f86-5dbc-58ab-925f-25e009e1838b
[Wed Aug 24 15:58:05 2022]
Error in rule r1:
    jobid: 1
    output: mybucket/testfile.txt
    shell:
        echo config['test'] > mybucket/testfile.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    jobid: snakejob-c3426f86-5dbc-58ab-925f-25e009e1838b

Unknown pod snakejob-c3426f86-5dbc-58ab-925f-25e009e1838b. Has the pod been deleted manually?
```

**Minimal example**
command:
```
snakemake --default-remote-provider GS --default-remote-prefix mybucket --jobs 1 --kubernetes --configfile config.yaml
```

Snakefile:
```
# # Still fails using `--configfile` if I set config['test'] in the snakefile
# config["test"] = "hello

rule all:
    input:
        f = "testfile.txt"


rule r1:
    output: "testfile.txt"
    shell:
        "echo config['test'] > {output}"
```

config.yaml:
```
test: hello
```

**context**
* My one addition to this thread is that the job still fails with the `--configfile` flag even if I set `config["test"] = "hello"` directly at the top of the Snakefile.
* `config.yaml` is tracked in git if that matters

**Comment by peter-fsdx** [comment]
My workaround at the moment is to manually load the contents of the config at the top of my snakemake:
```
with open("config.yaml", "r") as f:
    config = yaml.safe_load(f)
```

**Comment by jacogasp** [comment]
Hello everybody,

thanks for highlighting this issue, I'm experiencing the exact same problem with `--kubernetes` and `--configfiles` using a bare metal cluster with a custom S3 implementation and previously to this thread I was not aware about the two conflicting flags.

@peter-fsdx's workaround about manually reading the yaml file works, thank you.
