### ISSUE TITLE
Regular SSL errors using Snakemake with Google Life Sciences Executor

### ISSUE THREAD

**Issue by mw55309** [snakemake/snakemake#983]
**Snakemake version**
Version 6.3.0

**Describe the bug**

When executing a Snakemake workflow using google life sciences executor, the first few jobs go through and then I get an SSL error. The exact error differs between runs but has been:

```
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2627)
```

or

```
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)
```

This has happened on TWO different submitter nodes, one the Google Cloud Shell, and the other a University Linux box.

Both submitted from conda envs that follow the tutorial (https://snakemake.readthedocs.io/en/stable/executor_tutorial/google_lifesciences.html)

**Logs**
There have been two different errors. The first one is more frequent:

```
$ snakemake  --google-lifesciences --default-remote-prefix dog_microbiome_updated_env  --preemption-default 10 --use-conda --cores 16
Preemptible instances are only available for the Google Life Sciences Executor.
['Ash_p1', 'Avalanche_p1']
Building DAG of jobs...
Using shell: /bin/bash
Job counts:
        count   jobs
        1       all
        2       combine
        44      download_and_trim
        2       megahit
        49
Select jobs to execute...

[Sun May  9 13:05:05 2021]
rule download_and_trim:
    output: dog_microbiome_updated_env/trimmed/ERR1914540_1.t.fastq.gz, dog_microbiome_updated_env/trimmed/ERR1914540_2.t.fastq.gz
    jobid: 49
    wildcards: id=ERR1914540
    threads: 2
    resources: mem_mb=16000, disk_mb=18000

Get status with:
gcloud config set project cloud-practice-metagenomics
gcloud beta lifesciences operations describe projects/cloud-practice-metagenomics/locations/us-central1/operations/17495592641206175770
gcloud beta lifesciences operations list
Logs will be saved to: dog_microbiome_updated_env/dog_microbiome_updated_env/google-lifesciences-logs


[Sun May  9 13:05:09 2021]
rule download_and_trim:
    output: dog_microbiome_updated_env/trimmed/ERR1914532_1.t.fastq.gz, dog_microbiome_updated_env/trimmed/ERR1914532_2.t.fastq.gz
    jobid: 41
    wildcards: id=ERR1914532
    threads: 2
    resources: mem_mb=16000, disk_mb=18000

Get status with:
gcloud config set project cloud-practice-metagenomics
gcloud beta lifesciences operations describe projects/cloud-practice-metagenomics/locations/us-central1/operations/7968943226611757057
gcloud beta lifesciences operations list
Logs will be saved to: dog_microbiome_updated_env/dog_microbiome_updated_env/google-lifesciences-logs


[Sun May  9 13:05:12 2021]
rule download_and_trim:
    output: dog_microbiome_updated_env/trimmed/ERR1914536_1.t.fastq.gz, dog_microbiome_updated_env/trimmed/ERR1914536_2.t.fastq.gz
    jobid: 45
    wildcards: id=ERR1914536
    threads: 2
    resources: mem_mb=16000, disk_mb=18000

Traceback (most recent call last):
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 695, in snakemake
    success = workflow.execute(
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1017, in execute
    success = scheduler.schedule()
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 489, in schedule
    self.run(runjobs)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 500, in run
    executor.run_jobs(
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 136, in run_jobs
    self.run(
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 804, in run
    result = self._retry_request(operation)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 886, in _retry_request
    raise ex
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 875, in _retry_request
    return request.execute()
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/googleapiclient/http.py", line 920, in execute
    resp, content = _retry_request(
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/googleapiclient/http.py", line 222, in _retry_request
    raise exception
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/oauth2client/transport.py", line 173, in new_request
    resp, content = request(orig_request_method, uri, method, body,
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/oauth2client/transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/httplib2/__init__.py", line 1708, in request
    (response, content) = self._request(
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/httplib2/__init__.py", line 1424, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/httplib2/__init__.py", line 1376, in _conn_request
    response = conn.getresponse()
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2627)
```

The second one I have encountered once:

```
$ snakemake  --google-lifesciences --default-remote-prefix dog_microbiome_updated_env  --preemption-default 10 --use-conda --cores 400
Preemptible instances are only available for the Google Life Sciences Executor.
['Ash_p1', 'Avalanche_p1']
Building DAG of jobs...
Using shell: /bin/bash
Job counts:
        count   jobs
        1       all
        2       combine
        46      download_and_trim
        2       megahit
        51
Select jobs to execute...

[Sun May  9 12:54:41 2021]
rule download_and_trim:
    output: dog_microbiome_updated_env/trimmed/ERR1915352_1.t.fastq.gz, dog_microbiome_updated_env/trimmed/ERR1915352_2.t.fastq.gz
    jobid: 19
    wildcards: id=ERR1915352
    threads: 2
    resources: mem_mb=16000, disk_mb=18000

Get status with:
gcloud config set project cloud-practice-metagenomics
gcloud beta lifesciences operations describe projects/cloud-practice-metagenomics/locations/us-central1/operations/7547707234028273571
gcloud beta lifesciences operations list
Logs will be saved to: dog_microbiome_updated_env/dog_microbiome_updated_env/google-lifesciences-logs


[Sun May  9 12:54:44 2021]
rule download_and_trim:
    output: dog_microbiome_updated_env/trimmed/ERR1915359_1.t.fastq.gz, dog_microbiome_updated_env/trimmed/ERR1915359_2.t.fastq.gz
    jobid: 26
    wildcards: id=ERR1915359
    threads: 2
    resources: mem_mb=16000, disk_mb=18000

Get status with:
gcloud config set project cloud-practice-metagenomics
gcloud beta lifesciences operations describe projects/cloud-practice-metagenomics/locations/us-central1/operations/9219829443168301540
gcloud beta lifesciences operations list
Logs will be saved to: dog_microbiome_updated_env/dog_microbiome_updated_env/google-lifesciences-logs


[Sun May  9 12:54:48 2021]
rule download_and_trim:
    output: dog_microbiome_updated_env/trimmed/ERR1915337_1.t.fastq.gz, dog_microbiome_updated_env/trimmed/ERR1915337_2.t.fastq.gz
    jobid: 4
    wildcards: id=ERR1915337
    threads: 2
    resources: mem_mb=16000, disk_mb=18000

Traceback (most recent call last):
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 695, in snakemake
    success = workflow.execute(
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1017, in execute
    success = scheduler.schedule()
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 489, in schedule
    self.run(runjobs)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 500, in run
    executor.run_jobs(
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 136, in run_jobs
    self.run(
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 804, in run
    result = self._retry_request(operation)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 886, in _retry_request
    raise ex
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/google_lifesciences.py", line 875, in _retry_request
    return request.execute()
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/googleapiclient/http.py", line 920, in execute
    resp, content = _retry_request(
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/googleapiclient/http.py", line 222, in _retry_request
    raise exception
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/oauth2client/transport.py", line 173, in new_request
    resp, content = request(orig_request_method, uri, method, body,
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/oauth2client/transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/httplib2/__init__.py", line 1708, in request
    (response, content) = self._request(
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/httplib2/__init__.py", line 1424, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/site-packages/httplib2/__init__.py", line 1376, in _conn_request
    response = conn.getresponse()
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/mick_watson/miniconda3/envs/snakemake/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2627)
```

**Minimal example**
Encountered when running https://github.com/mw55309/dog_microbiome

You need a bucket, and to upload "dogs.txt" to the bucket, then run:

```
 snakemake  --google-lifesciences --default-remote-prefix NAME_OF_MY_BUCKET  --preemption-default 10 --use-conda --cores 14
```

**Additional context**

**Comment by mw55309** [comment]
@hnawar :)

**Comment by mw55309** [comment]
Hi

I created a test case which reproduces the error for me.

https://github.com/mw55309/crash_gcp

I would appreciate knowing if others see this?

Thanks
Mick

**Comment by mw55309** [comment]
Hooking in this conversation from the GCP Life Sciences discussion list https://groups.google.com/g/gcp-life-sciences-discuss/c/j4-h-qz4lR0

Some suggestion that this is due to too many requests to google:

```
I suspect it is a snakemake code strategy issue.  So in the snakemake codebase you will notice at the following retry section, that it is scheduled via the status_rate_limiter parameter:

  Section:

    https://github.com/snakemake/snakemake/blob/main/snakemake/executors/google_lifesciences.py#L908-L918

  Code:

    with self.status_rate_limiter:
    ...
      try:
          status = self._retry_request(request)
      except googleapiclient.errors.HttpError as ex:

The status_rate_limiter is defined in the following code section:

  Section:

    https://github.com/snakemake/snakemake/blob/main/snakemake/executors/__init__.py#L699-L703

  Code:

    self.max_status_checks_per_second = max_status_checks_per_second

    self.status_rate_limiter = RateLimiter(
        max_calls=self.max_status_checks_per_second, period=1
    )

Based on the RateLimiter documentation at the following link, your period is every 1 second performing a maximum of max_status_checks_per_second calls:

  https://github.com/RazerM/ratelimiter#overview

Most services guard against such simple repetitive requests, which could overload a service.  Instead most perform the scheduled retry requests using an exponential backoff logic, which is what Google recommends here:

  https://cloud.google.com/storage/docs/retry-strategy

```

Perhaps @vsoch has some insight?

Thanks
Mick

**Comment by vsoch** [comment]
I don't have insight to the implementation - it looks like rate limiting was added after my original development -> https://github.com/snakemake/snakemake/commit/72c1f89c65cb5909a3c93b334013e541aeba1bcb. But I will second using exponential backoff, that's typically considered best practice.

**Comment by mw55309** [comment]
Thanks @vsoch 

I haven't looked too deeply but it looks like some of those values are hard-coded... ?

If this is indeed the source of the errors then Snakemake Google life sciences executor code is essentially unusable right now

**Comment by vsoch** [comment]
I'm not sure I see definite proof that the SSL error is definitely linked to the retry, but it does seem reasonable to expose the max_status_checks_per_sceond as a variable. Why don't you suggest this and open a PR with your suggested changed?

**Comment by mw55309** [comment]
Thank you for your help.

The Snakemake documentation suggests max status checks per second is exposed

https://snakemake.readthedocs.io/en/stable/executing/cli.html

But in the code you posted it looked hard coded. Perhaps it's changed elsewhere based on parameters?

I'd definitely need to brush up my Python before submitting a PR ;) I'll have a hack at my local installation and see what I can do.

Cheers
Mick

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by vsoch** [comment]
it looks like it might not hit the GLS executor -- we can trace it. It is indeed already an argument, you can see it passed from the client here:

https://github.com/snakemake/snakemake/blob/ec87b97d8a7a92f3734001433d7fba3d5e4a642a/snakemake/__init__.py#L735

That gets passed to workflow.execute, here: https://github.com/snakemake/snakemake/blob/ec87b97d8a7a92f3734001433d7fba3d5e4a642a/snakemake/workflow.py#L563 which is handed to the job scheduler here:

https://github.com/snakemake/snakemake/blob/ec87b97d8a7a92f3734001433d7fba3d5e4a642a/snakemake/workflow.py#L930

and then in the scheduler here: https://github.com/snakemake/snakemake/blob/ec87b97d8a7a92f3734001433d7fba3d5e4a642a/snakemake/scheduler.py#L88

And then in this file you can see it's passed to tibanna and others, but not GLS:

https://github.com/snakemake/snakemake/blob/ec87b97d8a7a92f3734001433d7fba3d5e4a642a/snakemake/scheduler.py#L301

But it indeed is included as a variable https://github.com/snakemake/snakemake/blob/ec87b97d8a7a92f3734001433d7fba3d5e4a642a/snakemake/executors/google_lifesciences.py#L56. 

So the fix to test is very easy - just pass that variable to the GLS executor in the scheduler and make sure it's carried forward here https://github.com/snakemake/snakemake/blob/ec87b97d8a7a92f3734001433d7fba3d5e4a642a/snakemake/executors/google_lifesciences.py#L132. Likely that was hard coded based on testing / best practice (the max we could get without error) but it seems like what was working before is no longer, if it indeed is the case that this parameter is leading to these SSL issues.

**Comment by mw55309** [comment]
Thank you for this, I will dig in

The code throwing the error is this function, which interestingly does do a rudimentary "exponential backoff":

https://github.com/snakemake/snakemake/blob/ec87b97d8a7a92f3734001433d7fba3d5e4a642a/snakemake/executors/google_lifesciences.py#L861

It tries three times, each time waiting 2, 4 and 8 seconds.

Interestingly, this function is called within a loop:

```
for j in active_jobs:
```

Which means for workflows with large numbers of jobs, it's really being hammered; 

It's also being run within:

```
with self.status_rate_limiter:
```

And I am not sure how the "max_status_checks_per_second" variable interacts with this

**Comment by mw55309** [comment]
OK, I have tracked this down a little.

The error always comes from function _retry_request:

https://github.com/snakemake/snakemake/blob/a0b22a5c7f2e0761fd2686b6ac3bc4456bf0504a/snakemake/executors/google_lifesciences.py#L861

Now, from looking at the code and how it's executed, when I run snakemake there are two functions that run _retry_request. They are:

def run:
https://github.com/snakemake/snakemake/blob/ec87b97d8a7a92f3734001433d7fba3d5e4a642a/snakemake/executors/google_lifesciences.py#L804

def _wait_for_jobs:
https://github.com/snakemake/snakemake/blob/ec87b97d8a7a92f3734001433d7fba3d5e4a642a/snakemake/executors/google_lifesciences.py#L917

I have seen snakemake crash out from both of these.

The problem that I have is they appear to be running simultaneously, because no matter what I do, occasionally function run and function _wait_for_jobs make a call to _retry_request at essentially the same time and it crashes out

Here is an example where they do this, immediately after which snakemake crashed:

```
run  at 2021-05-13 10:23:48.469671
run  at 2021-05-13 10:23:53.171866
wait at 2021-05-13 10:23:56.597950
run  at 2021-05-13 10:23:58.040873
run  at 2021-05-13 10:24:02.842725
run  at 2021-05-13 10:24:07.594884
wait at 2021-05-13 10:24:07.634018
```

These are print statements to help me figure out when _retry_request is being called, with "run" and "wait" being shortcuts for the function name calling it. I have inserted time.sleep() calls in both functions to try and slow each one down, however because they are running simultaneously, occasionally they try and do calls at the same time. 

As you can see the last two calls were only 0.04s apart, and snakemake crashed.

It seems to me that it would be a major effort to co-ordinate the calls of these two functions?

**Comment by vsoch** [comment]
Have you tested if the with statement that adds another layer of rate limiting is not to blame? The requests you pointed out (that use the same function) are different - the first makes the request for an operation, and the second checks the status.

**Comment by mw55309** [comment]
The test pipeline I created has now run to completion 4/5 times. The time it failed is above.

https://github.com/mw55309/crash_gcp

Without any of the rate limiting code I've added (3 statements) it died **every single time**

I can re-run it with the current main branch of snakemake and collect more data if that's the evidence we need?

**Comment by mw55309** [comment]
So I took all the breaks off and just ran normal snakemake, with print statemente to figure out when ```_retry_request``` is being called and by which function.

In all three cases, Snakemake crashed when two calls to _retry_request happened **really close together***. The last two times are key as these are the calls right before the crash.

One:
```
wait at 2021-05-13 17:27:37.513581
run  at 2021-05-13 17:27:37.880589
wait at 2021-05-13 17:27:38.607179
run  at 2021-05-13 17:27:39.675230
wait at 2021-05-13 17:27:39.703162
```

Two:

```
wait at 2021-05-13 17:32:42.447928
run  at 2021-05-13 17:32:42.576260
wait at 2021-05-13 17:32:43.476152
wait at 2021-05-13 17:32:44.552502
run  at 2021-05-13 17:32:44.557964
```

Three:

```
wait at 2021-05-13 20:38:41.644943
run  at 2021-05-13 20:38:41.809560
wait at 2021-05-13 20:38:42.667255
run  at 2021-05-13 20:38:43.665409
wait at 2021-05-13 20:38:43.692654
```

In all cases, the last two calls are less than 1ms apart and snakemake crashes.

Full results are [here](https://gist.github.com/mw55309/4223bf6bc30391a0300cb0e160f644ff), [here ](https://gist.github.com/mw55309/56e489eb18d677f6bd0f7c17864d25ec) and [here](https://gist.github.com/mw55309/5adc605cd561285f891bac1a4c5578b1)

Given the top of the error says ```Exception in thread Thread-1:``` I think we have to at least acknowledge that multiple threads may be calling ```_retry_request``` simultaneously and causing this problem.

Inserting time.sleep() calls in both function ```run``` and function ```_wait_for_jobs``` largely stops the crashes, because it reduces the chances of two calls being less than 1ms apart - however, it is a hack because it does not completely remove the possibility of it happening.

Thoughts?

**Comment by vsoch** [comment]
See this comment that you missed - https://github.com/snakemake/snakemake/issues/983#issuecomment-840624095  I think you should test removing the with statement that adds the extra retry context. I don’t have comment beyond that, I can’t test this myself.

**Comment by mw55309** [comment]
Thanks, just to be clear, you think I should remove this with: statement?

https://github.com/snakemake/snakemake/blob/598a404e29cd8fd34e01eea5b11cf9cee13eeb59/snakemake/executors/google_lifesciences.py#L908

So just run the same code but without that with: statement?

What am I misisng? Why do you think this will avoid clashes?

**Comment by vsoch** [comment]
Yes it’s worth ruling that out.

**Comment by mw55309** [comment]
I have largely removed the SSL errors by using better exception handling (pull request will come soon), but I now instead run into this:

https://github.com/snakemake/snakemake/issues/1006

Any tips on even how to begin debugging this would be helpful....

**Comment by rashidalabri** [comment]
Any updates on this? I've encountered the same issue and cannot run my workflow without throwing this error.

**Comment by vsoch** [comment]
I think @mbargull was asking for additional debugging info in https://github.com/snakemake/snakemake/issues/1006#issuecomment-846386969 but nobody responded.

**Comment by mw55309** [comment]
Hi

The quickest way to deal with the SSL errors is as follows.

In https://github.com/snakemake/snakemake/blob/main/snakemake/executors/google_lifesciences.py there is come code at line 889:

```sh
        try:
            return request.execute()
        except BrokenPipeError as ex:
            if attempts > 0:
                time.sleep(timeout)
                return self._retry_request(request, timeout * 2, attempts - 1)
            raise ex
        except googleapiclient.errors.HttpError as ex:
            log_verbose_traceback(ex)
            raise ex
        except Exception as ex:
            log_verbose_traceback(ex)
            raise ex
```

The SSL errors come out of the third except statement and are caught but undealt with.

You can deal with both of the second and third except statements by a re-call to the function:

```
        try:
            return request.execute()
        except BrokenPipeError as ex:
            if attempts > 0:
                time.sleep(timeout)
                return self._retry_request(request, timeout * 2, attempts - 1)
            raise ex
        except googleapiclient.errors.HttpError as ex:
            log_verbose_traceback(ex)
            return self._retry_request(request, timeout * 2, attempts - 1)
            raise ex
        except Exception as ex:
            log_verbose_traceback(ex)
            return self._retry_request(request, timeout * 2, attempts - 1)
            raise ex
```

In my experience this will deal with most of the SSL errors, but does result eventually in the core dump described in https://github.com/snakemake/snakemake/issues/1006#issuecomment-846386969, which I have yet to try and deal with

I need to find time to put the above in a pull request, my apologies

Mick
