### ISSUE TITLE
KeyError when ambiguous rule follows a checkpoint

### ISSUE THREAD

**Issue by jmeppley** [snakemake/snakemake#988]
**Snakemake version**
Tested on the latest version: 6.3.0+2.gec87b97d

**Describe the bug**

Snakemake throws a KeyError while updating jobs after a checkpoint when there are two rules that can produce the same output. 

**Logs**

This is the error output:

```
Traceback (most recent call last):
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/executors/__init__.py", line 570, in _callback
    callback(job)
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/scheduler.py", line 544, in _proceed
    job, update_dynamic=update_dynamic
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/dag.py", line 1341, in finish
    updated_dag = self.update_checkpoint_dependencies(jobs)
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/dag.py", line 1302, in update_checkpoint_dependencies
    self.replace_job(j, newjob, recursive=False)
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/dag.py", line 1505, in replace_job
    self.delete_job(job, recursive=recursive)
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/dag.py", line 1464, in delete_job
    del self.dependencies[job_][job]
KeyError: multiple
```

**Minimal example**

Snakefile:
```
n_files = 4

rule all:
    input:
        faa='all.faa',
        fasta='all.fasta'

checkpoint make_files:
    """make a bunch of dummy fasta files"""
    output: 
        files=directory('files')
    run:
        os.makedirs(output.files)
        for i in range(n_files):
            filename = f'{output.files}/f{i}.fasta'
            with open(filename, 'wt') as fasta_out:
                fasta_out.write('>blank\nACTGACTG\n')

def get_cp_files(extension='txt'):
    """ after the checkpoint, get the names of the files with the given extension """
    files_dir = checkpoints.make_files.get().output.files
    files, = glob_wildcards(f'{files_dir}/{{file}}.fasta')
    return expand(f'{files_dir}/{{file}}.{extension}', file=files)
    
rule pattern:
    """ turn any fasta into a faa """
    input: "{any_file}.fasta"
    output: "{any_file}.faa"
    shell: "cp {input} {output}"
        

rule multiple:
    """ (pretends to) collect all the fasta and faa files into one of each """
    input: 
        fastas=lambda w: get_cp_files('fasta'),
        faas=lambda w: get_cp_files('faa'),
    output:
        fasta='all.fasta',
        faa='all.faa',
        report='all.txt'
    shell:
        "touch {output}"
```

To run:
```
 $ snakemake -j 1
```

Full log:
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	make_files
	1	multiple
	3
Select jobs to execute...

[Mon May 10 17:26:39 2021]
checkpoint make_files:
    output: files
    jobid: 2
Downstream jobs will be updated after completion.

Job counts:
	count	jobs
	1	make_files
	1
Updating job multiple.
[Mon May 10 17:26:41 2021]
Error in rule make_files:
    jobid: 2
    output: files

Traceback (most recent call last):
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/executors/__init__.py", line 570, in _callback
    callback(job)
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/scheduler.py", line 544, in _proceed
    job, update_dynamic=update_dynamic
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/dag.py", line 1341, in finish
    updated_dag = self.update_checkpoint_dependencies(jobs)
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/dag.py", line 1302, in update_checkpoint_dependencies
    self.replace_job(j, newjob, recursive=False)
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/dag.py", line 1505, in replace_job
    self.delete_job(job, recursive=recursive)
  File "/mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/snakemake/snakemake/dag.py", line 1464, in delete_job
    del self.dependencies[job_][job]
KeyError: multiple
Removing output files of failed job make_files since they might be corrupted:
files
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/data0/jmeppley/projects/snakemake_bugs/snakemake.two_outputs/.snakemake/log/2021-05-10T172638.910005.snakemake.log
```

**Additional context**

I attempted to fix with a ruleorder statement, but that made no difference. What fixes the problem is to explicitly make the `pattern` rule more selective so that it doesn't match all.fasta as an input.

So there are two things going on here. 

 * First snakemake is missing that these rules are ambiguous. 
 * Second, the `dag.cleanup()` step is removing the alternate rule (`pattern`) from `dag.dependencies`, but it remains in `dag.depending['multiple']`. So, when update_checkpoint_dependencies tries to delete `multiple`, it goes looking for a nonexistent `job_` in `dag.dependencies`. 

Incidentally, if there is no checkpoint preceding this ambiguous pair of rules, then the workflow completes correctly.

**Comment by jmeppley** [comment]
I have a proposed simple patch (#989) that just catches the error and moves on.

This assumes that the desired response to the redundant nature of these rule definitions is to ignore them.

**Comment by johanneskoester** [comment]
Thanks a lot! I have fixed this now via a slight modification of your PR.
