### ISSUE TITLE
Use singularity on MacBook with M1 Chip

### ISSUE THREAD

**Issue by thomasbtf** [snakemake/snakemake#999]
**Snakemake version**
6.3.0

**Describe the bug**
I am trying to use the `--use singularity` flag to run snakemake with containerization support. Snakemake throws the error below, when/after building the DAG. I have used the following in the Snakefile:

```
container: "docker://continuumio/miniconda3"
containerized: "docker://thomasbtf/docno:latest"
```

I`ve tried to use only of the container lines, but on both snakemake outputs the error below.

**Logs**
```
snakemake --cores all --use-conda --use-singularity

Building DAG of jobs...
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 695, in snakemake
    success = workflow.execute(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 894, in execute
    dag.create_conda_envs(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 291, in create_conda_envs
    env.create(dryrun)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 284, in create
    conda = Conda(self._container_img)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 425, in __new__
    inst._check()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 499, in _check
    version = version.split()[1]
IndexError: list index out of range
```

**Minimal example**
I am using a fresh clone of this repository: https://github.com/thomasbtf/document-anonymization
The only change regarding the master branch is, that `containerized: "docker://thomasbtf/docno:latest"` was added in a new line of the Snakefile after `container: "docker://continuumio/miniconda3"`.

**Additional context**
Machine: MacBook Pro
OS: macOS Big Sur Version 11.1
Chip: Apple M1

**Comment by FelixMoelder** [comment]
I'm trying to reproduce your issue but I was not able to set up singularity locally on an M1 device.
Probably due to the issue that x86 vms do not run on these devices. 
So how does your singularity setup look like and is it easily reproducible?

**Comment by thomasbtf** [comment]
Yeah, rember the setup of singularity wasn't straightforward. I installed it a couple of months back with the  Singularity Desktop app for macOS (but I`m not 100% sure about this). I think I downloaded it via the https://sylabs.io/singularity/ site, but it seems it isn't available via the site now. So you probably won't be able to reproduce the setup that easily :/

My singularity version is as follows. Maybe it helps? 
```
singularity --version
singularity version 3.3.0-rc.1.658.g7427b73f1.dirty
```
